#!/usr/bin/env python3
"""
er_yaml_lint.py -- sanity-check an Elden Ring Archipelago Players yaml for the
silent option interactions that waste playtests: dead (inert) knobs, conflicting
goals, and the known footguns.

Usage:
    python er_yaml_lint.py [PATH ...]      # files and/or dirs; default: Archipelago/Players
    python er_yaml_lint.py --strict ...    # exit non-zero on warnings too (default: only errors)

Severities:
    [ERROR] the option does the OPPOSITE of what you wrote, or gen will fail
    [WARN ] the option is silently IGNORED / overridden under these settings
    [INFO ] heads-up / style (e.g. a choice value yaml parsed as a bool)

Drift-proof: the set of valid option keys is parsed live from
worlds/eldenring/options.py (the EROptions dataclass), so adding an option in
options.py automatically teaches the linter about it. Pure stdlib + PyYAML.
"""
from __future__ import annotations
import os, re, sys, glob
from difflib import get_close_matches

try:
    import yaml
except ImportError:
    sys.stderr.write("er_yaml_lint: PyYAML not found (pip install pyyaml)\n")
    sys.exit(2)

# ---- the option surface, read WITHOUT importing Archipelago -----------------
# 🛑 THE SOURCE IS THREE THINGS AND IT HAS TO BE ALL THREE.
#
# The obvious fix -- read `wizard/options-metadata.json` and stop -- is WRONG, and wrong in the
# direction that hurts: it is the WIZARD-EXPOSED surface, while a yaml may legitimately carry a
# FROZEN option too (Archipelago drops those silently; naming one is stale, not invalid). Measured
# when it was tried: 19 false `unknown option` errors on Alaric_shattering.yaml alone, 8 of 8
# shipped fixtures dirty. A linter that cries wolf on every real yaml gets switched off, which is
# how rule 0 came to be dead in the first place.
#
# So: the generated wizard surface, PLUS defaults.FROZEN_OPTIONS, PLUS AP's own common keys.
# Retired options are deliberately NOT here -- they belong in REMOVED below, which gives the player
# the replacement instead of a bare "unknown".
_HERE = os.path.dirname(os.path.abspath(__file__))
_METADATA = os.path.join(_HERE, "wizard", "options-metadata.json")
_DEFAULTS = os.path.join(_HERE, "greenfield", "eldenring", "defaults.py")

# Common (non-ER) keys that are valid in the EldenRing block via PerGameCommonOptions/CommonOptions.
_COMMON_KEYS = {
    "progression_balancing", "accessibility", "local_items", "non_local_items",
    "start_inventory", "start_inventory_from_pool", "start_hints", "start_location_hints",
    "exclude_locations", "priority_locations", "item_links", "plando_items", "death_link",
}

def _wizard_surface() -> set[str]:
    """Player-facing options, from the generated wizard metadata. Regenerated by
    tools/dump_options_metadata.py, so it cannot drift from the option classes without a red."""
    try:
        import json
        with open(_METADATA, "r", encoding="utf-8") as f:
            md = json.load(f)
    except Exception:
        return set()
    keys = set(md.get("field_order") or ())
    for g in md.get("groups") or ():
        for o in (g.get("options") or g.get("fields") or ()):
            keys.add(o if isinstance(o, str) else o.get("name"))
    keys.update(o if isinstance(o, str) else o.get("name") for o in (md.get("ungrouped") or ()))
    return {k for k in keys if k}


def _frozen_keys() -> set[str]:
    """defaults.FROZEN_OPTIONS -- off the wizard surface but VALID in a yaml. AP silently drops
    them, so naming one is stale rather than wrong and must not be reported as unknown.

    Loaded by file path, not by import: this script has to stay AP-free so it can run in the fast
    CI job, and `greenfield.eldenring.defaults` is a leaf module with no Archipelago import."""
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location("_gf_defaults", _DEFAULTS)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return set(getattr(mod, "FROZEN_OPTIONS", {}) or ())
    except Exception:
        return set()


def load_valid_keys() -> set[str]:
    """Every key a yaml may name without being wrong. Empty -> the unknown-key rule SKIPS, so the
    two loaders above failing open is a deliberate soft landing rather than a wall of false errors.

    🛑 An empty return means rule 0 is OFF, and it was off, silently, for the whole life of this
    file -- both paths it used to look for stopped existing at the greenfield port, `EROptions` was
    replaced by `GFOptions`, and the `if VALID_KEYS:` guard below turned that into silence rather
    than a failure. `--self-check` exists so that cannot recur unnoticed."""
    surface = _wizard_surface()
    if not surface:
        return set()
    return surface | _frozen_keys() | _COMMON_KEYS

VALID_KEYS = load_valid_keys()

# ---- choice option name<->int maps (only what rules / the bool-bug check need) ----
CHOICE = {
    "ending_condition": {"region_locks":0,"great_runes":1},
    "world_logic": {"region_lock":0,"region_bosses":1,"region_lock_bosses":2,"open_world":3},
    "region_access": {"geographic":0,"warp":1},
    "dlc_timing": {"early":0,"off":1,"late":2},
    "completion_scaling": {"off":0,"flat":1,"gentle":2,"steep":3,"smoothstep":4},
    "completion_scaling_basis": {"geographic":0,"sphere":1},
    "dungeon_sweep": {"none":0,"minidungeons":1,"all":2,"bosses":3},
    "location_pool": {"all":0,"trimmed":1,},
    "global_scadutree_blessing": {"off":0,"player_only":1,"scaled":2},
    "crafting_kit_option": {"randomize":0,"early":1,"do_not_randomize":2,"start_with":3},
    "map_option": {"randomize":0,"give":1,"do_not_randomize":2},
    "smithing_bell_bearing_option": {"randomize":0,"progression_randomize":1,"do_not_randomize":2},
    "merchant_bell_logic": {"off":0,"logic_only":1},
    "bell_physick_option": {"start_with":0,"do_not_randomize":1,"randomize":2},
    "torrent_start": {"auto":0,"on":1,"off":2},
    "random_start_region": {"off":0,"overworld":1,"any_major":2},
    "start_region_freebie": {"hub_only":0,"to_limgrave":1},
    "junk_retention_style": {"comedy":0,"comedy_and_generic":1,"uniform":2},
    "filler_replacement": {"off":0,"runes":1,"stones_and_runes":2},
    "excluded_location_behavior": {"allow_useful":1,"forbid_useful":2,"do_not_randomize":3},
    "missable_location_behavior": {"allow_useful":1,"forbid_useful":2,"do_not_randomize":3},
}
# defaults rules fall back to when a key is absent
DEFAULT = {
    "ending_condition":"final_boss","world_logic":"region_lock","region_access":"geographic",
    "dlc_only":False,"enable_dlc":False,"enemy_rando":False,"grace_rando":True,
    "num_regions":0,"num_regions_order":"rolled","minimum_enemy_difficulty":0,"graces_per_region":3,
    "pool_builder":False,"pool_builder_dlc_gear":False,"soft_progression":False,
    "dlc_only_chain":False,"messmer_kindle":False,"quick_start":False,
    "dlc_only_rune_catchup":False,"num_regions_chain":False,
    "location_pool":"all","excluded_location_behavior":"forbid_useful",
    "missable_location_behavior":"forbid_useful",
}
# options removed in a hard merge -> give a migration hint instead of a bare "unknown"
REMOVED = {
    "region_count": "merged into num_regions -- use `num_regions: N` + `num_regions_order: spine`",
    "flask_upgrade_option": "merged into important_locations (list Seedtree/Church) -- use vanilla_upgrades: [flasks] for the old do_not_randomize",
    "blessing_option": "merged into important_locations (list Fragment/Revered) -- use vanilla_upgrades: [blessings] for the old do_not_randomize",
    "pool_builder_dlc_gear": "removed (Part 2) -- pool_builder injects base juice only; use dlc_gear_curation for DLC gear",
    "great_runes_present": "removed (Part 2) -- num_regions pool deficit injection now targets great_runes_required",    "region_boss_type": "removed (Part 2) -- only fed the disabled region_bosses rules block",
    "num_regions_rune_source": "removed 2026-07-02 (one-sound-mode) -- rune deficits vs great_runes_required are pool-injected automatically in all num_regions modes; delete the key",
    "shop_checks": "removed 2026-07-02 (one-sound-mode) -- shop-slot handling is no longer optional; delete the key",
    # Options.Removed stubs. These still exist as fields, and Archipelago RAISES on them at
    # generation -- so the value of catching them here is the replacement line, delivered before
    # the player has queued a seed rather than after it dies.
    "pool_builder": "retired 2026-07-28 -- for a VANILLA ITEM POOL use `vanilla_pool: true`; for no gear injection set `juice: 0` in curated_filler",
    "pool_builder_scope": "retired 2026-07-28 -- steer gear with the pool_builder_pct_* proportions instead",
    "pool_builder_juice_cap": "retired 2026-07-28 -- the `juice` weight in curated_filler is the amount now",
    "pool_builder_juice_pct": "retired 2026-07-28 -- the `juice` weight in curated_filler is the amount now",
    "completion_scaling_floor": "retired -- use minimum_enemy_difficulty",
    "completion_scaling_ramp": "retired -- use difficulty_ramp_speed",
    "local_item_only": "retired 2026-08-14 -- use `keep_local: [everything]`, which is the identical sweep under the name that survived",
    "exclude_local_item_only": "retired 2026-08-14 with local_item_only -- name what you KEEP in `keep_local` instead of what you release",
    "progression_surface_mode": "retired 2026-08-14 -- strict was the only reachable value and is now the only behaviour; use `progression_surface` to choose the classes and `confine_foreign_progression` for the foreign half",
}

# ---- QUARANTINE THE v0.1 ROT ------------------------------------------------------------------
# Measured 2026-08-14, the day the block lookup was fixed and these rules ran for the first time
# since the greenfield port: 17 of 21 CHOICE entries and 16 of 22 DEFAULT entries name options that
# NO LONGER EXIST (world_logic, region_access, location_pool, grace_rando, the *_option family...).
# Rules keyed on them cannot say anything true, and left armed they emit confident nonsense -- the
# shipped template drew a "num_regions only takes effect with ending_condition: capital" warning,
# against an ending_condition whose values have been region_locks/great_runes for two releases.
#
# 🛑 DROPPED, NOT FIXED, and deliberately: porting fifteen rules is a separate job with fifteen
# separate verifications, and a rule ported by guesswork is worse than an absent one. Filtering on
# VALID_KEYS makes the dead ones structurally unable to fire, and `--self-check` prints the count so
# the debt is a number somebody can watch rather than a silence.
def _live_only(table):
    return {k: v for k, v in table.items() if not VALID_KEYS or k in VALID_KEYS}


_CHOICE_QUARANTINED = sorted(set(CHOICE) - set(_live_only(CHOICE)))
_DEFAULT_QUARANTINED = sorted(set(DEFAULT) - set(_live_only(DEFAULT)))
CHOICE = _live_only(CHOICE)
DEFAULT = _live_only(DEFAULT)


class Finding:
    __slots__ = ("sev","key","msg")
    def __init__(self, sev, key, msg): self.sev, self.key, self.msg = sev, key, msg

# ---- value helpers ----------------------------------------------------------
def as_bool(v):
    if isinstance(v, bool): return v
    if isinstance(v, (int, float)): return bool(v)
    if isinstance(v, str): return v.strip().lower() not in {"off","0","false","none","null","no",""}
    return bool(v)

class Cfg:
    def __init__(self, block: dict):
        self.b = block or {}
        self.bool_choice_hits = []  # (key) where a choice value got parsed as a python bool

    def has(self, k): return k in self.b
    def raw(self, k, d=None): return self.b.get(k, d)

    def truthy(self, k):
        return as_bool(self.b.get(k, DEFAULT.get(k, False)))

    def num(self, k):
        v = self.b.get(k, DEFAULT.get(k, 0))
        try: return int(v)
        except (TypeError, ValueError): return 0

    def cval(self, k):
        """Return the normalized choice NAME (str) for a choice key, or None if absent."""
        if k not in self.b:
            return DEFAULT.get(k)
        v = self.b[k]
        names = CHOICE.get(k, {})
        if isinstance(v, bool):
            # yaml turned an unquoted on/off/yes/no into a python bool -- AP maps it via int(0/1)
            self.bool_choice_hits.append(k)
            inv = {i: n for n, i in names.items()}
            return inv.get(1 if v else 0)
        if isinstance(v, int) and not isinstance(v, bool):
            inv = {i: n for n, i in names.items()}
            return inv.get(v, str(v))
        return str(v).strip().lower()

# ---- the rules --------------------------------------------------------------
def lint_block(block: dict) -> list[Finding]:
    c = Cfg(block)
    out: list[Finding] = []
    def err(k,m): out.append(Finding("ERROR",k,m))
    def warn(k,m): out.append(Finding("WARN",k,m))
    def info(k,m): out.append(Finding("INFO",k,m))

    goal = c.cval("ending_condition")
    wl   = c.cval("world_logic")
    lock_based = wl in ("region_lock", "region_lock_bosses")
    nr   = c.num("num_regions")
    seal_goal = goal in ("capital","messmer","godrick") or nr > 0
    eff_dlc = c.truthy("enable_dlc") or c.truthy("dlc_only") or goal == "messmer"

    # 0) unknown keys (typos / stranded options)
    if VALID_KEYS:
        for k in c.b:
            if k not in VALID_KEYS:
                if k in REMOVED:
                    err(k, f"REMOVED -- {REMOVED[k]}")
                else:
                    sugg = get_close_matches(k, VALID_KEYS, n=3, cutoff=0.6)
                    hint = f" -- did you mean {', '.join(repr(s) for s in sugg)}?" if sugg else " -- typo?"
                    err(k, f"unknown option '{k}'{hint} (silently ignored by AP)")

    # 1) goal forcing
    if goal == "messmer":
        if c.has("dlc_only") and not c.truthy("dlc_only"):
            warn("dlc_only", "ending_condition: messmer FORCES dlc_only ON -- your 'false' is overridden")
        if c.truthy("messmer_kindle"):
            warn("messmer_kindle", "forced OFF under ending_condition: messmer (Enir Ilim is sealed)")
    if goal == "godrick":
        if c.truthy("dlc_only"):
            warn("dlc_only", "ending_condition: godrick FORCES dlc_only OFF -- your 'true' is overridden")
        if wl == "open_world":
            err("world_logic", "ending_condition: godrick needs lock-based world_logic (region_lock / region_lock_bosses)")
    if c.truthy("dlc_only") and c.has("enable_dlc") and not c.truthy("enable_dlc"):
        info("enable_dlc", "dlc_only FORCES enable_dlc ON -- your 'false' is overridden")

    # 2) random_start_region
    rsr = c.cval("random_start_region")
    if rsr and rsr != "off":
        if seal_goal:
            # Name the specific seal goal in play so the message points at the real cause.
            active = []
            if goal in ("capital","messmer","godrick"): active.append(f"ending_condition: {goal}")
            if nr > 0: active.append(f"num_regions: {nr}")
            cause = " + ".join(active)
            _chain = c.truthy("num_regions_chain")
            if nr > 0 and _chain:
                # The chain's link-0 rolls your start region: random_start_region the OPTION is
                # inert, but functionally you DO get a random start -- working as intended.
                # (num_regions_rune_source deleted 2026-07-02; deficit injection is automatic.)
                info("random_start_region",
                     f"the option itself is inert under the seal goal ({cause}), but "
                     "num_regions_chain is set, so the chain's link-0 already rolls your "
                     "start region -- working as intended.")
            else:
                # Why: a seal goal prunes the world to a kept set with the goal boss inside it; a free
                # random spawn could land in a SEALED region, so the apworld resets it and you start at
                # The First Step regardless of this value.
                msg = (f"IGNORED -- a region-seal goal is active ({cause}). random_start_region is "
                       "silently reset to 'off' (the world is pruned to a kept set the goal boss must "
                       "sit inside, and a free spawn could land in a sealed region). You'll start at "
                       "The First Step (Limgrave).")
                if nr > 0:
                    msg += ("\n    Fix (num_regions runs): set num_regions_chain: true to SPAWN in the "
                            "rolled link-0 region.")
                else:
                    msg += ("\n    No random-start path exists under this goal yet (the Roundtable re-root "
                            "rides on num_regions). Drop random_start_region, or switch to a non-seal goal "
                            "(elden_beast / final_boss / all_remembrances / all_bosses) to use it.")
                warn("random_start_region", msg)
        if c.truthy("dlc_only"):
            warn("random_start_region", "INERT under dlc_only -- Gravesite is the fixed sphere-1 hub, "
                 "so there is no overworld region to roll a start in.")
        if not lock_based:
            err("random_start_region", "requires lock-based world_logic (region_lock / region_lock_bosses) "
                f"-- you have world_logic: {wl}. The roll pre-collects a region's LOCK as the free hub, "
                "which only exists when regions are lock-gated.")

    # 3) enemy_rando gates. NOTE: completion_scaling has a scale-only bake pass now, so it
    #    does NOT require enemy_rando; only the swap/runes/impolite toggles do.
    if not c.truthy("enemy_rando"):
        for k in ("swap_multiboss","boss_runes_match","impolite_enemies"):
            if c.truthy(k):
                warn(k, "INERT without enemy_rando: true")
    # RENAMED 2026-07-27 -> minimum_enemy_difficulty / difficulty_ramp_speed. The old rule here
    # ("INERT without completion_scaling on") is dead twice over: completion_scaling is not a yaml
    # option any more (scaling is unconditionally on), so it fired on every valid yaml that set a
    # floor. Flag the stale NAMES instead -- the world now rejects them outright via Options.Removed,
    # and saying so here is friendlier than a generation traceback.
    for _old, _new in (("completion_scaling_floor", "minimum_enemy_difficulty"),
                       ("completion_scaling_ramp", "difficulty_ramp_speed")):
        if c.cval(_old) is not None:
            warn(_old, f"RENAMED to {_new}; generation will refuse this key"
                       + (" (and the ramp INVERTED: higher is now harder)" if "ramp" in _old else ""))

    # 4) dlc_only gates
    if not c.truthy("dlc_only"):
        for k in ("quick_start","dlc_only_rune_catchup"):
            if c.truthy(k):
                warn(k, "INERT unless dlc_only: true")

    # 5) DROPPED 2026-08-14. Both halves were v0.1 premises that had become false, and both fired
    #    on the SHIPPED TEMPLATE the moment the linter started reading modern yamls:
    #      * "num_regions only takes effect with ending_condition: capital" -- `capital` has not
    #        been an ending_condition value for two releases (region_locks / great_runes), so the
    #        comparison could only ever be unequal.
    #      * "only takes effect with lock-based world_logic" -- `world_logic` no longer exists, so
    #        `lock_based` is always False and the warning was unconditional.
    #    num_regions is unconditional now: it is the region DRAW SIZE, always consulted.
    #    `extra_region_locks` goes with them -- same dead `lock_based`.

    # 6) num_regions_order: spine requested but no regions to order.
    #    `spine` was renamed `vanilla_order`; accept both so an older yaml still gets the warning.
    if c.cval("num_regions_order") in ("spine", "vanilla_order") and nr == 0:
        warn("num_regions_order", "ordering set but num_regions is 0 (nothing to keep)")

    # 7) num_regions sub-options
    if c.truthy("num_regions_chain"):
        if nr == 0:
            warn("num_regions_chain", "INERT unless num_regions > 0")
        elif goal != "capital":
            warn("num_regions_chain", "only takes effect with ending_condition: capital")

    # 7c) rune/region decoupling + Roundtable-hub re-root (spine surgery 2026-07-02): num_regions
    #     counts your ROLLED majors only -- the Roundtable hub and the (lockless) Leyndell capstone
    #     are always kept and never counted. Altus is force-kept on top of the roll (it is the only
    #     route into lockless Leyndell), so the effective kept count is num_regions + 1 and the
    #     structural floor is 2 (Altus + one rolled major). Great runes never raise the count
    #     (the deficit is pool-injected). Any num_regions >= 1 is valid; 0 disables the mode.
    if nr == 1:
        info("num_regions", "1 rolls a single major on top of the force-kept Altus -> effective 2 "
             "(Altus + 1 rolled major, plus the uncounted Roundtable hub and Leyndell capstone)")
    # 2026-08-10: this guard read `great_runes_required` -- the pre-rename key. The option became
    # `goal_great_runes` on 2026-07-14 (core._CORE_OPTION_FIELDS), so `c.num()` fell through to its
    # default of 0 and the rule could not fire on any current yaml. Found via LordChungle's v0.3.9
    # report (#504): he believed he had asked for six runes and the seed resolved to one.
    if nr > 0 and c.num("goal_great_runes") > 4:
        err("goal_great_runes", "num_regions runs can satisfy at most 4 great runes "
            "(Godrick/Rennala/Radahn/Rykard exist before the capital) -- gen rejects this (OptionError)")

    # 8) dlc_only_chain
    if c.truthy("dlc_only_chain") and goal != "messmer":
        warn("dlc_only_chain", "Phase 1 only acts under ending_condition: messmer -- plain dlc_only warns + no-ops")

    # 10) sweep
    if c.cval("grace_sweep") not in (None,"off") and c.cval("dungeon_sweep") != "bosses":
        warn("grace_sweep", "INERT unless dungeon_sweep: bosses")

    # 11) soft_progression vs accessibility
    if c.truthy("soft_progression") and c.cval("accessibility") == "minimal":
        warn("soft_progression", "no effect under accessibility: minimal (everything spills there anyway)")

    # 12) grace bundle override
    if c.truthy("grace_rando") and lock_based and c.has("graces_per_region") and c.num("graces_per_region") != 3:
        info("graces_per_region", "grace_rando (on) overrides the graces_per_region bundle -- set grace_rando: false to use it")

    # 13) baked-dependency reminders (can't verify from yaml)
    if c.truthy("soft_consumable_shop"):
        info("soft_consumable_shop", "REQUIRES the baked Twin Maiden rows (patch_baker_soft_consumable_shop) -- dead without them")

    # 14) choice value parsed as a YAML boolean (the unquoted on/off/yes/no footgun:
    #     e.g. `dlc_timing: off` -> False -> resolves to option index 0 = 'early', NOT off)
    #    ONLY when the coercion actually lands on the WRONG option. `off` -> False -> index 0, so
    #    for a choice whose index 0 IS named `off` the unquoted form is harmless -- and the shipped
    #    template uses exactly that shape twice. Warning there is a false positive that trains
    #    people to ignore the rule, which matters because the true case is genuinely silent.
    for k, vals in CHOICE.items():
        if k in c.b and isinstance(c.b[k], bool):
            idx = 1 if c.b[k] else 0
            intended = "on" if c.b[k] else "off"
            if vals.get(intended) != idx:
                landed = next((n for n, i in vals.items() if i == idx), f"index {idx}")
                info(k, f"YAML parsed this choice as the boolean {intended}, which resolves to "
                        f"`{landed}` -- quote it ({k}: \"{intended}\") if you meant the option of "
                        f"that name")

    # 15b) trimmed + forbid_useful filler shortage (observed 3/3 FillError on the
    #      wizard short_solo sample 2026-07-02: "Not enough filler items for excluded
    #      locations"; the trimmed pool runs out of pure filler for excluded/missables,
    #      especially under seal goals). forbid_useful is the DEFAULT, so this fires on
    #      absent keys too -- allow_useful is the supported pairing with trimmed.
    if c.cval("location_pool") == "trimmed":
        for k in ("excluded_location_behavior", "missable_location_behavior"):
            if c.cval(k) == "forbid_useful":
                warn(k, "trimmed pool + forbid_useful can FillError ('not enough filler "
                        "items for excluded locations') -- set allow_useful")

    # 15) tight-pool accessibility heads-up
    if c.cval("accessibility") == "full" and (seal_goal or c.cval("location_pool") == "lean" or c.raw("extra_region_locks")):
        info("accessibility", "full can FillError on tight/region-locked pools; minimal lets them spill")

    return out

# ---- driver -----------------------------------------------------------------
def lint_file(path: str) -> list[Finding]:
    try:
        docs = list(yaml.safe_load_all(open(path, "r", encoding="utf-8-sig")))
    except Exception as e:
        return [Finding("ERROR", "<file>", f"could not parse yaml: {e}")]
    findings = []
    for doc in docs:
        if not isinstance(doc, dict):
            continue
        # 🛑 BOTH SPELLINGS, and this is not politeness -- it is the bug that made this whole file
        # a no-op. The game id became `Elden Ring` (WITH the space) at the v0.2 rename, and this
        # function only ever looked for the v0.1 `EldenRing`. Every current yaml therefore fell
        # through to zero findings, which reads exactly like a clean file: not just rule 0 but ALL
        # fifteen rules had never run on anything anyone actually plays.
        #
        # Caught 2026-08-14 by injecting `local_item_only: true` into a preset and watching the
        # linter report OK. Keep the old key: a v0.1 yaml is precisely the one that most needs the
        # REMOVED migration messages.
        for key in ("Elden Ring", "EldenRing"):
            if isinstance(doc.get(key), dict):
                findings += lint_block(doc[key])
    return findings

def iter_yaml_paths(paths):
    for p in paths:
        if os.path.isdir(p):
            yield from sorted(glob.glob(os.path.join(p, "*.yaml"))) + sorted(glob.glob(os.path.join(p, "*.yml")))
        else:
            yield p

def self_check() -> int:
    """Prove rule 0 is ARMED. It was dead for the whole life of this file and nothing noticed,
    because `if VALID_KEYS:` turns a failed load into silence instead of a failure. CI calls this
    before linting anything, so the loaders breaking is a red rather than a quiet green.

    Three assertions, each a way the load has actually failed or could:
      1. the surface loaded at all (both old paths stopped existing at the greenfield port);
      2. it is PLAUSIBLE, not a stub -- a one-key parse would satisfy (1) and lint nothing;
      3. FROZEN options are included, which is the half that produced 19 false errors on a real
         yaml the first time someone tried metadata-only.
    """
    problems = []
    if not VALID_KEYS:
        problems.append("VALID_KEYS is EMPTY -- rule 0 is off. wizard/options-metadata.json "
                        "unreadable, or its shape changed.")
    elif len(VALID_KEYS) < 40:
        problems.append(f"VALID_KEYS has only {len(VALID_KEYS)} entries -- too few to be the real "
                        f"surface; the loader is probably parsing a fragment.")
    if VALID_KEYS and not _frozen_keys():
        problems.append("defaults.FROZEN_OPTIONS did not load -- frozen keys would be reported as "
                        "unknown, which is the false-positive that gets a linter switched off.")
    for p in problems:
        print(f"  [SELF-CHECK] {p}")
    if problems:
        print("er_yaml_lint: SELF-CHECK FAILED -- the unknown-key rule cannot be trusted.")
        return 1
    print(f"er_yaml_lint: self-check ok ({len(VALID_KEYS)} valid key(s), "
          f"{len(_frozen_keys())} frozen, {len(REMOVED)} retired)")
    if _CHOICE_QUARANTINED or _DEFAULT_QUARANTINED:
        print(f"  {len(_CHOICE_QUARANTINED)} CHOICE + {len(_DEFAULT_QUARANTINED)} DEFAULT "
              f"entry(s) quarantined as v0.1 rot (their option no longer exists), so the rules "
              f"keyed on them cannot fire. This number should go DOWN as rules are ported; it "
              f"going UP means an option was retired and its rule was left behind.")
        print(f"    CHOICE:  {', '.join(_CHOICE_QUARANTINED) or '-'}")
        print(f"    DEFAULT: {', '.join(_DEFAULT_QUARANTINED) or '-'}")
    return 0


def main(argv):
    strict = "--strict" in argv
    if "--self-check" in argv:
        return self_check()
    args = [a for a in argv if not a.startswith("-")]
    if not args:
        for cand in (os.path.join(_HERE, "Archipelago", "Players"), os.path.join(_HERE, "Players")):
            if os.path.isdir(cand): args = [cand]; break
    if not args:
        print("usage: python er_yaml_lint.py [PATH ...]   (no Players dir found)"); return 2

    total_err = total_warn = 0
    any_file = False
    for path in iter_yaml_paths(args):
        any_file = True
        findings = lint_file(path)
        name = os.path.basename(path)
        if not findings:
            print(f"  OK    {name}")
            continue
        print(f"\n{name}")
        order = {"ERROR":0,"WARN":1,"INFO":2}
        for f in sorted(findings, key=lambda x: order[x.sev]):
            print(f"  [{f.sev:<5}] {f.key}: {f.msg}")
            if f.sev == "ERROR": total_err += 1
            elif f.sev == "WARN": total_warn += 1
    if not any_file:
        print("no yaml files found"); return 2
    print(f"\n{total_err} error(s), {total_warn} warning(s)")
    if total_err or (strict and total_warn):
        return 1
    return 0

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
