-- Elden Ring Archipelago PopTracker pack — entry point (M1 + M3a map variant).
-- Pairs with tools/gen_poptracker.py + tools/build_map.py (regenerate on apworld/dump changes).

-- Generated logic data first, then the logic that consumes it.
ScriptHost:LoadScript("scripts/region_graph.lua")
ScriptHost:LoadScript("scripts/logic.lua")

-- Generated, churn-prone pack data (do NOT hand-edit; run tools/gen_poptracker.py):
Tracker:AddItems("items/items.json")
Tracker:AddLocations("locations/locations.json")  -- carries map_locations pins for the map variant

-- Shared generated item grid (referenced by both variant layouts):
Tracker:AddLayouts("layouts/item_grid.json")

-- Variant-specific view. Both layout files define "tracker_default"; load exactly one.
if Tracker.ActiveVariantUID == "map" then
  Tracker:AddMaps("maps/maps.json")              -- generated by tools/build_map.py (needs a coord dump)
  Tracker:AddLayouts("layouts/map.json")          -- map widget + item grid
else
  Tracker:AddLayouts("layouts/items_only.json")   -- list-only (no map art)
end

-- Generated id tables (authoritative; ap_code == AP network id):
ScriptHost:LoadScript("scripts/ap_map.lua")    -- AP_ITEM_ID_TO_CODE
ScriptHost:LoadScript("scripts/loc_map.lua")   -- AP_LOC_ID_TO_SECTION

-- Auto-tracking (Archipelago) glue:
ScriptHost:LoadScript("scripts/autotracking.lua")
