-- GENERATED by tools/gen_poptracker.py -- do not edit.
-- Region reachability graph (slug-keyed) for logic.lua.
REGION_ROOT = "roundtable_hold"

REGION_ADJ = {
  ["altus"] = {"leyndell"},
  ["leyndell"] = {"sewer"},
  ["liurnia"] = {"raya_lucaria_academy"},
  ["roundtable_hold"] = {"limgrave", "weeping", "stormveil", "liurnia", "caelid", "siofra_river", "altus", "mt_gelmir", "ainsel_river", "deeproot_depths", "mohgwyn", "mountaintops_of_the_giants", "haligtree", "farum_azula", "gravesite", "ensis", "cerulean", "charo_s", "belurat", "scadu_altus", "shadow_keep", "stone_coffin", "ancient_ruins", "rauh_base", "jagged_peak", "abyssal", "enir_ilim", "ashen_capital"},
  ["shadow_keep"] = {"scaduview"},
}

-- Region -> lock-item codes (applied only when region gating is active):
REGION_LOCK_GATES = {
  ["abyssal"] = {"lock_abyssal_lock"},
  ["ainsel_river"] = {"lock_ainsel_river_lock"},
  ["altus"] = {"lock_altus_lock"},
  ["ancient_ruins"] = {"lock_ancient_ruins_lock"},
  ["belurat"] = {"lock_belurat_lock"},
  ["caelid"] = {"lock_caelid_lock"},
  ["cerulean"] = {"lock_cerulean_lock"},
  ["charo_s"] = {"lock_charo_s_lock"},
  ["deeproot_depths"] = {"lock_deeproot_depths_lock"},
  ["enir_ilim"] = {"lock_enir_ilim_lock"},
  ["ensis"] = {"lock_ensis_lock"},
  ["farum_azula"] = {"lock_farum_azula_lock"},
  ["gravesite"] = {"lock_gravesite_lock"},
  ["haligtree"] = {"lock_haligtree_lock"},
  ["jagged_peak"] = {"lock_jagged_peak_lock"},
  ["leyndell"] = {"lock_leyndell_lock"},
  ["limgrave"] = {"lock_limgrave_lock"},
  ["liurnia"] = {"lock_liurnia_lock"},
  ["mohgwyn"] = {"lock_mohgwyn_lock"},
  ["mountaintops_of_the_giants"] = {"lock_mountaintops_of_the_giants_lock"},
  ["mt_gelmir"] = {"lock_mt_gelmir_lock"},
  ["rauh_base"] = {"lock_rauh_base_lock"},
  ["raya_lucaria_academy"] = {"lock_raya_lucaria_academy_lock"},
  ["scadu_altus"] = {"lock_scadu_altus_lock"},
  ["scaduview"] = {"lock_scaduview_lock"},
  ["sewer"] = {"lock_sewer_lock"},
  ["shadow_keep"] = {"lock_shadow_keep_lock"},
  ["siofra_river"] = {"lock_siofra_river_lock"},
  ["stone_coffin"] = {"lock_stone_coffin_lock"},
  ["stormveil"] = {"lock_stormveil_lock"},
  ["weeping"] = {"lock_weeping_lock"},
}

-- Region -> key-item codes (applied in all logic modes):
REGION_KEY_GATES = {
}

-- Flat list of all gate codes (logic.lua uses it to cheaply detect state changes):
REGION_GATE_CODES = {"lock_abyssal_lock", "lock_ainsel_river_lock", "lock_altus_lock", "lock_ancient_ruins_lock", "lock_belurat_lock", "lock_caelid_lock", "lock_cerulean_lock", "lock_charo_s_lock", "lock_deeproot_depths_lock", "lock_enir_ilim_lock", "lock_ensis_lock", "lock_farum_azula_lock", "lock_gravesite_lock", "lock_haligtree_lock", "lock_jagged_peak_lock", "lock_leyndell_lock", "lock_limgrave_lock", "lock_liurnia_lock", "lock_mohgwyn_lock", "lock_mountaintops_of_the_giants_lock", "lock_mt_gelmir_lock", "lock_rauh_base_lock", "lock_raya_lucaria_academy_lock", "lock_scadu_altus_lock", "lock_scaduview_lock", "lock_sewer_lock", "lock_shadow_keep_lock", "lock_siofra_river_lock", "lock_stone_coffin_lock", "lock_stormveil_lock", "lock_weeping_lock"}

-- Every region slug in the pack (logic.lua creates one can_reach_<slug> per entry):
REGION_ALL = {"abyssal", "ainsel_river", "altus", "ancient_ruins", "ashen_capital", "belurat", "caelid", "cerulean", "charo_s", "deeproot_depths", "enir_ilim", "ensis", "farum_azula", "gravesite", "haligtree", "jagged_peak", "leyndell", "limgrave", "liurnia", "mohgwyn", "mountaintops_of_the_giants", "mt_gelmir", "rauh_base", "raya_lucaria_academy", "roundtable_hold", "scadu_altus", "scaduview", "sewer", "shadow_keep", "siofra_river", "stone_coffin", "stormveil", "weeping"}

-- DLC (Land of Shadow) region slugs; 1 == DLC:
REGION_IS_DLC = {
  ["abyssal"] = 1,
  ["ancient_ruins"] = 1,
  ["belurat"] = 1,
  ["cerulean"] = 1,
  ["charo_s"] = 1,
  ["enir_ilim"] = 1,
  ["ensis"] = 1,
  ["gravesite"] = 1,
  ["jagged_peak"] = 1,
  ["rauh_base"] = 1,
  ["scadu_altus"] = 1,
  ["scaduview"] = 1,
  ["shadow_keep"] = 1,
  ["stone_coffin"] = 1,
}

-- Graph root for a dlc_only seed: you START in Gravesite (base regions are
-- locked-vanilla transit with no checks), so reachability bootstraps from here.
REGION_DLC_ROOT = "gravesite"

return REGION_ADJ
