"""SPEC-PARITY -- filler foreign locality knob (multiworld filler routing).

Controls how much of THIS slot's FILLER is allowed to travel to other players' worlds. Greenfield's
filler is the generic 'Rune' grant that every un-shuffled check pays out, plus -- when Shuffle
Vanilla Items is on -- the GOODS-nibble vanilla items core classifies as `filler` (consumables,
crafting mats, etc.). None of that is progression, so routing it never changes winnability.

Greenfield applies NO filler-locality control by default: filler can already land in any world (fully
open). This feature adds a single Range knob to pull some of it back home, mirroring the old apworld's
filler_foreign_pct but INVERTED to greenfield's model. The old world started from a fully-localized
filler set and carved `filler_foreign_pct`% back OUT of local_items (default 15 = keep 85% home).
Greenfield starts fully open, so here `filler_foreign_pct` directly names the share that MAY go
foreign: we force `(100 - pct)%` of the distinct filler item NAMES into `local_items`, leaving the
rest free to travel.

  * pct = 100 (DEFAULT) -> 0% localized -> NO CHANGE (current greenfield behavior: fully open).
  * pct = 0            -> 100% localized -> all filler stays in-world.
  * pct = 50           -> ~half the distinct filler names kept home, half free.

MECHANISM mirrors features/local_items.py: `local_items.value` is AP's mutable set[str]; we
`.update(...)` it in generate_early, and AP's `locality_rules(multiworld)` reads it fresh during fill
(players > 1) to forbid other worlds from holding those names. Solo seeds wipe local_items -> inert
(as intended). Composes with local_items (Local Items Only) since we only ADD names -- if that toggle
already localized everything, this is a further no-op.

⚠️ COPY-based since 2026-08-16, and it was NAME-based before. The fraction is of filler item
COPIES, spent per CATEGORY, drawn from the pool's real classifications -- see `_select` for the
measurements that forced all three changes. The short version: a name-uniform draw cannot steer a
copy-weighted outcome when one name carries 38 copies and the median carries one, so the old lever
was a switch (0.47:1 fully open, 1.75:1 fully closed, and everything in between stuck at 0.38-0.63)
rather than the dial its docstring promised. Deterministic either way: drawn with world.random
(seeded), never the global RNG.

Matt-free: filler names come from core's FILLER constant + the param-derived ITEM_CATALOG GOODS
nibble -- no curated/location data. slot_data: locality is enforced AP-server-side in fill, the client
never needs it -> {} (we still surface a tiny diag of how many names were localized).
"""
from typing import Any, Dict, List

from Options import Range
from ..registry import Feature, register

try:  # generated by gen_data.py (real-item-pool: {vanilla_item_name: ER FullID}); matt-free
    from ..item_ids import ITEM_CATALOG
except Exception:  # not yet generated -> only the generic Rune filler exists
    ITEM_CATALOG = {}

# core's generic filler item name + the GOODS high-nibble. Kept as local constants (importing core
# would cycle); these mirror core.FILLER / core._GOODS_NIBBLE.
FILLER_NAME = "Rune"
_GOODS_NIBBLE = 0x40000000

# 🛑 THE NIBBLE IS NOT THE CLASS, and this module treated them as one until 2026-08-16. The header
# above used to say "the GOODS-nibble vanilla items core classifies as `filler`" -- which was true
# when the private nibble test WAS the taxonomy, and false from 2026-08-12, when `spells`,
# `spirit_ashes` and `crystal_tears` (and later `upgrade_bells`) were promoted to USEFUL. 341 of the
# 950 GOODS names are useful gear, so the old candidate set held back weapons-grade items at the
# same rate as crafting mats. `item_categories` is the ONE taxonomy (see its class_of docstring);
# ask it rather than re-deriving from the FullID.
from ..item_categories import FILLER as _FILLER_CLASS, category_of, class_of

# pct that means "no change" (fully open == current greenfield behavior). Documented default.
NO_CHANGE_PCT = 100


def _shuffle_on(world) -> bool:
    sh = getattr(world.options, "item_shuffle", None)
    return bool(sh and sh.value)


def filler_names(world) -> List[str]:
    """Distinct filler item NAMES for this world, sorted (deterministic). Always includes the
    generic Rune; adds GOODS-nibble catalog items only when Shuffle Vanilla Items is on (they only
    exist in the pool then)."""
    names = {FILLER_NAME}
    if _shuffle_on(world):
        _excl = getattr(world, "gf_dlc_excluded", ())
        names.update(n for n, full in ITEM_CATALOG.items()
                     if (full & 0xF0000000) == _GOODS_NIBBLE and n not in _excl
                     and class_of(n) == _FILLER_CLASS)
    return sorted(names)


class FillerForeignPct(Range):
    """Percent of THIS slot's filler COPIES that may travel to other players' worlds. 100
    (default) = fully open, no change. Lower keeps more of your filler home: at pct we hold back
    (100 - pct)% of your filler copies. 0 = keep all filler home.

    Every category keeps something eligible. The share is spent WITHIN each category and never takes
    a category's last item, so lowering this thins what you export rather than silently barring a
    whole category -- `keep_local` is the knob for barring one, and it should stay the only one.
    (`pct: 0` is exempt: you asked for all of it home.)

    ⚠️ THE USEFUL RANGE IS THE BOTTOM OF THE SLIDER. Measured cross-game beside Hollow Knight, one
    ER slot, useful:filler in what the partner receives: 100 -> 0.47:1, 50 -> 0.52:1, 25 -> 0.61:1,
    12 -> 0.82:1, 0 -> 1.87:1. The 1:1 composition target lands around 6-12, and the exact crossing
    moves by seed. Above ~50 you are adjusting almost nothing. Exported USEFUL rises the whole way
    (43 -> 58 items), so holding filler back buys your partner gear rather than shrinking the
    export.

    Inert in a solo seed (no other worlds) and composes with keep_local."""
    display_name = "Filler Open to Foreign (%)"
    range_start = 0
    range_end = 100
    # 🛑 70, NOT 100, SINCE 2026-08-16 -- this option now SHIPS NON-DEFAULT, and the number is the
    # answer to "what does the composition target actually need", measured rather than chosen.
    #
    # `NO_CHANGE_PCT` (100) is still the no-op sentinel and still what `_select` short-circuits on;
    # it is no longer the default. Alaric's ruling 2026-08-15 was to aim the export composition at
    # 1:1 useful:filler, and 70 is where that lands with the SHIPPED `keep_local` in place. Measured
    # cross-game, one ER slot, num_regions 4, POOLED over seeds (sum of useful / sum of filler,
    # which is what a partner actually receives -- a mean of per-seed ratios flatters the tail):
    #
    #   Hollow Knight, 5 seeds:     pct 100 -> 0.79:1     pct 70 -> 1.00:1  (272 useful / 272 filler)
    #   Bumper Stickers, 3 seeds:   pct 100 -> 0.77:1     pct 70 -> 0.97:1  ( 96 useful /  99 filler)
    #
    # Both partner sizes land on the target, which is what makes 70 a DEFAULT rather than a number
    # tuned to one partner. Per-seed spread at 70 is 0.79-1.27 (HK) -- centred, not tight; a fixed
    # percentage cannot be tight, which is the argument for a target-ratio option instead.
    #
    # ⚠️ THIS NUMBER IS ONLY VALID WITH THE SHIPPED `keep_local`. Against `keep_local: []` the same
    # sweep put 1:1 at pct 6-12 -- an order of magnitude away. The two levers compose, so re-measure
    # BOTH if either default moves; a pct read off the wrong keep_local is the failure this comment
    # exists to prevent.
    default = 70


@register
class FillerForeignFeature(Feature):
    name = "filler_foreign"
    OPTIONS = {"filler_foreign_pct": FillerForeignPct}

    # ---- helpers ------------------------------------------------------------------------------
    def _pct(self, world) -> int:
        opt = getattr(world.options, "filler_foreign_pct", None)
        return int(opt.value) if opt is not None else NO_CHANGE_PCT

    def _pool_filler_counts(self, world) -> Dict[str, int]:
        """{filler item name: copies} for THIS player, read off the real itempool.

        The real `ItemClassification`, not a name list: `core._class_for` promotes some catalog
        names per-NAME (required great runes, the Leyndell-gate runes, legacy and natural keys), and
        a candidate set derived from the catalog cannot see those promotions. Asking the pool is the
        only way to be sure a name is filler IN THIS SEED."""
        from BaseClasses import ItemClassification as _IC  # noqa: PLC0415 -- AP import at call time
        counts: Dict[str, int] = {}
        for it in world.multiworld.itempool:
            if it.player == world.player and it.classification == _IC.filler:
                counts[it.name] = counts.get(it.name, 0) + 1
        return counts

    def names_to_localize(self, world) -> List[str]:
        """The distinct filler names forced local for `world`. Cached per world: the draw consumes
        `world.random`, so recomputing it (slot_data used to) would both move the seed and answer a
        different question than the one `set_rules` acted on."""
        cached = getattr(world, "_gf_ff_localized", None)
        if cached is not None:
            return cached
        out = self._select(world)
        try:
            world._gf_ff_localized = out
        except Exception:                       # not a real world (pure callers) -> no cache
            pass
        return out

    def _select(self, world) -> List[str]:
        """Spend a COPY budget, category by category.

        # WHY COPIES AND NOT NAMES (2026-08-16)

        This drew a uniform sample of distinct NAMES until today, and a name-uniform draw cannot
        steer a copy-weighted outcome. Measured in a default pool, the candidate set is 121 names /
        293 copies: the median name carries ONE copy, `Smithing Stone [1]` carries 38, and the top
        ten names are 41% of every copy. So the result depended on whether the draw happened to take
        the big stacks -- measured cross-game useful:filler beside Hollow Knight, one ER slot:

            pct 100 -> 0.47:1   pct 50 -> 0.38:1   pct 25 -> 0.63:1   pct 10 -> 0.59:1   pct 0 -> 1.75:1

        Non-monotone, and effectively a switch rather than a dial: every intermediate setting sat in
        0.38-0.63 while the endpoints were 0.47 and 1.75. Spending a copy budget makes it monotone
        (0.47 / 0.52 / 0.61 / 0.82 / 1.87 over the same points) and puts the 1:1 composition target
        inside the range, at roughly pct 6-12.

        # WHY PER CATEGORY, AND WHY NEVER THE LAST NAME

        🛑 A single pool-wide draw at 90% swept `merchant_bells` (11 names), `other` (2) and
        `crafting` (2) to ZERO free names -- measured. Nothing targeted them; they are small enough
        that a 90% draw takes all of them. That silently reproduces the whole-category bar that
        `keep_local` is the explicit knob for, and it would do it in a seed where the player named no
        category at all. Spending the share WITHIN each category, and never taking a category's last
        name, makes "every category still has something eligible to travel" a property of the
        mechanism instead of a probability.

        `pct == 0` is exempt: the player asked for every scrap of filler to stay home, and a
        guarantee that overrides an explicit request is a bug, not a safeguard.
        """
        pct = self._pct(world)
        if pct >= NO_CHANGE_PCT:
            return []                            # fully open -> nothing localized (no change)
        counts = self._pool_filler_counts(world)
        if not counts:
            return []
        if pct <= 0:
            return sorted(counts)                # explicit "keep it all home" -- no carve-out
        by_cat: Dict[str, List[str]] = {}
        for name in counts:
            by_cat.setdefault(category_of(name), []).append(name)
        picked: List[str] = []
        for cat in sorted(by_cat):               # sorted: the draw order must not depend on dict order
            names = sorted(by_cat[cat])
            if len(names) < 2:
                continue                         # its one name IS the category's eligibility
            world.random.shuffle(names)
            budget = (sum(counts[x] for x in names) * (100 - pct)) // 100
            spent = 0
            for x in names[:-1]:                 # never the last -> the category keeps a free name
                if spent >= budget:
                    break
                picked.append(x)
                spent += counts[x]
        return sorted(picked)

    # ---- hooks --------------------------------------------------------------------------------
    def set_rules(self, world) -> None:
        """🛑 NOT `generate_early` -- the itempool does not exist yet there.

        AP order (Main.py): create_items (115) -> set_rules (118) -> locality_rules (140). The pool
        is populated by the first and read by the last, so this is the one window where the copy
        counts and the real classifications are both available AND `local_items` is still read
        afterwards. `generate_early`, where this used to run, is before create_items -- which is
        exactly why the old implementation had to guess from a name list."""
        names = self.names_to_localize(world)
        if not names:
            return
        # local_items.value is a plain mutable set[str]; add (never clear) so we compose with the
        # player's hand list and with keep_local. locality_rules reads it later in Main.py.
        world.options.local_items.value.update(names)

    def slot_data(self, world) -> Dict[str, Any]:
        # Locality is enforced AP-server-side during fill; the client never needs it. Surface a tiny
        # diag of how many distinct filler names were forced local. Reads the CACHE (see
        # names_to_localize) -- recomputing would draw again and disagree with what set_rules did.
        return {"filler_foreign_localized": len(self.names_to_localize(world))}
