"""SPEC-PARITY Phase 7 -- Local Items convenience toggle (COMPLETE).

Greenfield's real vanilla items (ItemShuffle's weapons/armor/talismans/goods, plus the progressive
"Progressive X" upgrade items) are Elden-Ring-specific and mostly only useful *in* an ER game. In a
multiworld a player usually wants them to stay in their OWN world rather than scatter into other
games' pools, where they'd be dead weight. AP already supports this via the inherited `local_items`
OptionSet -- but that means the player has to list every item name by hand. This feature is a
one-flag convenience: flip it on and every real vanilla item (and every progressive item) is added
to `local_items`, so only the region Locks (progression) and Rune (generic filler) can appear in
other players' games.

MECHANISM (why mutating local_items in generate_early is both safe and effective):
  * `local_items` is AP's `LocalItems(ItemSet(OptionSet))`. `OptionSet.__init__` does
    `self.value = set(...)`, so `world.options.local_items.value` is a plain mutable `set[str]`.
    We mutate it IN PLACE (`.update(...)`), which is what AP itself does (Main.py subtracts sets in
    place). Rebinding `.value` would be fine too, but in-place update is the least surprising.
  * ORDERING. During YAML rolling, Generate.py calls `option.verify(...)` once, BEFORE any world
    hook. Because `LocalItems` is an `ItemSet` (`verify_item_name = True`), that verify checks that
    every listed name is a valid item name of this world -- but it runs on the *player-authored*
    value only, and never re-runs after generate_early. So adding names in generate_early cannot
    trip verify_item_name. (We only add names that ARE valid greenfield item names anyway --
    ITEM_CATALOG names + progressive names, all registered in core.item_name_to_id -- so even if a
    late re-verify were added upstream, our additions would pass.)
  * EFFECT. AP enforces locality in `Main.py` at `locality_rules(multiworld)` (called just before
    connect_entrances/generate_basic, i.e. long AFTER generate_early). It reads
    `world.options.local_items.value` fresh at that point and forbids every OTHER player's locations
    from holding those items. So our generate_early mutation is picked up. (locality_rules only runs
    when players > 1; in a solo game Main.py wipes local_items to the empty set -- a no-op, and the
    seed is trivially "all local" anyway. Our test asserts on options.local_items.value directly,
    which we populate regardless of player count.)

Matt-free: item names come from the param-derived ITEM_CATALOG and the progressive feature's own
constant names -- no curated/location data. slot_data: none (locality is enforced AP-server-side in
fill, the client never needs to know) -> {}.
"""
from typing import Any, Dict, List

from Options import Range, Removed, Toggle, OptionSet
from ..registry import Feature, register

try:  # generated by gen_data.py (real-item-pool: {vanilla_item_name: ER FullID}); matt-free
    from ..item_ids import ITEM_CATALOG
except Exception:  # not yet generated -> no real items exist -> feature is a no-op
    ITEM_CATALOG = {}

# Progressive "Progressive X" item names (registered by features/progressive.py, NOT in
# ITEM_CATALOG). Imported by NAME so this stays a pure data dependency -- importing the sibling
# feature module is fine (features may import other features; only ..core is forbidden). Guarded so
# a future removal of progressive.py degrades this to catalog-only rather than breaking import.
try:
    from .progressive import (PROG_FLASK, PROG_STONESWORD_KEY,
                              PROG_SMITHING_BELL, PROG_SOMBER_BELL,
                              PROG_GRAVE_GLOVEWORT_BELL, PROG_GHOST_GLOVEWORT_BELL)
    _PROGRESSIVE_NAMES: List[str] = [PROG_FLASK, PROG_STONESWORD_KEY,
                                     PROG_SMITHING_BELL, PROG_SOMBER_BELL,
                                     PROG_GRAVE_GLOVEWORT_BELL, PROG_GHOST_GLOVEWORT_BELL]
except Exception:
    _PROGRESSIVE_NAMES = []

from ..item_categories import (CATEGORIES, PROGRESSIVE_CATEGORY, SELECTABLE, category_of,
                                expand, names_in, rune_payout)


def _all_local_names():
    """Every real vanilla item name (ITEM_CATALOG) + every progressive item name. These are exactly
    the items that only make sense in an ER game and that a player may want kept local."""
    return sorted(ITEM_CATALOG) + list(_PROGRESSIVE_NAMES)


class LocalItemOnly(Removed):
    """Retired 2026-08-14. Use `keep_local: [everything]` -- it does exactly this, and it is the
    same knob you would reach for to keep only SOME of your items, so there is one thing to learn
    instead of two.

    Not a judgement call: the two were measured identical, and they are identical by construction.
    `local_item_only` localized `sorted(ITEM_CATALOG) + progressives`; `keep_local: [everything]`
    expands to every category in `item_categories.CATEGORIES`, and `category_of` is TOTAL (every
    catalog name resolves to one of them, pinned by test_gf_item_categories), so the two name sets
    are equal. Both then feed the same `local_items.value.update()`.

    (This docstring is where a player who typed `local_item_only: true` lands, which is why it
    leads with the replacement line to paste rather than with the retirement.)"""


class ExcludeLocalItemOnly(Removed):
    """Retired 2026-08-14 with `local_item_only`, whose subtraction it was. Name the categories you
    want kept in `keep_local` instead of naming the ones you want released.

    It only ever meant something as "everything, MINUS these", so there is no direct translation --
    `keep_local` has no except-form. List what you want to keep:

        keep_local: [consumables, crafting, runes, crystal_tears]

    Same category vocabulary, same umbrellas (`goods`, `bell_bearings`, `everything`), same table in
    eldenring/item_categories.py. The one shape that is genuinely gone is
    `local_item_only: true` + `exclude_local_item_only: [everything]`, which was a third spelling of
    OFF -- that is now just leaving `keep_local` empty."""


class KeepLocal(OptionSet):
    """Categories of item to hold in YOUR OWN world, listed one per line. Nothing else is affected,
    so this is the knob for "keep my consumables and crafting mats, send the gear out" without
    reaching for Local Items Only (which keeps everything) or Filler Open to Foreign (which picks
    which of your filler stays home at random and cannot be aimed at a category).

    Same categories as Exclude From Local Items Only, and they compose: this adds to whatever that
    pair already localized, it never releases anything.

    Example, and the one this was written for:
        keep_local: [consumables, crafting, upgrade_materials, runes]
    -- crafting materials, smithing stones and ghost gloveworts, every consumable and every rune
    stay yours; weapons, armour, talismans, spells, spirit ashes and ashes of war still travel.
    Bell bearings are `key_items`, not `upgrade_materials`, so that example still sends them out.

    # Why the default is not empty (#703)

    🛑 THIS SHIPS NON-EMPTY, and it is the only locality option that does. The default is the `goods`
    umbrella MINUS `runes`, `key_items`, `spells` and `spirit_ashes` -- i.e. hold back the
    consumables, crafting materials, smithing stones, cookbooks and bell bearings, and let every
    rune, key item, weapon, piece of armour, talisman, ash, spell and spirit ash travel.

    🛑 `key_items` IS EXCLUDED ON EVIDENCE, not taste. Holding it was the obvious call, but the
    category covers Great Runes -- which `great_runes_required` makes a GOAL condition -- both Dectus
    medallions and every Remembrance -- so keeping it home took natural_progression's cross-world
    placements from 12 to ZERO in tools/gf_multiworld_smoke.py. Those are the items a multiworld
    exists to trade. The smoke is the gate that catches this; re-run it before adding the line back.

    The measurement it answers: at the shipped settings, upgrade_materials 23.7% and runes 24.0% of
    a 312-item export -- two thirds of what we placed abroad was junk. The export budget is
    SLOT-limited, not willingness-limited, so those items were not extra: they were occupying
    foreign locations that YOUR OWN gear would otherwise have taken.

    🛑 THE COST IS NOT THAT THE PARTNER CANNOT USE THEM -- they were never theirs to use. An item
    Elden Ring "sends abroad" is still YOUR item; what moves is the TRIGGER, into their world, so
    that their progress is what hands it to you. That is the whole point of a multiworld and it is
    why bobler asked for gear to travel in the first place ("you need to send your friends items to
    auto equip to int them"). A foreign location holding your Smithing Stone [1] instead of your
    Moonveil is a worse trade for YOU, not a discourtesy to them.

    🛑 NAMING ONE CATEGORY DOES ALMOST NOTHING, and that is the finding that shaped this list.
    Holding `runes` alone moved exported filler by ZERO (202 -> 202): whichever large pool stays open
    expands to fill every available slot, so filler must be closed close to as a CLASS before the mix
    moves. Measured useful:filler across the lattice -- shipped 0.53:1, `runes` 0.54:1,
    `runes + upgrade_materials` 0.60:1, `goods` minus `consumables` 0.73:1, whole `goods` 2.69:1.
    There is no category subset that lands near 1:1, which is why the rune cap below carries the
    fine adjustment rather than this list.

    Alaric's ruling, 2026-08-15: aim the composition at 1:1 useful:filler."""
    display_name = "Keep Local"
    valid_keys = frozenset(SELECTABLE)
    # The `goods` umbrella minus runes/spells/spirit_ashes. Written out rather than computed: a
    # default a player reads in their yaml has to be a literal list they can edit and shorten, and
    # deriving it would make `keep_local:` mean something different after a catalog change with
    # nothing in the diff to say so. test_gf_local_defaults pins it against the live umbrella.
    default = frozenset({
        "consumables", "cookbooks", "crafting", "crystal_tears",
        "merchant_bells", "other", "upgrade_bells", "upgrade_materials",
    })


class KeepLocalRuneCap(Range):
    """Hold back rune items worth this many runes or fewer; larger ones may still travel.
    **Defaults to 12,500**, which holds 18 of the 31 rune items -- everything from Golden Rune [1]
    up to and including Numen's Rune. Set it to 0 to turn this off and send every rune you find.

    ⚠️ CORRECTED 2026-08-16, and every corrected line was player-facing. This docstring opened
    "0 (default) is OFF -- no rune is held back by this option" while the default was 12,500 and it
    held 18 items; it was headed "Why the default is 6250" and argued for 6250 in the body, while
    the measurement paragraph below it bolded 12,500 and the code said 12,500; and its ladder was
    off by one from [4] up. The same text is in `release/EldenRing.yaml`, so a player reading their
    own options file was told the default was off. This is the #707 failure -- prose that stopped
    describing the code -- in the help text rather than in a guard, and the ladder below is now
    pinned by test_the_documented_rune_ladder_matches_the_params so it cannot drift again.

    "Small rune amounts should not be sent out" is the ask this answers, and the payout is a number
    the game publishes (EquipParamGoods.refId_default -> SpEffectParam.soul), so it does not have to
    be guessed from the item name. The ladder, MEASURED:

        Golden Rune [1]     200        Golden Rune [10]    5,000
        Golden Rune [4]   1,200        Golden Rune [11]    6,250
        Golden Rune [8]   3,000        Golden Rune [13]   10,000
        Golden Rune [9]   3,800        Numen's Rune       12,500   <- the default cap
                                       Hero's Rune [1]    15,000
                                       Lord's Rune        50,000
                                       Marika's Rune      80,000   <- the largest

    A cap of 3,000 keeps the small change (Golden Rune [1]-[8]) and lets the rest go.

    Independent of Keep Local: setting `runes` there keeps every rune home whatever this says.

    # Why the default is 12,500 (#703)

    Runes are the only large filler category `keep_local` leaves open by default, which makes this
    the FINE ADJUSTMENT on the export mix -- and unlike a percentage it is aimable, because the
    threshold is a quantity the game publishes rather than a share of a pool nobody can picture.
    12,500 is Numen's Rune: Golden Rune [13] and everything cheaper stays home, Hero's, Leda's,
    Lord's and Marika's Runes travel.

    Measured on 1xER + 1xHK (the adverse config) over 4 seeds, with the shipped `keep_local` above
    and everything else identical: cap 0 -> 0.57:1, cap 6250 -> 0.68:1, **cap 12500 -> 0.72:1**,
    cap 80000 (every rune home) -> 0.73:1. Against the PRE-#703 defaults (`keep_local` empty, cap 0)
    the pair moves 0.55:1 -> 0.72:1 -- and note what moved: exported useful is FLAT at 228 -> 231,
    while filler falls 412 -> 320. The partner does not receive less that they can use; they receive
    92 fewer Golden Runes and smithing stones. Foreign progression absorbed on-surface stays 100%
    throughout. 12,500 is NUMEN'S RUNE (Golden Rune [13] is 10,000 -- see the ladder above); Hero's,
    Leda's, Lord's and Marika's Runes still travel.

    🛑 THE TARGET WAS 1:1 AND THIS DOES NOT REACH IT -- it gets from the old 0.53:1 to 0.72:1, and
    the curve is flat past here (80000 buys 0.01 more). The binding constraint is `key_items`, which
    has to stay released because it carries the Great Runes, the Dectus medallions and every
    Remembrance -- holding it took natural_progression's cross-world placements to zero. It also
    carries 52 Stonesword Keys per 4 seeds, and at 32.3% of everything exported it is the largest
    single category. 1:1 needs that category split, the way `cookbooks` was peeled off it; until
    then this is the honest ceiling.

    Alaric's ruling, 2026-08-15: aim the composition at 1:1 useful:filler."""
    display_name = "Keep Local: Rune Cap"
    range_start = 0
    range_end = 80000
    default = 12500


@register
class LocalItemsFeature(Feature):
    name = "local_items"
    OPTIONS = {
        "local_item_only": LocalItemOnly,
        "exclude_local_item_only": ExcludeLocalItemOnly,
        "keep_local": KeepLocal,
        "keep_local_rune_cap": KeepLocalRuneCap,
    }

    # ---- helpers ------------------------------------------------------------------------------
    def _shuffle_on(self, world) -> bool:
        sh = getattr(world.options, "item_shuffle", None)
        return bool(sh and sh.value)

    # `local_item_only` / `exclude_local_item_only` were retired 2026-08-14 (see the Removed stubs
    # above). Their sweep is not reimplemented here because `keep_local: [everything]` already IS
    # it -- same names, same destination -- so there is exactly one code path that forces an item
    # local, and `category_names` below is it.

    # ---- the fine-grained half ------------------------------------------------------------------
    def _keep_local_categories(self, world):
        opt = getattr(world.options, "keep_local", None)
        return expand(opt.value) if opt is not None else []

    def _rune_cap(self, world) -> int:
        opt = getattr(world.options, "keep_local_rune_cap", None)
        return int(opt.value) if opt is not None else 0

    def category_names(self, world):
        """The names the CATEGORY controls (keep_local + keep_local_rune_cap) force local. Kept
        separate from names_to_localize so the two halves stay independently testable and so the
        report can say which knob held what back.

        Like Local Items Only this needs item_shuffle: with it off the pool holds no real vanilla
        items to keep, only the generic Rune. Returning names anyway would be harmless (AP would
        localize items that are not in the pool) but the diagnostics would claim to hold back items
        that do not exist, and that number is the thing a player is being shown."""
        if not self._shuffle_on(world):
            return []
        categories = self._keep_local_categories(world)
        names = set(names_in(categories, _PROGRESSIVE_NAMES))
        # Progressive stone bells REPLACE the vanilla upgrade-bell names in the pool. They still
        # belong to the same player-facing category: selecting `upgrade_bells` must keep the
        # replacement items local too, or conversion silently releases them into another player's
        # world. `names_in` cannot express this semantic subtype because all feature-minted items
        # share its broad `progressive` category (which also contains flasks and stonesword keys).
        if "upgrade_bells" in categories:
            names.update((PROG_SMITHING_BELL, PROG_SOMBER_BELL,
                          PROG_GRAVE_GLOVEWORT_BELL, PROG_GHOST_GLOVEWORT_BELL))
        cap = self._rune_cap(world)
        if cap > 0:
            names.update(n for n in ITEM_CATALOG
                         if (pay := rune_payout(n)) is not None and pay <= cap)
        return sorted(names)

    def all_names_to_localize(self, world):
        """Everything THIS feature forces local. Since the Local Items Only sweep was retired this
        is exactly `category_names`, but the name is kept: it is what the report, the tests and
        `vanilla_placement` all call, and one place to add a second source back is the point."""
        return sorted(set(self.category_names(world)))

    # ---- hooks --------------------------------------------------------------------------------
    def generate_early(self, world) -> None:
        names = self.all_names_to_localize(world)
        if not names:
            return  # toggle off, or shuffle off (no real items) -> leave local_items untouched
        # local_items.value is a plain mutable set[str] (OptionSet.__init__ -> set(...)). Mutate it
        # in place; locality_rules reads it later in Main.py to forbid foreign locations. We only add
        # (never clear) so we compose with any names the player listed by hand.
        world.options.local_items.value.update(names)

    def slot_data(self, world) -> Dict[str, Any]:
        # Locality is enforced AP-server-side during fill (worlds/generic/Rules.locality_rules).
        # The client never needs to know, so no slot_data contract.
        return {}
