"""SPEC-PARITY Phase 7 -- Local Items convenience toggle (COMPLETE).

Greenfield's real vanilla items (ItemShuffle's weapons/armor/talismans/goods, plus the progressive
"Progressive X" upgrade items) are Elden-Ring-specific and mostly only useful *in* an ER game. In a
multiworld a player usually wants them to stay in their OWN world rather than scatter into other
games' pools, where they'd be dead weight. AP already supports this via the inherited `local_items`
OptionSet -- but that means the player has to list every item name by hand. This feature is a
one-flag convenience: flip it on and every real vanilla item (and every progressive item) is added
to `local_items`, so only the region Locks (progression) and Rune (generic filler) can appear in
other players' games.

MECHANISM (why mutating local_items in generate_early is both safe and effective):
  * `local_items` is AP's `LocalItems(ItemSet(OptionSet))`. `OptionSet.__init__` does
    `self.value = set(...)`, so `world.options.local_items.value` is a plain mutable `set[str]`.
    We mutate it IN PLACE (`.update(...)`), which is what AP itself does (Main.py subtracts sets in
    place). Rebinding `.value` would be fine too, but in-place update is the least surprising.
  * ORDERING. During YAML rolling, Generate.py calls `option.verify(...)` once, BEFORE any world
    hook. Because `LocalItems` is an `ItemSet` (`verify_item_name = True`), that verify checks that
    every listed name is a valid item name of this world -- but it runs on the *player-authored*
    value only, and never re-runs after generate_early. So adding names in generate_early cannot
    trip verify_item_name. (We only add names that ARE valid greenfield item names anyway --
    ITEM_CATALOG names + progressive names, all registered in core.item_name_to_id -- so even if a
    late re-verify were added upstream, our additions would pass.)
  * EFFECT. AP enforces locality in `Main.py` at `locality_rules(multiworld)` (called just before
    connect_entrances/generate_basic, i.e. long AFTER generate_early). It reads
    `world.options.local_items.value` fresh at that point and forbids every OTHER player's locations
    from holding those items. So our generate_early mutation is picked up. (locality_rules only runs
    when players > 1; in a solo game Main.py wipes local_items to the empty set -- a no-op, and the
    seed is trivially "all local" anyway. Our test asserts on options.local_items.value directly,
    which we populate regardless of player count.)

Matt-free: item names come from the param-derived ITEM_CATALOG and the progressive feature's own
constant names -- no curated/location data. slot_data: none (locality is enforced AP-server-side in
fill, the client never needs to know) -> {}.
"""
from typing import Any, Dict, List

from Options import Range, Removed, Toggle, OptionSet
from ..registry import Feature, register

try:  # generated by gen_data.py (real-item-pool: {vanilla_item_name: ER FullID}); matt-free
    from ..item_ids import ITEM_CATALOG
except Exception:  # not yet generated -> no real items exist -> feature is a no-op
    ITEM_CATALOG = {}

# Progressive "Progressive X" item names (registered by features/progressive.py, NOT in
# ITEM_CATALOG). Imported by NAME so this stays a pure data dependency -- importing the sibling
# feature module is fine (features may import other features; only ..core is forbidden). Guarded so
# a future removal of progressive.py degrades this to catalog-only rather than breaking import.
try:
    from .progressive import (PROG_FLASK, PROG_STONESWORD_KEY,
                              PROG_SMITHING_BELL, PROG_SOMBER_BELL)
    _PROGRESSIVE_NAMES: List[str] = [PROG_FLASK, PROG_STONESWORD_KEY,
                                     PROG_SMITHING_BELL, PROG_SOMBER_BELL]
except Exception:
    _PROGRESSIVE_NAMES = []

from ..item_categories import (CATEGORIES, PROGRESSIVE_CATEGORY, SELECTABLE, category_of,
                                expand, names_in, rune_payout)


def _all_local_names():
    """Every real vanilla item name (ITEM_CATALOG) + every progressive item name. These are exactly
    the items that only make sense in an ER game and that a player may want kept local."""
    return sorted(ITEM_CATALOG) + list(_PROGRESSIVE_NAMES)


class LocalItemOnly(Removed):
    """Retired 2026-08-14. Use `keep_local: [everything]` -- it does exactly this, and it is the
    same knob you would reach for to keep only SOME of your items, so there is one thing to learn
    instead of two.

    Not a judgement call: the two were measured identical, and they are identical by construction.
    `local_item_only` localized `sorted(ITEM_CATALOG) + progressives`; `keep_local: [everything]`
    expands to every category in `item_categories.CATEGORIES`, and `category_of` is TOTAL (every
    catalog name resolves to one of them, pinned by test_gf_item_categories), so the two name sets
    are equal. Both then feed the same `local_items.value.update()`.

    (This docstring is where a player who typed `local_item_only: true` lands, which is why it
    leads with the replacement line to paste rather than with the retirement.)"""


class ExcludeLocalItemOnly(Removed):
    """Retired 2026-08-14 with `local_item_only`, whose subtraction it was. Name the categories you
    want kept in `keep_local` instead of naming the ones you want released.

    It only ever meant something as "everything, MINUS these", so there is no direct translation --
    `keep_local` has no except-form. List what you want to keep:

        keep_local: [consumables, crafting, runes, crystal_tears]

    Same category vocabulary, same umbrellas (`goods`, `bell_bearings`, `everything`), same table in
    eldenring/item_categories.py. The one shape that is genuinely gone is
    `local_item_only: true` + `exclude_local_item_only: [everything]`, which was a third spelling of
    OFF -- that is now just leaving `keep_local` empty."""


class KeepLocal(OptionSet):
    """Categories of item to hold in YOUR OWN world, listed one per line. Nothing else is affected,
    so this is the knob for "keep my consumables and crafting mats, send the gear out" without
    reaching for Local Items Only (which keeps everything) or Filler Open to Foreign (which picks
    which of your filler stays home at random and cannot be aimed at a category).

    Same categories as Exclude From Local Items Only, and they compose: this adds to whatever that
    pair already localized, it never releases anything.

    Example, and the one this was written for:
        keep_local: [consumables, crafting, upgrade_materials, runes]
    -- crafting materials, smithing stones and ghost gloveworts, every consumable and every rune
    stay yours; weapons, armour, talismans, spells, spirit ashes and ashes of war still travel.
    Bell bearings are `key_items`, not `upgrade_materials`, so that example still sends them out."""
    display_name = "Keep Local"
    valid_keys = frozenset(SELECTABLE)


class KeepLocalRuneCap(Range):
    """Hold back rune items worth this many runes or fewer; larger ones may still travel. 0
    (default) is OFF -- no rune is held back by this option.

    "Small rune amounts should not be sent out" is the ask this answers, and the payout is a number
    the game publishes (EquipParamGoods.refId_default -> SpEffectParam.soul), so it does not have to
    be guessed from the item name. The ladder: Golden Rune [1] 200, [4] 1,600, [8] 3,800, [10] 6,250,
    [13] 12,500, Hero's Rune [1] 15,000, Lord's Rune 50,000, and the DLC's largest 80,000. A cap of
    3,000 keeps the small change and lets the big ones go.

    Independent of Keep Local: setting `runes` there keeps every rune home whatever this says."""
    display_name = "Keep Local: Rune Cap"
    range_start = 0
    range_end = 80000
    default = 0


@register
class LocalItemsFeature(Feature):
    name = "local_items"
    OPTIONS = {
        "local_item_only": LocalItemOnly,
        "exclude_local_item_only": ExcludeLocalItemOnly,
        "keep_local": KeepLocal,
        "keep_local_rune_cap": KeepLocalRuneCap,
    }

    # ---- helpers ------------------------------------------------------------------------------
    def _shuffle_on(self, world) -> bool:
        sh = getattr(world.options, "item_shuffle", None)
        return bool(sh and sh.value)

    # `local_item_only` / `exclude_local_item_only` were retired 2026-08-14 (see the Removed stubs
    # above). Their sweep is not reimplemented here because `keep_local: [everything]` already IS
    # it -- same names, same destination -- so there is exactly one code path that forces an item
    # local, and `category_names` below is it.

    # ---- the fine-grained half ------------------------------------------------------------------
    def _keep_local_categories(self, world):
        opt = getattr(world.options, "keep_local", None)
        return expand(opt.value) if opt is not None else []

    def _rune_cap(self, world) -> int:
        opt = getattr(world.options, "keep_local_rune_cap", None)
        return int(opt.value) if opt is not None else 0

    def category_names(self, world):
        """The names the CATEGORY controls (keep_local + keep_local_rune_cap) force local. Kept
        separate from names_to_localize so the two halves stay independently testable and so the
        report can say which knob held what back.

        Like Local Items Only this needs item_shuffle: with it off the pool holds no real vanilla
        items to keep, only the generic Rune. Returning names anyway would be harmless (AP would
        localize items that are not in the pool) but the diagnostics would claim to hold back items
        that do not exist, and that number is the thing a player is being shown."""
        if not self._shuffle_on(world):
            return []
        names = set(names_in(self._keep_local_categories(world), _PROGRESSIVE_NAMES))
        cap = self._rune_cap(world)
        if cap > 0:
            names.update(n for n in ITEM_CATALOG
                         if (pay := rune_payout(n)) is not None and pay <= cap)
        return sorted(names)

    def all_names_to_localize(self, world):
        """Everything THIS feature forces local. Since the Local Items Only sweep was retired this
        is exactly `category_names`, but the name is kept: it is what the report, the tests and
        `vanilla_placement` all call, and one place to add a second source back is the point."""
        return sorted(set(self.category_names(world)))

    # ---- hooks --------------------------------------------------------------------------------
    def generate_early(self, world) -> None:
        names = self.all_names_to_localize(world)
        if not names:
            return  # toggle off, or shuffle off (no real items) -> leave local_items untouched
        # local_items.value is a plain mutable set[str] (OptionSet.__init__ -> set(...)). Mutate it
        # in place; locality_rules reads it later in Main.py to forbid foreign locations. We only add
        # (never clear) so we compose with any names the player listed by hand.
        world.options.local_items.value.update(names)

    def slot_data(self, world) -> Dict[str, Any]:
        # Locality is enforced AP-server-side during fill (worlds/generic/Rules.locality_rules).
        # The client never needs to know, so no slot_data contract.
        return {}
