"""lot_stacks -- register the STACKED AP items for locations whose vanilla lot hands over more
than one copy (#624).

ItemLotParam slots carry a quantity. `item_ids.LOCATION_UNITS` (generated, #616) records every
location that grants more than one; `core.stacked_vanilla_name` promotes such a location from
`<name>` to `<name> x<n>` -- but ONLY when that stacked name is a registered AP item. This feature
is what registers them, from the generated `LOT_STACK_GRANTS` mint list.

🛑 A STACK IS AN AP ITEM ID, NOT A FLAG OR A LOT. The stacked name is a SECOND AP id pointing at the
SAME game FullID, carrying `slot_data itemCounts = n`. No acquisition flag is minted and none is
needed; no ItemLotParam row is touched. The client already resolves through `apIdsToItemIds` and
multiplies by `itemCounts` (`unwrap_or(1).max(1)`), so this moves NO contract and needs no client
half.

WHY A SECOND ID RATHER THAN itemCounts ON THE EXISTING ONE -- the argument features/scadu_supply
made first and this generalises: `itemCounts` is keyed by AP item id and EVERY copy of a name shares
one, so stacking there is all-or-nothing and would silently multiply the x1 placements too. A
separate id keeps them independent: a lot that grants one Smithing Stone [2] still grants one.

`LOT_STACK_GRANTS` contains every quantity actually carried by a source lot. Curated filler bundles
are registered here too, but under their own `<name> x<n>` ids. Keeping those two populations on
quantity-specific ids is what lets a vanilla x1 Arrow stay x1 while a curated Arrow is a quiver.

CLASSIFICATION mirrors the base item rather than being asserted: a stacked Smithing Stone is filler
exactly as one Smithing Stone is. Reading it off item_categories keeps the two from drifting the
next time a category moves -- never read provenance off an ItemClassification.
"""
from BaseClasses import ItemClassification
from ..registry import Feature, register

try:  # generated by gen_data.py (#624). Absent on a pre-regen tree -> feature is inert, not broken.
    from ..item_ids import ITEM_CATALOG, LOT_STACK_GRANTS
except Exception:
    ITEM_CATALOG, LOT_STACK_GRANTS = {}, {}

try:
    # scadu_supply mints `Scadutree Fragment x2` itself, because its INJECTION needs the id whether
    # or not any vanilla lot pays two. One name, one owner: registering it here as well would be a
    # duplicate item name across two features' ITEMS. It stays with the feature that needs it for a
    # second reason; the generated mint list still names it, and this is the one place that knows to
    # step aside.
    from .scadu_supply import FRAGMENT_X2
except Exception:
    FRAGMENT_X2 = "Scadutree Fragment x2"

try:
    from ..item_categories import CATEGORY_CLASS, category_of
except Exception:
    CATEGORY_CLASS, category_of = {}, None


def _base_of(name):
    """`Smithing Stone [2] x3` -> `Smithing Stone [2]`. The suffix is minted by gen_data from a
    quantity, so it is always ` x<digits>` at the tail -- split from the RIGHT, because base names
    legitimately contain spaces and an `x`."""
    head, _, tail = name.rpartition(" x")
    return head if head and tail.isdigit() else name


def _class_for(name):
    """The stack is whatever the BASE item is. Falls back to filler, which is what every phase-1
    member (stones, collectathon lines) already is -- a stack must never be more valuable than the
    item it stacks, or fill would treat a quantity as a promotion."""
    if category_of is None:
        return ItemClassification.filler
    try:
        cls = CATEGORY_CLASS.get(category_of(_base_of(name)))
    except Exception:
        return ItemClassification.filler
    return cls if isinstance(cls, ItemClassification) else ItemClassification.filler


try:
    from .filler_curation import curated_stack_name, stack_qty_by_name
except Exception:
    curated_stack_name = None
    stack_qty_by_name = None


MINTED = {n: v for n, v in LOT_STACK_GRANTS.items() if n != FRAGMENT_X2}
if stack_qty_by_name is not None and curated_stack_name is not None:
    # Category quantities describe CURATED picks, not the vanilla location they happen to replace.
    # Register those bundles on separate ids so core no longer has to put a global count on the base
    # item (which was silently turning every vanilla x1/x3 throwable into x5).
    for _base, _qty in stack_qty_by_name().items():
        _full = ITEM_CATALOG.get(_base)
        if _full is None:
            continue
        _name = curated_stack_name(_base)
        _grant = (_full, _qty)
        if _name in MINTED and MINTED[_name] != _grant:
            raise ValueError("lot/category stack disagreement for %s" % _name)
        if _name != FRAGMENT_X2:
            MINTED[_name] = _grant


@register
class LotStacksFeature(Feature):
    name = "lot_stacks"
    # No options and no slot_data key of its own: the stacks reach the client through the item id
    # map and itemCounts that core already emits. This feature exists to REGISTER names.
    ITEMS = {n: _class_for(n) for n in MINTED}
    ITEM_GRANTS = {n: (full, qty) for n, (full, qty) in MINTED.items()}

    def create_items(self, world):
        # Nothing is INJECTED. A stacked item enters the pool only by being the vanilla item of a
        # location that actually grants that many copies (core.create_items), so the pool stays
        # count-exact and no seed gains items from this feature existing.
        return []
