"""missable_locations -- keep required progression OUT of checks that can be permanently lost (matt-free).

Parity with the old apworld's `missable` location marker, but greenfield derives the set from its OWN
data (missable_locations.py, generated by gen_data): checks gated behind a LIMITED consumable or a
killable NPC, where a player might spend the resource elsewhere / kill the NPC and never obtain the
check. Currently:
  * Deathroot -- the Gurranq (Bestial Sanctum) reward checks (delivering deathroots; Gurranq killable).
  * Alt-currency -- Dragon Communion incantation purchases and friends (ShopLineupParam costType != 0;
    the old costType == 1 predicate was too narrow and missed Bayle's-Heart rows, fixed 2026-07-24).
  * Questline -- NPC-quest rewards (QUEST_GATED_FLAGS), which since 2026-07-26 also carries the
    CROSS-REGION-gated set: a check sitting in region A that does not EXIST until a questline advances
    in region B. Those were briefly EXCLUDED from the pool instead (`906b3e1`); Alaric reversed it --
    randomised + missable keeps the pickup and still bars the one thing that can strand a seed.
    `test_gf_lot_gates_cross_region` is the keeper: it re-derives that population and fails if any
    member is not tagged here.

Enforcement is fill-side only (no slot_data key; the client is unaffected): each in-play missable
location gets an item-rule forbidding *advancement* (progression) items. Useful/filler are still allowed
-- a missable location may hold a nice-to-have you could miss, but never something required to win, so
the seed stays beatable even if the location is never reached. Default ON (parity + winnability).
"""
from Options import DefaultOnToggle
from ..registry import Feature, register

try:
    from ..missable_locations import MISSABLE_LOCATIONS
except Exception:  # not yet generated
    MISSABLE_LOCATIONS = {}


class ProtectMissableLocations(DefaultOnToggle):
    """Keep required progression out of missable checks (gated behind a limited consumable, a
    killable NPC, or NPC-questline progress: deathroot Gurranq rewards, Dragon-Communion and other
    alt-currency purchases, and quest rewards -- including ones whose prerequisite sits in a
    DIFFERENT region than the item). On by default so the seed stays winnable even if those checks
    are never reached. Turning it off allows progression there and means you are accepting that a
    seed can require a questline step -- expert / guaranteed-access play."""
    display_name = "Protect Missable Locations"


@register
class MissableLocationsFeature(Feature):
    name = "missable_locations"
    OPTIONS = {"protect_missable_locations": ProtectMissableLocations}

    def set_rules(self, world) -> None:
        if not world.options.protect_missable_locations.value or not MISSABLE_LOCATIONS:
            return
        tagged = [loc for loc in world.multiworld.get_locations(world.player)
                  if getattr(loc, "address", None) in MISSABLE_LOCATIONS]
        if not tagged:
            return
        # Fill-safety: forbidding advancement is only feasible if the pool has enough non-advancement
        # items to fill the tagged locations. This is essentially always true (filler alone dwarfs the
        # ~29 missable checks), but guard anyway so a degenerate pool degrades cleanly instead of churning.
        avail = sum(1 for i in world.multiworld.itempool
                    if i.player == world.player and not i.advancement)
        if avail < len(tagged):
            return
        for loc in tagged:
            prev = loc.item_rule
            loc.item_rule = lambda item, p=prev: p(item) and not item.advancement
