"""missable_locations -- keep valuable items OUT of checks that can be permanently lost (matt-free).

Parity with the old apworld's `missable` location marker, but greenfield derives the set from its OWN
data (missable_locations.py, generated by gen_data): checks gated behind a LIMITED consumable or a
killable NPC, where a player might spend the resource elsewhere / kill the NPC and never obtain the
check. Currently:
  * Deathroot -- the Gurranq (Bestial Sanctum) reward checks (delivering deathroots; Gurranq killable).
  * Alt-currency -- Dragon Communion incantation purchases and friends (ShopLineupParam costType != 0;
    the old costType == 1 predicate was too narrow and missed Bayle's-Heart rows, fixed 2026-07-24).
  * Questline -- NPC-quest rewards (QUEST_GATED_FLAGS), which since 2026-07-26 also carries the
    CROSS-REGION-gated set: a check sitting in region A that does not EXIST until a questline advances
    in region B. Those were briefly EXCLUDED from the pool instead (`906b3e1`); Alaric reversed it --
    randomised + missable keeps the pickup and still bars the one thing that can strand a seed.
    `test_gf_lot_gates_cross_region` is the keeper: it re-derives that population and fails if any
    member is not tagged here.

Enforcement is fill-side only (no slot_data key; the client is unaffected). The default bars both
progression and useful items from each in-play missable location, leaving only filler; the narrower
``progression`` mode preserves the old behaviour, and ``off`` accepts the risk explicitly.
"""
from BaseClasses import ItemClassification
from Options import Choice, OptionError
from ..registry import Feature, register

try:
    from ..missable_locations import MISSABLE_LOCATIONS
except Exception:  # not yet generated
    MISSABLE_LOCATIONS = {}


class ProtectMissableLocations(Choice):
    """What may be placed at checks that can be lost behind a limited consumable, a killable NPC,
    or NPC-questline progress. ``progression and useful`` (default) leaves only filler there;
    ``progression`` protects winnability but may lose useful gear; ``off`` permits either and accepts
    that a seed can require a missable questline step. Legacy ``true`` selects the new default and
    ``false`` selects off."""
    display_name = "Protect Missable Locations"
    option_off = 0
    option_progression = 1
    option_progression_and_useful = 2
    default = 2

    @classmethod
    def from_any(cls, data):
        if isinstance(data, bool):
            return cls(cls.default if data else cls.option_off)
        if isinstance(data, str) and data.strip().lower() in (
                "progression+useful", "progression useful"):
            return cls(cls.option_progression_and_useful)
        return super().from_any(data)


@register
class MissableLocationsFeature(Feature):
    name = "missable_locations"
    OPTIONS = {"protect_missable_locations": ProtectMissableLocations}

    def set_rules(self, world) -> None:
        protection = world.options.protect_missable_locations.value
        if protection == ProtectMissableLocations.option_off or not MISSABLE_LOCATIONS:
            return
        tagged = [loc for loc in world.multiworld.get_locations(world.player)
                  if getattr(loc, "address", None) in MISSABLE_LOCATIONS]
        if not tagged:
            return
        barred = ItemClassification.progression
        if protection == ProtectMissableLocations.option_progression_and_useful:
            barred |= ItemClassification.useful

        # Fill-safety is load-bearing: the generated whole-map population currently has 285 tagged
        # checks. Refuse a degenerate pool explicitly instead of silently disabling the promise the
        # player selected. Count the classification bits the item-rule below actually rejects.
        avail = sum(1 for i in world.multiworld.itempool
                    if i.player == world.player and not (i.classification & barred))
        if avail < len(tagged):
            raise OptionError(
                "protect_missable_locations=%s needs %d eligible items for %d missable checks, "
                "but this seed's pool supplies only %d. Choose a less restrictive protection "
                "level or enable item shuffle."
                % (world.options.protect_missable_locations.current_key,
                   len(tagged), len(tagged), avail))
        for loc in tagged:
            prev = loc.item_rule
            loc.item_rule = lambda item, p=prev, mask=barred: (
                p(item) and not (item.classification & mask))


def reserve_filler(world) -> None:
    """Pre-place compatible filler when the default makes missable checks filler-only.

    Archipelago's ordinary remaining fill places useful and filler together. An item-rule alone can
    therefore spend compatible filler elsewhere first and leave useful items opposite filler-only
    checks, producing a late FillError despite ample filler in the pool. `EXCLUDED` is not enough:
    several missable locations carry independent item-rules, so its greedy filler pass can choose
    the wrong filler and strand the last few rows. Match the whole set here before general fill.
    """
    option = world.options.protect_missable_locations
    if option.value != ProtectMissableLocations.option_progression_and_useful:
        return
    locations = [loc for loc in world.multiworld.get_locations(world.player)
                 if loc.item is None and getattr(loc, "address", None) in MISSABLE_LOCATIONS]
    if not locations:
        return
    candidates = [item for item in world.multiworld.itempool
                  if item.player == world.player
                  and not (item.classification
                           & (ItemClassification.progression | ItemClassification.useful))]

    # Seed-derived order avoids publishing one permanent filler allocation while the augmenting
    # matcher, unlike a greedy pass, proves whether a complete assignment exists.
    world.random.shuffle(locations)
    world.random.shuffle(candidates)
    eligible = [[i for i, item in enumerate(candidates) if loc.item_rule(item)]
                for loc in locations]
    order = sorted(range(len(locations)), key=lambda n: len(eligible[n]))
    item_to_location = {}

    def assign(location_index, seen):
        for item_index in eligible[location_index]:
            if item_index in seen:
                continue
            seen.add(item_index)
            previous = item_to_location.get(item_index)
            if previous is None or assign(previous, seen):
                item_to_location[item_index] = location_index
                return True
        return False

    matched = 0
    for location_index in order:
        if not assign(location_index, set()):
            raise OptionError(
                "protect_missable_locations=progression_and_useful needs compatible filler for "
                "%d missable checks, but this seed can match only %d. Choose `progression` or "
                "`off`, enable item shuffle, or keep more regions."
                % (len(locations), matched))
        matched += 1

    chosen = set(item_to_location)
    for item_index, location_index in item_to_location.items():
        location = locations[location_index]
        world.multiworld.push_item(location, candidates[item_index], False)
        location.locked = True
    world.multiworld.itempool[:] = [item for item in world.multiworld.itempool
                                    if all(item is not candidates[i] for i in chosen)]
