"""SPEC-PARITY Phase 5 -- pool builder (item-quality juice, COMPLETE).

Curates the shuffled vanilla item pool by displacing the Rune-fallback tail with high-tier "juice"
(A/S weapons, armor, spells/incantations, ashes of war, and talismans). Tiers come from item_tiers.tsv
(curated PvE tiers, broad-sourced + provenance-clean, mapped S->3 A->2 B->1 C/D/F->0), with the ER
param `rarity` filling any gap the TSV doesn't cover. See gen_data.py -> item_tiers.py
(ITEM_TIERS = {vanilla_item_name: tier 0..3}).

Only meaningful when item_shuffle is ON (there is a shuffled vanilla pool to curate). When item_shuffle
is OFF every check pays a Rune and there is nothing to curate -> the feature is a no-op.

SCOPE. Retired 2026-07-28 along with pool_builder_scope. There is one filler budget now
(features/filler_budget.budget_slots) and juice competes inside it against every other category by
its `curated_filler` weight -- it no longer has a private tail of its own to displace.

Count-neutral by construction. core.create_items builds `pool` (locks + every feature's
create_items()), then computes `slots = total_locations - len(pool)` and fills those slots from the
shuffled vanilla `extras` list -- which core sorts with the Rune fallbacks LAST. So every item this
feature returns from create_items() reduces `slots` by one, trimming one item off the TAIL of that
fill list. While a Rune tail exists (item_shuffle leaves a chunk of checks as Rune fallback) the
trimmed tail is Rune, so juice cleanly DISPLACES Rune.

We bound the juice count to the *true* remaining Rune tail: the count of Rune-fallback checks MINUS
the slots that the other pool contributors already consume (the region Locks, and -- when grace rando
is on -- its scatter items). This keeps juice from spilling past the Rune tail into real vanilla
items, so it upgrades Rune specifically. (Even if the estimate were loose, core's `range(slots)` fill
clamps the total, so the pool stays count-exact and the seed stays winnable; the reserve only sharpens
*which* tail items get displaced.)

Juice items are `useful` (equippables, never progression) -- region Locks stay the sole progression,
so any curated pool is still winnable. No new item names are introduced: every juice item is already
a real-item-pool catalog item registered by core, so world.create_item(name) resolves. The catalog is
augmented at gen time from the tier list itself (gen_data.py) so gear the tier list rates but that
greenfield never DETECTED as a placed vanilla item -- Moonveil, Nagakiba, the Banished Knight /
Bull-Goat / Cleanrot sets, etc. -- is still a registered catalog item and therefore injectable.

INTENSITY (pool_builder_intensity). The juice list is the set of catalog gear whose community PvE
TIER (item_tiers.tsv -> ITEM_TIERS, letters mapped S=3 A=2 B=1 C/D/F=0; ER param `rarity` fills any
gap the tier list doesn't cover) is at or above a FLOOR. The tier list rates all six injected gear
categories -- weapons, armor, spells/incantations, talismans, and ashes of war. The floor is chosen
per-world from this Choice:
  * normal -> tier >= 3 (S only)
  * high   -> tier >= 2 (S + A)
  * max    -> tier >= 1 (S + A + B)  [DEFAULT]
The juice list is computed PER-WORLD from the floor (juice_order_for_floor), sorted best-first
(highest tier, then name) so it stays deterministic and count-neutral, and it is still bounded by
the Rune tail and the juice cap. A higher intensity only widens the CANDIDATE set; the count actually
added is unchanged (still the Rune tail, clamped by the cap) -- so it changes *which* equippables the
Rune tail becomes, not how many.

PORTION (pool_builder_juice_pct). How much of the Rune tail is replaced is configurable: the budget is
`rune_tail * pct // 100`, then still clamped by the juice cap and the catalog size. pct 100 (DEFAULT)
replaces the whole available tail (historical behavior); pct 50 replaces about half and leaves the
rest as Rune; pct 0 replaces none. This changes HOW MANY tail items become juice (unlike intensity,
which changes which ones).
"""
from typing import List

from Options import Choice, Range, Removed, Toggle
from BaseClasses import ItemClassification
from ..registry import Feature, register
from ..data import HUB, LOCATIONS

try:  # generated by gen_data.py (param-derived rarity; matt-free)
    from ..item_tiers import ITEM_TIERS
except Exception:  # not yet generated -> feature degrades to a no-op (no juice available)
    ITEM_TIERS = {}
try:  # per-item gear category (WEAPON/ARMOR/SPELL/TALISMAN/ASHOFWAR) for per-category juice percents
    from ..item_tiers import ITEM_TIER_CATEGORY
except Exception:  # older generated file without categories -> per-category percents degrade to off
    ITEM_TIER_CATEGORY = {}

# pool_builder per-category percent option -> ITEM_TIER_CATEGORY value. "spells" covers sorceries AND
# incantations (the community tier list rates them under one SPELL category).
CATEGORY_OPTION = {
    "pool_builder_pct_weapons": "WEAPON",
    "pool_builder_pct_armor": "ARMOR",
    "pool_builder_pct_spells": "SPELL",
    "pool_builder_pct_talismans": "TALISMAN",
    "pool_builder_pct_ashes_of_war": "ASHOFWAR",
}
try:  # the real-item-pool catalog + per-location assignment (generated by gen_data.py)
    from ..item_ids import ITEM_CATALOG, LOCATION_ITEM
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}

# ER param `rarity`: 0 = trivial/ammo, 1 = common, 2 = rare, 3 = legendary.
# Intensity -> juice rarity FLOOR.
# 🛑 DEFAULT_INTENSITY is the FALLBACK for a world with no resolvable option, and it must agree with
# PoolBuilderIntensity.default and with filler_budget.juice_floor's fallback. It said "high" while
# both of those said max, so an unresolvable option quietly composed from the 536-item catalog
# instead of the 1013-item one -- three fallbacks, two answers, no test.
INTENSITY_FLOOR = {"normal": 3, "high": 2, "max": 1}
DEFAULT_INTENSITY = "max"

# Back-compat module-level aliases (the default 'high' intensity == the historical behavior).
# JUICE_MIN_RARITY / JUICE_ORDER are the historical names, kept for importers; both now track
# DEFAULT_INTENSITY rather than a frozen literal.
JUICE_MIN_RARITY = INTENSITY_FLOOR[DEFAULT_INTENSITY]


def juice_order_for_floor(floor: int) -> List[str]:
    """Catalog equippables with param rarity >= floor, best-first (legendary first, then name).
    Deterministic (pure sort). A higher floor is a SUBSET of a lower floor, so max >= high >= normal
    in length. Empty when tiers/catalog are not yet generated."""
    return sorted(
        (n for n, r in ITEM_TIERS.items() if r >= floor and n in ITEM_CATALOG),
        key=lambda n: (-ITEM_TIERS[n], n),
    )

# Default-intensity juice list (floor = high) for back-compat imports / diagnostics.
JUICE_ORDER = juice_order_for_floor(JUICE_MIN_RARITY)



class PoolBuilder(Removed):
    """Retired 2026-07-28. If you wanted a VANILLA ITEM POOL, set `vanilla_pool: true` -- that is the
    one switch for it. There is no separate pool builder to switch off: gear injection is the `juice`
    weight in `curated_filler`, so `juice: 0` (or omitting it) gets you no gear, and the generator
    warns on a recipe with no juice so it cannot happen silently. But `juice: 0` is NOT a vanilla
    pool -- the guaranteed physick-tear and bell-bearing set is added by a different feature and
    `vanilla_pool` is what stands that down too (#618).

    (This docstring is where a player who typed `pool_builder: false` actually lands, which is why it
    leads with the thing they were probably reaching for rather than with the retirement.)"""


class PoolBuilderIntensity(Choice):
    """How good a piece of gear has to be before it counts as `juice`.

    normal -- legendary only (~149 items).  high -- legendary + rare (~536).  max (default) -- also
    B-tier (~1013).

    A HIGHER FLOOR MEANS LESS GEAR, NOT BETTER GEAR. Each level is a strictly smaller catalog while
    the `juice` weight in curated_filler is unchanged, so raising it asks for the same number of items
    out of a shorter list and the surplus spills to junk. Measured on one seed: max 1518 gear in the
    pool, high 872, normal 230. It buys quality by paying quantity, which is the trade worth exposing.

    (Inert from the filler_budget refactor until 2026-07-28: it had become the constant JUICE_FLOOR
    because the option was frozen and could not move. filler_budget.juice_floor reads it again.)"""
    display_name = "Pool Builder Intensity"
    option_normal = 0
    option_high = 1
    option_max = 2
    # 🛑 default = max, NOT high. While this option was FROZEN, defaults.FROZEN_OPTIONS pinned it at
    # ("max"), so every seed generated at floor 1 -- the class default underneath was stale and
    # unreachable. Unfreezing it without moving the class default would have silently reverted every
    # default seed from the 1013-item catalog to the 536-item one, which is a behaviour change
    # wearing a docs-and-yaml release's clothes. Caught in review; the freeze value IS the default.
    default = 2  # max -> rarity floor 1, matching the frozen value this option shipped with


class PoolBuilderJuiceCap(Removed):
    """Retired 2026-07-28. It capped juice's PRIVATE budget. The filler tail has one
    budget now and the `juice` weight in `curated_filler` IS the cap."""


class PoolBuilderJuicePct(Removed):
    """Retired 2026-07-28. It was juice's share of the tail -- that is the `juice`
    weight in `curated_filler`."""


class PoolBuilderScope(Removed):
    """Retired 2026-07-28. It chose what juice could displace; `filler_budget.budget_slots`
    defines the tail now and juice competes inside it like every other category."""


class _PoolBuilderPctCategory(Range):
    """Base for the per-category gear percents: they steer WHICH gear you get, not how much.

    These are RELATIVE PROPORTIONS, not percentages of anything. features/filler_budget.plan()
    normalises them against each other (`want = (n * pct) // tot`, `tot = sum(pcts)`), where `n` is
    the size of the `juice` allocation the curated_filler recipe already decided. So
    {weapons: 10, armor: 10} and {weapons: 90, armor: 90} are the SAME request and produce identical
    pools -- MEASURED 2026-07-28, byte-identical item pools on one seed.

    ⚠️ THEY CAN ONLY COST YOU GEAR, NEVER ADD ANY. Each category is drawn best-first from a curated
    list with a finite number of items at the rarity floor. Ask a category for more slots than it can
    supply and the shortfall SPILLS TO JUNK (logged). Spells are the smallest catalog (~56 items at
    the floor), so any real spell weighting spills. Measured on one seed:
        all 0 (default)          1518 gear in pool, 0 spilled   <- the MAXIMUM
        weapons 1, armor 1       1432,  88 spilled
        weapons 3, spells 1      1138, 405 spilled  (-25% gear)
        weapons 100             1085, 461 spilled  (-29% gear)
    Leaving every category at 0 fills the whole juice allocation best-first across ALL categories and
    is the setting that yields the most gear.

    🛑 The old text here said each was "the SHARE of the Rune fallback tail" and that ">0 makes the
    global Juice Percent ignored". Both are dead: pool_builder no longer owns a budget (its
    create_items returns []), the budget is the curated_filler `juice` category, and
    pool_builder_juice_pct is not consulted by plan() at all. This docstring is the generation source
    for wizard/options-metadata.json, so a stale claim here becomes a stale claim in the web UI."""
    range_start = 0
    range_end = 100
    default = 0


class PoolBuilderPctWeapons(_PoolBuilderPctCategory):
    """Relative weight for weapon gear within the juice allocation -- steers the MIX, never the
    amount. Drawn best-first by curated tier. 0 (default) across every category = fill best-
    first from all of them, which yields the MOST gear; concentrating spills the shortfall to
    junk."""
    display_name = "Pool Builder % Weapons"


class PoolBuilderPctArmor(_PoolBuilderPctCategory):
    """Relative weight for armor gear within the juice allocation -- steers the MIX, never the
    amount. Drawn best-first by curated tier. 0 (default) across every category = fill best-
    first from all of them, which yields the MOST gear; concentrating spills the shortfall to
    junk."""
    display_name = "Pool Builder % Armor"


class PoolBuilderPctSpells(_PoolBuilderPctCategory):
    """Relative weight for spell gear within the juice allocation -- steers the MIX, never the
    amount. Drawn best-first by curated tier. 0 (default) across every category = fill best-
    first from all of them, which yields the MOST gear; concentrating spills the shortfall to
    junk. Spells have the SMALLEST catalog, so weighting them spills the most."""
    display_name = "Pool Builder % Spells & Incantations"


class PoolBuilderPctTalismans(_PoolBuilderPctCategory):
    """Relative weight for talisman gear within the juice allocation -- steers the MIX, never the
    amount. Drawn best-first by curated tier. 0 (default) across every category = fill best-
    first from all of them, which yields the MOST gear; concentrating spills the shortfall to
    junk."""
    display_name = "Pool Builder % Talismans"


class PoolBuilderPctAshesOfWar(_PoolBuilderPctCategory):
    """Relative weight for Ash of War gear within the juice allocation -- steers the MIX, never the
    amount. Drawn best-first by curated tier. 0 (default) across every category = fill best-
    first from all of them, which yields the MOST gear; concentrating spills the shortfall to
    junk."""
    display_name = "Pool Builder % Ashes of War"


@register
class PoolBuilderFeature(Feature):
    name = "pool_builder"
    ITEMS = {}   # no NEW item names: juice items are catalog items core already registered
    OPTIONS = {
        "pool_builder": PoolBuilder,
        "pool_builder_intensity": PoolBuilderIntensity,
        "pool_builder_scope": PoolBuilderScope,
        "pool_builder_juice_cap": PoolBuilderJuiceCap,
        "pool_builder_juice_pct": PoolBuilderJuicePct,
        "pool_builder_pct_weapons": PoolBuilderPctWeapons,
        "pool_builder_pct_armor": PoolBuilderPctArmor,
        "pool_builder_pct_spells": PoolBuilderPctSpells,
        "pool_builder_pct_talismans": PoolBuilderPctTalismans,
        "pool_builder_pct_ashes_of_war": PoolBuilderPctAshesOfWar,
    }

    # ---- helpers ----------------------------------------------------------------
    def _floor(self, world) -> int:
        """Resolved juice rarity floor for this world from pool_builder_intensity (default high)."""
        opt = getattr(world.options, "pool_builder_intensity", None)
        key = DEFAULT_INTENSITY
        if opt is not None:
            try:
                key = opt.current_key
            except Exception:
                key = DEFAULT_INTENSITY
        return INTENSITY_FLOOR.get(key, INTENSITY_FLOOR[DEFAULT_INTENSITY])

    def _juice_order(self, world) -> List[str]:
        """Per-world juice candidate list (best-first) at this world's intensity floor.
        DLC-only catalog items are dropped when this world has DLC off (see core.gf_dlc_excluded)."""
        _excl = getattr(world, "gf_dlc_excluded", ())
        _order = juice_order_for_floor(self._floor(world))
        return [n for n in _order if n not in _excl] if _excl else _order

    def create_items(self, world):
        # RETIRED. pool_builder no longer owns a private slice of the filler tail: `juice` is a recipe
        # category inside features/filler_budget, which is the single owner of that budget. Owning a
        # separate budget is exactly what let it eat curated_filler's larder and silently starve the
        # upgrade economy. The juice LIST (juice_order_for_floor) lives on and is used by the
        # allocator; only the private budget is gone.
        return []

    def slot_data(self, world):
        """Diagnostics only -- no client reads these (contract.py tags each one as such).

        RE-DERIVED 2026-07-28 rather than removed. Three of these five described the retired private
        juice budget, and the obvious move was to delete them -- but a contract key is not free to
        drop: removing any key moves CONTRACT_HASH, and a moved hash stops every already-released
        client pairing with this apworld. Paying a forced client update to delete a diagnostic
        nothing reads is a bad trade, so the keys stay and report the CURRENT mechanism.

        🛑 REPORT THE MEASUREMENT, DO NOT RE-DERIVE IT. The first version of this recomputed juice
        from the recipe as `min((tail * juice_w) // total_w, catalog)` -- a plausible formula that
        was never checked against a real generation. Measured, it said 536 where `plan()` had placed
        423: it used the UN-filtered catalog on a DLC-off seed and ignored the econ-first two-stage
        split inside `allocate()`. A diagnostic that recomputes its subject will drift from it; this
        one now reads what plan() actually recorded (`world.gf_filler_alloc`, set during
        create_items, before fill_slot_data runs) and the same DLC-filtered order `create_items`
        drew from. See CONTRIBUTING, "the silent wrong answer".
        """
        from .filler_budget import recipe_of

        floor = self._floor(world)
        order = self._juice_order(world)          # DLC-filtered, exactly what create_items used
        alloc = getattr(world, "gf_filler_alloc", None)
        if alloc is None:                         # slot_data before create_items: say so, don't guess
            added = -1
        else:
            added = min(int(alloc.get("juice", 0) or 0), len(order))
        recipe = recipe_of(world) or {}
        total_w = sum(int(v or 0) for v in recipe.values())
        juice_w = int(recipe.get("juice", 0) or 0)
        return {
            "pool_builder": juice_w > 0,
            "pool_builder_juice_added": added,
            "pool_builder_intensity_floor": floor,
            "pool_builder_juice_candidates": len(order),
            "pool_builder_juice_pct": (juice_w * 100) // total_w if total_w else 0,
        }
