"""Pure structural invariants for the Greenfield ER data tables (no Archipelago import).

Same pattern as the existing eldenring test_data_tables.py: importlib-load data.py by path so
this runs in ANY environment in milliseconds (sandbox, CI, Windows) with no AP / Python 3.11
dependency. data.py is regenerated by gen_data.py from region_map.csv + grace anchors; a typo'd
region, a duplicate id, or an id-space shift survives generation and only degrades in-game (the
client keys checks off the flag and the contiguous ap-id space). These guards catch that class
of silent drift up front.

Run:  python -m pytest greenfield/eldenring_gf/tests/test_gf_data.py
  or: python greenfield/eldenring_gf/tests/test_gf_data.py   (unittest fallback)
"""
import importlib.util
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PY = os.path.join(os.path.dirname(HERE), "data.py")

# ap-id space the client contract depends on (see __init__.py _ITEM_BASE=7780000 / gen_data
# BASE_AP=7770000). A shift here silently remaps every check.
BASE_AP = 7770000


def _load_data():
    spec = importlib.util.spec_from_file_location("gf_data_under_test", DATA_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


class GreenfieldDataInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.d = _load_data()
        cls.locs = [t for v in cls.d.LOCATIONS.values() for t in v]

    def test_hub_is_not_a_spoke(self):
        self.assertIsInstance(self.d.HUB, str)
        self.assertTrue(self.d.HUB)
        self.assertNotIn(self.d.HUB, self.d.REGIONS)

    def test_regions_nonempty_unique_sorted(self):
        r = self.d.REGIONS
        self.assertTrue(r, "REGIONS is empty")
        self.assertEqual(len(r), len(set(r)), "duplicate region names")
        self.assertEqual(r, sorted(r), "REGIONS not sorted (gen_data emits sorted spokes)")
        self.assertTrue(all(isinstance(x, str) and x for x in r))

    def test_location_keys_match_hub_plus_regions(self):
        self.assertEqual(set(self.d.LOCATIONS), set([self.d.HUB]) | set(self.d.REGIONS),
                         "LOCATIONS keys must be exactly HUB + every region")

    def test_every_region_has_at_least_one_location(self):
        empty = [r for r in self.d.REGIONS if not self.d.LOCATIONS.get(r)]
        self.assertEqual(empty, [], f"regions with no locations: {empty}")

    def test_core_and_phantom_flags_are_never_checks(self):
        """Regression (2026-07-10): the Flask of Crimson Tears (flag 60000) is the core tutorial
        healing flask whose flag fires in Stormveil's m10_00 EMEVD -- it kept surfacing as a phantom
        Stormveil check. It, and the other known Stormveil-EMEVD phantoms, must never be a randomized
        location (gen_data._MISC_NON_CHECK). Guards against them 'sneaking back in' on a regen."""
        banned = {60000, 60210, 590000}  # Flask of Crimson Tears, Wizened Finger, empty-item check
        present = sorted({fl for (_n, _ap, fl) in self.locs if fl in banned})
        self.assertEqual(present, [], f"phantom/core flags must not be checks: {present}")

    def test_tuple_shape(self):
        for name, ap_id, flag in self.locs:
            self.assertIsInstance(name, str)
            self.assertIsInstance(ap_id, int)
            self.assertIsInstance(flag, int)

    def test_location_names_globally_unique(self):
        names = [n for n, _a, _f in self.locs]
        self.assertEqual(len(names), len(set(names)), "duplicate location names")

    def test_ap_ids_unique_contiguous_from_base(self):
        ids = sorted(a for _n, a, _f in self.locs)
        self.assertEqual(len(ids), len(set(ids)), "duplicate ap ids")
        self.assertEqual(ids[0], BASE_AP, f"ap-id space shifted (min={ids[0]}, expected {BASE_AP})")
        self.assertEqual(ids, list(range(BASE_AP, BASE_AP + len(ids))),
                         "ap ids are not contiguous (gen_data assigns them sequentially)")

    def test_flags_positive(self):
        bad = [(n, f) for n, _a, f in self.locs if f <= 0]
        self.assertEqual(bad, [], f"non-positive event flags: {bad[:5]}")

    def test_enough_locations_for_lock_items(self):
        # fill needs one slot per progression lock item (one per region) plus filler.
        self.assertGreaterEqual(len(self.locs), len(self.d.REGIONS))



class GreenfieldRegionOpenFlags(unittest.TestCase):
    """Phase 0 boot contract: region_open_flags.py (generated by gen_data.py). Skips cleanly if
    not yet generated so a fresh checkout still passes; CI generates it in the gen step."""
    @classmethod
    def setUpClass(cls):
        cls.d = _load_data()
        cls.path = os.path.join(os.path.dirname(DATA_PY), "region_open_flags.py")
        cls.present = os.path.exists(cls.path)
        if cls.present:
            spec = importlib.util.spec_from_file_location("gf_open_flags", cls.path)
            m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
            cls.rof = m

    def test_open_flags_shape(self):
        if not self.present:
            self.skipTest("region_open_flags.py not generated yet (run gen_data.py)")
        regions = set(self.d.REGIONS)
        vals = list(self.rof.REGION_OPEN_FLAGS.values())
        for r, f in self.rof.REGION_OPEN_FLAGS.items():
            self.assertIn(r, regions, f"open-flag region {r!r} not in REGIONS")
            self.assertIsInstance(f, int)
            self.assertGreater(f, 0)
        self.assertEqual(len(vals), len(set(vals)), "duplicate open flags across regions")

    def test_resolved_and_pending_partition_regions(self):
        if not self.present:
            self.skipTest("region_open_flags.py not generated yet (run gen_data.py)")
        resolved = set(self.rof.REGION_OPEN_FLAGS)
        pending = set(self.rof.REGION_OPEN_PENDING)
        self.assertEqual(resolved & pending, set(), "a region is both resolved and pending")
        self.assertEqual(resolved | pending, set(self.d.REGIONS),
                         "every region must be either resolved or pending")



class GreenfieldSpine(unittest.TestCase):
    """Phase 1 num_regions spine (region_spine.py) -- pure (region_spine imports only .data)."""
    @classmethod
    def setUpClass(cls):
        import types
        cls.d = _load_data()
        pkg = types.ModuleType("gf_stub"); pkg.__path__ = [os.path.dirname(DATA_PY)]
        sys.modules["gf_stub"] = pkg; sys.modules["gf_stub.data"] = cls.d
        spec = importlib.util.spec_from_file_location(
            "gf_stub.region_spine", os.path.join(os.path.dirname(DATA_PY), "region_spine.py"))
        cls.rs = importlib.util.module_from_spec(spec); spec.loader.exec_module(cls.rs)

    def test_spine_is_permutation_of_regions(self):
        self.assertEqual(sorted(self.rs.SPINE), sorted(self.d.REGIONS),
                         "SPINE must be a permutation of REGIONS (no missing/extra region)")

    def test_goal_region_valid(self):
        self.assertIn(self.rs.GOAL_REGION, self.d.REGIONS)

    def test_compute_kept_zero_is_all(self):
        import random
        self.assertEqual(len(self.rs.compute_kept(0, "spine", random.Random(1))), len(self.d.REGIONS))
        self.assertEqual(len(self.rs.compute_kept(999, "spine", random.Random(1))), len(self.d.REGIONS))

    def test_compute_kept_spine_prefix_plus_goal(self):
        import random
        k = self.rs.compute_kept(3, "spine", random.Random(1))
        self.assertEqual(k[:3], self.rs.SPINE[:3])
        self.assertIn(self.rs.GOAL_REGION, k)

    def test_compute_kept_rolled_has_goal_unique(self):
        import random
        k = self.rs.compute_kept(5, "rolled", random.Random(7))
        self.assertIn(self.rs.GOAL_REGION, k)
        self.assertEqual(len(k), len(set(k)))
        self.assertTrue(5 <= len(k) <= 6)



class GreenfieldRegistry(unittest.TestCase):
    """Feature-registry aggregation helpers (core.py merges phases through these). Pure: registry.py
    imports only typing, so it loads standalone with synthetic features -- no Archipelago needed."""
    @classmethod
    def setUpClass(cls):
        path = os.path.join(os.path.dirname(DATA_PY), "registry.py")
        spec = importlib.util.spec_from_file_location("gf_registry", path)
        cls.reg = importlib.util.module_from_spec(spec); spec.loader.exec_module(cls.reg)

    def _feat(self, options=None, items=None, sd=None):
        f = self.reg.Feature()
        f.OPTIONS = options or {}
        f.ITEMS = items or {}
        if sd is not None:
            f.slot_data = lambda world, _sd=sd: _sd
        return f

    def test_option_fields_merge_in_order(self):
        core = [("num_regions", object)]
        feats = [self._feat(options={"floor": object}), self._feat(options={"sweep": object})]
        names = [n for n, _ in self.reg.collect_option_fields(core, feats)]
        self.assertEqual(names, ["num_regions", "floor", "sweep"])

    def test_option_field_collision_raises(self):
        core = [("num_regions", object)]
        with self.assertRaises(ValueError):
            self.reg.collect_option_fields(core, [self._feat(options={"num_regions": object})])

    def test_item_ids_allocated_unique_blocks(self):
        base = {"A Lock": 100}
        feats = [self._feat(items={"X": "p"}), self._feat(items={"Y": "p", "Z": "f"})]
        ids = self.reg.allocate_item_ids(base, 200, feats)
        self.assertEqual(ids["A Lock"], 100)
        self.assertEqual(sorted([ids["X"], ids["Y"], ids["Z"]]), [200, 201, 202])
        self.assertEqual(len(set(ids.values())), len(ids))

    def test_item_class_collision_raises(self):
        with self.assertRaises(ValueError):
            self.reg.collect_item_classes({"X": "p"}, [self._feat(items={"X": "f"})])

    def test_slot_data_merge_and_collision(self):
        base = {"world_logic": "region_lock"}
        merged = self.reg.merge_slot_data(base, [self._feat(sd={"dungeonSweeps": {}})], world=None)
        self.assertIn("dungeonSweeps", merged)
        self.assertIn("world_logic", merged)
        with self.assertRaises(ValueError):
            self.reg.merge_slot_data(base, [self._feat(sd={"world_logic": "x"})], world=None)


class GreenfieldAreaLockGeometry(unittest.TestCase):
    """SINGLE SOURCE OF TRUTH guard (replaces the old two-table parity test). The region ->
    play_region geometry (REGION_PLAY_IDS) lives ONLY in features/area_locks.py, which ships the
    fully-resolved kick-watch ranges as slot_data `areaLockFlags`. The client consumes those ranges
    and must NOT keep a mirror table -- a duplicated static geometry in region.rs repeatedly drifted
    from the generator (e.g. the Consecrated Snowfield -> Mountaintops fold). This test makes the
    drift structurally impossible: it FAILS if a REGION_PLAY_IDS mirror is reintroduced client-side.
    Skips cleanly if the client source is not checked out beside the apworld."""

    def test_client_has_no_region_play_ids_mirror(self):
        repo = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
        rs = os.path.join(repo, "from-software-archipelago-clients", "crates",
                          "eldenring-archipelago", "src", "region.rs")
        if not os.path.exists(rs):
            self.skipTest("client region.rs not present")
        with open(rs, encoding="utf-8") as f:
            text = f.read()
        self.assertNotIn(
            "REGION_PLAY_IDS", text,
            "client region.rs must NOT mirror REGION_PLAY_IDS -- the generator (area_locks.py) is the "
            "single source of truth and ships the resolved ranges as areaLockFlags. Consume the "
            "shipped ranges; do not re-add a static table that silently drifts.")


if __name__ == "__main__":
    unittest.main()
