"""Greenfield Elden Ring apworld — MVP (Shattering).

A fresh AP world whose location data is derived from vanilla game files (params + MSB + grace
anchors), independent of the existing apworld. Rules are keyed by REGION only (see
../LESSONS-LEARNED.md) so the name-coupling that blocked the retrofit cannot occur.

Hub-and-spoke: Menu -> Roundtable Hold (free) -> each region, entrance gated by "<Region> Lock".
Goal: collect every region lock. fill_slot_data emits locationFlags {ap_id: [game event flag]}.
"""
from dataclasses import dataclass
from typing import Dict, Any, List

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions

from .data import HUB, REGIONS, LOCATIONS
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags emitted (regions load unlocked)
    REGION_OPEN_FLAGS = {}

GAME = "Elden Ring (Greenfield)"
FILLER = "Rune"
_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS (weapon=0, armor/acc/ash differ)
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_ITEM_BASE = 7780000
item_name_to_id: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
item_name_to_id[FILLER] = _ITEM_BASE + len(REGIONS)

location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_LOCATION_FLAGS: Dict[str, List[int]] = {
    str(ap_id): [flag] for locs in LOCATIONS.values() for (_name, ap_id, flag) in locs
}

# Phase 0 boot contract: received-item grants + region-open on lock receipt.
# Locks are synthetic (grant = set a region-open flag); only real items need a game id.
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}
_REGION_OPEN_FLAGS: Dict[str, int] = {
    f"{r} Lock": REGION_OPEN_FLAGS[r] for r in REGIONS if r in REGION_OPEN_FLAGS
}


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


@dataclass
class GFOptions(PerGameCommonOptions):
    pass


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    def create_item(self, name: str) -> GFItem:
        cls = ItemClassification.progression if name.endswith(" Lock") else ItemClassification.filler
        return GFItem(name, cls, self.item_name_to_id[name], self.player)

    def get_filler_item_name(self) -> str:
        return FILLER

    def create_items(self) -> None:
        pool: List[GFItem] = [self.create_item(f"{r} Lock") for r in REGIONS]
        total_locations = sum(len(v) for v in LOCATIONS.values())
        pool += [self.create_item(FILLER) for _ in range(total_locations - len(pool))]
        self.multiworld.itempool += pool

    def _add_locations(self, region: Region, region_name: str) -> None:
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            region.locations.append(GFLocation(self.player, name, ap_id, region))

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)                    # Roundtable Hold is free
        self._add_locations(hub, HUB)
        for r in REGIONS:
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            lock = f"{r} Lock"
            hub.connect(reg, f"To {r}", rule=lambda state, l=lock: state.has(l, self.player))

    def set_rules(self) -> None:
        locks = [f"{r} Lock" for r in REGIONS]
        self.multiworld.completion_condition[self.player] = \
            lambda state: state.has_all(locks, self.player)

    def fill_slot_data(self) -> Dict[str, Any]:
        return {
            "world_logic": "region_lock",
            "locationFlags": _LOCATION_FLAGS,
            "apIdsToItemIds": _AP_IDS_TO_ITEM_IDS,   # {ap_id: GOODS-packed FullID} filler grant
            "regionOpenFlags": _REGION_OPEN_FLAGS,   # {"<Region> Lock": warp_flag} set on receipt
        }
