"""Greenfield Elden Ring apworld -- Shattering + num_regions (SPEC-PARITY Phase 1).

A fresh AP world whose location data is derived from vanilla game files (params + MSB + grace
anchors), independent of the existing apworld. Rules are keyed by REGION only (see
../LESSONS-LEARNED.md) so the name-coupling that blocked the retrofit cannot occur.

Hub-and-spoke: Menu -> Roundtable Hold (free) -> each KEPT region, entrance gated by "<Region>
Lock". num_regions seals the world down to N regions (spine or rolled); the goal region is always
kept. Goal: collect every kept region's lock. fill_slot_data emits the keyless client contract.
"""
from dataclasses import dataclass
from typing import Dict, Any, List

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions, Choice, Range

from .data import HUB, REGIONS, LOCATIONS
from .region_spine import compute_kept, GOAL_REGION
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags emitted (regions load unlocked)
    REGION_OPEN_FLAGS = {}

GAME = "Elden Ring (Greenfield)"
FILLER = "Rune"
_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS (weapon=0, armor/acc/ash differ)
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_ITEM_BASE = 7780000
item_name_to_id: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
item_name_to_id[FILLER] = _ITEM_BASE + len(REGIONS)

# Full catalogs stay class-level (AP datapackage); per-seed subsets are chosen at gen time.
location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}


class NumRegions(Range):
    """How many regions are in play this seed. 0 = all regions (full Shattering). N > 0 seals the
    rest: only the kept regions get locks, checks, and goal requirement, so you play a shorter run."""
    display_name = "Number of Regions"
    range_start = 0
    range_end = len(REGIONS)
    default = 0


class NumRegionsOrder(Choice):
    """How the kept regions are chosen when num_regions > 0. 'spine' keeps the first N of a fixed
    progression path (Limgrave first); 'rolled' keeps N random regions. The goal region (Leyndell)
    is always kept either way, so the seed is always winnable."""
    display_name = "Region Selection"
    option_spine = 0
    option_rolled = 1
    default = 0


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


@dataclass
class GFOptions(PerGameCommonOptions):
    num_regions: NumRegions
    num_regions_order: NumRegionsOrder


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    # ---- per-seed region scope (num_regions) --------------------------------------
    def generate_early(self) -> None:
        self.gf_kept: List[str] = compute_kept(
            int(self.options.num_regions.value),
            self.options.num_regions_order.current_key,
            self.random,
        )

    def _kept(self) -> List[str]:
        # generate_early always runs first, but guard for direct unit construction.
        return getattr(self, "gf_kept", list(REGIONS))

    # ---- items --------------------------------------------------------------------
    def create_item(self, name: str) -> GFItem:
        cls = ItemClassification.progression if name.endswith(" Lock") else ItemClassification.filler
        return GFItem(name, cls, self.item_name_to_id[name], self.player)

    def get_filler_item_name(self) -> str:
        return FILLER

    def create_items(self) -> None:
        kept = self._kept()
        pool: List[GFItem] = [self.create_item(f"{r} Lock") for r in kept]
        total_locations = len(LOCATIONS.get(HUB, [])) + sum(len(LOCATIONS.get(r, [])) for r in kept)
        pool += [self.create_item(FILLER) for _ in range(total_locations - len(pool))]
        self.multiworld.itempool += pool

    # ---- regions ------------------------------------------------------------------
    def _add_locations(self, region: Region, region_name: str) -> None:
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            region.locations.append(GFLocation(self.player, name, ap_id, region))

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)                    # Roundtable Hold is free
        self._add_locations(hub, HUB)
        for r in self._kept():               # sealed regions are simply not created
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            lock = f"{r} Lock"
            hub.connect(reg, f"To {r}", rule=lambda state, l=lock: state.has(l, self.player))

    def set_rules(self) -> None:
        locks = [f"{r} Lock" for r in self._kept()]
        self.multiworld.completion_condition[self.player] = \
            lambda state: state.has_all(locks, self.player)

    # ---- client contract ----------------------------------------------------------
    def fill_slot_data(self) -> Dict[str, Any]:
        kept = self._kept()
        loc_flags: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            for (_n, ap_id, flag) in LOCATIONS.get(rn, []):
                loc_flags[str(ap_id)] = [flag]
        region_open = {f"{r} Lock": REGION_OPEN_FLAGS[r] for r in kept if r in REGION_OPEN_FLAGS}
        # ordinal sphere tiers over the kept order (refined to real fill spheres in Phase 2/scaling)
        span = max(len(kept) - 1, 1)
        sphere_targets = {r: round(i / span, 4) for i, r in enumerate(kept)}
        return {
            "world_logic": "region_lock",
            "locationFlags": loc_flags,
            "apIdsToItemIds": _AP_IDS_TO_ITEM_IDS,   # {ap_id: GOODS-packed FullID} filler grant
            "regionOpenFlags": region_open,          # {"<Region> Lock": warp_flag} set on receipt
            "region_count": len(kept),               # num_regions marquee -- kept region count
            "completionScalingBasis": 1,             # 1 = sphere (client contract; P2 tunes curve)
            "regionSphereTargets": sphere_targets,
        }
