"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal Woods': [
        (7770837, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Altus Plateau': [
        (7770817, 510040, 'Remembrance of the Omen King'),
        (7770818, 510070, 'Remembrance of Hoarah Loux'),
        (7770827, 510230, 'Elden Remembrance'),
    ],
    'Ancient Ruins of Rauh': [
        (7770838, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Belurat': [
        (7770831, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Enir-Ilim': [
        (7770833, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Eternal Cities': [
        (7770819, 510080, 'Remembrance of the Naturalborn'),
        (7770821, 510110, 'Remembrance of the Lichdragon'),
        (7770830, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Farum Azula': [
        (7770823, 510150, 'Remembrance of the Dragonlord'),
        (7770824, 510160, 'Remembrance of the Black Blade'),
    ],
    'Gravesite Plain': [
        (7770835, 510480, 'Remembrance of Putrescence'),
        (7770843, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Liurnia of the Lakes': [
        (7770008, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    "Miquella's Haligtree": [
        (7770006, 176, "Malenia's Great Rune"),
    ],
    'Mohgwyn Palace': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770829, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770826, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Scadu Altus': [
        (7770836, 510550, 'Remembrance of the Mother of Fingers'),
        (7770839, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770841, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Shadow Keep': [
        (7770834, 510460, 'Remembrance of the Impaler'),
    ],
    'Stormveil Castle': [
        (7770816, 510010, 'Remembrance of the Grafted'),
    ],
}
