"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal Woods': [
        (7770832, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Altus Plateau': [
        (7770814, 510040, 'Remembrance of the Omen King'),
    ],
    'Ancient Ruins of Rauh': [
        (7770833, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Belurat': [
        (7770826, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Enir-Ilim': [
        (7770828, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Eternal Cities': [
        (7770815, 510080, 'Remembrance of the Naturalborn'),
        (7770817, 510110, 'Remembrance of the Lichdragon'),
        (7770825, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Farum Azula': [
        (7770819, 510150, 'Remembrance of the Dragonlord'),
        (7770820, 510160, 'Remembrance of the Black Blade'),
    ],
    'Gravesite Plain': [
        (7770830, 510480, 'Remembrance of Putrescence'),
        (7770838, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Liurnia of the Lakes': [
        (7770008, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    "Miquella's Haligtree": [
        (7770006, 176, "Malenia's Great Rune"),
        (7773949, 15000850, "[Sorcery] Loretta's Mastery"),
    ],
    'Mohgwyn Palace': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770824, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770822, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Scadu Altus': [
        (7770831, 510550, 'Remembrance of the Mother of Fingers'),
    ],
    'Shadow Keep': [
        (7770829, 510460, 'Remembrance of the Impaler'),
        (7770834, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770836, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Stormveil Castle': [
        (7770813, 510010, 'Remembrance of the Grafted'),
    ],
}

_GEN_STAMP = {'inputs_hash': 'sha256:95e1e755c66141b266b6c48e380c834be6be4f83f5abaaf07a12c2fd7215149d', 'generated_utc': '2026-07-11T11:45:15Z', 'host': 'windows', 'module': 'boss_data.py', 'body_sha256': 'sha256:fed799b0e90cf216b365bb614219d6d7cf2b081b12ad8c9ca3bd5ec17d773ef2'}
