"""Greenfield ER world -- CORE (stable).

Owns the parts every seed needs and every feature depends on: region scope (num_regions), the
hub-and-spoke regions, locks, goal, and the base keyless client contract. SPEC-PARITY phases live in
features/ and are aggregated here via registry.py -- adding a phase does NOT edit this file.

Data-derived + matt-free (see ../LESSONS-LEARNED.md): rules keyed by REGION only.
"""
from typing import Any, Dict, List

from dataclasses import make_dataclass

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions, Range, Choice, Toggle, DefaultOnToggle

from .data import HUB, REGIONS, LOCATIONS
from .region_spine import (compute_kept, GOAL_REGION, DLC_REGIONS,  # noqa: F401 (GOAL_REGION used by tests/features)
                           base_regions, dlc_regions)
from . import registry
from . import contract
from . import features as _features  # noqa: F401  -- import triggers feature self-registration
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags (regions load unlocked)
    REGION_OPEN_FLAGS = {}
try:
    from .item_ids import ITEM_CATALOG, LOCATION_ITEM  # generated by gen_data.py (real-item-pool)
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}

GAME = "Elden Ring (Greenfield)"
FILLER = "Rune"
_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_FEATURES = registry.features()

# ---- Great Runes (ending goal) ---------------------------------------------------------------
# The Great Rune items exist in the real-item-pool ONLY when ItemShuffle is on (they are the
# vanilla drops of the Great-Rune boss locations). Identified purely by name from ITEM_CATALOG, so
# this stays data-derived + matt-free. There are 6 in vanilla ER (Godrick's, Radahn's, Morgott's,
# Rykard's, Mohg's, Malenia's). The great_runes ending goal can require up to this many.
GREAT_RUNES: List[str] = sorted(nm for nm in ITEM_CATALOG if nm.endswith("Great Rune"))


# ---- core options ----------------------------------------------------------------------------
class NumRegions(Range):
    """How many regions are in play this seed. 0 = all regions (full Shattering). N > 0 seals the
    rest: only kept regions get locks, checks, and goal requirement, for a shorter run."""
    display_name = "Number of Regions"
    range_start = 0
    range_end = len(REGIONS)
    default = 0


class NumRegionsOrder(Choice):
    """How kept regions are chosen when num_regions > 0. 'spine' keeps the first N of a fixed
    progression path (Limgrave first); 'rolled' keeps N random regions. The goal region (Leyndell)
    is always kept, so the seed is always winnable."""
    display_name = "Region Selection"
    option_spine = 0
    option_rolled = 1
    default = 0


class ItemShuffle(Toggle):
    """off (default): every check pays out a generic Rune. on: each location's own vanilla item
    becomes an AP item and all of them are shuffled among the checks (74% of checks carry a real
    vanilla item; the rest fall back to Rune). Region Locks stay the only progression, so any
    shuffle is winnable."""
    display_name = "Shuffle Vanilla Items"


class EndingCondition(Choice):
    """What the seed's goal requires. 'region_locks' (default): reach the goal region -- hold every
    kept Region Lock (the classic Shattering goal). 'great_runes': ALSO collect Great Runes. Great
    Runes only exist as real items when Shuffle Vanilla Items is on, so with shuffle off this falls
    back to the region_locks goal. The requirement is auto-clamped to the number of Great Runes
    actually reachable this seed, so it can never make a seed unbeatable."""
    display_name = "Ending Condition"
    option_region_locks = 0
    option_great_runes = 1
    default = 0


class GreatRunesRequired(Range):
    """How many Great Runes the 'great_runes' ending needs. Ignored unless Ending Condition is
    great_runes (and Shuffle Vanilla Items is on). The effective requirement is clamped down to the
    count of Great Runes reachable in the kept regions, so sealing away Great-Rune regions
    (num_regions) lowers -- never breaks -- the goal."""
    display_name = "Great Runes Required"
    range_start = 1
    range_end = 7
    default = 2


class EnableDLC(DefaultOnToggle):
    """Whether the Shadow of the Erdtree DLC regions (Land of Shadow, Belurat, Scadu Altus, Shadow
    Keep, Jagged Peak, Abyssal Woods) are in play. on (default): DLC regions are eligible and can be
    kept by num_regions alongside base-game regions. off: DLC regions are excluded from the region
    pool entirely -- num_regions draws only from base-game regions, and every DLC lock/check/grace is
    sealed like any non-kept region. Ignored (forced on) when DLC Only is on."""
    display_name = "Enable DLC"


class DLCOnly(Toggle):
    """off (default): normal -- base game (and DLC when Enable DLC is on) are all in play. on: ONLY
    the Shadow of the Erdtree DLC regions are eligible; every base-game region is sealed. Implies
    Enable DLC (turning this on forces the DLC in even if Enable DLC is off). The goal becomes "hold
    every kept DLC lock"; the base-game goal region (Leyndell) is sealed but is not required, so the
    seed stays winnable. Land of Shadow carries all six Great Runes, so the great_runes ending still
    works under DLC Only."""
    display_name = "DLC Only"


_CORE_OPTION_FIELDS = [("num_regions", NumRegions), ("num_regions_order", NumRegionsOrder),
                       ("item_shuffle", ItemShuffle), ("ending_condition", EndingCondition),
                       ("great_runes_required", GreatRunesRequired),
                       ("enable_dlc", EnableDLC), ("dlc_only", DLCOnly)]
GFOptions = make_dataclass(
    "GFOptions",
    registry.collect_option_fields(_CORE_OPTION_FIELDS, _FEATURES),
    bases=(PerGameCommonOptions,),
)
GFOptions.__module__ = __name__


# ---- item + location catalogs (core + feature items) ----------------------------------------
_ITEM_BASE = 7780000
_core_item_ids: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
_core_item_ids[FILLER] = _ITEM_BASE + len(REGIONS)
item_name_to_id: Dict[str, int] = registry.allocate_item_ids(
    _core_item_ids, _ITEM_BASE + len(REGIONS) + 1, _FEATURES)

_core_item_class: Dict[str, Any] = {f"{r} Lock": ItemClassification.progression for r in REGIONS}
_core_item_class[FILLER] = ItemClassification.filler
_item_class: Dict[str, Any] = registry.collect_item_classes(_core_item_class, _FEATURES)

location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}

# real-item-pool: register each distinct vanilla item as an AP item (id -> game FullID). GOODS are
# filler; weapons/armor/accessories/ashes are useful. Locks remain the only progression.
_REAL_ITEM_BASE = 7790000
def _classify_full(full: int) -> ItemClassification:
    return ItemClassification.filler if (full & 0xF0000000) == _GOODS_NIBBLE else ItemClassification.useful
for _idx, _nm in enumerate(sorted(ITEM_CATALOG)):
    if _nm not in item_name_to_id:
        _aid = _REAL_ITEM_BASE + _idx
        item_name_to_id[_nm] = _aid
        _AP_IDS_TO_ITEM_IDS[str(_aid)] = ITEM_CATALOG[_nm]
        _item_class[_nm] = _classify_full(ITEM_CATALOG[_nm])


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    # ---- region scope (num_regions) -------------------------------------------
    def _eligible_regions(self) -> List[str]:
        """The region pool num_regions draws from this seed, after the DLC toggles.
        dlc_only -> DLC regions only (implies DLC enabled). enable_dlc off -> base game only.
        both default -> everything. Never empty: the fallbacks below guarantee a non-empty pool so
        compute_kept always has something to keep and the seed stays winnable."""
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        if dlc_only:
            pool = dlc_regions()          # DLC only (implies enabled)
        elif enable_dlc:
            pool = list(REGIONS)          # base + DLC (default)
        else:
            pool = base_regions()         # base only
        return pool if pool else list(REGIONS)  # defensive: never seal every region

    def generate_early(self) -> None:
        self.gf_eligible: List[str] = self._eligible_regions()
        self.gf_kept: List[str] = compute_kept(
            int(self.options.num_regions.value),
            self.options.num_regions_order.current_key,
            self.random,
            self.gf_eligible,
        )
        # Resolve the Great-Rune goal now (once), so create_item/set_rules/slot_data agree.
        self.gf_required_runes: List[str] = self._resolve_required_runes()
        for f in _FEATURES:
            f.generate_early(self)

    def _kept(self) -> List[str]:
        return getattr(self, "gf_kept", list(REGIONS))

    # ---- ending goal (great runes) --------------------------------------------
    def _shuffle_on(self) -> bool:
        return bool(getattr(self.options, "item_shuffle", None) and self.options.item_shuffle.value)

    def _available_runes(self) -> List[str]:
        """Great Rune item NAMES that actually appear on a kept region's locations this seed --
        i.e. the ones that will be in the pool. Only meaningful when item_shuffle is on."""
        if not self._shuffle_on() or not GREAT_RUNES:
            return []
        seen: Dict[str, None] = {}
        for rn in self._kept():
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if nm in GREAT_RUNES and nm not in seen:
                    seen[nm] = None
        return list(seen)

    def _resolve_required_runes(self) -> List[str]:
        """The concrete set of Great Rune names completion will require. Empty unless the goal is
        great_runes AND shuffle is on. Clamped to what's reachable (available), so the requirement
        can never exceed the runes in the pool -> never makes the seed unbeatable. When regions are
        sealed so that fewer than N runes are available, the requirement simply shrinks (to 0 if no
        Great-Rune region survives, collapsing the goal to region_locks-only)."""
        ec = getattr(self.options, "ending_condition", None)
        if ec is None or ec.current_key != "great_runes":
            return []
        want = int(getattr(self.options, "great_runes_required").value)
        avail = self._available_runes()
        want = min(max(want, 0), len(avail))
        # Deterministic pick of `want` reachable runes (sorted for reproducibility).
        return sorted(avail)[:want]

    def _required_runes(self) -> List[str]:
        return getattr(self, "gf_required_runes", [])

    # ---- items ----------------------------------------------------------------
    def _class_for(self, name: str) -> ItemClassification:
        """Classification for an item, upgrading a required Great Rune to progression so AP fill
        guarantees it lands in a reachable location (Great Runes are GOODS -> filler by default)."""
        base = _item_class.get(name, ItemClassification.filler)
        if name in self._required_runes():
            return ItemClassification.progression
        return base

    def create_item(self, name: str) -> GFItem:
        return GFItem(name, self._class_for(name),
                      self.item_name_to_id[name], self.player)

    def get_filler_item_name(self) -> str:
        return FILLER

    def create_items(self) -> None:
        kept = self._kept()
        pool: List[Item] = [self.create_item(f"{r} Lock") for r in kept]
        for f in _FEATURES:
            pool += f.create_items(self)
        total = len(LOCATIONS.get(HUB, [])) + sum(len(LOCATIONS.get(r, [])) for r in kept)
        slots = total - len(pool)
        shuffle = self._shuffle_on()
        required = set(self._required_runes())
        extras: List[str] = []
        if shuffle:
            for rn in [HUB] + kept:
                for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                    nm = LOCATION_ITEM.get(ap_id)
                    extras.append(nm if nm and nm in item_name_to_id else FILLER)
            # keep real items first; among reals, keep required Great Runes ahead of everything so
            # the over-provision trim (below) can never drop a rune the goal needs.
            extras.sort(key=lambda x: (x == FILLER, x not in required))
        for k in range(slots):
            pool.append(self.create_item(extras[k] if k < len(extras) else FILLER))
        self.multiworld.itempool += pool

    # ---- regions --------------------------------------------------------------
    def _add_locations(self, region: Region, region_name: str) -> None:
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            region.locations.append(GFLocation(self.player, name, ap_id, region))

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)  # Roundtable Hold is free
        self._add_locations(hub, HUB)
        for r in self._kept():  # sealed regions are simply not created
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            lock = f"{r} Lock"
            hub.connect(reg, f"To {r}", rule=lambda state, l=lock: state.has(l, self.player))
        for f in _FEATURES:
            f.create_regions(self)

    def set_rules(self) -> None:
        locks = [f"{r} Lock" for r in self._kept()]
        required = self._required_runes()
        if required:
            need = len(required)
            self.multiworld.completion_condition[self.player] = \
                lambda state, lk=locks, rn=required, n=need: (
                    state.has_all(lk, self.player)
                    and sum(1 for gr in rn if state.has(gr, self.player)) >= n)
        else:
            self.multiworld.completion_condition[self.player] = \
                lambda state, lk=locks: state.has_all(lk, self.player)
        for f in _FEATURES:
            f.set_rules(self)

    # ---- client contract ------------------------------------------------------
    def _base_slot_data(self) -> Dict[str, Any]:
        kept = self._kept()
        loc_flags: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            for (_n, ap_id, flag) in LOCATIONS.get(rn, []):
                # scalar {ap_id: flag} -- the client reads locationFlags via i64_to_u32_map (scalar),
                # NOT a list; a [flag] value parsed to EMPTY -> no detection table -> checks never
                # registered and goal was checked-fallback (2026-07-06). One flag per location.
                loc_flags[str(ap_id)] = flag
        region_open = {f"{r} Lock": REGION_OPEN_FLAGS[r] for r in kept if r in REGION_OPEN_FLAGS}
        span = max(len(kept) - 1, 1)
        sphere_targets = {r: round(i / span, 4) for i, r in enumerate(kept)}
        required = self._required_runes()
        return {
            contract.WORLD_LOGIC: "region_lock",
            contract.LOCATION_FLAGS: loc_flags,
            contract.AP_IDS_TO_ITEM_IDS: _AP_IDS_TO_ITEM_IDS,
            contract.REGION_OPEN_FLAGS: region_open,
            "region_count": len(kept),
            "completionScalingBasis": 1,
            contract.REGION_SPHERE_TARGETS: sphere_targets,
            # ending goal contract (client shows/validates the goal). great_runes_required is the
            # EFFECTIVE (clamped) count; ending_condition reflects the resolved goal, which is
            # region_locks whenever no Great Rune is actually required this seed.
            "ending_condition": "great_runes" if required else "region_locks",
            "great_runes_required": len(required),
            "great_rune_items": list(required),
        }

    def fill_slot_data(self) -> Dict[str, Any]:
        sd = registry.merge_slot_data(self._base_slot_data(), _FEATURES, self)
        contract.validate_slot_data(sd, strict=True)
        return sd

    def generate_output(self, output_directory: str) -> None:
        # Post-fill CHECK BREAKDOWN, printed to the generate log so a seed can be judged on
        # progression shape + filler locality at a glance (not just "it genned"): how each of this
        # slot's checks was filled -- own progression / own useful / own (local) filler / another
        # world's item (foreign), split useful vs filler. Solo seeds show foreign = 0.
        p = self.player
        prog = useful = local_filler = foreign_filler = foreign_useful = 0
        for loc in self.multiworld.get_locations(p):
            it = loc.item
            if it is None:
                continue
            important = bool(it.advancement) or bool(it.classification & ItemClassification.useful)
            if it.player == p:
                if it.advancement:
                    prog += 1
                elif it.classification & ItemClassification.useful:
                    useful += 1
                else:
                    local_filler += 1
            elif important:
                foreign_useful += 1
            else:
                foreign_filler += 1
        total = prog + useful + local_filler + foreign_filler + foreign_useful
        print(
            f"[greenfield] {self.multiworld.get_player_name(p)}: {total} checks | "
            f"progression {prog} | useful {useful} | local filler {local_filler} | "
            f"foreign filler {foreign_filler} | foreign useful {foreign_useful}"
        )
