"""Greenfield ER world -- CORE (stable).

Owns the parts every seed needs and every feature depends on: region scope (num_regions), the
hub-and-spoke regions, locks, goal, and the base keyless client contract. SPEC-PARITY phases live in
features/ and are aggregated here via registry.py -- adding a phase does NOT edit this file.

Data-derived + matt-free (see ../LESSONS-LEARNED.md): rules keyed by REGION only.
"""
from typing import Any, Dict, List

from dataclasses import make_dataclass

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions, Range, Choice

from .data import HUB, REGIONS, LOCATIONS
from .region_spine import compute_kept, GOAL_REGION  # noqa: F401 (GOAL_REGION used by tests/features)
from . import registry
from . import features as _features  # noqa: F401  -- import triggers feature self-registration
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags (regions load unlocked)
    REGION_OPEN_FLAGS = {}

GAME = "Elden Ring (Greenfield)"
FILLER = "Rune"
_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_FEATURES = registry.features()


# ---- core options ----------------------------------------------------------------------------
class NumRegions(Range):
    """How many regions are in play this seed. 0 = all regions (full Shattering). N > 0 seals the
    rest: only kept regions get locks, checks, and goal requirement, for a shorter run."""
    display_name = "Number of Regions"
    range_start = 0
    range_end = len(REGIONS)
    default = 0


class NumRegionsOrder(Choice):
    """How kept regions are chosen when num_regions > 0. 'spine' keeps the first N of a fixed
    progression path (Limgrave first); 'rolled' keeps N random regions. The goal region (Leyndell)
    is always kept, so the seed is always winnable."""
    display_name = "Region Selection"
    option_spine = 0
    option_rolled = 1
    default = 0


_CORE_OPTION_FIELDS = [("num_regions", NumRegions), ("num_regions_order", NumRegionsOrder)]
GFOptions = make_dataclass(
    "GFOptions",
    registry.collect_option_fields(_CORE_OPTION_FIELDS, _FEATURES),
    bases=(PerGameCommonOptions,),
)
GFOptions.__module__ = __name__


# ---- item + location catalogs (core + feature items) ----------------------------------------
_ITEM_BASE = 7780000
_core_item_ids: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
_core_item_ids[FILLER] = _ITEM_BASE + len(REGIONS)
item_name_to_id: Dict[str, int] = registry.allocate_item_ids(
    _core_item_ids, _ITEM_BASE + len(REGIONS) + 1, _FEATURES)

_core_item_class: Dict[str, Any] = {f"{r} Lock": ItemClassification.progression for r in REGIONS}
_core_item_class[FILLER] = ItemClassification.filler
_item_class: Dict[str, Any] = registry.collect_item_classes(_core_item_class, _FEATURES)

location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    # ---- region scope (num_regions) -------------------------------------------
    def generate_early(self) -> None:
        self.gf_kept: List[str] = compute_kept(
            int(self.options.num_regions.value),
            self.options.num_regions_order.current_key,
            self.random,
        )
        for f in _FEATURES:
            f.generate_early(self)

    def _kept(self) -> List[str]:
        return getattr(self, "gf_kept", list(REGIONS))

    # ---- items ----------------------------------------------------------------
    def create_item(self, name: str) -> GFItem:
        return GFItem(name, _item_class.get(name, ItemClassification.filler),
                      self.item_name_to_id[name], self.player)

    def get_filler_item_name(self) -> str:
        return FILLER

    def create_items(self) -> None:
        kept = self._kept()
        pool: List[Item] = [self.create_item(f"{r} Lock") for r in kept]
        for f in _FEATURES:
            pool += f.create_items(self)
        total = len(LOCATIONS.get(HUB, [])) + sum(len(LOCATIONS.get(r, [])) for r in kept)
        pool += [self.create_item(FILLER) for _ in range(total - len(pool))]
        self.multiworld.itempool += pool

    # ---- regions --------------------------------------------------------------
    def _add_locations(self, region: Region, region_name: str) -> None:
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            region.locations.append(GFLocation(self.player, name, ap_id, region))

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)  # Roundtable Hold is free
        self._add_locations(hub, HUB)
        for r in self._kept():  # sealed regions are simply not created
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            lock = f"{r} Lock"
            hub.connect(reg, f"To {r}", rule=lambda state, l=lock: state.has(l, self.player))
        for f in _FEATURES:
            f.create_regions(self)

    def set_rules(self) -> None:
        locks = [f"{r} Lock" for r in self._kept()]
        self.multiworld.completion_condition[self.player] = \
            lambda state: state.has_all(locks, self.player)
        for f in _FEATURES:
            f.set_rules(self)

    # ---- client contract ------------------------------------------------------
    def _base_slot_data(self) -> Dict[str, Any]:
        kept = self._kept()
        loc_flags: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            for (_n, ap_id, flag) in LOCATIONS.get(rn, []):
                loc_flags[str(ap_id)] = [flag]
        region_open = {f"{r} Lock": REGION_OPEN_FLAGS[r] for r in kept if r in REGION_OPEN_FLAGS}
        span = max(len(kept) - 1, 1)
        sphere_targets = {r: round(i / span, 4) for i, r in enumerate(kept)}
        return {
            "world_logic": "region_lock",
            "locationFlags": loc_flags,
            "apIdsToItemIds": _AP_IDS_TO_ITEM_IDS,
            "regionOpenFlags": region_open,
            "region_count": len(kept),
            "completionScalingBasis": 1,
            "regionSphereTargets": sphere_targets,
        }

    def fill_slot_data(self) -> Dict[str, Any]:
        return registry.merge_slot_data(self._base_slot_data(), _FEATURES, self)
