"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot
contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in
the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""
REGION_OPEN_FLAGS = {
    'Abyssal Woods': 76860,
    'Altus Plateau': 73204,
    'Ancient Ruins of Rauh': 74001,
    'Belurat': 72001,
    'Caelid': 73207,
    'Enir-Ilim': 72012,
    'Eternal Cities': 71211,
    'Farum Azula': 71303,
    'Gravesite Plain': 76800,
    'Jagged Peak': 76850,
    'Limgrave': 73100,
    'Liurnia of the Lakes': 73202,
    "Miquella's Haligtree": 71501,
    'Mohgwyn Palace': 71251,
    'Mountaintops of the Giants': 73017,
    'Mt. Gelmir': 76350,
    'Scadu Altus': 76900,
    'Shadow Keep': 72102,
    'Stormveil Castle': 71002,
    'Weeping Peninsula': 73102,
}

REGION_OPEN_PENDING = [
]
