"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot
contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in
the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""
REGION_OPEN_FLAGS = {
    'Abyssal Woods': 72801,
    'Altus Plateau': 73204,
    'Ancient Ruins of Rauh': 76803,
    'Belurat': 72001,
    'Caelid': 73207,
    'Enir-Ilim': 72012,
    'Eternal Cities': 71211,
    'Farum Azula': 71303,
    'Gravesite Plain': 76800,
    'Jagged Peak': 76850,
    'Limgrave': 73100,
    'Liurnia of the Lakes': 73202,
    "Miquella's Haligtree": 71501,
    'Mohgwyn Palace': 71251,
    'Mountaintops of the Giants': 73017,
    'Mt. Gelmir': 76350,
    'Scadu Altus': 76834,
    'Shadow Keep': 72102,
    'Stormveil Castle': 71002,
    'Weeping Peninsula': 73102,
}

REGION_OPEN_PENDING = [
]

_GEN_STAMP = {'inputs_hash': 'sha256:46cbefcfda4a1f931ddfc44e375e59a8b15e98410885070b7c8ea1553f2e7142', 'generated_utc': '2026-07-11T10:16:57Z', 'host': 'windows', 'module': 'region_open_flags.py', 'body_sha256': 'sha256:998b858750faddf03b004b8e290681b15ee782e6882f02fbdbae05f73ebec5f3'}
