"""SPEC-PARITY Phase 5 -- pool builder (item-quality juice, COMPLETE).

Curates the shuffled vanilla item pool by displacing the Rune-fallback tail with high-tier "juice"
(A/S weapons, armor, spells/incantations, ashes of war, and talismans). Tiers come from item_tiers.tsv
(curated PvE tiers, broad-sourced + provenance-clean, mapped S->3 A->2 B->1 C/D/F->0), with the ER
param `rarity` filling any gap the TSV doesn't cover. See gen_data.py -> item_tiers.py
(ITEM_TIERS = {vanilla_item_name: tier 0..3}).

Only meaningful when item_shuffle is ON (there is a shuffled vanilla pool to curate). When item_shuffle
is OFF every check pays a Rune and there is nothing to curate -> the feature is a no-op.

SCOPE (pool_builder_scope). By default juice displaces ONLY the Rune-fallback tail. Set to 'all_filler'
and it may ALSO displace junk-consumable vanilla filler (throwables/pots/greases/...), economy-safe:
the tuned economy (runes, smithing/somber stones, seeds/tears/glovewort/great runes), funny junk, real
gear, and progression (e.g. promoted key gates) are never touched. This widens the juice ceiling far
past the small Rune tail; the drop order lives in core.create_items' extras-sort, which ranks exactly
the same displaceable_filler set to the tail so the budget here and the drop there cannot drift.

Count-neutral by construction. core.create_items builds `pool` (locks + every feature's
create_items()), then computes `slots = total_locations - len(pool)` and fills those slots from the
shuffled vanilla `extras` list -- which core sorts with the Rune fallbacks LAST. So every item this
feature returns from create_items() reduces `slots` by one, trimming one item off the TAIL of that
fill list. While a Rune tail exists (item_shuffle leaves a chunk of checks as Rune fallback) the
trimmed tail is Rune, so juice cleanly DISPLACES Rune.

We bound the juice count to the *true* remaining Rune tail: the count of Rune-fallback checks MINUS
the slots that the other pool contributors already consume (the region Locks, and -- when grace rando
is on -- its scatter items). This keeps juice from spilling past the Rune tail into real vanilla
items, so it upgrades Rune specifically. (Even if the estimate were loose, core's `range(slots)` fill
clamps the total, so the pool stays count-exact and the seed stays winnable; the reserve only sharpens
*which* tail items get displaced.)

Juice items are `useful` (equippables, never progression) -- region Locks stay the sole progression,
so any curated pool is still winnable. No new item names are introduced: every juice item is already
a real-item-pool catalog item registered by core, so world.create_item(name) resolves. The catalog is
augmented at gen time from the tier list itself (gen_data.py) so gear the tier list rates but that
greenfield never DETECTED as a placed vanilla item -- Moonveil, Nagakiba, the Banished Knight /
Bull-Goat / Cleanrot sets, etc. -- is still a registered catalog item and therefore injectable.

INTENSITY (pool_builder_intensity). The juice list is the set of catalog gear whose community PvE
TIER (item_tiers.tsv -> ITEM_TIERS, letters mapped S=3 A=2 B=1 C/D/F=0; ER param `rarity` fills any
gap the tier list doesn't cover) is at or above a FLOOR. The tier list rates all six injected gear
categories -- weapons, armor, spells/incantations, talismans, and ashes of war. The floor is chosen
per-world from this Choice:
  * normal -> tier >= 3 (S only)
  * high   -> tier >= 2 (S + A)  [DEFAULT -- the historical behavior]
  * max    -> tier >= 1 (S + A + B)
The juice list is computed PER-WORLD from the floor (juice_order_for_floor), sorted best-first
(highest tier, then name) so it stays deterministic and count-neutral, and it is still bounded by
the Rune tail and the juice cap. A higher intensity only widens the CANDIDATE set; the count actually
added is unchanged (still the Rune tail, clamped by the cap) -- so it changes *which* equippables the
Rune tail becomes, not how many.

PORTION (pool_builder_juice_pct). How much of the Rune tail is replaced is configurable: the budget is
`rune_tail * pct // 100`, then still clamped by the juice cap and the catalog size. pct 100 (DEFAULT)
replaces the whole available tail (historical behavior); pct 50 replaces about half and leaves the
rest as Rune; pct 0 replaces none. This changes HOW MANY tail items become juice (unlike intensity,
which changes which ones).
"""
from typing import List

from Options import Toggle, Range, Choice
from BaseClasses import ItemClassification
from ..registry import Feature, register
from ..data import HUB, LOCATIONS

try:  # generated by gen_data.py (param-derived rarity; matt-free)
    from ..item_tiers import ITEM_TIERS
except Exception:  # not yet generated -> feature degrades to a no-op (no juice available)
    ITEM_TIERS = {}
try:  # per-item gear category (WEAPON/ARMOR/SPELL/TALISMAN/ASHOFWAR) for per-category juice percents
    from ..item_tiers import ITEM_TIER_CATEGORY
except Exception:  # older generated file without categories -> per-category percents degrade to off
    ITEM_TIER_CATEGORY = {}

# pool_builder per-category percent option -> ITEM_TIER_CATEGORY value. "spells" covers sorceries AND
# incantations (the community tier list rates them under one SPELL category).
CATEGORY_OPTION = {
    "pool_builder_pct_weapons": "WEAPON",
    "pool_builder_pct_armor": "ARMOR",
    "pool_builder_pct_spells": "SPELL",
    "pool_builder_pct_talismans": "TALISMAN",
    "pool_builder_pct_ashes_of_war": "ASHOFWAR",
}
try:  # the real-item-pool catalog + per-location assignment (generated by gen_data.py)
    from ..item_ids import ITEM_CATALOG, LOCATION_ITEM
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}

# ER param `rarity`: 0 = trivial/ammo, 1 = common, 2 = rare, 3 = legendary.
# Intensity -> juice rarity FLOOR. high == the historical JUICE_MIN_RARITY of 2 (DEFAULT).
INTENSITY_FLOOR = {"normal": 3, "high": 2, "max": 1}
DEFAULT_INTENSITY = "high"

# Back-compat module-level aliases (the default 'high' intensity == the historical behavior).
# JUICE_MIN_RARITY was the old fixed floor (2 == high); JUICE_ORDER was the default juice list.
JUICE_MIN_RARITY = INTENSITY_FLOOR[DEFAULT_INTENSITY]


def juice_order_for_floor(floor: int) -> List[str]:
    """Catalog equippables with param rarity >= floor, best-first (legendary first, then name).
    Deterministic (pure sort). A higher floor is a SUBSET of a lower floor, so max >= high >= normal
    in length. Empty when tiers/catalog are not yet generated."""
    return sorted(
        (n for n, r in ITEM_TIERS.items() if r >= floor and n in ITEM_CATALOG),
        key=lambda n: (-ITEM_TIERS[n], n),
    )

# Default-intensity juice list (floor = high) for back-compat imports / diagnostics.
JUICE_ORDER = juice_order_for_floor(JUICE_MIN_RARITY)



class PoolBuilder(Toggle):
    """Off (default): the shuffled vanilla pool is used as-is (with a long tail of Rune fillers when
    item_shuffle is on). On: curate the pool -- replace the Rune tail with high-tier juice (rare +
    legendary weapons, armor, and talismans), count-neutral. Has no effect unless Shuffle Vanilla
    Items is also on (there is no vanilla pool to curate otherwise)."""
    display_name = "Pool Builder"


class PoolBuilderIntensity(Choice):
    """How wide a net Pool Builder casts when picking juice (the equippables it turns the Rune tail
    into). Sets the minimum param rarity a vanilla equippable needs to qualify:
    'normal' = legendary only (rarity 3); 'high' = rare + legendary (rarity 2, the DEFAULT and
    historical behavior); 'max' = also include common/B-tier equippables (rarity 1). Only the
    candidate SET changes -- the count added stays the Rune tail (clamped by the juice cap), so a
    higher intensity changes *which* equippables you get, not how many. Ignored unless Pool Builder
    and Shuffle Vanilla Items are both on."""
    display_name = "Pool Builder Intensity"
    option_normal = 0
    option_high = 1
    option_max = 2
    default = 1  # high -> rarity floor 2 == the original JUICE_MIN_RARITY (no change)


class PoolBuilderJuiceCap(Range):
    """Maximum number of high-tier juice items Pool Builder adds (when on). Bounded so juice only
    ever displaces the Rune fallback tail, never real vanilla items. 0 lets Pool Builder auto-size
    to the whole available Rune tail (still clamped to the number of juice items in the catalog)."""
    display_name = "Pool Builder Juice Cap"
    range_start = 0
    range_end = 400
    default = 120


class PoolBuilderJuicePct(Range):
    """What SHARE of the Rune fallback tail Pool Builder replaces with juice, as a percent.
    100 (DEFAULT) = replace the whole available tail (historical behavior); 50 = replace about half
    (leaving the rest as Rune fillers); 0 = replace none (Pool Builder becomes a no-op even when on).
    Applied to the *true* remaining Rune tail (fallback checks minus what region Locks / grace scatter
    already consume), then still clamped by the Juice Cap and the number of juice items in the
    catalog. Ignored unless Pool Builder and Shuffle Vanilla Items are both on."""
    display_name = "Pool Builder Juice Percent"
    range_start = 0
    range_end = 100
    default = 100


class PoolBuilderScope(Choice):
    """What Pool Builder juice is allowed to DISPLACE.
    'rune_tail' (DEFAULT): only the Rune fallback tail -- checks with no real vanilla item (historical
    behavior). The juice ceiling is the size of that tail.
    'all_filler': ALSO the junk-consumable vanilla filler in the shuffled pool -- throwables, pots,
    greases, boluses, and the like. This is economy-SAFE: the tuned economy (Golden/Lord's/Hero's/
    Numen's Runes, Smithing/Somber stones, Golden Seed, Sacred Tear, Glovewort, Great Rune), the funny
    junk, all real gear, and anything the seed treats as progression (e.g. the Academy Glintstone Key
    gate) are never displaced. Vastly raises the juice ceiling, so it is mostly meaningful with a
    raised or 0 (auto) Juice Cap; an aggressive setting can thin the stone/rune economy that
    stone_injection / stone_ramp draw from. Juice Percent and the per-category percents then read as a
    share of this wider juice-eligible set. Ignored unless Pool Builder and Shuffle Vanilla Items are
    both on."""
    display_name = "Pool Builder Scope"
    option_rune_tail = 0
    option_all_filler = 1
    default = 0


class _PoolBuilderPctCategory(Range):
    """Base for the per-category juice percents. Each is the SHARE of the Rune fallback tail Pool
    Builder fills with THIS gear category's juice, as a percent, drawn best-first (highest tier first)
    within the category and still floored by Pool Builder Intensity (S / S+A / S+A+B). Default 0.

    These are OPT-IN and OVERRIDE the single global Juice Percent: while every per-category percent is
    0 (the default), Pool Builder behaves exactly as before -- Juice Percent of the tail, filled
    best-first across ALL categories combined. As soon as ANY per-category percent is >0, the global
    Juice Percent is ignored and the tail is filled per category by these percents instead (a category
    left at 0 then contributes no juice). The percents need not sum to 100 -- the total is still
    clamped to the available Rune tail and the Juice Cap, so setting them >100 in aggregate just fills
    the whole tail in the given proportions. Ignored unless Pool Builder and Shuffle Vanilla Items are
    both on."""
    range_start = 0
    range_end = 100
    default = 0


class PoolBuilderPctWeapons(_PoolBuilderPctCategory):
    """Share of the Rune tail Pool Builder fills with weapon juice (best-first by community tier,
    floored by Intensity). Opt-in per-category percent -- see the other % options for how these
    override the global Juice Percent. Default 0."""
    display_name = "Pool Builder % Weapons"


class PoolBuilderPctArmor(_PoolBuilderPctCategory):
    """Share of the Rune tail Pool Builder fills with armor juice (best-first by community tier,
    floored by Intensity). Opt-in per-category percent -- see the other % options for how these
    override the global Juice Percent. Default 0."""
    display_name = "Pool Builder % Armor"


class PoolBuilderPctSpells(_PoolBuilderPctCategory):
    """Share of the Rune tail filled with sorcery + incantation juice (the community tier list rates
    both under one SPELL category). See the per-category percent notes on the other % options."""
    display_name = "Pool Builder % Spells & Incantations"


class PoolBuilderPctTalismans(_PoolBuilderPctCategory):
    """Share of the Rune tail Pool Builder fills with talisman juice (best-first by community tier,
    floored by Intensity). Opt-in per-category percent -- see the other % options for how these
    override the global Juice Percent. Default 0."""
    display_name = "Pool Builder % Talismans"


class PoolBuilderPctAshesOfWar(_PoolBuilderPctCategory):
    """Share of the Rune tail Pool Builder fills with ash-of-war juice (best-first by community tier,
    floored by Intensity). Opt-in per-category percent -- see the other % options for how these
    override the global Juice Percent. Default 0."""
    display_name = "Pool Builder % Ashes of War"


@register
class PoolBuilderFeature(Feature):
    name = "pool_builder"
    ITEMS = {}   # no NEW item names: juice items are catalog items core already registered
    OPTIONS = {
        "pool_builder": PoolBuilder,
        "pool_builder_intensity": PoolBuilderIntensity,
        "pool_builder_scope": PoolBuilderScope,
        "pool_builder_juice_cap": PoolBuilderJuiceCap,
        "pool_builder_juice_pct": PoolBuilderJuicePct,
        "pool_builder_pct_weapons": PoolBuilderPctWeapons,
        "pool_builder_pct_armor": PoolBuilderPctArmor,
        "pool_builder_pct_spells": PoolBuilderPctSpells,
        "pool_builder_pct_talismans": PoolBuilderPctTalismans,
        "pool_builder_pct_ashes_of_war": PoolBuilderPctAshesOfWar,
    }

    # ---- helpers ----------------------------------------------------------------
    def _enabled(self, world) -> bool:
        pb = getattr(world.options, "pool_builder", None)
        sh = getattr(world.options, "item_shuffle", None)
        return bool(pb and pb.value) and bool(sh and sh.value)

    def _floor(self, world) -> int:
        """Resolved juice rarity floor for this world from pool_builder_intensity (default high)."""
        opt = getattr(world.options, "pool_builder_intensity", None)
        key = DEFAULT_INTENSITY
        if opt is not None:
            try:
                key = opt.current_key
            except Exception:
                key = DEFAULT_INTENSITY
        return INTENSITY_FLOOR.get(key, INTENSITY_FLOOR[DEFAULT_INTENSITY])

    def _pct(self, world) -> int:
        """Resolved share of the Rune tail to replace (0..100, default 100 = whole tail)."""
        opt = getattr(world.options, "pool_builder_juice_pct", None)
        if opt is None:
            return 100
        return max(0, min(100, int(opt.value)))

    def _juice_order(self, world) -> List[str]:
        """Per-world juice candidate list (best-first) at this world's intensity floor.
        DLC-only catalog items are dropped when this world has DLC off (see core.gf_dlc_excluded)."""
        _excl = getattr(world, "gf_dlc_excluded", ())
        _order = juice_order_for_floor(self._floor(world))
        return [n for n in _order if n not in _excl] if _excl else _order

    def _rune_fallback_locations(self, world) -> int:
        """Kept-region checks with no real vanilla item -> Rune under item_shuffle."""
        rune = 0
        for rn in [HUB] + list(world._kept()):
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if not (nm and nm in ITEM_CATALOG):
                    rune += 1
        return rune

    def _reserved_slots(self, world) -> int:
        """Slots the OTHER pool contributors consume, which shrink the true Rune tail below the raw
        Rune-fallback-location count: one region Lock per kept region."""
        return len(world._kept())  # one Lock per kept region

    def _cap(self, world) -> int:
        cap_opt = getattr(world.options, "pool_builder_juice_cap", None)
        return int(cap_opt.value) if cap_opt is not None else 0

    def _scope_all_filler(self, world) -> bool:
        opt = getattr(world.options, "pool_builder_scope", None)
        if opt is None:
            return False
        try:
            return opt.current_key == "all_filler"
        except Exception:
            return False

    def _rune_tail(self, world) -> int:
        """Displaceable-slot budget = juice-eligible checks minus slots other contributors eat.

        scope=rune_tail (default): only Rune-fallback checks (byte-identical to the historical count).
        scope=all_filler: ALSO the junk-consumable vanilla filler (displaceable_filler -- the SAME
        predicate core's extras-sort uses to rank those items to the drop tail, so the budget and the
        drop order cannot drift). Conservative: DLC-excluded-but-in-catalog items are counted as
        neither (core turns them into FILLER, so this only under-counts -> juice never over-runs into a
        protected slot)."""
        base = self._rune_fallback_locations(world)
        if self._scope_all_filler(world):
            from ..features.filler_curation import displaceable_filler
            excl = getattr(world, "gf_dlc_excluded", ())
            for rn in [HUB] + list(world._kept()):
                for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                    nm = LOCATION_ITEM.get(ap_id)
                    if (nm and nm in ITEM_CATALOG and not (excl and nm in excl)
                            and displaceable_filler(world, nm)):
                        base += 1
        return max(0, base - self._reserved_slots(world))

    def _category_pcts(self, world) -> dict:
        """{gear category -> percent} for every per-category percent set >0 ({} = global mode)."""
        out = {}
        for opt, cat in CATEGORY_OPTION.items():
            o = getattr(world.options, opt, None)
            v = max(0, min(100, int(o.value))) if o is not None else 0
            if v > 0:
                out[cat] = v
        return out

    def _juice_list(self, world) -> List[str]:
        """The ordered catalog item names to inject as juice, handling both modes.

        GLOBAL (every per-category percent 0, the default): Juice Percent of the Rune tail, best-first
        across ALL categories combined (historical behavior). PER-CATEGORY (any percent >0): each
        category fills its OWN percent of the tail, best-first WITHIN the category, and the global
        Juice Percent is ignored. Both modes are clamped to the available tail and the Juice Cap."""
        if not self._enabled(world):
            return []
        order = self._juice_order(world)                 # best-first, floor + DLC filtered
        if not order:
            return []
        rune_tail = self._rune_tail(world)
        cats = self._category_pcts(world)
        if not cats:                                     # GLOBAL mode
            picks = order[: (rune_tail * self._pct(world)) // 100]
        else:                                            # PER-CATEGORY mode
            picks = []
            for cat, pct in cats.items():
                budget = (rune_tail * pct) // 100
                if budget > 0:
                    cat_items = [n for n in order if ITEM_TIER_CATEGORY.get(n) == cat]
                    picks.extend(cat_items[:budget])
        # count-safety: never exceed the true Rune tail (percents may aggregate >100), then the cap.
        picks = picks[:rune_tail]
        cap = self._cap(world)
        if cap > 0:
            picks = picks[:cap]
        return picks

    def _juice_budget(self, world) -> int:
        """Count of juice items injected (both modes) -- for diagnostics / back-compat."""
        return len(self._juice_list(world))

    # ---- hooks ------------------------------------------------------------------
    def create_items(self, world):
        # core adds these to `pool`, which trims the Rune tail 1:1 -> count-neutral displacement.
        items = []
        for name in self._juice_list(world):
            it = world.create_item(name)
            # Juice is intentional USEFUL gear, never junk filler. Some catalog gear -- notably
            # spells & incantations -- carries the GOODS FullID nibble, so core._classify_full
            # defaults it to `filler`. Left that way, features/filler_curation.curate() and core's
            # stone_injection would SEIZE the juice slot (both protect `useful`, not `filler`) and
            # overwrite an S-tier sorcery with a throwable / smithing stone. Force `useful` so those
            # guards honor pool_builder's picks. (Weapons/armor/talismans/ashes are already useful;
            # this is idempotent for them.)
            it.classification = ItemClassification.useful
            items.append(it)
        return items

    def slot_data(self, world):
        # pure pool curation -> no client contract needed; expose the resolved knobs for diagnostics.
        floor = self._floor(world)
        return {
            "pool_builder": bool(self._enabled(world)),
            "pool_builder_juice_added": self._juice_budget(world),
            "pool_builder_intensity_floor": floor,
            "pool_builder_juice_candidates": len(self._juice_order(world)),
            "pool_builder_juice_pct": self._pct(world),
        }
