"""SPEC-PARITY Phase 5 -- pool builder (item-quality juice, COMPLETE).

Curates the shuffled vanilla item pool by displacing the Rune-fallback tail with high-tier "juice"
(Rare + Legendary weapons, armor, and talismans). Matt-free: tiers come from the vanilla ER param
`rarity` column (EquipParamWeapon/Protector/Accessory), NOT from any curated/location data. See
gen_data.py -> item_tiers.py (ITEM_TIERS = {vanilla_item_name: rarity 0..3}).

Only meaningful when item_shuffle is ON (there is a shuffled vanilla pool to curate). When item_shuffle
is OFF every check pays a Rune and there is nothing to curate -> the feature is a no-op.

Count-neutral by construction. core.create_items builds `pool` (locks + every feature's
create_items()), then computes `slots = total_locations - len(pool)` and fills those slots from the
shuffled vanilla `extras` list -- which core sorts with the Rune fallbacks LAST. So every item this
feature returns from create_items() reduces `slots` by one, trimming one item off the TAIL of that
fill list. While a Rune tail exists (item_shuffle leaves a chunk of checks as Rune fallback) the
trimmed tail is Rune, so juice cleanly DISPLACES Rune.

We bound the juice count to the *true* remaining Rune tail: the count of Rune-fallback checks MINUS
the slots that the other pool contributors already consume (the region Locks, and -- when grace rando
is on -- its scatter items). This keeps juice from spilling past the Rune tail into real vanilla
items, so it upgrades Rune specifically. (Even if the estimate were loose, core's `range(slots)` fill
clamps the total, so the pool stays count-exact and the seed stays winnable; the reserve only sharpens
*which* tail items get displaced.)

Juice items are `useful` (equippables, never progression) -- region Locks stay the sole progression,
so any curated pool is still winnable. No new item names are introduced: every juice item is already
a real-item-pool catalog item registered by core, so world.create_item(name) resolves.
"""
from typing import List

from Options import Toggle, Range
from ..registry import Feature, register
from ..data import HUB, LOCATIONS

try:  # generated by gen_data.py (param-derived rarity; matt-free)
    from ..item_tiers import ITEM_TIERS
except Exception:  # not yet generated -> feature degrades to a no-op (no juice available)
    ITEM_TIERS = {}
try:  # the real-item-pool catalog + per-location assignment (generated by gen_data.py)
    from ..item_ids import ITEM_CATALOG, LOCATION_ITEM
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}
try:  # to reserve slots that grace-rando scatter items consume (leaf data module; no cycle)
    from ..region_graces import REGION_GRACE_POINTS
except Exception:
    REGION_GRACE_POINTS = {}

# ER param `rarity`: 0 = trivial/ammo, 1 = common, 2 = rare, 3 = legendary.
JUICE_MIN_RARITY = 2   # rare + legendary equippables are the "juice"

# All juice item names, best-first (legendary before rare), stable & deterministic.
JUICE_ORDER: List[str] = sorted(
    (n for n, r in ITEM_TIERS.items() if r >= JUICE_MIN_RARITY and n in ITEM_CATALOG),
    key=lambda n: (-ITEM_TIERS[n], n),
)


class PoolBuilder(Toggle):
    """Off (default): the shuffled vanilla pool is used as-is (with a long tail of Rune fillers when
    item_shuffle is on). On: curate the pool -- replace the Rune tail with high-tier juice (rare +
    legendary weapons, armor, and talismans), count-neutral. Has no effect unless Shuffle Vanilla
    Items is also on (there is no vanilla pool to curate otherwise)."""
    display_name = "Pool Builder"


class PoolBuilderJuiceCap(Range):
    """Maximum number of high-tier juice items Pool Builder adds (when on). Bounded so juice only
    ever displaces the Rune fallback tail, never real vanilla items. 0 lets Pool Builder auto-size
    to the whole available Rune tail (still clamped to the number of juice items in the catalog)."""
    display_name = "Pool Builder Juice Cap"
    range_start = 0
    range_end = 400
    default = 120


@register
class PoolBuilderFeature(Feature):
    name = "pool_builder"
    ITEMS = {}   # no NEW item names: juice items are catalog items core already registered
    OPTIONS = {"pool_builder": PoolBuilder, "pool_builder_juice_cap": PoolBuilderJuiceCap}

    # ---- helpers ----------------------------------------------------------------
    def _enabled(self, world) -> bool:
        pb = getattr(world.options, "pool_builder", None)
        sh = getattr(world.options, "item_shuffle", None)
        return bool(pb and pb.value) and bool(sh and sh.value)

    def _rune_fallback_locations(self, world) -> int:
        """Kept-region checks with no real vanilla item -> Rune under item_shuffle."""
        rune = 0
        for rn in [HUB] + list(world._kept()):
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if not (nm and nm in ITEM_CATALOG):
                    rune += 1
        return rune

    def _reserved_slots(self, world) -> int:
        """Slots the OTHER pool contributors consume, which shrink the true Rune tail below the raw
        Rune-fallback-location count: the region Locks, plus grace-rando scatter items when on."""
        kept = list(world._kept())
        reserved = len(kept)  # one Lock per kept region
        grace = getattr(world.options, "grace_rando", None)
        if grace and grace.value:
            kset = set(kept)
            reserved += sum(max(0, len(REGION_GRACE_POINTS[r]) - 1)
                            for r in REGION_GRACE_POINTS if r in kset)
        return reserved

    def _juice_budget(self, world) -> int:
        if not self._enabled(world) or not JUICE_ORDER:
            return 0
        # true remaining Rune tail = Rune-fallback checks minus slots other contributors eat.
        rune_tail = max(0, self._rune_fallback_locations(world) - self._reserved_slots(world))
        budget = min(rune_tail, len(JUICE_ORDER))
        cap_opt = getattr(world.options, "pool_builder_juice_cap", None)
        cap = int(cap_opt.value) if cap_opt is not None else 0
        if cap > 0:
            budget = min(budget, cap)
        return max(0, budget)

    # ---- hooks ------------------------------------------------------------------
    def create_items(self, world):
        n = self._juice_budget(world)
        if n <= 0:
            return []
        # best-first, deterministic; core adds these to `pool`, which trims the Rune tail 1:1.
        return [world.create_item(name) for name in JUICE_ORDER[:n]]

    def slot_data(self, world):
        # pure pool curation -> no client contract needed; expose the resolved knob for diagnostics.
        return {
            "pool_builder": bool(self._enabled(world)),
            "pool_builder_juice_added": self._juice_budget(world),
        }
