"""SPEC-PARITY Phase 5 -- pool builder (item-quality juice, COMPLETE).

Curates the shuffled vanilla item pool by displacing the Rune-fallback tail with high-tier "juice"
(Rare + Legendary weapons, armor, and talismans). Matt-free: tiers come from the vanilla ER param
`rarity` column (EquipParamWeapon/Protector/Accessory), NOT from any curated/location data. See
gen_data.py -> item_tiers.py (ITEM_TIERS = {vanilla_item_name: rarity 0..3}).

Only meaningful when item_shuffle is ON (there is a shuffled vanilla pool to curate). When item_shuffle
is OFF every check pays a Rune and there is nothing to curate -> the feature is a no-op.

Count-neutral by construction. core.create_items builds `pool` (locks + every feature's
create_items()), then computes `slots = total_locations - len(pool)` and fills those slots from the
shuffled vanilla `extras` list -- which core sorts with the Rune fallbacks LAST. So every item this
feature returns from create_items() reduces `slots` by one, trimming one item off the TAIL of that
fill list. While a Rune tail exists (item_shuffle leaves a chunk of checks as Rune fallback) the
trimmed tail is Rune, so juice cleanly DISPLACES Rune.

We bound the juice count to the *true* remaining Rune tail: the count of Rune-fallback checks MINUS
the slots that the other pool contributors already consume (the region Locks, and -- when grace rando
is on -- its scatter items). This keeps juice from spilling past the Rune tail into real vanilla
items, so it upgrades Rune specifically. (Even if the estimate were loose, core's `range(slots)` fill
clamps the total, so the pool stays count-exact and the seed stays winnable; the reserve only sharpens
*which* tail items get displaced.)

Juice items are `useful` (equippables, never progression) -- region Locks stay the sole progression,
so any curated pool is still winnable. No new item names are introduced: every juice item is already
a real-item-pool catalog item registered by core, so world.create_item(name) resolves.

INTENSITY (pool_builder_intensity). The juice list is the set of catalog equippables whose param
`rarity` is at or above a FLOOR. The floor is chosen per-world from this Choice:
  * normal -> rarity >= 3 (legendary only)
  * high   -> rarity >= 2 (rare + legendary)  [DEFAULT -- the historical behavior]
  * max    -> rarity >= 1 (also common/B-tier equippables)
The juice list is computed PER-WORLD from the floor (juice_order_for_floor), sorted best-first
(highest rarity, then name) so it stays deterministic and count-neutral, and it is still bounded by
the Rune tail and the juice cap. A higher intensity only widens the CANDIDATE set; the count actually
added is unchanged (still the Rune tail, clamped by the cap) -- so it changes *which* equippables the
Rune tail becomes, not how many.

PORTION (pool_builder_juice_pct). How much of the Rune tail is replaced is configurable: the budget is
`rune_tail * pct // 100`, then still clamped by the juice cap and the catalog size. pct 100 (DEFAULT)
replaces the whole available tail (historical behavior); pct 50 replaces about half and leaves the
rest as Rune; pct 0 replaces none. This changes HOW MANY tail items become juice (unlike intensity,
which changes which ones).
"""
from typing import List

from Options import Toggle, Range, Choice
from ..registry import Feature, register
from ..data import HUB, LOCATIONS

try:  # generated by gen_data.py (param-derived rarity; matt-free)
    from ..item_tiers import ITEM_TIERS
except Exception:  # not yet generated -> feature degrades to a no-op (no juice available)
    ITEM_TIERS = {}
try:  # the real-item-pool catalog + per-location assignment (generated by gen_data.py)
    from ..item_ids import ITEM_CATALOG, LOCATION_ITEM
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}
try:  # to reserve slots that grace-rando scatter items consume (leaf data module; no cycle)
    from ..region_graces import REGION_GRACE_POINTS
except Exception:
    REGION_GRACE_POINTS = {}

# ER param `rarity`: 0 = trivial/ammo, 1 = common, 2 = rare, 3 = legendary.
# Intensity -> juice rarity FLOOR. high == the historical JUICE_MIN_RARITY of 2 (DEFAULT).
INTENSITY_FLOOR = {"normal": 3, "high": 2, "max": 1}
DEFAULT_INTENSITY = "high"

# Back-compat module-level aliases (the default 'high' intensity == the historical behavior).
# JUICE_MIN_RARITY was the old fixed floor (2 == high); JUICE_ORDER was the default juice list.
JUICE_MIN_RARITY = INTENSITY_FLOOR[DEFAULT_INTENSITY]


def juice_order_for_floor(floor: int) -> List[str]:
    """Catalog equippables with param rarity >= floor, best-first (legendary first, then name).
    Deterministic (pure sort). A higher floor is a SUBSET of a lower floor, so max >= high >= normal
    in length. Empty when tiers/catalog are not yet generated."""
    return sorted(
        (n for n, r in ITEM_TIERS.items() if r >= floor and n in ITEM_CATALOG),
        key=lambda n: (-ITEM_TIERS[n], n),
    )

# Default-intensity juice list (floor = high) for back-compat imports / diagnostics.
JUICE_ORDER = juice_order_for_floor(JUICE_MIN_RARITY)



class PoolBuilder(Toggle):
    """Off (default): the shuffled vanilla pool is used as-is (with a long tail of Rune fillers when
    item_shuffle is on). On: curate the pool -- replace the Rune tail with high-tier juice (rare +
    legendary weapons, armor, and talismans), count-neutral. Has no effect unless Shuffle Vanilla
    Items is also on (there is no vanilla pool to curate otherwise)."""
    display_name = "Pool Builder"


class PoolBuilderIntensity(Choice):
    """How wide a net Pool Builder casts when picking juice (the equippables it turns the Rune tail
    into). Sets the minimum param rarity a vanilla equippable needs to qualify:
    'normal' = legendary only (rarity 3); 'high' = rare + legendary (rarity 2, the DEFAULT and
    historical behavior); 'max' = also include common/B-tier equippables (rarity 1). Only the
    candidate SET changes -- the count added stays the Rune tail (clamped by the juice cap), so a
    higher intensity changes *which* equippables you get, not how many. Ignored unless Pool Builder
    and Shuffle Vanilla Items are both on."""
    display_name = "Pool Builder Intensity"
    option_normal = 0
    option_high = 1
    option_max = 2
    default = 1  # high -> rarity floor 2 == the original JUICE_MIN_RARITY (no change)


class PoolBuilderJuiceCap(Range):
    """Maximum number of high-tier juice items Pool Builder adds (when on). Bounded so juice only
    ever displaces the Rune fallback tail, never real vanilla items. 0 lets Pool Builder auto-size
    to the whole available Rune tail (still clamped to the number of juice items in the catalog)."""
    display_name = "Pool Builder Juice Cap"
    range_start = 0
    range_end = 400
    default = 120


class PoolBuilderJuicePct(Range):
    """What SHARE of the Rune fallback tail Pool Builder replaces with juice, as a percent.
    100 (DEFAULT) = replace the whole available tail (historical behavior); 50 = replace about half
    (leaving the rest as Rune fillers); 0 = replace none (Pool Builder becomes a no-op even when on).
    Applied to the *true* remaining Rune tail (fallback checks minus what region Locks / grace scatter
    already consume), then still clamped by the Juice Cap and the number of juice items in the
    catalog. Ignored unless Pool Builder and Shuffle Vanilla Items are both on."""
    display_name = "Pool Builder Juice Percent"
    range_start = 0
    range_end = 100
    default = 100


@register
class PoolBuilderFeature(Feature):
    name = "pool_builder"
    ITEMS = {}   # no NEW item names: juice items are catalog items core already registered
    OPTIONS = {
        "pool_builder": PoolBuilder,
        "pool_builder_intensity": PoolBuilderIntensity,
        "pool_builder_juice_cap": PoolBuilderJuiceCap,
        "pool_builder_juice_pct": PoolBuilderJuicePct,
    }

    # ---- helpers ----------------------------------------------------------------
    def _enabled(self, world) -> bool:
        pb = getattr(world.options, "pool_builder", None)
        sh = getattr(world.options, "item_shuffle", None)
        return bool(pb and pb.value) and bool(sh and sh.value)

    def _floor(self, world) -> int:
        """Resolved juice rarity floor for this world from pool_builder_intensity (default high)."""
        opt = getattr(world.options, "pool_builder_intensity", None)
        key = DEFAULT_INTENSITY
        if opt is not None:
            try:
                key = opt.current_key
            except Exception:
                key = DEFAULT_INTENSITY
        return INTENSITY_FLOOR.get(key, INTENSITY_FLOOR[DEFAULT_INTENSITY])

    def _pct(self, world) -> int:
        """Resolved share of the Rune tail to replace (0..100, default 100 = whole tail)."""
        opt = getattr(world.options, "pool_builder_juice_pct", None)
        if opt is None:
            return 100
        return max(0, min(100, int(opt.value)))

    def _juice_order(self, world) -> List[str]:
        """Per-world juice candidate list (best-first) at this world's intensity floor.
        DLC-only catalog items are dropped when this world has DLC off (see core.gf_dlc_excluded)."""
        _excl = getattr(world, "gf_dlc_excluded", ())
        _order = juice_order_for_floor(self._floor(world))
        return [n for n in _order if n not in _excl] if _excl else _order

    def _rune_fallback_locations(self, world) -> int:
        """Kept-region checks with no real vanilla item -> Rune under item_shuffle."""
        rune = 0
        for rn in [HUB] + list(world._kept()):
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if not (nm and nm in ITEM_CATALOG):
                    rune += 1
        return rune

    def _reserved_slots(self, world) -> int:
        """Slots the OTHER pool contributors consume, which shrink the true Rune tail below the raw
        Rune-fallback-location count: the region Locks, plus grace-rando scatter items when on."""
        kept = list(world._kept())
        reserved = len(kept)  # one Lock per kept region
        grace = getattr(world.options, "grace_rando", None)
        if grace and grace.value:
            kset = set(kept)
            reserved += sum(max(0, len(REGION_GRACE_POINTS[r]) - 1)
                            for r in REGION_GRACE_POINTS if r in kset)
        return reserved

    def _juice_budget(self, world) -> int:
        order = self._juice_order(world)
        if not self._enabled(world) or not order:
            return 0
        # true remaining Rune tail = Rune-fallback checks minus slots other contributors eat.
        rune_tail = max(0, self._rune_fallback_locations(world) - self._reserved_slots(world))
        # replace only the configured SHARE of that tail (pct 100 == whole tail, the default).
        share = (rune_tail * self._pct(world)) // 100
        budget = min(share, len(order))
        cap_opt = getattr(world.options, "pool_builder_juice_cap", None)
        cap = int(cap_opt.value) if cap_opt is not None else 0
        if cap > 0:
            budget = min(budget, cap)
        return max(0, budget)

    # ---- hooks ------------------------------------------------------------------
    def create_items(self, world):
        n = self._juice_budget(world)
        if n <= 0:
            return []
        order = self._juice_order(world)
        # best-first, deterministic; core adds these to `pool`, which trims the Rune tail 1:1.
        return [world.create_item(name) for name in order[:n]]

    def slot_data(self, world):
        # pure pool curation -> no client contract needed; expose the resolved knobs for diagnostics.
        floor = self._floor(world)
        return {
            "pool_builder": bool(self._enabled(world)),
            "pool_builder_juice_added": self._juice_budget(world),
            "pool_builder_intensity_floor": floor,
            "pool_builder_juice_candidates": len(self._juice_order(world)),
            "pool_builder_juice_pct": self._pct(world),
        }
