"""Pure structural invariants for the Greenfield ER data tables (no Archipelago import).

Same pattern as the existing eldenring test_data_tables.py: importlib-load data.py by path so
this runs in ANY environment in milliseconds (sandbox, CI, Windows) with no AP / Python 3.11
dependency. data.py is regenerated by gen_data.py from region_map.csv + grace anchors; a typo'd
region, a duplicate id, or an id-space shift survives generation and only degrades in-game (the
client keys checks off the flag and the contiguous ap-id space). These guards catch that class
of silent drift up front.

Run:  python -m pytest greenfield/eldenring/tests/test_gf_data.py
  or: python greenfield/eldenring/tests/test_gf_data.py   (unittest fallback)
"""
import importlib.util
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PY = os.path.join(os.path.dirname(HERE), "data.py")

try:  # package import (pytest from the repo)
    from ._util import find_repo_root, REPO_ONLY_REASON
except ImportError:  # direct/unittest fallback
    sys.path.insert(0, HERE)
    from _util import find_repo_root, REPO_ONLY_REASON

# 🛑 Derived by SEARCHING UPWARD for a marker, never positionally. `_util.find_repo_root`'s
# docstring spells out why: under `tools/gf_test.py` the world is copied to `_ap/worlds/eldenring/`,
# so `dirname(dirname(dirname(HERE)))` yields `_ap` rather than the repo. Returns None when there is
# no checkout, and the tests below skip on None instead of resolving to a wrong path.
_ROOT = find_repo_root(HERE)

# ap-id space the client contract depends on (see __init__.py _ITEM_BASE=7780000 / gen_data
# BASE_AP=7770000). A shift here silently remaps every check.
BASE_AP = 7770000
# Reserved band for CO-CHECK sibling lots (SPEC-flag-lot-item-model / gen_data.COCHECK_BASE). These
# ap-ids are allocated ONCE from the append-only co_check_ids.tsv registry, NOT positionally, so they
# are intentionally NOT contiguous with the main band (the positional band tops out ~7775300). Keep in
# sync with gen_data.COCHECK_BASE.
COCHECK_BASE = 7900000


def _load_data():
    spec = importlib.util.spec_from_file_location("gf_data_under_test", DATA_PY)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _registered_cocheck_ids():
    """The set of co-check sibling ap-ids declared in co_check_ids.tsv (the append-only registry), or
    an empty set if the file isn't beside data.py or in the greenfield/ source dir. The built apworld
    ships the registry next to data.py; the raw source tree keeps it one level up in greenfield/. An
    empty result means 'no registry here' -- only meaningful when the data ALSO has no co-check band
    (the pre-regen source tree), which the caller checks."""
    eldenring_dir = os.path.dirname(DATA_PY)
    candidates = [os.path.join(eldenring_dir, "co_check_ids.tsv"),
                  os.path.join(os.path.dirname(eldenring_dir), "co_check_ids.tsv")]
    for p in candidates:
        if not os.path.exists(p):
            continue
        ids = set()
        with open(p, encoding="utf-8") as fh:
            for ln in fh:
                ln = ln.strip()
                if not ln or ln.startswith("#") or ln.startswith("flag\t"):
                    continue
                parts = ln.split("\t")
                if len(parts) >= 4:
                    try:
                        ids.add(int(parts[3]))
                    except ValueError:
                        pass
        return ids
    return set()


class GreenfieldDataInvariants(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.d = _load_data()
        cls.locs = [t for v in cls.d.LOCATIONS.values() for t in v]

    def test_hub_is_not_a_spoke(self):
        self.assertIsInstance(self.d.HUB, str)
        self.assertTrue(self.d.HUB)
        self.assertNotIn(self.d.HUB, self.d.REGIONS)

    def test_regions_nonempty_unique_sorted(self):
        r = self.d.REGIONS
        self.assertTrue(r, "REGIONS is empty")
        self.assertEqual(len(r), len(set(r)), "duplicate region names")
        self.assertEqual(r, sorted(r), "REGIONS not sorted (gen_data emits sorted spokes)")
        self.assertTrue(all(isinstance(x, str) and x for x in r))

    def test_location_keys_match_hub_plus_regions(self):
        # + FINALE_REGION: the conditional Ashen Capital bucket (never rollable, so never in
        # REGIONS; created per-seed by features/finale.py -- see test_gf_finale.py).
        self.assertEqual(set(self.d.LOCATIONS),
                         set([self.d.HUB]) | set(self.d.REGIONS) | {self.d.FINALE_REGION},
                         "LOCATIONS keys must be exactly HUB + every region + the finale bucket")

    def test_every_region_has_at_least_one_location(self):
        empty = [r for r in self.d.REGIONS if not self.d.LOCATIONS.get(r)]
        self.assertEqual(empty, [], f"regions with no locations: {empty}")

    def test_core_and_phantom_flags_are_never_checks(self):
        """Regression (2026-07-10): the Flask of Crimson Tears (flag 60000) is the core tutorial
        healing flask whose flag fires in Stormveil's m10_00 EMEVD -- it kept surfacing as a phantom
        Stormveil check. It, and the other known Stormveil-EMEVD phantoms, must never be a randomized
        location (gen_data._MISC_NON_CHECK). Guards against them 'sneaking back in' on a regen."""
        banned = {60000, 60210, 590000}  # Flask of Crimson Tears, Wizened Finger, empty-item check
        present = sorted({fl for (_n, _ap, fl) in self.locs if fl in banned})
        self.assertEqual(present, [], f"phantom/core flags must not be checks: {present}")

    def test_tuple_shape(self):
        for name, ap_id, flag in self.locs:
            self.assertIsInstance(name, str)
            self.assertIsInstance(ap_id, int)
            self.assertIsInstance(flag, int)

    def test_location_names_globally_unique(self):
        names = [n for n, _a, _f in self.locs]
        self.assertEqual(len(names), len(set(names)), "duplicate location names")

    def test_ap_ids_unique_contiguous_from_base(self):
        ids = sorted(a for _n, a, _f in self.locs)
        self.assertEqual(len(ids), len(set(ids)), "duplicate ap ids")
        # Two disjoint bands. The MAIN (positional) band is assigned sequentially by gen_data and must
        # be contiguous from BASE_AP -- a shift or gap here silently remaps every check. The CO-CHECK
        # band (>= COCHECK_BASE, SPEC-flag-lot-item-model) is sparse and registry-allocated, so it is
        # NOT contiguous with the main band; every id in it must be one the co_check_ids.tsv registry
        # declares (an invented or positional co-check id is the drift this guards).
        main = [i for i in ids if i < COCHECK_BASE]
        co = [i for i in ids if i >= COCHECK_BASE]
        self.assertTrue(main, "no positional ap-ids below COCHECK_BASE -- id space misconfigured")
        self.assertEqual(main[0], BASE_AP, f"ap-id space shifted (min={main[0]}, expected {BASE_AP})")
        self.assertEqual(main, list(range(BASE_AP, BASE_AP + len(main))),
                         "positional ap ids are not contiguous (gen_data assigns them sequentially)")
        if co:
            registered = _registered_cocheck_ids()
            self.assertTrue(registered,
                            f"data has co-check band ap-ids (>= {COCHECK_BASE}) but co_check_ids.tsv "
                            "registry was not found beside data.py or in greenfield/")
            unregistered = sorted(set(co) - registered)
            self.assertEqual(unregistered, [],
                             f"co-check ap-ids not declared in co_check_ids.tsv registry: {unregistered}")

    def test_flags_positive(self):
        bad = [(n, f) for n, _a, f in self.locs if f <= 0]
        self.assertEqual(bad, [], f"non-positive event flags: {bad[:5]}")

    def test_enough_locations_for_lock_items(self):
        # fill needs one slot per progression lock item (one per region) plus filler.
        self.assertGreaterEqual(len(self.locs), len(self.d.REGIONS))



class GreenfieldRegionOpenFlags(unittest.TestCase):
    """Phase 0 boot contract: region_open_flags.py (generated by gen_data.py). Skips cleanly if
    not yet generated so a fresh checkout still passes; CI generates it in the gen step."""
    @classmethod
    def setUpClass(cls):
        cls.d = _load_data()
        cls.path = os.path.join(os.path.dirname(DATA_PY), "region_open_flags.py")
        cls.present = os.path.exists(cls.path)
        if cls.present:
            spec = importlib.util.spec_from_file_location("gf_open_flags", cls.path)
            m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
            cls.rof = m

    def test_open_flags_shape(self):
        if not self.present:
            self.skipTest("region_open_flags.py not generated yet (run gen_data.py)")
        regions = set(self.d.REGIONS)
        vals = list(self.rof.REGION_OPEN_FLAGS.values())
        for r, f in self.rof.REGION_OPEN_FLAGS.items():
            self.assertIn(r, regions, f"open-flag region {r!r} not in REGIONS")
            self.assertIsInstance(f, int)
            self.assertGreater(f, 0)
        self.assertEqual(len(vals), len(set(vals)), "duplicate open flags across regions")

    def test_resolved_and_pending_partition_regions(self):
        if not self.present:
            self.skipTest("region_open_flags.py not generated yet (run gen_data.py)")
        resolved = set(self.rof.REGION_OPEN_FLAGS)
        pending = set(self.rof.REGION_OPEN_PENDING)
        self.assertEqual(resolved & pending, set(), "a region is both resolved and pending")
        self.assertEqual(resolved | pending, set(self.d.REGIONS),
                         "every region must be either resolved or pending")



class GreenfieldSpine(unittest.TestCase):
    """Phase 1 num_regions spine (region_spine.py) -- pure (region_spine imports only .data)."""
    @classmethod
    def setUpClass(cls):
        import types
        cls.d = _load_data()
        pkg = types.ModuleType("gf_stub"); pkg.__path__ = [os.path.dirname(DATA_PY)]
        sys.modules["gf_stub"] = pkg; sys.modules["gf_stub.data"] = cls.d
        spec = importlib.util.spec_from_file_location(
            "gf_stub.region_spine", os.path.join(os.path.dirname(DATA_PY), "region_spine.py"))
        cls.rs = importlib.util.module_from_spec(spec); spec.loader.exec_module(cls.rs)

    def test_spine_is_permutation_of_regions(self):
        self.assertEqual(sorted(self.rs.SPINE), sorted(self.d.REGIONS),
                         "SPINE must be a permutation of REGIONS (no missing/extra region)")

    def test_goal_region_valid(self):
        self.assertIn(self.rs.GOAL_REGION, self.d.REGIONS)

    def test_compute_kept_zero_is_all(self):
        import random
        self.assertEqual(len(self.rs.compute_kept(0, random.Random(1))), len(self.d.REGIONS))
        self.assertEqual(len(self.rs.compute_kept(999, random.Random(1))), len(self.d.REGIONS))

    # test_compute_kept_spine_prefix_plus_goal was DELETED 2026-08-05 with the spine draw. It
    # asserted the kept set by IDENTITY (k[:3] == SPINE[:3]), which a random draw cannot satisfy.
    # What it was really guarding -- n regions drawn from the pool, the goal region present, the
    # parent closure held -- is now stated as properties over a 400-seed sweep in
    # test_gf_region_selection.py, which runs in this same AP-free generators job.

    def test_compute_kept_rolled_has_goal_unique(self):
        import random
        k = self.rs.compute_kept(5, random.Random(7))
        self.assertIn(self.rs.GOAL_REGION, k)
        self.assertEqual(len(k), len(set(k)))
        # N or N+goal, plus REGION_PARENT closure (a kept gated child pulls its ancestors in;
        # bound derived from parent_chain, never re-pinned).
        extra = sum(len(self.rs.parent_chain(r)) for r in k)
        self.assertTrue(5 <= len(k) <= 6 + extra)
        for r in k:
            for anc in self.rs.parent_chain(r):
                self.assertIn(anc, k, f"kept child {r} without ancestor {anc}")



class GreenfieldRegistry(unittest.TestCase):
    """Feature-registry aggregation helpers (core.py merges phases through these). Pure: registry.py
    imports only typing, so it loads standalone with synthetic features -- no Archipelago needed."""
    @classmethod
    def setUpClass(cls):
        path = os.path.join(os.path.dirname(DATA_PY), "registry.py")
        spec = importlib.util.spec_from_file_location("gf_registry", path)
        cls.reg = importlib.util.module_from_spec(spec); spec.loader.exec_module(cls.reg)

    def _feat(self, options=None, items=None, sd=None):
        f = self.reg.Feature()
        f.OPTIONS = options or {}
        f.ITEMS = items or {}
        if sd is not None:
            f.slot_data = lambda world, _sd=sd: _sd
        return f

    def test_option_fields_merge_in_order(self):
        core = [("num_regions", object)]
        feats = [self._feat(options={"floor": object}), self._feat(options={"sweep": object})]
        names = [n for n, _ in self.reg.collect_option_fields(core, feats)]
        self.assertEqual(names, ["num_regions", "floor", "sweep"])

    def test_option_field_collision_raises(self):
        core = [("num_regions", object)]
        with self.assertRaises(ValueError):
            self.reg.collect_option_fields(core, [self._feat(options={"num_regions": object})])

    def test_item_ids_allocated_unique_blocks(self):
        base = {"A Lock": 100}
        feats = [self._feat(items={"X": "p"}), self._feat(items={"Y": "p", "Z": "f"})]
        ids = self.reg.allocate_item_ids(base, 200, feats)
        self.assertEqual(ids["A Lock"], 100)
        self.assertEqual(sorted([ids["X"], ids["Y"], ids["Z"]]), [200, 201, 202])
        self.assertEqual(len(set(ids.values())), len(ids))

    def test_item_class_collision_raises(self):
        with self.assertRaises(ValueError):
            self.reg.collect_item_classes({"X": "p"}, [self._feat(items={"X": "f"})])

    def test_slot_data_merge_and_collision(self):
        base = {"world_logic": "region_lock"}
        merged = self.reg.merge_slot_data(base, [self._feat(sd={"dungeonSweeps": {}})], world=None)
        self.assertIn("dungeonSweeps", merged)
        self.assertIn("world_logic", merged)
        with self.assertRaises(ValueError):
            self.reg.merge_slot_data(base, [self._feat(sd={"world_logic": "x"})], world=None)


class GreenfieldAreaLockGeometry(unittest.TestCase):
    """SINGLE SOURCE OF TRUTH guard. The EDITABLE region -> play_region geometry
    (REGION_PLAY_IDS) lives ONLY in features/area_locks.py, which ships the fully-resolved
    kick-watch ranges as slot_data `areaLockFlags`. The client holds exactly one copy: the
    GENERATED er-logic `region_locks.rs` (tools/gen_region_locks.py, the foreign-apworld
    fallback), which CI regenerates and diffs so it cannot drift. What stays forbidden is a
    HAND-typed mirror in region.rs -- that is the thing that repeatedly drifted (e.g. the
    Consecrated Snowfield -> Mountaintops fold). Skips cleanly if the client source is not
    checked out beside the apworld."""

    @unittest.skipUnless(_ROOT is not None, REPO_ONLY_REASON)
    def setUp(self):
        pass

    def _client_path(self, *parts):
        return os.path.join(_ROOT or "", "from-software-archipelago-clients", *parts)

    def test_client_has_no_hand_written_region_play_ids_mirror(self):
        rs = self._client_path("crates", "eldenring-archipelago", "src", "region.rs")
        if not os.path.exists(rs):
            self.skipTest("client region.rs not present")
        with open(rs, encoding="utf-8") as f:
            text = f.read()
        self.assertNotIn(
            "REGION_PLAY_IDS", text,
            "client region.rs must NOT hand-mirror REGION_PLAY_IDS -- the generator "
            "(area_locks.py) is the single source of truth; the only client copy allowed is the "
            "GENERATED er-logic region_locks.rs (tools/gen_region_locks.py). Consume slot_data "
            "or the generated table; do not re-add a static table that silently drifts.")

    def test_generated_client_table_matches_the_source_tables(self):
        """Same comparison the CI drift gate runs (gen_region_locks --check), as a local test:
        the baked client table must be byte-identical to what these sources generate."""
        out_rs = self._client_path("crates", "er-logic", "src", "region_locks.rs")
        if not os.path.exists(out_rs):
            self.skipTest("client region_locks.rs not present")
        import importlib.util
        tool = os.path.join(_ROOT or "", "tools", "gen_region_locks.py")
        if not os.path.exists(tool):
            # Arming the gate by putting the client beside the AP checkout used to get this far
            # and then die on FileNotFoundError, because the client existed and `tools/` did not.
            self.skipTest(REPO_ONLY_REASON)
        spec = importlib.util.spec_from_file_location("gen_region_locks", tool)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        expected = mod.render_rs(mod.load_rows())
        with open(out_rs, encoding="utf-8") as f:
            current = f.read().replace("\r\n", "\n")
        self.assertEqual(
            current, expected,
            "region_locks.rs is STALE against region_open_flags.py/area_locks.py -- "
            "run: python tools/gen_region_locks.py (then commit the client)")


class RepoRootIsNeverDerivedPositionally(unittest.TestCase):
    """RATCHET for the idiom `_util.find_repo_root` exists to kill.

    A positional walk (`dirname(dirname(dirname(HERE)))`, `Path(__file__).parents[3]`) is correct
    in the repo and WRONG under `tools/gf_test.py`, which copies `greenfield/eldenring` into
    `_ap/worlds/eldenring/` and copies no `tools/`. It does not fail loudly there -- it resolves to
    `_ap` and dies on FileNotFoundError, or worse, finds something.

    That cost 45 tests going green locally and red in CI on 2026-07-27, and then cost this very
    file again: `test_generated_client_table_matches_the_source_tables` (#245) skipped for so long
    that nobody noticed, and the moment the cross-side gate was ARMED by putting the client beside
    the AP checkout, the client path resolved, the `tools/` path did not, and it errored.

    Scans the tests directory itself, so it runs under the harness too -- where the bug lives.
    """

    _BANNED = (
        ("dirname(os.path.dirname(os.path.dirname(", "positional dirname walk"),
        (").parents[", "positional pathlib walk"),
    )

    def test_no_test_module_walks_up_a_fixed_number_of_directories(self):
        scanned, offenders = 0, []
        for name in sorted(os.listdir(HERE)):
            if not name.endswith(".py"):
                continue
            path = os.path.join(HERE, name)
            with open(path, encoding="utf-8") as f:
                text = f.read()
            scanned += 1
            if name == os.path.basename(__file__):
                # this module: skip the literals in _BANNED / this docstring, not the code
                text = text.split("class RepoRootIsNeverDerivedPositionally")[0]
            for needle, why in self._BANNED:
                if needle in text:
                    offenders.append(f"{name}: {why} ({needle!r})")
        # Rule 2 -- an empty result is a failure, not a clean run. A scan that matched no files
        # would report success while checking nothing.
        self.assertGreater(
            scanned, 50,
            f"only {scanned} test modules scanned -- the sweep is not seeing the suite")
        self.assertEqual(
            offenders, [],
            "derive the repo root with _util.find_repo_root(HERE) and skip on None; "
            "a fixed-depth walk resolves to the AP checkout under tools/gf_test.py:\n  "
            + "\n  ".join(offenders))


if __name__ == "__main__":
    unittest.main()
