#!/usr/bin/env bash
# greenfield/ci-linux.sh -- Linux-native twin of the run_ci.ps1 GREENFIELD step.
#
# Runs the greenfield sub-gates natively under Python 3.11 (no Windows, no Cowork mount):
#   (a0) FRESHNESS   gen-input stamp gate (tools/gen_manifest.py --verify): the COMMITTED generated
#                    data must match a hash of the gen inputs on disk. STALE -> FAIL. Runs BEFORE
#                    DRIFT, which re-runs gen_data.py and would rewrite the stamp (masking staleness).
#                    SKIPs when elden_ring_artifacts/ is absent (exit 4: the hash cannot be recomputed
#                    without the licensing-restricted artifacts).
#   (a) DATA DRIFT   regen data.py + region_open_flags.py; fail if they differ (line-ending-
#                    normalized). SKIPS if elden_ring_artifacts/ is absent -- those grace anchors
#                    are licensing-restricted and NOT in git, so a fresh clone can't regenerate.
#                    data.py/region_open_flags.py are committed and still validated by GEN/WORLD.
#   (a1) TRACKER DRIFT  tools/gen_location_regions.py --check: the CLIENT's tracker_regions.rs is
#                    GENERATED FROM the greenfield data (location_tags + contract.has_class), and it
#                    lives in the client submodule -- a cross-repo generated artifact with, until now,
#                    nothing watching it. On 2026-07-12 `contract.is_big_ticket` was renamed to
#                    `has_class` and the generator (which calls it) was never re-run: the star column
#                    went stale AND `build.ps1 -Rust` died on an AttributeError -- while the client's
#                    own CI stayed green, because the client's CI does not run this generator. A green
#                    signal that is structurally blind to the break is worse than no signal.
#                    0 = fresh | 1 = STALE -> FAIL | 4 = submodule not checked out -> SKIP.
#   (b) PURE UNIT    direct unittest on data.py invariants (no AP import)
#   (c) ISOLATED GEN install the world into the AP runtime + Generate.py a greenfield seed
#   (d) WORLD UNIT   WorldTestBase suite (fill/goal/slot_data) against the installed world
# Exits non-zero if any gate FAILS (SKIP does not fail). Auto-provisions the env if missing.
#
#   bash greenfield/ci-linux.sh
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GF="$HERE"; REPO="$(cd "$GF/.." && pwd)"
CACHE="${GF_CI_HOME:-$HOME/.greenfield-ci}"
VENV="$CACHE/.venv"; AP="$CACHE/ap"; PY="$VENV/bin/python"

if [ ! -x "$PY" ] || [ ! -d "$AP" ]; then
  echo "[ci-linux] env missing -> provisioning ..."
  bash "$GF/provision-linux-env.sh" || { echo "provision failed"; exit 2; }
fi

fail=0; declare -a RESULTS
step(){ printf '\n==== %s\n' "$1"; }
record(){ RESULTS+=("$1|$2"); [ "$2" = PASS ] || [ "$2" = SKIP ] || fail=1; }
nhash(){ [ -f "$1" ] && tr -d '\r' < "$1" | sha256sum | cut -d' ' -f1 || echo NONE; }

step "INTEGRITY (mount-truncation gate)"
# Cheapest gate, runs first: catch silent mount-write truncation, NUL injection, or
# zero-byte files in any tracked source before the heavier gates. ERROR -> FAIL;
# delimiter/newline WARNs are advisory and do not fail. In a normal clone (this
# script's intended env) there is no truncating mount, so it is quiet on clean trees.
if [ -f "$REPO/tools/check_integrity.py" ]; then
  if ( cd "$REPO" && "$PY" tools/check_integrity.py --tracked ); then
    record INTEGRITY PASS; else record INTEGRITY FAIL; fi
else
  echo "  SKIP: tools/check_integrity.py absent"; record INTEGRITY SKIP
fi

step "GREENFIELD (a0) GEN-INPUT STAMP FRESHNESS"
# SPEC-gen-input-hash-gate-20260710.md: tools/gen_manifest.py is the ONE definition of the hash. It
# re-hashes the gen inputs (region_map.csv, item_tiers.tsv, the datamined artifacts + intermediates,
# gen_data.py itself) and compares against the _GEN_STAMP written into greenfield/eldenring.
#   0 = fresh -> PASS | 3 = STALE -> FAIL | 4 = required inputs absent -> SKIP (cannot recompute)
# Deliberately BEFORE (a): DRIFT re-runs gen_data.py, which rewrites the stamp -- a stale tree would
# silently self-heal and this gate would never see it.
stampJson="$GF/eldenring/_gen_stamp.json"; genManifest="$REPO/tools/gen_manifest.py"
if [ ! -f "$genManifest" ]; then
  echo "  SKIP: tools/gen_manifest.py absent"; record FRESH SKIP
elif [ ! -f "$stampJson" ]; then
  echo "  FAIL: $stampJson missing -- data was generated by a pre-stamp gen_data.py; rerun gen_data.py."
  record FRESH FAIL
else
  ( cd "$REPO" && "$PY" tools/gen_manifest.py --verify "$stampJson" ); stampRc=$?
  case "$stampRc" in
    0) record FRESH PASS ;;
    4) echo "  SKIP: elden_ring_artifacts/ absent (licensing-restricted, not in git) -- the input hash"
       echo "        cannot be recomputed here. Run this gate where the artifacts live."
       record FRESH SKIP ;;
    *) echo "  STALE: the committed greenfield data does not match the gen inputs on disk (exit $stampRc)."
       echo "         Regenerate and commit: python greenfield/gen_data.py  (or build.ps1 -Greenfield)"
       record FRESH FAIL ;;
  esac
fi

step "GREENFIELD (a) DATA DRIFT"
dataPy="$GF/eldenring/data.py"; openPy="$GF/eldenring/region_open_flags.py"
if [ ! -f "$REPO/elden_ring_artifacts/grace_flags.tsv" ]; then
  echo "  SKIP: elden_ring_artifacts/ absent (licensing-restricted, not in git). data.py +"
  echo "        region_open_flags.py are committed and validated by GEN/WORLD; run drift where"
  echo "        the grace anchors live (or set GF_ARTIFACTS out-of-band)."
  record DRIFT SKIP
else
  bossPy="$GF/eldenring/boss_data.py"; gracePy="$GF/eldenring/region_graces.py"; sweepPy="$GF/eldenring/boss_sweeps.py"; shopPy="$GF/eldenring/shop_data.py"; itemPy="$GF/eldenring/item_ids.py"; tierPy="$GF/eldenring/item_tiers.py"
  b1=$(nhash "$dataPy"); b2=$(nhash "$openPy"); b3=$(nhash "$bossPy"); b4=$(nhash "$gracePy"); b5=$(nhash "$sweepPy"); b6=$(nhash "$shopPy"); b7=$(nhash "$itemPy"); b8=$(nhash "$tierPy")
  if ( cd "$GF" && "$PY" gen_data.py ); then
    if [ "$b1" = "$(nhash "$dataPy")" ] && [ "$b2" = "$(nhash "$openPy")" ] && [ "$b3" = "$(nhash "$bossPy")" ] && [ "$b4" = "$(nhash "$gracePy")" ] && [ "$b5" = "$(nhash "$sweepPy")" ] && [ "$b6" = "$(nhash "$shopPy")" ] && [ "$b7" = "$(nhash "$itemPy")" ] && [ "$b8" = "$(nhash "$tierPy")" ]; then record DRIFT PASS
    else echo "  STALE: gen_data.py regenerated different data -- commit it."; record DRIFT FAIL; fi
  else record DRIFT FAIL; fi
fi

step "GREENFIELD (a1) TRACKER DRIFT (cross-repo generated artifact)"
# tracker_regions.rs lives in the CLIENT submodule but is generated from THIS repo's data. Nothing was
# watching it, so it could rot against its own source of truth -- and did.
( cd "$REPO" && "$PY" tools/gen_location_regions.py --check ); trkRc=$?
case "$trkRc" in
  0) record TRACKER PASS ;;
  4) echo "  SKIP: client submodule not checked out (git submodule update --init)."
     record TRACKER SKIP ;;
  *) echo "  STALE: the client's tracker_regions.rs no longer matches the greenfield data it is"
     echo "         generated FROM. Regenerate and commit the submodule:"
     echo "           python tools/gen_location_regions.py"
     record TRACKER FAIL ;;
esac

step "GREENFIELD (b) PURE UNIT"
# test_gf_data.py = structural invariants; test_gf_region_correctness.py = tier-A semantic-value
# oracle (region assignment vs the region_map.csv placement, independent of region_of). Both run
# from SOURCE where region_map.csv lives; the region gate skips itself in the installed-world copy.
if "$PY" "$GF/eldenring/tests/test_gf_data.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_region_correctness.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_grace_region_correctness.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_region_artifact_oracle.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_grace_skip_oracle.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_grace_skip_classes.py" \
   && "$PY" "$GF/eldenring/tests/test_gf_client_contract_paths.py"; then
  record PURE PASS; else record PURE FAIL; fi

step "GREENFIELD (c) ISOLATED GEN"
rm -rf "$AP/worlds/eldenring"; cp -r "$GF/eldenring" "$AP/worlds/eldenring"
out="$CACHE/out"; rm -rf "$out"; mkdir -p "$out"
if ( cd "$AP" && AP_NONINTERACTIVE=1 SKIP_REQUIREMENTS_UPDATE=1 \
      "$PY" Generate.py --player_files_path "$GF/players" --outputpath "$out" ) \
   && ls "$out"/AP_*.zip >/dev/null 2>&1; then record GEN PASS; else record GEN FAIL; fi

step "GREENFIELD (d) WORLD UNIT"
if ( cd "$AP" && AP_NONINTERACTIVE=1 SKIP_REQUIREMENTS_UPDATE=1 \
      "$PY" -m pytest "worlds/eldenring/tests/" -q -p no:cacheprovider \
        --ignore="worlds/eldenring/tests/test_gf_data.py" ); then
  record WORLD PASS; else record WORLD FAIL; fi

step "GREENFIELD (e) YAML FUZZ"
# CONTRIBUTING headline gate: any greenfield option combo -> clean gen or graceful OptionError.
# Portable scorer; override count/pass via GF_FUZZ_COUNT / GF_FUZZ_PASS. The contract validator is
# wired into fill_slot_data, so a contract-shape drift also fails a fuzzed seed here.
if "$PY" "$GF/fuzz_gf.py" --count "${GF_FUZZ_COUNT:-24}" --pass-pct "${GF_FUZZ_PASS:-90}" --ap "$AP"; then
  record FUZZ PASS; else record FUZZ FAIL; fi

step "RUST PURE (cargo test -p er-logic -- host-tested client logic incl. the *_replay tier)"
# Gates the pure/seam client decisions (region_bloom_settled, start_items_settled, the grant/grace/
# deathlink/vanilla-suppress/watermark *_replay regression tiers, etc.). Windows-free crate, so it
# runs natively here. SKIP (not FAIL) when no Rust toolchain is present, mirroring the DRIFT skip.
if command -v cargo >/dev/null 2>&1; then
  if ( cd "$REPO/from-software-archipelago-clients" && cargo test -p er-logic -q ); then
    record RUST PASS; else record RUST FAIL; fi
else
  echo "  SKIP: cargo not on PATH (install rustup to gate the host-tested client logic + *_replay tiers)"
  record RUST SKIP
fi

step "GREENFIELD VERDICT"
for r in "${RESULTS[@]}"; do printf '  %-6s %s\n' "${r%%|*}" "${r##*|}"; done
if [ "$fail" -eq 0 ]; then echo "  GREENFIELD: PASS"; exit 0; else echo "  GREENFIELD: FAIL"; exit 1; fi
