#!/usr/bin/env python3
"""Generate eldenring_gf/data.py (regions + flag-keyed locations) for the Greenfield ER apworld.
Self-contained + data-derived: reads region_map.csv (this dir) + grace/BonfireWarp anchors from
elden_ring_artifacts. No dependency on any externally-named file. See LESSONS-LEARNED.md.

CANONICAL GENERATOR: this file (greenfield/gen_data.py) is the ONE generator. It WRITES the
eldenring_gf/*.py data modules (data.py, region_open_flags.py, boss_data.py, region_graces.py,
boss_sweeps.py, shop_data.py, missable_locations.py, item_ids.py, item_tiers.py, location_tags.py),
each stamped "AUTO-GENERATED by greenfield/gen_data.py". Do NOT hand-edit those outputs -- edit
THIS file and regenerate. There is no second generator; a copy inside eldenring_gf/ would be stale
cruft (deleted 2026-07-08)."""
import csv, re, os, math
from collections import Counter, defaultdict, OrderedDict
csv.field_size_limit(10**7)
HERE=os.path.dirname(os.path.abspath(__file__))
REPO=os.path.abspath(os.path.join(HERE,".."))
AR=os.path.join(REPO,"elden_ring_artifacts")
OUT=os.path.join(HERE,"eldenring_gf","data.py")
HUB="Roundtable Hold"
# Boss-drop flags: boss-healthbar enemy DROPS, datamined from EMEVD common boss-handlers (matt-free).
# Committed generated module eldenring_gf/boss_drops.py (tools/datamine_boss_drops.py, run before this
# in gen-greenfield.ps1). Fallback = empty so gen_data still runs standalone (Boss tag simply empty).
import importlib.util as _ilu
try:
    _bspec = _ilu.spec_from_file_location("_boss_drops", os.path.join(HERE, "eldenring_gf", "boss_drops.py"))
    _bmod = _ilu.module_from_spec(_bspec); _bspec.loader.exec_module(_bmod)
    _BOSS_DROP_FLAGS = frozenset(_bmod.BOSS_DROP_FLAGS)
except Exception as _e:
    _BOSS_DROP_FLAGS = frozenset()
    print(f"[gen_data] boss_drops.py unavailable ({_e!r}); Boss tag empty -- run tools/datamine_boss_drops.py")
try:
    _hbspec = _ilu.spec_from_file_location("_boss_hb", os.path.join(HERE, "eldenring_gf", "boss_healthbars.py"))
    _hbmod = _ilu.module_from_spec(_hbspec); _hbspec.loader.exec_module(_hbmod)
    BOSS_HEALTHBARS = dict(_hbmod.BOSS_HEALTHBARS)
except Exception as _e:
    BOSS_HEALTHBARS = {}
    print(f"[gen_data] boss_healthbars.py unavailable ({_e!r}); sweeps fall back to region-wide banner scan -- run tools/datamine_boss_healthbars.py")
HUB="Roundtable Hold"
SKIP={"global","global_filler","shop_reference"}
# Map-fragment pickups are granted via the RE'd map-reveal FLAG path (the client's reveal_all_maps
# sets these exact flags), so they must NOT also be AP checks -- otherwise revealing the map trips
# all of them at once (start-of-run map-piece flood). Exclude any location whose acquisition flag is
# a map-reveal flag. Mirrors startgrants.rs MAP_REVEAL_FLAGS_BASE + MAP_REVEAL_FLAGS_DLC.
MAP_REVEAL_FLAGS=frozenset({62010,62011,62012,62020,62021,62022,62030,62031,62032,62040,62041,
                            62050,62051,62052,62060,62061,62062,62063,62064,
                            62080,62081,62082,62083,62084})
BASE_AP=7770000  # greenfield location id space

# ---- overworld tile -> play_region via grace anchors + nearest-neighbor ----
gf={}
# grace_flags.tsv carries the BonfireWarpParam rowId=0 default/template row (warpUnlockFlag=200,
# mapTile=m10_00_00) -- a placeholder, NOT a real site of grace. Its flag 200 is outside the
# 71xxx-76xxx region/grace event-flag group (all 421 REAL warp graces are 71000-76960), so it is
# not a writable in-game flag. Left in, it became the numerically-lowest candidate for Stormveil
# (a legacy dungeon with no overworld grace) and won _front_door -> bogus REGION_OPEN_FLAGS[
# "Stormveil Castle"]=200 AND polluted the Stormveil grace bundle. Reject any warpUnlockFlag
# outside the valid region/grace group at ingest so only real graces reach _open_cand.
for row in csv.DictReader(open(os.path.join(AR,"grace_flags.tsv")),delimiter="\t"):
    if not (71000 <= int(row["warpUnlockFlag"]) <= 76999): continue
    gf[row["warpUnlockFlag"]]=row["mapTile"]
greg={}
grm=[x for x in os.listdir(AR) if x.startswith("grace_region_map")][0]
for row in csv.DictReader(open(os.path.join(AR,grm)),delimiter="\t"): greg[row["grace_flag"]]=row["play_region_id"]
_acc=defaultdict(Counter)
for flag,tile in gf.items():
    pr=greg.get(flag); m=re.match(r"m60_(\d\d)_(\d\d)",tile)
    if pr and pr!="0" and m: _acc[(int(m.group(1)),int(m.group(2)))][pr]+=1
ANCHOR={xy:c.most_common(1)[0][0] for xy,c in _acc.items()}
def tile_pr(x,y):
    if (x,y) in ANCHOR: return ANCHOR[(x,y)]
    best,bd=None,1e18
    for (ax,ay),pr in ANCHOR.items():
        d=(ax-x)**2+(ay-y)**2
        if d<bd: bd,best=d,pr
    return best
PLAY2AP={'61000':'Limgrave','61001':'Limgrave','61002':'Weeping Peninsula','62000':'Liurnia of the Lakes',
 '62001':'Liurnia of the Lakes','62002':'Liurnia of the Lakes','63000':'Altus Plateau','63001':'Mt. Gelmir',
 '63002':'Altus Plateau','63003':'Altus Plateau','64000':'Caelid','64001':'Caelid','64002':'Caelid',
 '65000':'Mountaintops of the Giants','65001':'Mountaintops of the Giants','65002':'Mountaintops of the Giants'}
REGION_MAP={'Land of Shadow (DLC)':'Gravesite Plain','Eternal Cities & Underground Rivers':'Eternal Cities',
 'Mohgwyn / Consecrated-adjacent':'Mohgwyn Palace','Mohgwyn Palace':'Mohgwyn Palace','Leyndell / Roundtable / Shunning-Grounds':'Altus Plateau',
 'DLC Interior':'Shadow Keep','Caves':'Limgrave',"Roundtable Hold":'Roundtable Hold','Stormveil Castle':'Stormveil Castle',
 'Stormveil (assoc.)':'Stormveil Castle',"Miquella's Haligtree & Elphael":"Miquella's Haligtree",
 "Hero's Graves (Catacombs)":'Limgrave','Crumbling Farum Azula':'Farum Azula','Divine Tower':'Liurnia of the Lakes',
 'Raya Lucaria Academy':'Liurnia of the Lakes','Volcano Manor / Mt. Gelmir':'Mt. Gelmir','Volcano Manor (Rykard)':'Mt. Gelmir','Volcano Manor':'Mt. Gelmir',
 'DLC Dungeon':'Gravesite Plain','DLC Legacy Dungeon':'Belurat','Tunnels':'Caelid','Limgrave':'Limgrave',
 'Limgrave (Church of Elleh)':'Limgrave','Limgrave (Waypoint Ruins)':'Limgrave','Liurnia of the Lakes':'Liurnia of the Lakes',
 "Liurnia of the Lakes (Seluvis's Rise)":'Liurnia of the Lakes',"Liurnia of the Lakes (Ranni's Rise)":'Liurnia of the Lakes',
 'Weeping Peninsula':'Weeping Peninsula','Siofra River / Nokron':'Eternal Cities','Caelid':'Caelid',
 'Caelid (Redmane Castle)':'Caelid','Caelid (Cathedral of Dragon Communion)':'Caelid','Gravesite Plain (DLC)':'Gravesite Plain','Gravesite Plain':'Gravesite Plain',
 'Cathedral of Manus Metyr (DLC)':'Scadu Altus','Scadu Altus (DLC)':'Scadu Altus','Consecrated Snowfield':'Mountaintops of the Giants',
 'Shadow Keep (DLC)':'Shadow Keep','Altus Plateau':'Altus Plateau','Jagged Peak (DLC)':'Jagged Peak',
 'Grand Altar of Dragon Communion (Jagged Peak, DLC)':'Jagged Peak','Cerulean Coast (DLC)':'Gravesite Plain',
 'Abyssal Woods (DLC)':'Abyssal Woods','Mountaintops of the Giants':'Mountaintops of the Giants',
 'Leyndell, Royal Capital':'Altus Plateau','Leyndell (Ashen Capital)':'Altus Plateau','Nokron / Siofra (Ancestor Spirit)':'Eternal Cities',
 'Lake of Rot (Astel)':'Eternal Cities','Deeproot Depths (Lichdragon Fortissax)':'Eternal Cities','Fractured Marika (final)':'Altus Plateau',
 'Belurat, Tower Settlement (DLC)':'Belurat','Enir-Ilim (DLC)':'Enir-Ilim','Stone Coffin Fissure (DLC)':'Gravesite Plain',
 "Midra's Manse (DLC)":'Abyssal Woods','Church of the Bud (DLC)':'Ancient Ruins of Rauh','Castle Ensis (DLC)':'Gravesite Plain',
 'Ainsel River / Lake of Rot':'Eternal Cities','Nokstella, Eternal City':'Eternal Cities','Subterranean Shunning-Grounds':'Altus Plateau',
 'm22':'Eternal Cities','m28':'Gravesite Plain'}

def _region_of_raw(r):
    reg=r['region']; meth=r['method']
    if reg.startswith('Overworld m60'):
        m=re.match(r'.*m60_(\d\d)_(\d\d)',reg)
        return PLAY2AP.get(tile_pr(int(m.group(1)),int(m.group(2))),HUB) if m else HUB
    if meth=='shop_multi': return HUB
    return REGION_MAP.get(reg,HUB)

# ---- important_locations tags (matt-free): classify each check by TYPE from item_name + method,
# NOT names. Used by features/important_locations.py to force those checks to hold non-filler items.
# Remembrance/Seedtree/Church/Basin exclude shop rows (buying a duplicate is not the meaningful check).
def _loc_tags(r):
    nm = (r['item_name'] or '').lower(); meth = r['method']; shop = meth.startswith('shop')
    t = []
    # Boss = boss-healthbar enemy DROP (datamined from EMEVD common boss-handlers 90005860/861/880 ->
    # entity+rewardLot; field/evergaol/dragon, remembrance/great-rune majors excluded). Replaces the
    # old method=='boss_arena' tagging -- those 23 majors were a subset of Remembrance/GreatRune.
    _fl = (r.get('flag') or '').strip()
    if _fl.lstrip('-').isdigit() and int(_fl) in _BOSS_DROP_FLAGS: t.append('Boss')
    if 'remembrance' in nm and not shop: t.append('Remembrance')
    if 'golden seed' in nm and not shop: t.append('Seedtree')
    if 'sacred tear' in nm and not shop: t.append('Church')
    if 'scadutree fragment' in nm: t.append('Fragment')
    if 'revered spirit ash' in nm: t.append('Revered')
    if 'crystal tear' in nm and not shop: t.append('Basin')
    if shop: t.append('Shop')
    return t

# MINI-BAKER reserved shop row: the client repurposes ShopLineupParam row 101801 (Twin Maiden Husks'
# Blue Cipher Ring slot, eventFlag_forStock 60290) into an infinite Stonesword Key vendor at runtime
# (see features/minibaker.py + minibaker.rs). Exclude its flag so it is NOT also an AP shop check --
# otherwise the client's repurpose would clobber a tracked check. Costs one minor vanilla slot.
MINIBAKER_VENDOR_FLAGS=frozenset({60290})
_ALLROWS=list(csv.DictReader(open(os.path.join(HERE,"region_map.csv"))))

# ---- Hand-verified row corrections (matt-free) --------------------------------------------------
# region_map.csv's map_lot scan mis-attributed a few flags to the wrong map/region. Both num_regions
# (region label) and the map-keyed dungeon sweep read these columns, so a wrong map double-faults:
# wrong region AND wrong boss-sweep membership. Correct the source row here in code -- region_map.csv
# stays the raw pipeline output (same philosophy as FLAG_REGION_OVERRIDE / DUNGEON_REGION_OVERRIDE).
#   197 = Remembrance of the Full Moon Queen (Rennala): scanned into m10_00 Stormveil (Godrick's map)
#         but obtained in Raya Lucaria Academy (m14_00 -> folds to Liurnia via REGION_MAP). The map
#         error also mis-grouped it into Stormveil's sweep 10000800/10000850 not Rennala's 14000800.
# {flag: (map, region)} -- region must be a REGION_MAP key.
ROW_MAP_REGION_FIX = {197: ("m14_00_00_00", "Raya Lucaria Academy")}
for _rowfix in _ALLROWS:
    try:
        _ff = int(_rowfix["flag"])
    except (KeyError, ValueError):
        continue
    _fx = ROW_MAP_REGION_FIX.get(_ff)
    if _fx:
        _rowfix["map"], _rowfix["region"] = _fx
# Redundant obtained-flag TWINS of a physically-placed pickup: dropped so the medallion isn't a
# double check. 400280 = Haligtree Secret Medallion (Left) obtained flag, which the flag_prefix
# heuristic buckets into Leyndell -- but the Left half is a real world pickup (Castle Sol, flag
# 1051587800, FLAG_REGION_OVERRIDE'd to Mountaintops), so the obtained twin is a phantom Leyndell
# check that fires off the same pickup. (Rold 400001 stays: it is GRANTED, never placed, so its
# obtained flag is the only handle; Haligtree Right 400130 stays: its physical pickup isn't detected.)
# 191-196 = the Divine Tower RESTORATION duplicates of each great rune. Vanilla awards the great rune
# ONCE from the shardbearer (the 17x boss flag, set via failsafe event 6905 off the 510xxx boss/
# remembrance flag); the m34 Divine Tower event (90005110) re-references the same goods -> greenfield
# registered a SECOND check per rune, so in-game you receive two great runes and hit the max-inventory
# cap (in-game report 2026-07-08). Drop the tower copy; keep the boss check (171-176). The tower copies
# also carried the m34 "DLC Dungeon" misregion, so this removes 6 mis-bucketed checks too.
_GREAT_RUNE_TOWER_DUPES = frozenset({191, 192, 193, 194, 195, 196})
# 60210 = Tarnished's Wizened Finger: a Roundtable Hold system item (region_misc) whose flag fires
# inside Stormveil's m10_01 EMEVD, so it both mis-pinned to Stormveil AND showed up as a randomizer
# check. Per playtest (2026-07-08) it should NOT be randomized -- drop it so it stays a vanilla pickup
# and never becomes a check (this also drops ap-id 7770020 from the m10 dungeon sweep 10010800 on regen).
# ASHEN CAPITAL endgame drops (510070 Hoarah Loux/Godfrey, 510230 Elden Remembrance = Radagon/Elden
# Beast, 190540/190550 Gideon) are KEPT (Alaric 2026-07-08: make Ashen a logical region, not a rollable
# num_regions one). They fold into the always-kept GOAL region (Altus Plateau) via REGION_MAP -> reachable
# in logic when Altus opens, and collectable via Morgott's region-wide sweep (Morgott = reachable capital
# ending). NOT a separate rollable region. Morgott (510040) is the capital ending and already there.
_MISC_NON_CHECK = frozenset({60210, 590000, 550200, 550250})  # 590000 = empty-item Stormveil check; 60210 Wizened Finger; 550200/550250 = "About ..." tutorial-message popups (not loot, same class as 9100-9125)
# Unreachable ASHEN CAPITAL + final-boss drops -- EXCLUDED AS DEAD (user decision 2026-07-08). Post-
# Erdtree-burn / final content is not physically reachable in a region-lock game, and is NOT actually
# collectable via Morgott's region-wide sweep (boss_arena rewards are never swept, and the m11_05
# map_lot items fall outside the sweep member filter) -- so they were dead big-ticket checks. Drop
# them. m11_05 = Leyndell Ashen Capital (whole 11050000-11059999 range); 510070 Remembrance of Hoarah
# Loux (Godfrey, Ashen); 510230 Elden Remembrance (Radagon/Elden Beast, final); 190540/190550 = Sir
# Gideon the All-Knowing (Ashen). Morgott (510040) STAYS -- he is the reachable capital ending. Bolt of
# Gransax (11007xxx, Royal Capital m11_00) STAYS -- physically reachable. Excluding boss_arena 510070/
# 510230 also drops them from REGION_BOSSES (built from `rows`), so no dangling Felled trophy / key.
_ASHEN_DEAD_FLAGS = frozenset({510070, 510230, 190540, 190550})
def _is_ashen_dead(_fl):
    return _fl in _ASHEN_DEAD_FLAGS or 11050000 <= _fl <= 11059999
# PHANTOM recovery duplicates: a common-event/unplaced `global` flag that names a UNIQUE key item
# already fully placed elsewhere -- recovering it would inject an extra copy of a singleton key.
#   1033477020 = a 4th "Imbued Sword Key" (decodes to m60_33_47/Liurnia) that sits in the unplaced
#     `global` bucket (map PENDING) and is referenced in NO EMEVD, while the three real keys are
#     placed as method='treasure' (Raya Lucaria 14007630, Caelid 1050397910, Land of Shadow
#     2048447800). The game has exactly three -> drop this phantom so global-recovery doesn't
#     re-double the singleton (test_unique_key_items_are_singletons).
_RECOVER_PHANTOM_DUPES = frozenset({1033477020})
# UNREACHABLE big-ticket checks -- EXCLUDED AS DEAD (Alaric 2026-07-09). Physically gated behind
# mechanics a warp-grace region-lock shuffle can't guarantee, so a placed multiworld item strands.
#   30207900 = Silver Scarab: end of the Hidden Path to the Haligtree (m30_20), behind an imp-statue /
#     illusory-wall gate reachable only from the far side of the grace anchor.
#   1050567820 = Graven-Mass Talisman: the reward inside Albinauric Rise (Consecrated Snowfield,
#     folded into Mountaintops), sealed by the invisible-sniper imp seal (bewitching branch / fanged
#     imp ashes) -- not openable from the grace side, so the check is unreachable.
# Dropping these renumbers downstream ap-ids (needs a full regen) and removes the vanilla shuffle copy.
_UNREACHABLE_DEAD = frozenset({30207900, 1050567820})
EXCLUDE_FLAGS = (frozenset({400280}) | _GREAT_RUNE_TOWER_DUPES | _MISC_NON_CHECK
                | _RECOVER_PHANTOM_DUPES | _UNREACHABLE_DEAD)
# Walking Mausoleum remembrance DUPLICATES: every remembrance is also stocked by the Walking
# Mausoleum duplication menu, which is a ShopLineupParam -> method 'shop_multi'. That gave a SECOND
# check per remembrance for a copy you can only make once you already HOLD the remembrance -- which,
# once it is shuffled elsewhere, you may never obtain, so the check can strand. Keep the boss drop
# (510xxx); drop the mausoleum copy. (Finger Reader Enia TRADES remembrances for their rewards; she
# is not a duplicate seller -- the Walking Mausoleum is the only remembrance "shop".)
def _is_mausoleum_dupe(r):
    return r['method'] == 'shop_multi' and 'Remembrance' in (r.get('item_name') or '')
rows=[r for r in _ALLROWS
      if r['method'] not in SKIP and int(r['flag']) not in MAP_REVEAL_FLAGS
      and int(r['flag']) not in MINIBAKER_VENDOR_FLAGS and int(r['flag']) not in EXCLUDE_FLAGS
      and not _is_mausoleum_dupe(r) and not _is_ashen_dead(int(r['flag']))]

# ---- EMEVD/common-event region AUDIT + POST-PROCESS (matt-free) -------------------------------
# region_map.csv pins many emevd/global-method flags to a map/region taken from where the flag ID was
# SCANNED, not where the item's common-event actually FIRES. num_regions gates on the region, so a
# mis-pinned check becomes a false late-region gate (playtester killed Miranda in Weeping Peninsula
# and it registered as "Liurnia :: Viridian Amber Medallion"). We correct in code (region_map stays
# the raw input): scan every MAP emevd (m<map>.emevd.dcx.js, NOT common/common_func -- those are the
# common-event DEFINITIONS) for each flag on a WORD boundary; classify UNIQUE/AMBIGUOUS/NONE.
#   UNIQUE + m60 overworld tile     -> RE-PIN to that tile's region (map-scan is ground truth).
#   Overworld-m60 region column on a DIRECT grace-anchor tile -> trustworthy, keep.
#   Overworld-m60 region column on a nearest-neighbor (non-anchor) tile that is NOT map-verifiable
#     -> UNRELIABLE (the 520300 class) -> QUARANTINE to HUB (reachable-from-start, never a false gate).
#   currently-SKIPped `global` rows  -> RECOVER as checks (unique-m60 real region, else HUB).
#   name-column emevd (author-labeled region like "Stormveil Castle") -> keep (human region signal;
#     the flag lives only in common so map-scan can't confirm it, but the label is trustworthy).
# Item-lot/treasure + common-event flags live ONLY in common.emevd (parameterized $InitializeEvent),
# so they never appear in a MAP file -> class NONE -> not re-pinnable; those are handled by the
# anchor-vs-nearest-neighbor + quarantine rules above. Degrades to raw region_of if event/ is absent.
_EVDIR0 = os.path.join(AR, "event")
_FLAGS_OF_INTEREST = set()
for _r in _ALLROWS:
    if _r['method'] in ('emevd', 'global'):
        try: _FLAGS_OF_INTEREST.add(int(_r['flag']))
        except (KeyError, ValueError): pass
_FLAG2MAPS = defaultdict(set)   # flag(int) -> set of map ids (e.g. 'm60_33_42_00','m10_00_00_00')
# Entity-suffix index (matt-free GLOBAL RECOVERY): 6-digit common-event flags (e.g. O'Neil 530405) do
# NOT self-encode a tile, but their DROPPING ENTITY is a 10-digit self-encoding id (1[01]XXYYLLLL)
# whose last 6 digits equal the flag (entity 1040530405 -> flag 530405 -> decode the entity -> m60_40_53).
# Scan the MAP emevds for such entities, decode each to its tile, index by last-6 suffix. Tiebreak a
# shared suffix by FEWEST referencing files (the more specific placement). suffix -> {tile: set(files)}.
_ENT_SUF_FILES = defaultdict(lambda: defaultdict(set))
if os.path.isdir(_EVDIR0) and _FLAGS_OF_INTEREST:
    for _fn in os.listdir(_EVDIR0):
        _mm = re.match(r"(m\d\d.*)\.emevd\.dcx\.js$", _fn)
        if not _mm or _fn.startswith("common"):
            continue
        _mid = _mm.group(1)
        _txt = open(os.path.join(_EVDIR0, _fn), encoding="utf-8", errors="replace").read()
        _ints = set(int(_x) for _x in re.findall(r"\d+", _txt))   # maximal digit runs = word boundary
        for _fl in (_ints & _FLAGS_OF_INTEREST):
            _FLAG2MAPS[_fl].add(_mid)
        for _es in set(re.findall(r"\d+", _txt)):                 # 10-digit self-encoding drop entities
            if len(_es) == 10 and _es[0] == '1' and _es[1] in '01':
                _et = "m" + ("60" if _es[1] == '0' else "61") + "_" + _es[2:4] + "_" + _es[4:6]
                _ENT_SUF_FILES[_es[-6:]][_et].add(_fn)
_ENTITY_SUFFIX = {}             # 6-digit flag suffix -> decoded overworld tile of its drop entity
for _suf, _tf in _ENT_SUF_FILES.items():
    _ENTITY_SUFFIX[_suf] = min(_tf.items(), key=lambda _kv: (len(_kv[1]), _kv[0]))[0]
# A 6-digit common-event flag can be SHARED by multiple droppers in different tiles/regions (e.g.
# Commander's Standard 530405 drops from a generic commander at Bower of Bounty/Altus AND from
# Commander O'Neil in Caelid, whose named-boss entity is NOT in the ...530405 pattern). When the
# entity index sees >1 candidate tile the region is genuinely ambiguous -> recover as a HUB check
# (always-reachable, never a false gate) rather than guessing one dropper. GLOBAL_RECOVER still wins
# for any flag hand-pinned to its true region.
_ENTITY_SUFFIX_AMBIG = {_suf for _suf, _tf in _ENT_SUF_FILES.items() if len(_tf) > 1}
def _unique_m60(_fl):
    _ms = _FLAG2MAPS.get(_fl)
    if _ms and len(_ms) == 1:
        _only = next(iter(_ms))
        if _only.startswith("m60"):
            return _only
    return None
def _m60_tile_region(_mid):
    _m = re.match(r"m60_(\d\d)_(\d\d)", _mid)
    if not _m: return None
    return PLAY2AP.get(tile_pr(int(_m.group(1)), int(_m.group(2))))
_REPIN_N = [0]; _QUAR_N = [0]; _RECOVER_N = [0]

# ---- GLOBAL-recovery tile decode (matt-free FULL coverage) ------------------------------------
# ER lot/flag ids self-encode their map tile: 10-digit 1[01]XXYYLLLL -> m60_XX_YY (prefix 10->m60,
# 11->m61); 8-digit BBSSLLLL -> mBB_SS (interior); 6-digit common-event flags via the entity-suffix
# index above. A decoded tile is accepted only if it is REAL: it has an EMEVD map file OR appears
# among placed region_map maps -- matched by 3-part m60_XX_YY / 2-part mBB_SS PREFIX (EMEVD file
# names carry a 4th _NN block, e.g. m60_40_53_00). Degrades to no recovery if event/ + maps absent.
_VALID_TILE_PREFIXES = set()
def _add_tile_prefix(_p):
    _VALID_TILE_PREFIXES.add(_p)                            # 3-part (m60_XX_YY / mBB_SS_NN)
    _VALID_TILE_PREFIXES.add("_".join(_p.split("_")[:2]))  # 2-part (mBB_SS)
if os.path.isdir(_EVDIR0):
    for _fn in os.listdir(_EVDIR0):
        _pm = re.match(r"(m\d\d_\d\d_\d\d)", _fn)
        if _pm: _add_tile_prefix(_pm.group(1))
for _rr0 in _ALLROWS:
    _pm = re.match(r"(m\d\d_\d\d_\d\d)", _rr0.get("map") or "")
    if _pm: _add_tile_prefix(_pm.group(1))
def _recover_tile(_flag):
    """Decode a global/global_filler flag to a VALID map tile (overworld m60_XX_YY / m61_XX_YY, or
    interior mBB_SS), else None. Honors the SAME exclusions applied to the main `rows` filter
    (MAP_REVEAL / MINIBAKER / EXCLUDE_FLAGS / ashen-dead) plus the 9100-9125 tutorial-popup flags
    (a real tile, but not loot). GLOBAL_RECOVER precedence is enforced by the callers, not here."""
    try: _fl = int(_flag)
    except (TypeError, ValueError): return None
    if (_fl in MAP_REVEAL_FLAGS or _fl in MINIBAKER_VENDOR_FLAGS or _fl in EXCLUDE_FLAGS
            or _is_ashen_dead(_fl) or 9100 <= _fl <= 9125):
        return None
    _s = str(_fl); _tile = None
    if len(_s) == 10 and _s[0] == '1' and _s[1] in '01':
        _tile = "m" + ("60" if _s[1] == '0' else "61") + "_" + _s[2:4] + "_" + _s[4:6]
    elif len(_s) == 8:
        _tile = "m" + _s[0:2] + "_" + _s[2:4]
    elif len(_s) == 6:
        _tile = _ENTITY_SUFFIX.get(_s)
    if not _tile:
        return None
    _key = _tile if _tile[:3] in ("m60", "m61") else "_".join(_tile.split("_")[:2])
    return _tile if _key in _VALID_TILE_PREFIXES else None

# ---- Per-FLAG region override (matt-free, playtest-verified) ----------------------------------
# A few overworld pickups resolve to the wrong region: their source event/scan tile lands on a
# contested Liurnia/Altus boundary tile (nearest-neighbour tie) or is simply wrong in the emevd scan.
# This per-flag table wins over EVERY other path (dungeon override, emevd/global audit, tile NN).
# Keys are acquisition event flags (int); values are greenfield region names. Found via in-game
# tracker report 2026-07-08 (Godfrey Icon talisman + Haligtree medallion mis-shown under Liurnia).
FLAG_REGION_OVERRIDE = {
    1039507100: "Altus Plateau",               # Godfrey Icon = Godefroy the Grafted's drop at the
                                               #   Golden Lineage Evergaol (NW Altus). Its EMEVD tile
                                               #   m60_39_50 NN-ties Liurnia(38,50)/Altus(39,51) -> Liurnia.
    1051587800: "Mountaintops of the Giants",  # Haligtree Secret Medallion (Left) is physically in
                                               #   Castle Sol (Mountaintops); the EMEVD scan mis-tiled the
                                               #   flag to Liurnia (m60_36_41). Right half stays in Liurnia.
    520000: "Weeping Peninsula",               # Lhutel the Headless (spirit ash) -- Alaric-confirmed
                                               #   Weeping, mis-tiled to m10/Stormveil by the EMEVD scan.
    520010: "Weeping Peninsula",               # Demi-Human Ashes -- same (Alaric-confirmed Weeping).
    400031: "Liurnia of the Lakes",            # Lord of Blood's Favor = Varre's questline reward at the
    400033: "Liurnia of the Lakes",            #   Rose Church (Liurnia); mis-pinned to m10. (400031/400033
                                               #   are the given/blood-soaked states -- likely a dup, see below.)
    # DLC-dungeon dead-checks (Alaric playtest): flags encode true map mMM_SS (X0SS7000) but the
    # matt-free-pipeline mis-resolved them to an m18 fallback -> "Stormveil (assoc.)" -> Stormveil.
    # Re-regioned via the AUTHORITATIVE grace join (grace_flags mapTile -> grace_region_map play_region
    # -> REGION_ID_MAP), so each sub-dungeon lands in its real overworld region (reachable + swept).
    40007000: "Gravesite Plain",             # m40_00 Fog Rift Catacombs
    40017000: "Ancient Ruins of Rauh",       # m40_01 Scorpion River Catacombs (Rauh Base)
    40027000: "Scadu Altus",                 # m40_02 Darklight Catacombs
    41007000: "Gravesite Plain",             # m41_00 Belurat Gaol
    41027000: "Gravesite Plain",             # m41_02 Lamenter's Gaol (Charo's Hidden Grave)
    42007000: "Gravesite Plain",             # m42_00 Ruined Forge (Lava Intake)
    42037000: "Ancient Ruins of Rauh",       # m42_03 Taylew's Ruined Forge
    43007000: "Gravesite Plain",             # m43_00 Rivermouth Cave
    18007050: "Limgrave",                    # m18_00 Fringefolk Hero's Grave (off Stranded Graveyard): Erdtree's
    18007900: "Limgrave",                    #   Favor / Erdtree Greatbow. The grave exits into Limgrave and is
                                             #   gated only by 2 Stonesword Keys (gettable), so place it in
                                             #   Limgrave rather than quarantining to HUB (Alaric 2026-07-09).
    197: "Liurnia of the Lakes",               # Remembrance of the Full Moon Queen = RENNALA's drop.
                                               #   Her reward row is method=emevd (flag 197) mis-pinned to
                                               #   m10 (Stormveil) in region_map.csv, but flag 197 only fires
                                               #   on the Rennala kill at Raya Lucaria (folded into Liurnia),
                                               #   and the boss lives in Liurnia (_BOSS_SPECIALS 14000800).
                                               #   Without this the Stormveil-tagged check is UNREACHABLE
                                               #   (its flag never fires there) -> curated_fill can strand a
                                               #   region Lock on it (in-game soft-lock 2026-07-08). Re-region
                                               #   to Liurnia so location, detect-flag, boss + sweep all agree.
}

# ---- Curated dungeon-region OVERRIDE (matt-free, hand/playtest-verified) ----------------------
# The coarse REGION_MAP buckets every minor dungeon into one region ("Caves"->Limgrave,
# "Tunnels"->Caelid, catacombs->Limgrave, m34 Divine Towers->"DLC Dungeon"), which is wrong for any
# dungeon not physically in that region (e.g. Morne Tunnel m32_00 is Weeping Peninsula, not Caelid;
# the m34 Great-Rune Divine Towers are base game, not DLC). This per-map-id table wins over the coarse
# bucket AND the emevd/global audit. Keys are full map ids; values are greenfield region names.
DUNGEON_REGION_OVERRIDE = {
    # Split-map corrections: a 3-char map prefix conflates sub-maps that are DIFFERENT regions.
    # m20 = Belurat (m20_00) + Enir-Ilim (m20_01) DLC -- NOT Mohgwyn; m12_05 = Mohgwyn Palace --
    # NOT the rest of m12 (Eternal Cities/Underground Rivers). Without these, 170 m20 DLC checks
    # landed in BASE Mohgwyn (leaking DLC into DLC-off seeds) and Mohgwyn's real m12_05 checks went
    # to Eternal Cities. Graces are fixed in parallel by the per-play_region grace resolution.
    "m20_00_00_00": "Belurat",
    "m20_01_00_00": "Enir-Ilim",
    "m12_05_00_00": "Mohgwyn Palace",
    # DLC minor dungeons whose global-recovered checks otherwise fall through to HUB (map not placed
    # in region_map.csv + absent here). Regions per DLC-AREA-ID-CAPTURE.md / GLOBAL_RECOVER comments.
    "m40_01_00_00": "Ancient Ruins of Rauh",  # Scorpion River Catacombs (Rauh Base)
    "m42_00_00_00": "Gravesite Plain",        # Ruined Forge (Lava Intake)
    "m43_00_00_00": "Gravesite Plain",        # Rivermouth Cave
    "m30_20_00_00": "Mountaintops of the Giants",  # Hidden Path to the Haligtree (Snowfield folded into Mountaintops)
    "m31_01_00_00": "Weeping Peninsula",  # Earthbore Cave
    "m31_04_00_00": "Liurnia of the Lakes",  # Stillwater Cave
    "m31_05_00_00": "Liurnia of the Lakes",  # Lakeside Crystal Cave
    "m31_06_00_00": "Liurnia of the Lakes",  # Academy Crystal Cave
    "m31_07_00_00": "Mt. Gelmir",  # Seethewater Cave
    "m31_09_00_00": "Mt. Gelmir",  # Volcano Cave
    "m31_10_00_00": "Caelid",  # Dragonbarrow Cave (folded into Caelid)
    "m31_12_00_00": "Mountaintops of the Giants",  # Cave of the Forlorn (Snowfield folded into Mountaintops)
    "m31_18_00_00": "Altus Plateau",  # Altus Plateau: Perfumer's Grotto
    "m31_21_00_00": "Caelid",  # Gaol Cave
    "m30_00_00_00": "Weeping Peninsula",
    "m30_03_00_00": "Liurnia of the Lakes",
    "m30_05_00_00": "Liurnia of the Lakes",
    "m30_07_00_00": "Altus Plateau",
    "m30_09_00_00": "Mt. Gelmir",
    "m30_10_00_00": "Altus Plateau",
    "m30_13_00_00": "Altus Plateau",
    "m30_17_00_00": "Mohgwyn Palace",
    "m30_19_00_00": "Limgrave",
    "m31_02_00_00": "Weeping Peninsula",
    "m31_03_00_00": "Limgrave",
    "m31_11_00_00": "Caelid",
    "m31_15_00_00": "Limgrave",
    "m31_19_00_00": "Altus Plateau",
    "m31_20_00_00": "Caelid",
    "m31_22_00_00": "Mountaintops of the Giants",
    "m32_00_00_00": "Weeping Peninsula",
    "m32_05_00_00": "Altus Plateau",
    "m32_07_00_00": "Caelid",
    "m34_11_00_00": "Liurnia of the Lakes",  # Liurnia Divine Tower / Study Hall (was Limgrave)
    "m34_14_00_00": "Altus Plateau",  # was Leyndell (folded into Altus, capstone re-carve)
    # Divine Towers of Limgrave / West Altus / Caelid are BASE GAME, but region_map.csv marks every
    # m34 tile "DLC Dungeon"; without an override they misbundle into Land of Shadow (found by the
    # grace-region gate 2026-07-06; correct region = the grace independent play_region_id cluster).
    "m34_10_00_00": "Limgrave",       # Divine Tower of Limgrave (73410/73412, pid 61001)
    "m34_12_00_00": "Altus Plateau",  # Divine Tower of West Altus (73430/73432, pid 63002)
    "m34_13_00_00": "Caelid",         # Divine Tower of Caelid (73440/73441, pid 64001)
    "m34_15_00_00": "Caelid",         # Divine Tower (73460, pid 64001)
    # Subterranean Shunning-Grounds (m35_00) is play_region 35000 = Shunning-Grounds, which sits
    # UNDER Leyndell. region_map.csv mislabels every m35 row "Divine Tower" (-> Liurnia via REGION_MAP),
    # so without this override its checks AND its warp graces (73501 Underground Roadside, 73502
    # Forsaken Depths, 73503 Leyndell Catacombs, 73504 Frenzied Flame Proscription) misbundle into
    # Liurnia's lock (in-game report 2026-07-07; grace tile m35_00 inherits the m35 checks' region via
    # _pref2maj). Correct region = Leyndell (REGION_ID_MAP.md 35000 = Subterranean Shunning-Grounds).
    "m35_00_00_00": "Altus Plateau",  # Shunning-Grounds under Leyndell -> Altus (Leyndell folded in)
    "m39_20_00_00": "Mt. Gelmir",
    # Catacombs whose checks were UNPLACED (flag_prefix, map PENDING) -> never surfaced an override,
    # so they hit the coarse "Hero's Graves (Catacombs)"->Limgrave bucket. Regions are the AUTHORITATIVE
    # grace join (grace_flags mapTile -> grace_region_map play_region -> PLAY2AP); confirmed vs in-game.
    # Their checks are recovered onto these maps below (map-recovery loop) so the catacomb boss sweeps them.
    "m30_01_00_00": "Weeping Peninsula",   # Impaler's Catacombs
    "m30_02_00_00": "Limgrave",            # Stormfoot Catacombs
    "m30_04_00_00": "Limgrave",            # Murkwater Catacombs
    "m30_06_00_00": "Liurnia of the Lakes",# Cliffbottom Catacombs
    "m30_08_00_00": "Altus Plateau",       # Sainted Hero's Grave
    "m30_12_00_00": "Altus Plateau",       # Unsightly Catacombs
    "m30_14_00_00": "Caelid",              # Minor Erdtree Catacombs
    "m30_15_00_00": "Caelid",              # Caelid Catacombs
    "m30_16_00_00": "Caelid",              # War-Dead Catacombs
}
# Map recovery for UNPLACED dungeon checks: a catacomb/cave/tunnel pickup identified only by flag
# prefix (method 'flag_prefix', map PENDING) still encodes its map in the flag (30.XX.. -> m30_XX), so
# recover map = mAA_BB_00_00 -- IF that map is a known dungeon (in DUNGEON_REGION_OVERRIDE). Without
# this the check has no map, so region_of hits the coarse Catacombs->Limgrave bucket AND the map-local
# boss sweep for that dungeon can't grant it (9 catacombs were left with empty sweeps). region_of then
# regions it via DUNGEON_REGION_OVERRIDE (the recovered map id), and Phase 3b sweeps it map-locally.
for _rr in _ALLROWS:
    if _rr.get("method") != "flag_prefix" or (_rr.get("map") or "") not in ("", "PENDING"):
        continue
    _fs = str(_rr.get("flag") or "")
    if len(_fs) >= 8 and _fs[:2] in ("30", "31", "32", "34", "39", "40", "41", "42", "43"):
        _rec = f"m{_fs[:2]}_{_fs[2:4]}_00_00"
        if _rec in DUNGEON_REGION_OVERRIDE:
            _rr["map"] = _rec


# ---- Curated GLOBAL recovery (matt-free): common-event drops are excluded by default (they are not
# region-locatable and mostly generic). Only the flags listed here (physick tears etc., hand-assigned
# to the boss/location region they drop from) are recovered as real checks. Empty = none recovered
# (globals stay excluded, no hub sphere-0 balloon). {flag(int): region}.
GLOBAL_RECOVER = {
    # Physick crystal / cracked / hidden / hard tears (Alaric hand-assigned to drop region, 2026-07-06).
    65000: "Altus Plateau",            # Crimsonspill Crystal Tear
    65010: "Limgrave",                 # Greenspill Crystal Tear
    65020: "Limgrave",                 # Crimson Crystal Tear (2 copies: Limgrave + Altus -> earlier)
    65050: "Liurnia of the Lakes",     # Cerulean Crystal Tear (2: Liurnia + Mountaintops avatar -> earlier)
    65070: "Mountaintops of the Giants",  # Crimson Bubbletear (Mountaintops Erdtree Avatar)
    65080: "Weeping Peninsula",        # Opaline Bubbletear (Weeping Erdtree Avatar)
    65110: "Caelid",                   # Opaline Hardtear (Caelid Erdtree Avatar)
    65130: "Mountaintops of the Giants",  # Thorny Cracked Tear (Snowfield Erdtree Avatar; Snowfield folded in)
    65140: "Limgrave",                 # Spiked Cracked Tear
    65160: "Liurnia of the Lakes",     # Ruptured Crystal Tear (Liurnia Erdtree Avatar)
    65170: "Mountaintops of the Giants",  # Ruptured Crystal Tear (Snowfield Erdtree Avatar; Snowfield folded in)
    65210: "Limgrave",                 # Strength-knot Crystal Tear
    65220: "Liurnia of the Lakes",     # Dexterity-knot Crystal Tear
    65230: "Liurnia of the Lakes",     # Intelligence-knot Crystal Tear (Carian Manor)
    65250: "Mt. Gelmir",               # Cerulean Hidden Tear (Gelmir Ulcerated Tree Spirit)
    65260: "Caelid",                   # Stonebarb Cracked Tear (Caelid Erdtree Avatar)
    65280: "Caelid",                   # Flame-Shrouding Cracked Tear (Caelid Erdtree Avatar)
    65300: "Liurnia of the Lakes",     # Lightning-Shrouding Cracked Tear (Liurnia Erdtree Avatar)
    65310: "Liurnia of the Lakes",     # Holy-Shrouding Cracked Tear (Liurnia Erdtree Avatar)
    # DLC furnace-golem tears.
    65400: "Gravesite Plain",          # Viridian Hidden Tear (Gravesite Plains)
    65410: "Scadu Altus",              # Crimsonburst Dried Tear
    65420: "Scadu Altus",              # Crimson-Sapping Cracked Tear (Ancient Ruins of Rauh golem)
    65430: "Scadu Altus",              # Cerulean-Sapping Cracked Tear
    65440: "Scadu Altus",              # Oil-Soaked Tear
    65450: "Scadu Altus",              # Bloodsucking Cracked Tear
    65470: "Gravesite Plain",          # Deflecting Hardtear (Gravesite Plains golem)
    # Larval Tears: multiple scattered copies share these flags -> HUB (always reachable, never a false gate).
    510340: HUB,
    1049557700: HUB,
    # Haligtree Secret Medallion (Right): physically the reward in Castle Sol (Mountaintops of the
    # Giants), obtained by defeating Commander Niall -- NOT the Village-of-the-Albinaurics pickup (that
    # is the LEFT half). Only the obtained flag (400130, method global) exists (no map_lot), and it is
    # currently recovered to Liurnia, which is a mis-pin (real region Mountaintops). It IS reachable
    # (Niall is a normal combat boss), so it is left as a Liurnia check pending a proper re-pin to
    # Mountaintops (flagged 2026-07-09; distinct from the Albinauric Rise Graven-Mass Talisman above).
    400130: "Liurnia of the Lakes",
    # Deathroot rewards from Gurranq at the Bestial Sanctum (Dragonbarrow / NE Caelid). Recovered as
    # checks AND tagged missable below (gated behind delivering N deathroots -- a limited consumable +
    # Gurranq is killable -- so fill must not place required progression here). See DEATHROOT_FLAGS.
    400230: "Caelid",  # Ancient Dragon Smithing Stone (9th deathroot / kill Gurranq)  [method global_filler]
    400231: "Caelid",  # Gurranq's Beast Claw (8th)
    400232: "Caelid",  # Beastclaw Greathammer (7th)
    400233: "Caelid",  # Stone of Gurranq (6th)
    400234: "Caelid",  # Beast Claw (5th)
    400235: "Caelid",  # Ash of War: Beast's Roar (4th)
    400236: "Caelid",  # Bestial Vitality (3rd)
    400237: "Caelid",  # Bestial Sling (2nd)
    400238: "Caelid",  # Clawmark Seal (1st)
    400239: "Caelid",  # Beast Eye (1st / kill Gurranq)
    # Marais Executioner's Sword: Elemer of the Briar's drop at the Shaded Castle (NW Altus
    # Plateau). Fired via the common boss-drop handler (EMEVD event 82: entity 1100/reward 510820),
    # so it has no map lot and lands in the unplaced common-event bucket -- recover it as an Altus
    # check so felling Elemer sends a check instead of paying the vanilla sword.
    510820: "Altus Plateau",
    # Lord of Blood's Exultation (520220): Esgar, Priest of Blood's drop at the end of Leyndell
    # Catacombs (under Leyndell, which greenfield folds into Altus Plateau). Fired via the common
    # boss-drop handler with no map lot -> lands in the unplaced common-event bucket and was
    # quarantined to HUB. Recover it to Altus so felling Esgar sends a check, not the vanilla talisman
    # (Alaric 2026-07-09; the Catacombs are reachable by normal traversal once Leyndell/Altus opens).
    520220: "Altus Plateau",
    # Loretta's Mastery (510190): the sorcery dropped by Loretta, Knight of the Haligtree (m15 boss,
    # healthbar entity 15000850). She drops a SORCERY, not a remembrance, so the boss_arena join never
    # sees her and her drop sat in the unplaced common-event bucket. Recover it to Miquella's Haligtree
    # so felling her sends a check; she is also registered as a region boss via _BOSS_SPECIALS below
    # (Alaric 2026-07-09: Loretta was missing from the Haligtree boss list).
    510190: "Miquella's Haligtree",
    # Commander's Standard (530405): shared drop flag. The entity-suffix datamine finds only the
    # generic Altus commander at Bower of Bounty; but Commander O'Neil in the Swamp of Aeonia (CAELID)
    # also drops it (Alaric, ground truth 2026-07-09) and is the earlier/intended source. Pin to
    # Caelid so it isn't a false Altus gate. (Would otherwise HUB via _ENTITY_SUFFIX_AMBIG.)
    530405: "Caelid",
    # Grafted Blade Greatsword (510800): drops from the Leonine Misbegotten at Castle Morne, in the
    # Weeping Peninsula (Alaric, ground truth 2026-07-09 -- tracker showed it quarantined to HUB).
    # Shared/unplaced common-event flag -> pin so it sits behind the Weeping lock, not always-free.
    510800: "Weeping Peninsula",
}
# Missable location flags (matt-free): checks gated behind a LIMITED consumable or a killable NPC, so
# fill must not place required progression there (features/missable_locations.py enforces via item_rule).
#   Deathroot: the 10 Gurranq reward flags above (delivering deathroots; Gurranq killable).
#   Dragon Heart: the Dragon Communion incantation purchases -- derived below from ShopLineupParam
#     costType==1 (Dragon-Heart-cost shop rows) -> DRAGONHEART_FLAGS. Both fold into MISSABLE_FLAGS.
# (Stonesword-key / Shabriri / Seedbed deferred -- questline-avoidance covers the latter two.)
DEATHROOT_FLAGS = set(range(400230, 400240))


# Interior region fallback for RECOVERED globals: an interior dungeon tile (mBB_SS) not curated in
# DUNGEON_REGION_OVERRIDE still has a KNOWN region if PLACED (non-global) loot sits on the same tile.
# This map-prefix -> region table is derived from the placed `rows` below (their own region_of result,
# the ground truth), so a recovered interior drop lands in the same region as its dungeon's placed
# items instead of quarantining to HUB. Populated after region_of is defined (it needs region_of).
_MAP_PREFIX_REGION = {}
def _tile_prefix2(_m):
    if not _m or _m == "PENDING": return None
    _p = _m.split("_")
    return "_".join(_p[:3]) if (_m[:3] in ("m60", "m61") and len(_p) >= 3) else "_".join(_p[:2])

def region_of(r):
    """Corrected region: per-flag override (highest priority) -> curated dungeon override -> EMEVD/
    common-event audit for emevd+global rows -> raw region_of for everything else."""
    try: _ovfl = int(r['flag'])
    except (KeyError, ValueError): _ovfl = None
    if _ovfl is not None and _ovfl in FLAG_REGION_OVERRIDE:
        return FLAG_REGION_OVERRIDE[_ovfl]
    _dov = DUNGEON_REGION_OVERRIDE.get(r.get('map', ''))
    if _dov:
        return _dov
    _meth = r['method']
    # GLOBAL_RECOVER is authoritative for any listed global/global_filler flag (covers deathroot
    # rewards, which are method global_filler, not just 'global').
    try: _grfl = int(r['flag'])
    except (KeyError, ValueError): _grfl = None
    if _grfl is not None and _grfl in GLOBAL_RECOVER and _meth in ('global', 'global_filler'):
        return GLOBAL_RECOVER[_grfl]
    # Auto-recover globals NOT hand-listed in GLOBAL_RECOVER: decode the flag's own map tile.
    # Overworld tile -> grace-anchored region; interior tile -> set the map + interior region path.
    # A None/HUB result is acceptable (HUB = always-reachable, never a false gate).
    if _meth in ('global', 'global_filler'):
        _rt = _recover_tile(r.get('flag'))
        if _rt:
            _fs6 = str(_ovfl if _ovfl is not None else '')
            if len(_fs6) == 6 and _fs6 in _ENTITY_SUFFIX_AMBIG:
                return HUB                                  # shared-flag common drop: region ambiguous
            if _rt[:3] in ('m60', 'm61'):
                return _m60_tile_region(_rt) or HUB
            _im = _rt + '_00_00'                            # interior mBB_SS -> mBB_SS_00_00
            r['map'] = _im                                 # let the existing interior path region it
            return (DUNGEON_REGION_OVERRIDE.get(_im)        # curated dungeon region, else
                    or _MAP_PREFIX_REGION.get(_rt)          # region of PLACED loot on this tile, else
                    or _region_of_raw(r))                   # raw region (-> HUB if unknown)
    if _meth not in ('emevd', 'global'):
        return _region_of_raw(r)
    try: _fl = int(r['flag'])
    except (KeyError, ValueError): return _region_of_raw(r)
    _um = _unique_m60(_fl)
    if _um:                                            # UNIQUE map-scan hit on an overworld tile
        _rr = _m60_tile_region(_um)
        if _rr:
            _cur = _region_of_raw(r)
            if _meth == 'global': _RECOVER_N[0] += 1
            elif _rr != _cur:     _REPIN_N[0] += 1
            return _rr
    if _meth == 'global':                              # only curated globals are recovered
        _RECOVER_N[0] += 1
        return GLOBAL_RECOVER.get(_fl, HUB)
    _reg = r['region']
    _m = re.match(r"Overworld m60_(\d\d)_(\d\d)", _reg)
    if _m:
        _xy = (int(_m.group(1)), int(_m.group(2)))
        # Direct grace anchor OR a placed map_lot item (flag_source=='map_lot' => the tile is the
        # item's real ItemLotParam_map placement, not a scanned common-event flag) -> tile is ground
        # truth, resolve to its region. Only genuinely unverifiable nearest-neighbor common-event
        # (emevd-scanned) flags are quarantined to HUB.
        if _xy in ANCHOR or r.get('flag_source') == 'map_lot':
            return _region_of_raw(r)
        _QUAR_N[0] += 1                                # nearest-neighbor + unverifiable -> hub
        return HUB
    return _region_of_raw(r)                            # name-column emevd -> trust the human label

# Derive the interior map-prefix -> region table from the PLACED rows (before recovery is appended),
# so recovered interior drops inherit their dungeon's region instead of quarantining to HUB.
_mpr_votes = defaultdict(Counter)
for _r in rows:
    _pf = _tile_prefix2(_r.get('map'))
    if _pf and _pf[:3] not in ('m60', 'm61'):          # interior tiles only (overworld uses tile decode)
        _mpr_votes[_pf][region_of(_r)] += 1
_MAP_PREFIX_REGION.update({_p: _c.most_common(1)[0][0] for _p, _c in _mpr_votes.items()})

# RECOVER: append the currently-SKIPped `global` rows (real pickups: crystal tears, memory stones,
# effigies, etc.) as reachable checks. Appended AFTER `rows` so existing positional ap-ids are stable.
def _recover_row_ok(r):
    if r['method'] not in ('global', 'global_filler'):
        return False
    try: _fl = int(r['flag'])
    except (KeyError, ValueError): return False
    if _fl in MAP_REVEAL_FLAGS:
        return False
    if _fl in GLOBAL_RECOVER:                       # hand-verified region wins -> always recover
        return True
    if (_fl in MINIBAKER_VENDOR_FLAGS or _fl in EXCLUDE_FLAGS
            or _is_mausoleum_dupe(r) or _is_ashen_dead(_fl)):
        return False
    return _recover_tile(_fl) is not None           # auto-recover every DECODABLE global/filler
_recovered = [r for r in _ALLROWS if _recover_row_ok(r)]
rows = rows + _recovered
buckets=OrderedDict()
loc_tags={}
apid=BASE_AP; names=set()
for r in rows:
    reg=region_of(r); flag=int(r['flag']); item=r['item_name'] or 'check'
    nm=f"{reg} :: {item} [f{flag}]"
    if nm in names: nm=f"{nm}#{apid}"
    names.add(nm)
    _t=_loc_tags(r)
    if _t: loc_tags[apid]=_t
    buckets.setdefault(reg,[]).append((nm,apid,flag)); apid+=1

spokes=sorted(k for k in buckets if k!=HUB)
with open(OUT,"w",encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Greenfield ER data; data-derived, no external naming."""\n')
    f.write(f"HUB = {HUB!r}\n")
    f.write("REGIONS = [\n")
    for r in spokes: f.write(f"    {r!r},\n")
    f.write("]\n\nLOCATIONS = {\n")
    for r in [HUB]+spokes:
        f.write(f"    {r!r}: [\n")
        for nm,aid,flag in buckets.get(r,[]): f.write(f"        ({nm!r}, {aid}, {flag}),\n")
        f.write("    ],\n")
    f.write("}\n")
print(f"spokes={len(spokes)} hub_locs={len(buckets.get(HUB,[]))} total={sum(len(v) for v in buckets.values())}")
# ---- EMEVD/common-event audit REPORT (deterministic; classifies each emevd/global row once) ------
_A_UNIQUE=_A_AMBIG=_A_NONE=0; _A_REPIN=0; _A_QUAR=0; _A_RECOVER=0; _A_REPIN_NOOP=0
for _r in rows:
    _meth=_r['method']
    if _meth not in ('emevd','global'): continue
    try: _fl=int(_r['flag'])
    except (KeyError,ValueError): continue
    _ms=_FLAG2MAPS.get(_fl)
    if not _ms: _A_NONE+=1
    elif len(_ms)==1: _A_UNIQUE+=1
    else: _A_AMBIG+=1
    _um=_unique_m60(_fl); _rr=_m60_tile_region(_um) if _um else None
    _cur=_region_of_raw(_r)
    if _meth=='global':
        _A_RECOVER+=1
    elif _um and _rr:
        if _rr!=_cur: _A_REPIN+=1
        else: _A_REPIN_NOOP+=1
    else:
        _reg=_r['region']; _m=re.match(r"Overworld m60_(\d\d)_(\d\d)",_reg)
        if _m and (int(_m.group(1)),int(_m.group(2))) not in ANCHOR and _r.get('flag_source')!='map_lot': _A_QUAR+=1
print(f"emevd_audit: UNIQUE={_A_UNIQUE} AMBIGUOUS={_A_AMBIG} NONE={_A_NONE} | "
      f"re-pin(emevd unique-m60 changed)={_A_REPIN} (+{_A_REPIN_NOOP} already-correct) | "
      f"quarantine->HUB (nearest-neighbor unverifiable)={_A_QUAR} | recovered globals->checks={_A_RECOVER}")

# (location_tags.py is written LATER -- after ITEM_TIERS -- so catalog/rarity big-ticket tags can be added)

# ---- Phase 0 boot contract: one warp-grace open flag per major region (matt-free) -----------
# Derived from the SAME grace anchors used above. On lock receipt the client sets this flag
# (region.rs region_open_flags), lighting the region's front-door grace so the player can warp in.
# DLC sub-areas whose locations are all boss-arena (map=PENDING) don't resolve to a grace here ->
# left PENDING; the client treats an absent open flag as "unlocked" (SPEC-PARITY.md 14.4).
def _map_pref(m):
    if not m or m == "PENDING": return None
    p = m.split("_")
    return "_".join(p[:3]) if m.startswith("m60") and len(p) >= 3 else "_".join(p[:2])
_pref2maj = defaultdict(Counter)
for _r in rows:
    _mj = region_of(_r); _pf = _map_pref(_r["map"])
    if _pf and _mj: _pref2maj[_pf][_mj] += 1
_pref2maj = {p: c.most_common(1)[0][0] for p, c in _pref2maj.items()}
# ---- Boss-gated / arena grace SKIP set (matt-free; EMEVD-derived) -----------------------------
# A region's grace bundle must contain only graces that PHYSICALLY EXIST at region-open. These do
# not, so force-lighting them (num_regions lights the whole bundle on lock receipt) warps the
# player to a grace that isn't there yet / into a sealed boss arena -> soft-lock. Filtered from
# _open_cand below (feeds both the region-open front-door flag AND the grant bundle).
#   FLAG-GATED: EMEVD common event 9005810 hides the grace asset until a gate/boss-defeat flag is
#     set. COMPLETE (exhaustive sweep of all 90058xx grace-control commons x BonfireWarpParam).
#   ARENA: overworld remembrance arenas, MSB-placed grace behind a fog/summon trigger. No EMEVD
#     signal -> known/playtest set, NOT provably complete; expand if a playtest finds more.
_BOSS_GATED_GRACE_FLAGS = frozenset({76161, 71301, 71302, 72200, 76313, 73500, 76322, 72101, 71210, 73900, 72110, 71600, 71601, 71220, 71221, 71606, 72500, 71100, 71101, 71230, 72000, 71240, 76232, 72010, 71500, 71120, 71121, 71250, 71505, 76247, 71000, 71001, 76120, 71900, 72800, 71400, 71401})
_ARENA_GRACE_FLAGS = frozenset({76930, 76931, 76422, 76852, 76853, 76508, 76509, 76415,
    71300})  # +71300 Maliketh the Black Blade: fog-gated arena grace (not 9005810 bonfire-hidden, so EMEVD oracle missed it); leaked into Farum Azula grants (playtest 2026-07-07)
# m11_05 = Leyndell, Ashen Capital: a POST-ERDTREE-BURN map variant that region_of folds into base
# Leyndell. Vanilla lights these on the burn; force-lighting them with the Leyndell lock warps you
# into the ashen capital before you've burned the Erdtree (playtest 2026-07-07: 71123 "Leyndell,
# Capital of Ash" leaked). Skip -> they light naturally on burn. (State-variant gate: distinct from
# the boss-bonfire (9005810) and remembrance-arena classes.)
_ASHEN_LEYNDELL_GRACE_FLAGS = frozenset({71120, 71121, 71122, 71123, 71124, 71125})
_SKIP_GRACE_FLAGS = _BOSS_GATED_GRACE_FLAGS | _ARENA_GRACE_FLAGS | _ASHEN_LEYNDELL_GRACE_FLAGS
# Per-play_region grace region for SPLIT interior maps whose 3-char prefix conflates regions
# (m20 = Belurat 20000 + Enir-Ilim 20010; m12_05 = Mohgwyn 12050 vs the rest of m12 = Eternal
# Cities). The grace's own play_region_id (grace_region_map = greg) is authoritative; the coarse
# _pref2maj vote below cannot tell these apart. Mirrors the DUNGEON_REGION_OVERRIDE check fix.
_GRACE_PR_REGION = {"20000": "Belurat", "20010": "Enir-Ilim", "12050": "Mohgwyn Palace"}
_open_cand = defaultdict(list)
_open_cand_ow = defaultdict(list)   # overworld-only (m60/m61) graces: visible + warpable front doors
for _fl, _tile in gf.items():          # gf = {warpUnlockFlag(str): mapTile}, built at top
    if int(_fl) in _SKIP_GRACE_FLAGS: continue          # boss-gated / arena grace: never force-light
    _mj = None
    _m = re.match(r"m60_(\d\d)_(\d\d)", _tile)
    if _m:
        # OVERWORLD grace: the grace's own play_region_id (grace_region_map = ground truth) beats the
        # per-tile anchor VOTE, which mis-buckets graces on contested boundary tiles -- 76301 "Altus
        # Plateau" (tile 38,50) and 76502 "Grand Lift of Rold" (tile 49,53) have play_region 63xxx
        # (Altus) but their tiles vote Liurnia / Mountaintops. Fall back to the tile NN when the grace
        # has no overworld play_region entry. Interior/dungeon graces (no m60 tile) keep the prefix path.
        _mj = PLAY2AP.get(greg.get(_fl)) or PLAY2AP.get(tile_pr(int(_m.group(1)), int(_m.group(2))))
    if not _mj: _mj = _GRACE_PR_REGION.get(greg.get(_fl))   # split-map: per-play_region (authoritative)
    if not _mj: _mj = _pref2maj.get(_map_pref(_tile))
    if _mj and _mj != HUB:
        _open_cand[_mj].append(int(_fl))
        if _tile[:3] in ("m60", "m61"): _open_cand_ow[_mj].append(int(_fl))
# Front-door grace = an ACCESSIBLE OVERWORLD grace (m60/m61), NOT the numerically-lowest flag, which
# is often a catacomb/cave INTERIOR grace the player can never see (e.g. Limgrave min was 73000 =
# m30_00_00 catacomb -> "no graces in-game"). Serves as the region-open flag AND the start/front-door
# grace. Fall back to any grace only for a pure-dungeon bucket with no overworld grace at all.
def _front_door(r):
    return min(_open_cand_ow[r]) if _open_cand_ow.get(r) else min(_open_cand[r])
REGION_OPEN_FLAGS = {r: _front_door(r) for r in spokes if _open_cand.get(r)}
# DLC sub-areas whose locations are all boss-arena/PENDING never resolve to a grace above (their
# m61 tiles collapse into Land of Shadow's coarse bucket). Hand-verified front-door warp graces
# from grace_flags.tsv (grace_name-labeled) give them their own open flag:
#   Abyssal Woods -> 76860 'Abyssal Woods' (m61_50_42); Jagged Peak -> 76850 'Foot of the Jagged
#   Peak' (m61_52_40); Scadu Altus -> 76900 'Highroad Cross' (m61_48_45).
_DLC_OPEN_FALLBACK = {'Abyssal Woods': 76860, 'Jagged Peak': 76850, 'Scadu Altus': 76900,
                      # DLC legacy dungeons with only boss-arena locations (no grace resolves
                      # via _open_cand) -> hand-verified front-door warp graces (grace_region_map):
                      'Ancient Ruins of Rauh': 76941,  # 'Rauh Ancient Ruins, East' (m61_46_47)
                      'Enir-Ilim': 72012}              # 'Enir-Ilim: Outer Wall' (m20 entrance)
for _dr, _df in _DLC_OPEN_FALLBACK.items():
    if _dr in spokes and _dr not in REGION_OPEN_FLAGS:
        REGION_OPEN_FLAGS[_dr] = _df
REGION_OPEN_PENDING = [r for r in spokes if r not in REGION_OPEN_FLAGS]
OUT_OPEN = os.path.join(HERE, "eldenring_gf", "region_open_flags.py")
with open(OUT_OPEN, "w", encoding="utf-8") as _f:
    _f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot\n')
    _f.write('contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in\n')
    _f.write('the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""\n')
    _f.write("REGION_OPEN_FLAGS = {\n")
    for _r in spokes:
        if _r in REGION_OPEN_FLAGS: _f.write(f"    {_r!r}: {REGION_OPEN_FLAGS[_r]},\n")
    _f.write("}\n\nREGION_OPEN_PENDING = [\n")
    for _r in REGION_OPEN_PENDING: _f.write(f"    {_r!r},\n")
    _f.write("]\n")
print(f"region_open_flags: {len(REGION_OPEN_FLAGS)} resolved, {len(REGION_OPEN_PENDING)} pending -> {REGION_OPEN_PENDING}")


# ---- Phase 3 region bosses: the 25 major bosses (method=boss_arena), joined to greenfield ap-ids
# by FLAG (matt-free). Members-per-dungeon sweeps need a boss-kill-flag enrichment the backbone
# lacks (SPEC-PARITY.md P3), so only the labeled region bosses are emitted here.
_flag2apid = {int(r["flag"]): BASE_AP + i for i, r in enumerate(rows)}
_region_bosses = defaultdict(list)
for r in rows:
    if r["method"] == "boss_arena":
        reg = region_of(r); fl = int(r["flag"])
        _region_bosses[reg].append((_flag2apid[fl], fl, r["item_name"] or "boss"))

# ---- Non-standard region bosses missed by the method=boss_arena capture (matt-free special-case).
# Some major bosses do NOT resolve into a standard remembrance-drop boss_arena row, so the flag-join
# above never sees them. Captured here keyed to the ARTIFACT-VERIFIED boss-defeat flag from the map
# EMEVD (HandleBossDefeatAndDisplayBanner(<flag>, LegendFelled)), joined to the greenfield ap-id via
# the boss's reward-obtained flag (reward_join_flag). Tuple appended is (boss_ap_id, defeat_flag,
# reward_name) -- same shape as the boss_arena rows -- so features/boss_locks emits a correct
# "Felled: <boss>" trophy under the right region.
#   Rennala / Raya Lucaria Academy: her kill triggers the rebirth mechanic (Great Rune of the Unborn
#   + Remembrance of the Full Moon Queen), so her reward row is method=emevd (flag 197) and is even
#   mis-pinned to Stormveil in region_map.csv -- both reasons the boss_arena join skips her. Defeat
#   flag 14000800 verified in elden_ring_artifacts/event/m14_00_00_00.emevd.dcx.js.
# (region, defeat_flag, reward_join_flag, reward_name)
_BOSS_SPECIALS = [
    ("Liurnia of the Lakes", 14000800, 197, "Remembrance of the Full Moon Queen"),  # Rennala; Raya Lucaria folded into Liurnia
    # Loretta, Knight of the Haligtree: m15 boss (healthbar entity 15000850) who drops a sorcery
    # (Loretta's Mastery, 510190) rather than a remembrance, so the boss_arena join skips her. Her
    # drop is GLOBAL_RECOVER'd to Miquella's Haligtree above; register her as the region boss keyed to
    # defeat flag 15000850 (verified in BOSS_HEALTHBARS / m15_00 EMEVD), joined via 510190.
    ("Miquella's Haligtree", 15000850, 510190, "[Sorcery] Loretta's Mastery"),
]
for _reg, _dfl, _jfl, _nm in _BOSS_SPECIALS:
    _aid = _flag2apid.get(_jfl)
    if _aid is None:
        print(f"boss_data WARN: special boss {_nm!r} join flag {_jfl} absent from rows -- skipped")
        continue
    if any(t[1] == _dfl for t in _region_bosses[_reg]):
        continue  # already captured (defeat flag present) -- keep idempotent
    _region_bosses[_reg].append((_aid, _dfl, _nm))
OUT_BOSS = os.path.join(HERE, "eldenring_gf", "boss_data.py")
with open(OUT_BOSS, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,\n')
    f.write('joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""\n')
    f.write("REGION_BOSSES = {\n")
    for reg in sorted(_region_bosses):
        f.write(f"    {reg!r}: [\n")
        for aid, fl, nm in _region_bosses[reg]:
            f.write(f"        ({aid}, {fl}, {nm!r}),\n")
        f.write("    ],\n")
    f.write("}\n")
print(f"boss_data: {sum(len(v) for v in _region_bosses.values())} region bosses across {len(_region_bosses)} regions -> {sorted(_region_bosses)}")


# ---- Phase 6 grace rando: ALL warp graces per major region (matt-free; reuses _open_cand from the
# region-open-flags block above -- same grace_flags.tsv source). Bundle mode lights these on lock
# receipt; freebie+scatter is a v2 enhancement.
def _graces_frontdoor_first(r):
    _fs = sorted(_open_cand[r]); _fd = _front_door(r)
    return [_fd] + [f for f in _fs if f != _fd]
REGION_GRACE_POINTS = {r: _graces_frontdoor_first(r) for r in spokes if _open_cand.get(r)}
OUT_GRACES = os.path.join(HERE, "eldenring_gf", "region_graces.py")
with open(OUT_GRACES, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). All warp graces per major region (grace_flags.tsv). Matt-free."""\n')
    f.write("REGION_GRACE_POINTS = {\n")
    for r in spokes:
        if REGION_GRACE_POINTS.get(r):
            f.write(f"    {r!r}: {REGION_GRACE_POINTS[r]},\n")
    f.write("}\n")
print(f"region_graces: {sum(len(v) for v in REGION_GRACE_POINTS.values())} graces across {len(REGION_GRACE_POINTS)} regions")




# ---- Phase 4 shops: shop-purchase checks keyed by greenfield ap-id -> ShopLineupParam stock flag.
# Matt-free: region_map rows with method in {shop_merchant, shop_multi} carry flag_source=="shop",
# and for those rows region_map's `flag` IS ShopLineupParam.eventFlag_forStock (verified 505/505 on
# disk). cookbook rows are map_lot/enemy_lot pickups (not shop purchases) so they're NOT shop checks.
# SHOP_ROW_FLAGS {str(ap_id): stock_flag} is the client purchase-detect table; SHOP_LOC_REGION lets
# the feature scope to kept regions; SHOP_PREVIEW_GOODS {str(ap_id): vanilla equipId} (single-good
# rows only) is the vanilla preview. Degrades to empty if ShopLineupParam is absent.
_SLP_DIR = os.path.join(AR, "vanilla_er", "vanilla_er")
_SLP = os.path.join(_SLP_DIR, "ShopLineupParam.csv")
_REC = os.path.join(_SLP_DIR, "ShopLineupParam_Recipe.csv")
_flag2goods = defaultdict(list)   # stock_flag -> [(equipId, equipType)]
_flag2rows = defaultdict(list)    # stock_flag -> [ShopLineupParam row ID] (client shopRowFlags key)
_CAT_NIB = {0:0x00000000,1:0x10000000,2:0x20000000,3:0x40000000,4:0x80000000}
DRAGONHEART_FLAGS = set()         # stock flags whose ShopLineupParam row is paid in Dragon Hearts
                                  # (costType==1) = the Dragon Communion incantation altars -> missable.
_slp_present = os.path.isfile(_SLP)
if _slp_present:
    for _src in [_SLP] + ([_REC] if os.path.isfile(_REC) else []):
        for _sr in csv.DictReader(open(_src)):
            try:
                _fl = int(_sr["eventFlag_forStock"])
            except (KeyError, ValueError):
                continue
            if _fl <= 0:
                continue
            try:
                if int(_sr.get("costType", 0)) == 1:
                    DRAGONHEART_FLAGS.add(_fl)
            except (KeyError, ValueError):
                pass
            try:
                _flag2rows[_fl].append(int(_sr["ID"]))
            except (KeyError, ValueError):
                pass
            try:
                _flag2goods[_fl].append((int(_sr["equipId"]), int(_sr.get("equipType", 3))))
            except (KeyError, ValueError):
                pass
_SHOP_METHODS = {"shop_merchant", "shop_multi"}
SHOP_ROW_FLAGS = {}
SHOP_ROW_IDS = {}
SHOP_LOC_REGION = {}
SHOP_PREVIEW_GOODS = {}
for _i, _r in enumerate(rows):
    if _r["method"] not in _SHOP_METHODS or _r.get("flag_source") != "shop":
        continue
    try:
        _fl = int(_r["flag"])
    except (KeyError, ValueError):
        continue
    _aid = BASE_AP + _i
    SHOP_ROW_FLAGS[str(_aid)] = _fl
    # ShopLineupParam row ids whose eventFlag_forStock == this flag (client writes this flag
    # onto those rows). Usually one; a flag shared across rows lists them all (all get asserted).
    SHOP_ROW_IDS[str(_aid)] = sorted(set(_flag2rows.get(_fl, [])))
    SHOP_LOC_REGION[_aid] = region_of(_r)
    _goods = _flag2goods.get(_fl)
    if _goods and len({_e for _e, _t in _goods}) == 1:
        _eid, _et = _goods[0]
        SHOP_PREVIEW_GOODS[str(_aid)] = _eid | _CAT_NIB.get(_et, 0x40000000)
OUT_SHOP = os.path.join(HERE, "eldenring_gf", "shop_data.py")
with open(OUT_SHOP, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Shop-purchase checks: greenfield ap-id -> ShopLineupParam\n')
    f.write('eventFlag_forStock (region_map shop rows, flag_source=="shop"). Matt-free; preview goods are\n')
    f.write('vanilla equipIds. Empty if ShopLineupParam is absent (SPEC-PARITY.md 14.3)."""\n')
    f.write("SHOP_ROW_FLAGS = {\n")
    for _aid in sorted(SHOP_ROW_FLAGS, key=int):
        f.write(f"    {_aid!r}: {SHOP_ROW_FLAGS[_aid]},\n")
    f.write("}\n\nSHOP_ROW_IDS = {\n")
    for _aid in sorted(SHOP_ROW_IDS, key=int):
        f.write(f"    {_aid!r}: {SHOP_ROW_IDS[_aid]!r},\n")
    f.write("}\n\nSHOP_LOC_REGION = {\n")
    for _aid in sorted(SHOP_LOC_REGION):
        f.write(f"    {_aid}: {SHOP_LOC_REGION[_aid]!r},\n")
    f.write("}\n\nSHOP_PREVIEW_GOODS = {\n")
    for _aid in sorted(SHOP_PREVIEW_GOODS, key=int):
        f.write(f"    {_aid!r}: {SHOP_PREVIEW_GOODS[_aid]},\n")
    f.write("}\n")
print(f"shop_data: {len(SHOP_ROW_FLAGS)} shop checks, {len(SHOP_PREVIEW_GOODS)} with preview goods across {len(set(SHOP_LOC_REGION.values()))} regions (param_present={_slp_present})")

# ---- missable_locations.py: ap_ids of checks gated behind a limited consumable / killable NPC ------
# (matt-free). features/missable_locations.py forbids REQUIRED progression at these so the seed stays
# winnable if the player can't (or doesn't) reach them. Selected by flag: deathroot Gurranq rewards +
# Dragon-Communion (Dragon-Heart) shop purchases. `rows` is positional -> ap_id == BASE_AP + index
# (same indexing the bucket + shop loops use). Sources tagged for legibility / future stonesword add.
_MISSABLE = {}   # ap_id -> source label ("deathroot" | "dragon_heart")
for _i, _r in enumerate(rows):
    try: _mf = int(_r["flag"])
    except (KeyError, ValueError): continue
    if _mf in DEATHROOT_FLAGS:
        _MISSABLE[BASE_AP + _i] = "deathroot"
    elif _mf in DRAGONHEART_FLAGS:
        _MISSABLE[BASE_AP + _i] = "dragon_heart"
OUT_MISS = os.path.join(HERE, "eldenring_gf", "missable_locations.py")
with open(OUT_MISS, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). ap_ids of MISSABLE checks -- gated behind a limited\n')
    f.write('consumable or a killable NPC (deathroot Gurranq rewards; Dragon-Heart / Dragon Communion\n')
    f.write('purchases). features/missable_locations.py forbids required progression here. Matt-free\n')
    f.write('(deathroot flags 400230-400239; dragon-heart = ShopLineupParam costType==1)."""\n')
    f.write("MISSABLE_LOCATIONS = {\n")
    for _aid in sorted(_MISSABLE):
        f.write(f"    {_aid}: {_MISSABLE[_aid]!r},\n")
    f.write("}\n")
_mc = Counter(_MISSABLE.values())
print(f"missable_locations: {len(_MISSABLE)} checks (deathroot={_mc.get('deathroot',0)}, dragon_heart={_mc.get('dragon_heart',0)})")


# ---- Real-item-pool foundation: each location's vanilla item -> its ER FullID (matt-free).
# Names come from the WitchyBND FMG exports (msg/item-msgbnd-dcx + the item_dlc0{1,2}-msgbnd-dcx
# DLC name tables, *Name.fmg.xml); id == EquipParam/Goods/Gem id (verified Golden Rune [1]=2900 ->
# 0x40000B54, Golden Rune [12]=2911 -> 0x40000B5F). name -> FullID = id | category nibble, priority
# weapon>armor>accessory>goods>gem on cross-category name clashes. NOTE (measured on disk): spells
# already live in GoodsName (e.g. Glintstone Pebble = Goods id 4000 -> 0x40000FA0) and Ashes of War
# in GemName (e.g. Ash of War: Barbaric Roar = Gem id 0x13068 -> 0x80013068); the MagicName/ArtsName
# tables are empty stubs / redundant with GemName here and add no coverage, so they are omitted.
# Coverage beyond a direct hit is lifted by (a) the DLC name tables and (b) mechanically stripping the
# location bread-crumbs region_map decorates vanilla names with -- a leading "LG/(CE): " area code, a
# trailing " - <where>", a trailing " x<N>" count, and a "[Sorcery]/[Incantation]/[Ash of War]/[Skill]"
# prefix -- to re-match the BASE item, then falling back to a whitespace-normalized + diacritic-folded
# (accent/case-insensitive) match (0 fold collisions on this data). All matt-free: pure FMG/param joins
# plus mechanical string trims, no curation, no guessed ids. Emits item_ids.py:
#   ITEM_CATALOG {item_name: FullID}   -- distinct resolved BASE items (the AP item catalog)
#   LOCATION_ITEM {ap_id: item_name}   -- the BASE vanilla item that sits at each resolved location
#     (annotated location strings resolve to the base catalog name, so the same location grants base).
# Unresolved names (empty item_name, quest "Note:" text, source typos, items in no FMG) are omitted ->
# core falls back to Rune filler. Guard-to-empty if the FMG name dirs are absent.
import xml.etree.ElementTree as _ET
import unicodedata as _UD
_MSG    = os.path.join(AR, "msg", "item-msgbnd-dcx")
_MSG_D1 = os.path.join(AR, "msg", "item_dlc01-msgbnd-dcx")
_MSG_D2 = os.path.join(AR, "msg", "item_dlc02-msgbnd-dcx")
# (filename, category nibble, dir). base tables first so base ids win over DLC on any name clash.
_NAME_FMGS = [
    ("WeaponName.fmg.xml",    0x00000000, _MSG), ("ProtectorName.fmg.xml", 0x10000000, _MSG),
    ("AccessoryName.fmg.xml", 0x20000000, _MSG), ("GoodsName.fmg.xml",      0x40000000, _MSG),
    ("GemName.fmg.xml",       0x80000000, _MSG),
    ("WeaponName_dlc01.fmg.xml",    0x00000000, _MSG_D1), ("ProtectorName_dlc01.fmg.xml", 0x10000000, _MSG_D1),
    ("AccessoryName_dlc01.fmg.xml", 0x20000000, _MSG_D1), ("GoodsName_dlc01.fmg.xml",      0x40000000, _MSG_D1),
    ("GemName_dlc01.fmg.xml",       0x80000000, _MSG_D1),
    ("WeaponName_dlc02.fmg.xml",    0x00000000, _MSG_D2), ("ProtectorName_dlc02.fmg.xml", 0x10000000, _MSG_D2),
    ("AccessoryName_dlc02.fmg.xml", 0x20000000, _MSG_D2), ("GoodsName_dlc02.fmg.xml",      0x40000000, _MSG_D2),
    ("GemName_dlc02.fmg.xml",       0x80000000, _MSG_D2),
]
def _norm(_s):                                   # collapse internal whitespace
    return re.sub(r"\s+", " ", _s).strip()
def _fold(_s):                                   # accent-insensitive, case-insensitive key
    _s = _UD.normalize("NFKD", _norm(_s))
    return "".join(_c for _c in _s if not _UD.combining(_c)).casefold()
_name2full = {}        # exact display name -> FullID (first/higher-priority category wins)
_norm2full = {}; _norm2name = {}    # normalized name -> FullID / canonical display name
_fold2full = {}; _fold2name = {}    # folded name     -> FullID / canonical display name
for _fn, _nib, _dir in _NAME_FMGS:
    _p = os.path.join(_dir, _fn)
    if not os.path.exists(_p):
        continue
    for _t in _ET.parse(_p).getroot().iter("text"):
        _nm = (_t.text or "").strip(); _iid = _t.get("id")
        if not _nm or _nm in ("[ERROR]", "%null%") or not _iid:
            continue
        _full = int(_iid) | _nib
        if _nm not in _name2full:
            _name2full[_nm] = _full
        _nn = _norm(_nm)
        if _nn not in _norm2full:
            _norm2full[_nn] = _full; _norm2name[_nn] = _nm
        _ff = _fold(_nm)
        if _ff not in _fold2full:
            _fold2full[_ff] = _full; _fold2name[_ff] = _nm
# annotation strippers (region_map decorates vanilla names with location bread-crumbs)
_LEAD_RE   = re.compile(r"^[A-Z][A-Za-z0-9/()]*\s*:\s*")           # "LG/(CE): " / "RH: " / "MA/(LER): "
_ANNOT_RE  = re.compile(r"\s+-\s+.*$")                              # " - to SW up right stairs outside"
_COUNT_RE  = re.compile(r"\s*[x×]\s*\d+\s*$", re.I)        # trailing " x3" / " ×3"
_PREFIX_RE = re.compile(r"^\[(?:Sorcery|Incantation|Ash of War|Skill)\]\s*", re.I)
def _resolve_item(_raw):
    """(FullID, canonical_base_name) or (None, None). Matt-free mechanical strips + accent fold only."""
    _raw = (_raw or "").strip()
    if not _raw:
        return (None, None)
    _tries = []
    def _add(_s):
        _s = _norm(_s)
        if _s and _s not in _tries:
            _tries.append(_s)
    _add(_raw)
    _lead = _LEAD_RE.sub("", _raw); _add(_lead); _add(_ANNOT_RE.sub("", _lead))
    _core = _COUNT_RE.sub("", _ANNOT_RE.sub("", _lead)); _add(_core); _add(_PREFIX_RE.sub("", _core))
    for _t in _tries:                            # exact normalized hit -> canonical display name
        if _t in _norm2full:
            return (_norm2full[_t], _norm2name[_t])
    for _t in _tries:                            # accent/case-folded fallback -> canonical name
        _ff = _fold(_t)
        if _ff in _fold2full:
            return (_fold2full[_ff], _fold2name[_ff])
    return (None, None)
ITEM_CATALOG = {}; LOCATION_ITEM = {}
for _i, _r in enumerate(rows):
    _full, _base = _resolve_item(_r.get("item_name"))
    if _full is None:
        continue
    ITEM_CATALOG[_base] = _full                  # catalog keyed by canonical base name
    LOCATION_ITEM[BASE_AP + _i] = _base          # annotated locations -> base catalog name
# Finished throwing pots: crafted (never LOOTED), so absent from the placed-item catalog above -- but
# they are valid grantable GOODS (EquipParamGoods ids verified against GoodsName.fmg.xml). Added
# explicitly so the curated-consumables filler (features/filler_curation.py) can hand them out; the
# client grants them by FullID like any other good. Base game (not DLC).
_FINISHED_POTS = {"Fire Pot": 300, "Lightning Pot": 320, "Fetid Pot": 330, "Holy Water Pot": 350,
                  "Freezing Pot": 360, "Poison Pot": 370, "Volcano Pot": 600, "Sleep Pot": 640,
                  "Rancor Pot": 650}
for _pn, _pid in _FINISHED_POTS.items():
    ITEM_CATALOG.setdefault(_pn, 0x40000000 | _pid)
# ---- Community tier-list catalog augmentation (Alaric 2026-07-09). The broad-sourced community PvE
# tier list (item_tiers.tsv) rates GEAR -- weapons / armor / spells+incantations / talismans / ashes
# of war -- much of which greenfield never DETECTED as a placed vanilla item (e.g. Moonveil, Nagakiba,
# Golden Order Greatsword, the Banished Knight / Bull-Goat / Cleanrot armor sets). Those names never
# entered ITEM_CATALOG from `rows` above, so features/pool_builder (which only juices names present in
# ITEM_CATALOG) could never inject them and the tier list only informed the fraction of gear greenfield
# happened to place. Resolve every gear-category tier-list name to its real FMG FullID via the same
# _resolve_item map used for placed items and add it to the catalog so the FULL community list informs
# the injected gear. Only the INJECTABLE tiers (S/A/B -- pool_builder never juices C/D/F) are added, to
# avoid catalog bloat. Count-NEUTRAL: this only widens the pool_builder juice CANDIDATE set (juice is
# bounded by the Rune tail); the base shuffle pool is LOCATION_ITEM (placed items) and is untouched.
# DLC-only names among them are flagged by the DLC_ITEM_NAMES pass below (so DLC-off seeds exclude them).
_TIER_CATALOG_CATS = {"WEAPON", "ARMOR", "SPELL", "TALISMAN", "ASHOFWAR"}
_TIER_CATALOG_KEEP = {"S", "A", "B"}
_tier_tsv = os.path.join(REPO, "item_tiers.tsv")
_aug_added = 0; _aug_unresolved = []
if os.path.isfile(_tier_tsv):
    for _row in csv.DictReader(open(_tier_tsv, encoding="utf-8"), delimiter="\t"):
        if _row.get("category") not in _TIER_CATALOG_CATS or _row.get("tier") not in _TIER_CATALOG_KEEP:
            continue
        _nm = (_row.get("item_name") or "").strip()
        if not _nm or _nm in ITEM_CATALOG:
            continue
        _full, _base = _resolve_item(_nm)
        if _full is None:
            _aug_unresolved.append(_nm); continue
        if _base not in ITEM_CATALOG:
            ITEM_CATALOG[_base] = _full; _aug_added += 1
    print(f"item_ids: tier-list catalog augmentation +{_aug_added} gear items "
          f"({len(_aug_unresolved)} unresolved names skipped)")
# ---- DLC provenance: catalog names that come ONLY from the DLC FMG tables. gen_data reads the
# base tables (_MSG) and the DLC tables (_MSG_D1/_MSG_D2) into ITEM_CATALOG with no marker; core
# excludes these from pool augmentation (juice/filler) when a seed has DLC off. Matt-free: pure
# table membership (dlc-table names minus base-table names), no curation. Base<->DLC name
# collisions (e.g. Golden Vow, Larval Tear) resolve to BASE and are therefore NOT excluded.
_dlc_base_nm = set(); _dlc_dlc_nm = set()
for _fn, _nib, _dir in _NAME_FMGS:
    _p = os.path.join(_dir, _fn)
    if not os.path.exists(_p):
        continue
    _tgt = _dlc_base_nm if _dir == _MSG else _dlc_dlc_nm
    for _t in _ET.parse(_p).getroot().iter("text"):
        _nm = (_t.text or "").strip()
        if _nm and _nm not in ("[ERROR]", "%null%"):
            _tgt.add(_nm)
_DLC_ONLY = _dlc_dlc_nm - _dlc_base_nm
DLC_ITEM_NAMES = {_n for _n in ITEM_CATALOG if _n in _DLC_ONLY}
print(f"item_ids: DLC_ITEM_NAMES {len(DLC_ITEM_NAMES)} DLC-only catalog items")
OUT_ITEMS = os.path.join(HERE, "eldenring_gf", "item_ids.py")
with open(OUT_ITEMS, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Real-item-pool: vanilla item_name -> ER FullID, from the\n')
    f.write('FMG name exports (base + DLC, matt-free). ITEM_CATALOG = distinct {name: FullID}; LOCATION_ITEM =\n')
    f.write('{ap_id: base name}. Unresolved locations fall back to Rune filler. core ItemShuffle consumes this."""\n')
    f.write("ITEM_CATALOG = {\n")
    for _nm in sorted(ITEM_CATALOG):
        f.write(f"    {ascii(_nm)}: {ITEM_CATALOG[_nm]},\n")
    f.write("}\n\nLOCATION_ITEM = {\n")
    for _aid in sorted(LOCATION_ITEM):
        f.write(f"    {_aid}: {ascii(LOCATION_ITEM[_aid])},\n")
    f.write("}\n\nDLC_ITEM_NAMES = {\n")
    for _nm in sorted(DLC_ITEM_NAMES):
        f.write(f"    {ascii(_nm)},\n")
    f.write("}\n")
_cov = 100.0 * len(LOCATION_ITEM) / max(len(rows), 1)
print(f"item_ids: {len(ITEM_CATALOG)} distinct items, {len(LOCATION_ITEM)} locations resolved ({_cov:.1f}%)")


# ---- FILLER_POOL: varied real-junk filler (matt-free). Goods-tier consumables/materials from the
# catalog (greases, boluses, butterflies, glowstones, stones, etc.) -- the generic common-event junk.
# core draws received filler from this instead of a monotone "Rune". Junk only (goods-tier, excludes
# tears/great runes/key items/spells/cookbooks/whetblades/maps): mechanical EquipParamGoods filter --
# goodsType in {0 normal, 2 crafting material, 14 reinforcement}, isConsume=1, rarity<=1 -- plus a
# tiny name guard for quest-adjacent goods the type/rarity columns don't separate.
# [RECONSTRUCTED 2026-07-06: the original section was lost to a mount truncation of this file; same
#  contract (item_ids.py FILLER_POOL = [junk good names]), filter re-derived from params.]
_GOODS_CSV = os.path.join(_SLP_DIR, "EquipParamGoods.csv")
_FILLER_TYPES = {"0", "2", "14"}
# NOTE (A, 2026-07-07): Smithing/Somber smithing stones are DELIBERATELY NOT guarded here -- they are
# rarity<=1 reinforcement goods (type 14), so they pass the filter and land in FILLER_POOL, where
# varied_filler distributes them as fill-safe upgrade materials. pool_builder juices EQUIPPABLES only
# (goods are omitted from ITEM_TIERS), so without this stones would be handled by nobody. The rarity<=1
# gate keeps the end-tier Ancient Dragon (Somber) stones (rarity 3) OUT. Golden Seed / Sacred Tear /
# Scadutree Fragment / Revered Spirit Ash are rarity>=2 -> already excluded by the rarity gate (capped
# resources, correctly kept out). Stone density here is tuned against the per-sphere upgrade curve
# measured by tools/analyze_upgrade_curve.py.
_FILLER_NAME_GUARD = ("Deathroot", "Dragon Heart", "Rune Arc", "Larval Tear", "Golden Seed",
                      "Sacred Tear", "Memory Stone", "Talisman Pouch", "Great Rune", "Map:")
FILLER_POOL = []
if os.path.isfile(_GOODS_CSV):
    _junk_ok = {}
    for _row in csv.DictReader(open(_GOODS_CSV, newline="", encoding="utf-8", errors="replace")):
        try:
            _junk_ok[int(_row["ID"])] = (_row.get("goodsType") in _FILLER_TYPES
                                         and _row.get("isConsume") == "1"
                                         and int(_row.get("rarity") or 9) <= 1)
        except (KeyError, ValueError):
            continue
    for _nm in sorted(ITEM_CATALOG):
        _full = ITEM_CATALOG[_nm]
        if (_full & 0xF0000000) != 0x40000000:      # GOODS nibble only
            continue
        if not _junk_ok.get(_full & 0x0FFFFFFF, False):
            continue
        if any(_g in _nm for _g in _FILLER_NAME_GUARD):
            continue
        FILLER_POOL.append(_nm)
with open(OUT_ITEMS, "a", newline="\n", encoding="utf-8") as f:
    f.write("\n# Varied junk filler (goods-tier consumables/materials); features/varied_filler consumes this.\n")
    f.write("FILLER_POOL = [\n")
    for _nm in FILLER_POOL:
        f.write(f"    {ascii(_nm)},\n")
    f.write("]\n")
print(f"filler_pool: {len(FILLER_POOL)} junk goods -> item_ids.py FILLER_POOL")


# ---- Phase 5 pool-builder tiers: vanilla item quality from the ER param `rarity` column
# (matt-free -- param-derived, no curation). Joins each ITEM_CATALOG FullID back to its EquipParam
# row (weapon/protector/accessory) and reads `rarity` (0=trivial/ammo, 1=common, 2=rare,
# 3=legendary). Goods (0x40000000) and gems/ashes (0x80000000) are not equippable "juice" and are
# omitted -> they stay filler. Emits item_tiers.py:  ITEM_TIERS {item_name: rarity 0..3}.
# Degrades to an empty map if the vanilla_er param CSVs are absent (feature then no-ops).
_TIER_PARAMS = [(0x00000000, "EquipParamWeapon.csv"),      # weapons/staves/shields/bows (nibble 0x0)
                (0x10000000, "EquipParamProtector.csv"),   # armor                        (nibble 0x1)
                (0x20000000, "EquipParamAccessory.csv")]   # talismans                    (nibble 0x2)
_rarity_by_full = {}   # FullID (id | category nibble) -> rarity int
for _nib, _csv in _TIER_PARAMS:
    _p = os.path.join(_SLP_DIR, _csv)
    if not os.path.isfile(_p):
        continue
    for _row in csv.DictReader(open(_p, newline="", encoding="utf-8", errors="replace")):
        try:
            _rarity_by_full[(int(_row["ID"]) | _nib)] = int(_row["rarity"])
        except (KeyError, ValueError):
            continue
# Param rarity is the FALLBACK tier (talismans + any equippable the curated TSV omits).
_param_tier = {}
for _nm, _full in ITEM_CATALOG.items():
    _r = _rarity_by_full.get(_full)
    if _r is not None:
        _param_tier[_nm] = _r
# Curated PvE tiers (item_tiers.tsv): broad-sourced, provenance-clean (NOT param-derived, NOT matt IP).
# Authoritative for every category it covers -- weapons, armor, spells/incantations, ashes of war --
# so it TAKES PRECEDENCE over param rarity. Letters map to the numeric floors pool_builder uses:
# S->3 (juice at 'normal'+), A->2 (juice at 'high'/default), B->1 (juice at 'max'), C/D/F->0 (never
# juiced). Names are matched to ITEM_CATALOG; unresolved rows (DLC/name-variant/not-a-check) are skipped.
_LETTER_TIER = {"S": 3, "A": 2, "B": 1, "C": 0, "D": 0, "F": 0}
_tsv_tier = {}
_TSV_PATH = os.path.join(REPO, "item_tiers.tsv")
if os.path.isfile(_TSV_PATH):
    for _row in csv.DictReader(open(_TSV_PATH, encoding="utf-8"), delimiter="\t"):
        _t = _LETTER_TIER.get((_row.get("tier") or "").strip().upper())
        _nm = (_row.get("item_name") or "").strip()
        if _t is not None and _nm in ITEM_CATALOG:
            _tsv_tier[_nm] = _t
ITEM_TIERS = dict(_param_tier); ITEM_TIERS.update(_tsv_tier)   # TSV precedence; param fills the gaps
OUT_TIERS = os.path.join(HERE, "eldenring_gf", "item_tiers.py")
with open(OUT_TIERS, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Pool-builder tiers: vanilla item_name -> quality\n')
    f.write('tier 0..3. PRIMARY source = item_tiers.tsv (curated PvE tiers, broad-sourced, provenance-clean,\n')
    f.write('NOT matt IP; S->3 A->2 B->1 C/D/F->0) covering weapons/armor/spells/ashes-of-war. ER param\n')
    f.write('`rarity` (EquipParamWeapon/Protector/Accessory) fills the gaps (talismans + TSV-omitted items).\n')
    f.write('features/pool_builder.py consumes this."""\n')
    f.write("ITEM_TIERS = {\n")
    for _nm in sorted(ITEM_TIERS):
        f.write(f"    {_nm!r}: {ITEM_TIERS[_nm]},\n")
    f.write("}\n")
from collections import Counter as _Cnt
_td = _Cnt(ITEM_TIERS.values())
print(f"item_tiers: {len(ITEM_TIERS)} equippables tiered "
      f"(legendary={_td.get(3,0)}, rare={_td.get(2,0)}, common={_td.get(1,0)}, trivial={_td.get(0,0)})")


# ---- location_tags.py: {ap_id: [type,...]} + TAG_COUNTS (important_locations source, matt-free) ----
# Written HERE (after ITEM_TIERS) so big-ticket types that need the greenfield catalog / param rarity
# can be added on top of the name/method tags _loc_tags collected inline (Boss/Remembrance/Church/
# Seedtree/Basin/Fragment/Revered/Shop): GreatRune + KeyItem from LOCATION_ITEM (greenfield catalog
# name), Legendary from ITEM_TIERS rarity==3. Matt-free (own catalog + param rarity, no curation).
OUT_TAGS = os.path.join(HERE, "eldenring_gf", "location_tags.py")
_KEYITEMS = ("Dectus Medallion", "Rold Medallion", "Haligtree Secret Medallion",
             "Carian Inverted Statue", "Rusty Key", "Discarded Palace Key", "Imbued Sword Key",
             "Academy Glintstone Key", "Dark Moon Ring", "Pureblood Knight's Medal",
             "Drawing-Room Key", "Rusty Anchor")
for _ap, _inm in LOCATION_ITEM.items():
    _extra = []
    if "Great Rune" in _inm and "Unborn" not in _inm:
        _extra.append("GreatRune")
    if any(_k in _inm for _k in _KEYITEMS):
        _extra.append("KeyItem")
    if ITEM_TIERS.get(_inm) == 3:
        _extra.append("Legendary")
        if "Shop" in loc_tags.get(_ap, ()):   # shop slot holding a legendary = Enia's remembrance store
            _extra.append("EniaShop")
    if _extra:
        _cur = loc_tags.setdefault(_ap, [])
        for _e in _extra:
            if _e not in _cur:
                _cur.append(_e)
import collections as _c
_tagcount = _c.Counter(tg for tags in loc_tags.values() for tg in tags)
with open(OUT_TAGS, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Location TYPE tags for important_locations, matt-free:\n')
    f.write('name/method tags (Boss/Remembrance/Church/Seedtree/Basin/Fragment/Revered/Shop) from\n')
    f.write('_loc_tags; GreatRune/KeyItem from LOCATION_ITEM name; Legendary from ITEM_TIERS rarity==3.\n')
    f.write('LOCATION_TAGS = {ap_id: [type,...]}."""\n')
    f.write('LOCATION_TAGS = {\n')
    for _aid in sorted(loc_tags):
        f.write(f'    {_aid}: {loc_tags[_aid]!r},\n')
    f.write('}\n\nTAG_COUNTS = ' + repr(dict(sorted(_tagcount.items()))) + '\n')
print(f'location_tags: {len(loc_tags)} tagged locations; counts ' + repr(dict(sorted(_tagcount.items()))))


# ---- Phase 3b boss sweeps (2026-07-08 rework -- scope by boss CLASS). Placed AFTER location_tags so
# the field filler-only cut sees the FULL tag set (GreatRune/KeyItem/Legendary added above). Triggers
# come from the authoritative DisplayBossHealthBar set (tools/datamine_boss_healthbars.py ->
# BOSS_HEALTHBARS); the trigger flag IS the boss entity id (== its defeat flag, SetEventFlagID(entity,
# ON) on death). Member scope by class:
#   legacy / interior (region majors)    -> REGION-WIDE + FILLER-ONLY (felling grants the region's
#                                           filler; important/big-ticket-tagged checks are excluded)
#   catacomb / cave / tunnel (m30/31/32) -> MAP-LOCAL     (only that dungeon map's own checks)
#   field / overworld (m60)              -> OWN-TILE + FILLER-ONLY (checks on the boss's m60_XX_YY tile
#                                           minus any important/big-ticket-tagged check)
# Recovered flag_prefix dungeon checks are swept map-locally, so a catacomb boss grants its whole
# catacomb. Falls back to the pre-rework region-wide banner scan if BOSS_HEALTHBARS is unavailable.
def _mp2(m):
    if not m or m == "PENDING":
        return None
    return "_".join(m.split("_")[:2])
def _is_dungeon(_mp):
    return bool(_mp) and _mp[:3] in ("m30", "m31", "m32", "m34", "m39", "m40", "m41", "m42", "m43")
# = contract.IMPORTANT_LOCATION_TYPES (superset of BIG_TICKET_TYPES); guarded vs drift by
# tests/test_gf_boss_sweeps.test_field_exclude_matches_contract.
_FIELD_EXCLUDE_TAGS = frozenset({"Remembrance", "Seedtree", "Church", "Boss", "Fragment", "Revered",
                                 "Basin", "GreatRune", "KeyItem", "Legendary", "Shop"})
_mem_region = defaultdict(list); _mem_map = defaultdict(list); _mem_tile = defaultdict(list)
_mreg = {}; _ap_region = {}
for _i, _r in enumerate(rows):
    _swept = _r["method"] in ("treasure", "emevd") or (
        _r["method"] == "flag_prefix" and _is_dungeon(_mp2(_r["map"])))
    if not _swept:
        continue
    _ap = BASE_AP + _i; _reg = region_of(_r); _mp = _mp2(_r["map"])
    _ap_region[_ap] = _reg
    _mem_region[_reg].append(_ap)
    if _mp:
        _mem_map[_mp].append(_ap); _mreg.setdefault(_mp, _reg)
    _mt = re.match(r"(m60_\d\d_\d\d)", _r["map"] or "")
    if _mt:
        _mem_tile[_mt.group(1)].append(_ap)
def _filler_only(_aps):
    return [_a for _a in _aps if not (_FIELD_EXCLUDE_TAGS & set(loc_tags.get(_a, ())))]

DUNGEON_SWEEPS = {}; SWEEP_REGION = {}
if BOSS_HEALTHBARS:
    for _ent, _info in sorted(BOSS_HEALTHBARS.items()):
        _bmap, _tile, _cls, _name = _info
        if _cls == "field":
            _members = _filler_only(_mem_tile.get(_tile, []))
        elif _cls in ("catacomb", "cave", "tunnel", "dungeon"):
            _members = _mem_map.get(_bmap, [])
        else:  # legacy / interior region major -> region-wide + FILLER-ONLY (same cut as field)
            _members = _filler_only(_mem_region.get(_mreg.get(_bmap, HUB), []))
        _members = sorted(set(_members))
        if not _members:
            continue  # e.g. a field boss whose tile has no (non-important) checks -> no sweep
        DUNGEON_SWEEPS[_ent] = _members
        # region label from a member's OWN region (own-tile/map-local members are region-consistent;
        # avoids a coarse m60_XX bucket mislabelling a field boss whose tile straddles a region).
        SWEEP_REGION[_ent] = _ap_region.get(_members[0], _mreg.get(_bmap, HUB))
else:
    # FALLBACK (module absent): pre-rework region-wide sweep keyed by the EMEVD felled-banner scan.
    import re as _re2
    _EVDIR = os.path.join(AR, "event"); _map_boss = defaultdict(list)
    if os.path.isdir(_EVDIR):
        for _fn in os.listdir(_EVDIR):
            _mm = _re2.match(r"(m\d\d_\d\d)_\d\d_\d\d\.emevd\.dcx\.js$", _fn)
            if not _mm:
                continue
            _txt = open(os.path.join(_EVDIR, _fn), encoding="utf-8", errors="replace").read()
            for _fl in _re2.findall(r"HandleBossDefeatAndDisplayBanner\((\d+),", _txt):
                _map_boss[_mm.group(1)].append(int(_fl))
    for _mp, _flags in _map_boss.items():
        _members = _mem_region.get(_mreg.get(_mp, HUB))
        if not _members:
            continue
        for _fl in _flags:
            DUNGEON_SWEEPS[_fl] = sorted(set(_members)); SWEEP_REGION[_fl] = _mreg.get(_mp, HUB)

OUT_SWEEP = os.path.join(HERE, "eldenring_gf", "boss_sweeps.py")
with open(OUT_SWEEP, "w", newline="\n", encoding="utf-8") as f:
    f.write('"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Boss sweeps: defeat flag (boss entity id) ->\n')
    f.write('member check ap-ids + region. Scope by class: legacy=region-wide+filler-only, catacomb/cave/tunnel=map-local, field=own-tile+filler-only. Matt-free. Needs a client flag-watch handler."""\n')
    f.write("DUNGEON_SWEEPS = {\n")
    for _fl in sorted(DUNGEON_SWEEPS):
        f.write(f"    {_fl}: {DUNGEON_SWEEPS[_fl]},\n")
    f.write("}\n\nSWEEP_REGION = {\n")
    for _fl in sorted(SWEEP_REGION):
        f.write(f"    {_fl}: {SWEEP_REGION[_fl]!r},\n")
    f.write("}\n")
print(f"boss_sweeps: {len(DUNGEON_SWEEPS)} triggers, {sum(len(v) for v in DUNGEON_SWEEPS.values())} member links across {len(set(SWEEP_REGION.values()))} regions "
      f"({'healthbar-classed' if BOSS_HEALTHBARS else 'FALLBACK region-wide banner scan'})")
