"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal Woods': [
        (7770785, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Altus Plateau': [
        (7770767, 510040, 'Remembrance of the Omen King'),
    ],
    'Ancient Ruins of Rauh': [
        (7770786, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Belurat': [
        (7770779, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Enir-Ilim': [
        (7770781, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Eternal Cities': [
        (7770768, 510080, 'Remembrance of the Naturalborn'),
        (7770770, 510110, 'Remembrance of the Lichdragon'),
        (7770778, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Farum Azula': [
        (7770772, 510150, 'Remembrance of the Dragonlord'),
        (7770773, 510160, 'Remembrance of the Black Blade'),
    ],
    'Gravesite Plain': [
        (7770783, 510480, 'Remembrance of Putrescence'),
        (7770791, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Liurnia of the Lakes': [
        (7770008, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    "Miquella's Haligtree": [
        (7770006, 176, "Malenia's Great Rune"),
        (7773902, 15000850, "[Sorcery] Loretta's Mastery"),
    ],
    'Mohgwyn Palace': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770777, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770775, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Scadu Altus': [
        (7770784, 510550, 'Remembrance of the Mother of Fingers'),
    ],
    'Shadow Keep': [
        (7770782, 510460, 'Remembrance of the Impaler'),
        (7770787, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770789, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Stormveil Castle': [
        (7770766, 510010, 'Remembrance of the Grafted'),
    ],
}
