"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal Woods': [
        (7770786, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Altus Plateau': [
        (7770768, 510040, 'Remembrance of the Omen King'),
    ],
    'Ancient Ruins of Rauh': [
        (7770787, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Belurat': [
        (7770780, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Enir-Ilim': [
        (7770782, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Eternal Cities': [
        (7770769, 510080, 'Remembrance of the Naturalborn'),
        (7770771, 510110, 'Remembrance of the Lichdragon'),
        (7770779, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Farum Azula': [
        (7770773, 510150, 'Remembrance of the Dragonlord'),
        (7770774, 510160, 'Remembrance of the Black Blade'),
    ],
    'Gravesite Plain': [
        (7770784, 510480, 'Remembrance of Putrescence'),
        (7770792, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Liurnia of the Lakes': [
        (7770008, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    "Miquella's Haligtree": [
        (7770006, 176, "Malenia's Great Rune"),
        (7773900, 15000850, "[Sorcery] Loretta's Mastery"),
    ],
    'Mohgwyn Palace': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770778, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770776, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Scadu Altus': [
        (7770785, 510550, 'Remembrance of the Mother of Fingers'),
    ],
    'Shadow Keep': [
        (7770783, 510460, 'Remembrance of the Impaler'),
        (7770788, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770790, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Stormveil Castle': [
        (7770767, 510010, 'Remembrance of the Grafted'),
    ],
}

_GEN_STAMP = {'inputs_hash': 'sha256:5dbf3a9266689eece811c520d0a42c94d4e5ac5970d804ffa89bd41f5a18b938', 'module': 'boss_data.py', 'body_sha256': 'sha256:562e6494bc053fe9b6d6f043b52f67d1cf635c496f759d97ceac6d205271543c'}
