"""Greenfield ER world -- CORE (stable).

Owns the parts every seed needs and every feature depends on: region scope (num_regions), the
hub-and-spoke regions, locks, goal, and the base keyless client contract. SPEC-PARITY phases live in
features/ and are aggregated here via registry.py -- adding a phase does NOT edit this file.

Data-derived + matt-free (see ../LESSONS-LEARNED.md): rules keyed by REGION only.
"""
import logging
import os
from typing import Any, Dict, List

from dataclasses import make_dataclass

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions, Range, Choice, Toggle, DefaultOnToggle, OptionError

from .data import HUB, REGIONS, LOCATIONS, FINALE_REGION, FINALE_HOST_REGION
try:
    from .location_tags import DEFAULTED_REGION_APS   # checks whose region is a GUESS -> filler only
except ImportError:                                    # pre-regen data: fail OPEN, guard is inert
    DEFAULTED_REGION_APS = frozenset()

try:
    # m11_00 (normal Leyndell) -- DESTROYED when Maliketh dies. Same predicate, different cause.
    from .location_tags import ERDTREE_BURN_APS
except ImportError:
    ERDTREE_BURN_APS = frozenset()

# A check that can become PERMANENTLY UNREACHABLE may not carry PROGRESSION. Two independent causes,
# one rule: we don't know where it is (DEFAULTED_REGION_APS), or the player can destroy it
# (ERDTREE_BURN_APS -- kill Maliketh, the Erdtree burns, normal Leyndell ceases to exist).
try:
    from .location_tags import SHOP_RELEASE_GATED_APS
except ImportError:
    SHOP_RELEASE_GATED_APS = frozenset()

# Three ways a check can be UNREACHABLE while AP believes otherwise. All three answer the same predicate:
# a check we cannot ASSERT is reachable may not be REQUIRED.
#   DEFAULTED_REGION_APS   -- we GUESSED the region (hub fallback); the item may sit in a sealed region.
#   ERDTREE_BURN_APS       -- m11_00 is DESTROYED when Maliketh dies; the player can burn it early.
#   SHOP_RELEASE_GATED_APS -- the merchant does not STOCK the row until an unlock event fires. Region
#                             reachability is necessary but NOT sufficient: the shop can be open and the
#                             row simply not on the shelf.
_NO_PROGRESSION_APS = (frozenset(DEFAULTED_REGION_APS) | frozenset(ERDTREE_BURN_APS)
                       | frozenset(SHOP_RELEASE_GATED_APS))
from .region_spine import (compute_kept, GOAL_REGION, DLC_REGIONS,  # noqa: F401 (GOAL_REGION used by tests/features)
                           base_regions, dlc_regions, REGION_PARENT)
from . import registry
from .defaults import FROZEN_OPTIONS, apply_frozen
from . import contract
from . import features as _features  # noqa: F401  -- import triggers feature self-registration
from .features import natural_progression as _np  # vanilla/natural-progression mode (zero synthetic locks)
from .features import goal_locations as _gl  # GOAL_CHOICES / forced_regions (the explicit `goal` option)
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags (regions load unlocked)
    REGION_OPEN_FLAGS = {}
try:
    from .item_ids import ITEM_CATALOG, LOCATION_ITEM  # generated by gen_data.py (real-item-pool)
    from .item_ids import GOODS_HOLD_CAP               # generated: name -> game stack ceiling (#308)
    from .hold_cap import hold_budget, hold_slot_available
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}
    GOODS_HOLD_CAP = {}
    from .hold_cap import hold_budget, hold_slot_available
try:
    from .item_ids import FILLER_POOL  # varied junk filler (generated)
except Exception:
    FILLER_POOL = []
try:
    from .item_ids import DLC_ITEM_NAMES  # DLC-only catalog names (generated); excluded when DLC off
except Exception:
    DLC_ITEM_NAMES = set()

GAME = "Elden Ring"
FILLER = "Rune"


_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_FEATURES = registry.features()

# ---- Great Runes (ending goal) ---------------------------------------------------------------
# The Great Rune items exist in the real-item-pool ONLY when ItemShuffle is on (they are the
# vanilla drops of the Great-Rune boss locations). Identified purely by name from ITEM_CATALOG, so
# this stays data-derived + matt-free. There are 6 in vanilla ER (Godrick's, Radahn's, Morgott's,
# Rykard's, Mohg's, Malenia's). The great_runes ending goal can require up to this many.
GREAT_RUNES: List[str] = sorted(nm for nm in ITEM_CATALOG if nm.endswith("Great Rune"))


# ---- core options ----------------------------------------------------------------------------
class NumRegions(Range):
    """How many regions are in play this seed. 0 = all regions (full Shattering). N > 0 seals the
    rest: only kept regions get locks, checks, and goal requirement, for a shorter run.

    Default 6, not 0: a full 30-region Shattering is an enormous first run, and a six-region seed is
    the length most players actually finish. Set 0 for the full map."""
    display_name = "Number of Regions"
    range_start = 0
    range_end = len(REGIONS)
    default = 6


class NumRegionsOrder(Choice):
    """How kept regions are chosen when num_regions > 0. There is only one behaviour: N regions drawn
    at RANDOM from the eligible pool. `rolled` is an alias for `random`; `spine` is DEPRECATED, does
    the same thing, and warns -- it is accepted for one release so yamls in the wild keep rolling.

    WHY SPINE WENT (Alaric, 2026-08-05). It kept the first N of a fixed Limgrave-first path, so every
    seed at the default num_regions=6 kept the SAME eight regions -- Limgrave, Weeping, Stormveil,
    Liurnia, Raya Lucaria Academy, Caelid, plus Leyndell and Altus by goal closure -- and nine base
    regions could never appear at all. Measured over 3000 seeds, the random draw puts every base
    region in the 34-37% band and excludes none. Two shipped docs also called spine the DEFAULT (it
    was not) and said it controlled where you START (it did not -- the opening region is an
    independent size-weighted draw in features/start_grace.pick_anchor_region)."""
    display_name = "Region Selection"
    option_rolled = 0
    option_spine = 1          # DEPRECATED -- same behaviour as rolled; warned about at gen time
    default = 0

    # 🛑 `random` CANNOT be an option name here. Archipelago reserves it -- Options.py's metaclass
    # asserts "Choice option 'random' cannot be manually assigned", because `random` is already the
    # yaml-level magic that makes AP pick a value for you. Not a loss: with both remaining values
    # behaving identically, a yaml saying `num_regions_order: random` gets AP's own randomisation
    # and lands on the same draw either way. So `random`, `rolled` and `spine` all do the same
    # thing; `rolled` is simply the one AP will let us name.


class ItemShuffle(Toggle):
    """off (default): every check pays out a generic Rune. on: each location's own vanilla item
    becomes an AP item and all of them are shuffled among the checks (74% of checks carry a real
    vanilla item; the rest fall back to Rune). Region Locks stay the only progression, so any
    shuffle is winnable."""
    display_name = "Shuffle Vanilla Items"


class Goal(Choice):
    """WHICH BOSS ENDS THE RUN. 'auto' (default) derives it: the game's real terminus when this
    seed has one (Godfrey/Hoarah Loux + the Elden Beast, whenever both Farum Azula and Leyndell are
    kept), otherwise the major bosses of the deepest kept region.

    'elden_beast' pins the Ashen Capital and FORCES Farum Azula + Leyndell to be kept.
    'promised_consort' pins Enir Ilim -- Promised Consort Radahn, the DLC's final boss -- and
    FORCES Enir Ilim to be kept. This is the point of the option: on a full base+DLC seed 'auto'
    ends at the Elden Beast and the whole DLC is optional, so PCR can never be the goal by luck.

    A choice its toggles make impossible is a GENERATION ERROR, never a silent fallback:
    'promised_consort' needs DLC content in play (fails with Enable DLC off), 'elden_beast' needs
    base-game content (fails with DLC Only on). A goal that quietly evaporates is worse than a
    yaml that refuses to roll."""
    display_name = "Goal"
    option_auto = 0
    option_elden_beast = 1
    option_promised_consort = 2
    default = 0


class EndingCondition(Choice):
    """What the seed's goal requires. 'region_locks' (default): reach the goal region -- hold every
    kept Region Lock (the classic Shattering goal). 'great_runes': ALSO collect Great Runes. Great
    Runes only exist as real items when Shuffle Vanilla Items is on, so with shuffle off this falls
    back to the region_locks goal. The requirement is auto-clamped to the number of Great Runes
    actually reachable this seed, so it can never make a seed unbeatable."""
    display_name = "Ending Condition"
    option_region_locks = 0
    option_great_runes = 1
    default = 0


class GreatRunesRequired(Range):
    """How many Great Runes the 'great_runes' ending needs. INERT unless Ending Condition is
    great_runes -- core._resolve_required_runes returns before this value is ever read.

    RENAMED from `great_runes_required` (2026-07-14). It sat one line above `leyndell_runes_required`,
    which is a completely different thing (the Great Runes needed to ENTER Leyndell, live in every
    seed), and the pair read as two settings for one mechanic. One was a no-op in the default config
    and nothing said so.

    The effective requirement is clamped down to the Great Runes reachable in the kept regions, so
    sealing away Great-Rune regions (num_regions) lowers -- never breaks -- the goal.""" 
    display_name = "Great Runes Required"
    range_start = 1
    range_end = 7
    default = 2


class EnableDLC(DefaultOnToggle):
    """Whether the Shadow of the Erdtree DLC regions (Land of Shadow, Belurat, Scadu Altus, Shadow
    Keep, Jagged Peak, Abyssal Woods) are in play. on (default): DLC regions are eligible and can be
    kept by num_regions alongside base-game regions. off: DLC regions are excluded from the region
    pool entirely -- num_regions draws only from base-game regions, and every DLC lock/check/grace is
    sealed like any non-kept region. Ignored (forced on) when DLC Only is on."""
    display_name = "Enable DLC"


class DLCOnly(Toggle):
    """off (default): normal -- base game (and DLC when Enable DLC is on) are all in play. on: ONLY
    the Shadow of the Erdtree DLC regions are eligible; every base-game region is sealed. Implies
    Enable DLC (turning this on forces the DLC in even if Enable DLC is off). The goal becomes "hold
    every kept DLC lock"; the base-game goal region (Leyndell) is sealed but is not required, so the
    seed stays winnable. Under DLC Only no Great Rune region survives, so a great_runes ending
    collapses to region_locks (the requirement shrinks to 0) rather than becoming unwinnable; a
    standalone Great Runes goal under DLC Only (runes in Land of Shadow) is scoped out of v0.2."""
    display_name = "DLC Only"


_CORE_OPTION_FIELDS = [("num_regions", NumRegions), ("num_regions_order", NumRegionsOrder),
                       ("item_shuffle", ItemShuffle), ("goal", Goal),
                       ("ending_condition", EndingCondition),
                       ("goal_great_runes", GreatRunesRequired),
                       ("enable_dlc", EnableDLC), ("dlc_only", DLCOnly)]
# v0.2 option-matrix slim: FROZEN_OPTIONS are no longer yaml-settable -- they are the BEHAVIOUR
# (see defaults.py). Their classes stay declared in the features (so the slot_data / options-echo
# keys keep being emitted and the client contract is unchanged); they are just filtered out of the
# yaml surface here and injected back as frozen stand-ins in generate_early.
GFOptions = make_dataclass(
    "GFOptions",
    [(n, o) for (n, o) in registry.collect_option_fields(_CORE_OPTION_FIELDS, _FEATURES)
     if n not in FROZEN_OPTIONS],
    bases=(PerGameCommonOptions,),
)
GFOptions.__module__ = __name__


# ---- item + location catalogs (core + feature items) ----------------------------------------
_ITEM_BASE = 7780000
_core_item_ids: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
_core_item_ids[FILLER] = _ITEM_BASE + len(REGIONS)
item_name_to_id: Dict[str, int] = registry.allocate_item_ids(
    _core_item_ids, _ITEM_BASE + len(REGIONS) + 1, _FEATURES)

_core_item_class: Dict[str, Any] = {f"{r} Lock": ItemClassification.progression for r in REGIONS}
_core_item_class[FILLER] = ItemClassification.filler
_item_class: Dict[str, Any] = registry.collect_item_classes(_core_item_class, _FEATURES)

location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}

# real-item-pool: register each distinct vanilla item as an AP item (id -> game FullID). GOODS are
# filler; weapons/armor/accessories/ashes are useful. Locks remain the only progression.
_REAL_ITEM_BASE = 7790000
def _classify_full(full: int) -> ItemClassification:
    return ItemClassification.filler if (full & 0xF0000000) == _GOODS_NIBBLE else ItemClassification.useful
for _idx, _nm in enumerate(sorted(ITEM_CATALOG)):
    if _nm not in item_name_to_id:
        _aid = _REAL_ITEM_BASE + _idx
        item_name_to_id[_nm] = _aid
        _AP_IDS_TO_ITEM_IDS[str(_aid)] = ITEM_CATALOG[_nm]
        _item_class[_nm] = _classify_full(ITEM_CATALOG[_nm])


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    # ---- region scope (num_regions) -------------------------------------------
    def _dlc_on(self) -> bool:
        """Resolved: is DLC content in play this seed? dlc_only implies on; enable_dlc defaults
        on. Mirrors _eligible_regions so region gating and pool-augmentation gating agree."""
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        return dlc_only or enable_dlc

    def _eligible_regions(self) -> List[str]:
        """The region pool num_regions draws from this seed, after the DLC toggles.
        dlc_only -> DLC regions only (implies DLC enabled). enable_dlc off -> base game only.
        both default -> everything. Never empty: the fallbacks below guarantee a non-empty pool so
        compute_kept always has something to keep and the seed stays winnable."""
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        if dlc_only:
            pool = dlc_regions()          # DLC only (implies enabled)
            # Base-game-only NPC content is sealed with the base game and does NOT reappear even when
            # that NPC's story continues into the DLC. E.g. Brother Corhyn: his only pooled check is
            # Corhyn's Bell Bearing (flag 400370, m11_05 ashen Leyndell -- a base region), so dlc_only
            # drops it and no DLC-side Corhyn check exists to keep. Intended (Alaric 2026-07-21), not a
            # coverage gap; documented here because "why did Corhyn vanish?" is a natural dlc_only Q.
        elif enable_dlc:
            pool = list(REGIONS)          # base + DLC (default)
        else:
            pool = base_regions()         # base only

        # REGIONS WITH NO MEASURED KICK GEOMETRY ARE NOT ELIGIBLE (2026-07-13).
        #
        # A region whose play_region buckets we have not measured CANNOT have its lock enforced: the
        # client's kick is permissive on ground it has no entry for, so you would simply walk into the
        # sealed region and loot it. features/area_locks raises a ContractError rather than emit such a
        # seed -- correctly -- so the choice is not "ship it broken or not", it is "exclude it or fail
        # to generate at all".
        #
        # Excluding costs those regions' content this seed. Keeping them would ship a lock that does
        # nothing, which is precisely the bug (Weeping, and the whole DLC) that region_groups.py's
        # measured table exists to end. So: exclude, and SAY SO -- a shrinking region pool that nobody
        # announced is how you end up debugging the fill instead of the cause.
        # Generated into eldenring/region_play_ids.py by gen_data (from region_groups). Imported
        # lazily + tolerantly: an apworld generated before this existed simply has no pending set.
        try:
            from .region_play_ids import REGIONS_PENDING_BUCKET as _pending_set
        except ImportError:
            _pending_set = frozenset()
        # ONLY when region LOCKING is on. num_regions 0 = every region in play and NOTHING is locked,
        # so there is no kick to enforce and no reason to drop anything -- excluding regions there would
        # just delete 67 checks and make a "full" seed not full (which is exactly what the count-neutral
        # and DLC tests caught). The geometry only has to exist for a region whose lock must FIRE.
        n_regions = getattr(self.options, "num_regions", None)
        locking = bool(n_regions is not None and int(n_regions.value) > 0)
        pending = [r for r in pool if r in _pending_set] if locking else []
        if pending:
            logging.getLogger("Greenfield").warning(
                "[eldenring:%s] region(s) EXCLUDED from this seed -- their play_region buckets are not "
                "measured yet, so their locks could not be enforced: %s. Measure the bucket (warp to one "
                "of the region's graces and read the client's kick-watch line), move it into "
                "region_groups.PLAY_REGION_GROUPS, and drop it from REGIONS_PENDING_BUCKET.",
                self.player, ", ".join(sorted(pending)))
            pool = [r for r in pool if r not in _pending_set]

        return pool if pool else list(REGIONS)  # defensive: never seal every region

    def generate_early(self) -> None:
        # Frozen behaviour first: features read the removed knobs exactly as before (defaults.py).
        apply_frozen(self.options)
        self.gf_eligible: List[str] = self._eligible_regions()
        # DLC-off seeds must not receive DLC items as juice/filler. Publish the exclusion set
        # once here so every pool-augmentation feature reads the same resolved decision.
        self.gf_dlc_on: bool = self._dlc_on()
        self.gf_dlc_excluded = frozenset() if self.gf_dlc_on else frozenset(DLC_ITEM_NAMES)
        # natural_progression is the INVERSE of num_regions (the whole eligible map is in play, gated
        # by real vanilla keys), so it forces the full eligible pool -- num_regions is ignored here.
        _nr = 0 if _np.is_on(self) else int(self.options.num_regions.value)
        self.gf_goal_choice: str = self._resolve_goal_choice()
        if self.options.num_regions_order.current_key == "spine":
            logging.warning(
                "[eldenring] num_regions_order: spine is DEPRECATED and now behaves exactly as `rolled` -- "
                "the fixed Limgrave-first path is gone (it made every seed keep the same eight "
                "regions). Drop the key from your yaml; it will be removed after this release.")
        self.gf_kept: List[str] = compute_kept(
            _nr,
            self.random,
            self.gf_eligible,
            forced=_gl.forced_regions(self.gf_goal_choice),
        )
        # Resolve the Great-Rune goal now (once), so create_item/set_rules/slot_data agree.
        self.gf_required_runes: List[str] = self._resolve_required_runes()
        for f in _FEATURES:
            f.generate_early(self)

    def kept_lock_names(self) -> List[str]:
        """The Region Lock item names this seed's completion requires -- THE single source.

        `set_rules` closes its `has_all` over exactly this list and `features/goal_locations`
        emits `goalRequiredItems` from it, so the AP-side completion condition and the client-side
        Goal gate can never drift apart again. Empty under natural_progression, which mints no
        Lock items."""
        if _np.is_on(self):
            return []
        return [f"{r} Lock" for r in self._kept()]

    def goal_required_lock_names(self) -> List[str]:
        """`kept_lock_names` MINUS the precollected start anchor.

        The anchor lock is pushed via `push_precollected` and leaves the pool, so requiring the
        player to "hold" it would be requiring an item that is never sent. Excluding it here also
        makes the emission robust to the one thing I could not verify from the sandbox -- whether a
        precollected item shows up in ReceivedItems -- because the answer no longer matters."""
        free = {i.name for i in self.multiworld.precollected_items.get(self.player, ())}
        return [n for n in self.kept_lock_names() if n not in free]

    def _resolve_goal_choice(self) -> str:
        """The `goal` option value, VALIDATED against this seed's eligible region pool.

        A named goal whose region the DLC toggles have removed from play is an unsatisfiable yaml,
        and this is where it dies -- loudly, at generation, naming the conflicting toggle. The
        alternative (fall back to the ladder) is exactly the "I set my goal and the game ignored
        it" class this project has shipped before. `auto` skips all of it."""
        opt = getattr(self.options, "goal", None)
        chosen = opt.current_key if opt is not None else "auto"
        if chosen == "auto":
            return "auto"
        need = _gl.forced_regions(chosen)
        missing = [r for r in need if r not in set(self.gf_eligible)]
        if missing:
            raise OptionError(
                "goal: %s needs region(s) %s, which this seed's options removed from play "
                "(enable_dlc=%s, dlc_only=%s). Pick goal: auto, or turn the region scope back on -- "
                "a named goal is never silently downgraded."
                % (chosen, ", ".join(sorted(missing)),
                   getattr(getattr(self.options, "enable_dlc", None), "value", "?"),
                   getattr(getattr(self.options, "dlc_only", None), "value", "?")))
        logging.getLogger("Greenfield").info(
            "[eldenring:%s] goal ARMED: %s -> region %s (forcing %s kept)", self.player, chosen,
            _gl.GOAL_CHOICES[chosen][0], "+".join(need))
        return chosen

    def _kept(self) -> List[str]:
        return getattr(self, "gf_kept", list(REGIONS))

    # ---- ending goal (great runes) --------------------------------------------
    def _shuffle_on(self) -> bool:
        return bool(getattr(self.options, "item_shuffle", None) and self.options.item_shuffle.value)

    def _available_runes(self) -> List[str]:
        """Great Rune item NAMES that actually appear on a kept region's locations this seed --
        i.e. the ones that will be in the pool. Only meaningful when item_shuffle is on."""
        if not self._shuffle_on() or not GREAT_RUNES:
            return []
        seen: Dict[str, None] = {}
        for rn in self._kept():
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if nm in GREAT_RUNES and nm not in seen:
                    seen[nm] = None
        return list(seen)

    def _resolve_required_runes(self) -> List[str]:
        """The concrete set of Great Rune names completion will require. Empty unless the goal is
        great_runes AND shuffle is on. Clamped to what's reachable (available), so the requirement
        can never exceed the runes in the pool -> never makes the seed unbeatable. When regions are
        sealed so that fewer than N runes are available, the requirement simply shrinks (to 0 if no
        Great-Rune region survives, collapsing the goal to region_locks-only)."""
        ec = getattr(self.options, "ending_condition", None)
        if ec is None or ec.current_key != "great_runes":
            return []
        want = int(getattr(self.options, "goal_great_runes").value)
        avail = self._available_runes()
        want = min(max(want, 0), len(avail))
        # Deterministic pick of `want` reachable runes (sorted for reproducibility).
        return sorted(avail)[:want]

    def _required_runes(self) -> List[str]:
        return getattr(self, "gf_required_runes", [])

    # ---- items ----------------------------------------------------------------
    def _class_for(self, name: str) -> ItemClassification:
        """Classification for an item, upgrading a required Great Rune to progression so AP fill
        guarantees it lands in a reachable location (Great Runes are GOODS -> filler by default)."""
        base = _item_class.get(name, ItemClassification.filler)
        # A required Great Rune (great_runes ending), a Leyndell-gate rune (features/leyndell_gate.py),
        # or a legacy-dungeon key (features/legacy_key_gates.py, e.g. Academy Glintstone Key) must be
        # progression so AP fill guarantees it reachable (all are GOODS -> filler by default).
        if (name in self._required_runes() or name in getattr(self, "gf_leyndell_runes", [])
                or name in getattr(self, "gf_legacy_keys", [])
                or name in getattr(self, "gf_natural_keys", [])):
            return ItemClassification.progression
        return base

    def create_item(self, name: str) -> GFItem:
        return GFItem(name, self._class_for(name),
                      self.item_name_to_id[name], self.player)

    def _pick_filler(self) -> str:
        """Varied real-junk filler (greases/boluses/butterflies/...) when varied_filler is on and the
        pool resolved; else the monotone Rune. All FILLER_POOL items are ITEM_CATALOG goods (registered,
        filler-classified, client-grantable), so this is count-neutral and fill-safe. Deterministic."""
        vf = getattr(self.options, "varied_filler", None)
        if vf is not None and vf.value and FILLER_POOL:
            _excl = getattr(self, "gf_dlc_excluded", ())
            _pool = [x for x in FILLER_POOL if x not in _excl] if _excl else FILLER_POOL
            if _pool:
                # B: over-weight smithing/somber upgrade stones when filler_upgrade_weight > 1, so the
                # measured standard-weapon starvation can be tuned away (count-neutral -- only WHICH
                # filler item is chosen). Uniform when weight == 1 (default).
                _w = getattr(self.options, "filler_upgrade_weight", None)
                _wt = int(_w.value) if _w is not None else 1
                if _wt > 1:
                    _weights = [_wt if "Smithing Stone" in x else 1 for x in _pool]
                    return self.random.choices(_pool, weights=_weights, k=1)[0]
                return self.random.choice(_pool)
        return FILLER

    def get_filler_item_name(self) -> str:
        return self._pick_filler()

    def create_items(self) -> None:
        kept = self._kept()
        # natural_progression = ZERO synthetic locks: regions open on their real vanilla keys (already
        # in the pool via item_shuffle), so no "<Region> Lock" item is minted and no start anchor is
        # precollected -- the start regions (Limgrave/Weeping) open off the hub with no key.
        _natural = _np.is_on(self)
        lock_items: List[Item] = [] if _natural else [self.create_item(f"{r} Lock") for r in kept]
        # Start holding ONE region's lock (precollected) so a region is open from Roundtable at run
        # start. Count-neutral -- the precollected lock leaves the pool (its freed slot becomes filler),
        # so the remaining N-1 locks stay found progression and the goal (has_all locks) still requires
        # every one. WHICH lock is features/start_grace.pick_anchor_region: size-weighted by each
        # region's emitted check count (derived from LOCATIONS right here, never a frozen table) over
        # the kept BASE regions -- the anchor IS the run's opening region, and a uniform pick over all
        # kept locks opened ~1 run in 3 on a sub-80-check corridor, every one of them DLC (no
        # scadutree blessing on a fresh character on top). DLC locks stay in the pool as normal finds
        # and only anchor when no base region is kept (dlc_only). Under a STRICT progression_surface
        # (mode 2) the MajorBoss bias INTERSECTS that eligibility (degrading, logged, never raising).
        # Deterministic via self.random.
        _slr = getattr(self.options, "start_with_region_lock", None)
        if _slr is not None and _slr.value and lock_items and not _natural:
            from .features.progression_surface import (regions_with_major_boss, lock_region_name,
                                                       missable_barred_aps as _ps_missable)
            from .features.start_grace import pick_anchor_region
            _psm = getattr(self.options, "progression_surface_mode", None)
            _strict = _psm is not None and int(_psm.value) == 2
            _counts = {r: len(LOCATIONS.get(r, [])) for r in kept}
            _region, _rule, _pool_n = pick_anchor_region(
                kept, self.random, _counts, DLC_REGIONS,
                # `barred` = the MISSABLE set only, not the whole surface bar. A region whose
                # only MajorBoss check is questline-missable cannot host a Lock on the strength
                # of it (Deeproot Depths: its sole MajorBoss is the Fortissax reward). The
                # wider set was tried and REVERTED the same day: handing this the defaulted /
                # burn-stranded aps too moves the anchor pick in seeds that have nothing to do
                # with this fix, and test_gf_filler_economy_floor::FillerEconomyFloor -- which
                # sits one seed off its floor -- went red on the shift. Narrow instrument.
                major=regions_with_major_boss(
                    kept, barred=_ps_missable(self)) if _strict else None,
                gated=frozenset(REGION_PARENT))
            _by_region = {lock_region_name(it.name): it for it in lock_items}
            _anchor = _by_region[_region]
            lock_items.remove(_anchor)
            self.multiworld.push_precollected(_anchor)
            # Telemetry (CONTRIBUTING: a feature is armed, or it says why not). The anchor decides the
            # whole run's opening -- a silent pick is a fail at review.
            logging.getLogger("Greenfield").info(
                "[eldenring:%s] start anchor: %s (%d checks) via %s -- eligible %d of %d kept",
                self.player, _region, _counts[_region], _rule, _pool_n, len(kept))
        pool: List[Item] = list(lock_items)
        # Run pool_builder (the juice contributor) LAST, and record how many slots the OTHER
        # contributors already consumed -- locks (minus any precollected one, already popped above),
        # boss keys (boss_keys mode), progressive copies, ... = len(pool) at that point. pool_builder
        # sizes its juice against the TRUE remaining Rune tail (rune-fallback checks minus this count).
        # Previously _reserved_slots assumed only region Locks, so boss_keys/progressive were
        # uncounted and juice over-provisioned -- the over-provision trim then dropped real vanilla
        # gear past the Rune tail (a precision bug; count stayed exact via range(slots)).
        # Contributors (locks, boss keys, progressive copies). pool_builder is NO LONGER one of them:
        # its juice is a recipe category inside features/filler_budget, which is the single owner of
        # the filler tail. _gf_reserved_slots is what those contributors ate -- the allocator subtracts
        # it, exactly as pool_builder's private _rune_tail used to.
        for f in _FEATURES:
            pool += f.create_items(self)
        self._gf_reserved_slots = len(pool)
        total = len(LOCATIONS.get(HUB, [])) + sum(len(LOCATIONS.get(r, [])) for r in kept)
        # FEATURE-OWNED LOCATIONS (documented seam): a feature that creates locations beyond
        # LOCATIONS[HUB + kept] declares them in world.gf_extra_locations (generate_early) and
        # contributes exactly one pool item per entry from its create_items -- features/finale.py
        # is the model. Counting them here is what keeps items == locations when they exist.
        total += len(getattr(self, "gf_extra_locations", ()))
        slots = total - len(pool)
        shuffle = self._shuffle_on()
        required = set(self._required_runes())
        extras: List[str] = []
        if shuffle:
            _excl = getattr(self, "gf_dlc_excluded", ())
            # progressive_flasks: every Golden Seed / Sacred Tear check pays a "Progressive Flask
            # Upgrade" instead. Substituting here (rather than adding a fixed count of copies) keeps
            # the pool count-exact and lets the ladder length follow the checks the seed actually
            # kept -- num_regions and DLC scale it for free. {} when the option is off.
            from .features.progressive import vanilla_substitutions as _flask_sub_of
            _flask_sub = _flask_sub_of(self)
            # ---- THE GOODS HOLD CEILING (#308) --------------------------------------------------
            # The game has a stack ceiling per goods row (EquipParamGoods.maxNum), and for a good
            # that cannot be discarded, deposited or consumed a copy past it is not late -- it is
            # DESTROYED. AddItemFunc drops it, the client's grant reports success, and the AP stream
            # has spent the item. Measured on a default seed before this clamp: 27 Cracked Pots
            # against a ceiling of 19, and 21 undeliverable pot items across the four pot rows.
            #
            # The START LOADOUT draws on the same ceiling, so it is subtracted first -- that is where
            # the reported bug actually came from (9 Hefty Cracked Pots granted at spawn on top of
            # 10 held, against maxNum 10). A clamp that looked only at the pool would have left the
            # motivating case untouched.
            #
            # Count-neutral by construction: a clamped copy pays FILLER through the SAME append, so
            # `extras` keeps exactly one entry per location and the pool count cannot move. The
            # surplus sorts to the tail like any Rune and features/filler_budget re-spends it, so
            # the player gets curated filler instead of an item that would have evaporated.
            #
            # GOODS_HOLD_CAP holds ONLY goods that cannot leave the bag; consumables (Golden Rune,
            # greases, Starlight Shards) are absent by derivation, because their stack drains and
            # their surplus is merely early. Weapons/armour/talismans are not goods at all and their
            # intentional duplicates are untouched. See gen_data.py for the full ruling.
            from .features.start_items import start_hold_counts as _start_holds
            _hold_left = hold_budget(GOODS_HOLD_CAP, _start_holds(self)) if GOODS_HOLD_CAP else {}
            _hold_clamped = {}
            for rn in [HUB] + kept:
                for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                    nm = LOCATION_ITEM.get(ap_id)
                    # DLC off: a kept BASE / HUB location whose vanilla item is DLC-only pays Rune
                    # instead (the same rule the juice / varied-filler / filler-foreign paths follow).
                    # Without this the item_shuffle PRIMARY pool leaks DLC gear anchored to base
                    # regions (Roundtable Hold -- the HUB -- anchors Spear of the Impaler; Mohgwyn
                    # Palace; ...) into a DLC-off seed, and AP fill scatters it onto reachable
                    # checks/shops. FILLER routes through _pick_filler, which is already DLC-safe.
                    if nm and _excl and nm in _excl:
                        nm = None
                    if nm and _flask_sub:
                        nm = _flask_sub.get(nm, nm)
                    # Hold-ceiling clamp: past the ceiling this copy would be destroyed on delivery,
                    # so it pays filler instead. `_hold_left` is decremented only when a copy is
                    # KEPT, so the count is of surviving copies, not of locations considered.
                    if nm is not None and nm in _hold_left:
                        if not hold_slot_available(_hold_left, nm):
                            _hold_clamped[nm] = _hold_clamped.get(nm, 0) + 1
                            nm = None
                        else:
                            _hold_left[nm] -= 1
                    extras.append(nm if nm and nm in item_name_to_id else FILLER)
            # keep real items first; among reals, keep required Great Runes ahead of everything so
            # the over-provision trim (below) can never drop a rune the goal needs. FILLER (Rune)
            # sorts LAST, so growing `pool` (juice/locks) drops Rune off the tail.
            # pool_builder_scope=all_filler widens what juice can displace: junk-consumable vanilla
            # filler also sorts to the tail (rank 2), just ahead of the Rune sentinel (rank 3) and
            # BEHIND every protected item (required runes rank 0; useful gear + tuned economy +
            # progression keys rank 1). So the trim drops Rune first, then junk filler, and can never
            # reach a protected/progression item. displaceable_filler is the SAME predicate
            # features/pool_builder uses to size its budget, so the drop order and the juice count
            # cannot drift. Default scope=rune_tail keeps the historical 2-level sort byte-for-byte.
            # Rank every check's vanilla item so the count-trim drops the RIGHT things: the Rune
            # sentinel first (3), then displaceable junk consumables (2), never a required rune (0) or
            # a protected/real item (1). displaceable_filler is the same predicate features/
            # filler_budget sizes its budget with, so the drop order and the budget cannot drift.
            if _hold_clamped:
                # Tolerance requires telemetry: a clamp that silently reshapes the pool is the same
                # class of quiet as the bug it fixes. Names + counts, so a seed's log says exactly
                # which items were over the ceiling and by how much.
                print("[greenfield] goods hold-ceiling: %d pool cop(ies) past the game's stack "
                      "ceiling paid filler instead -- %s"
                      % (sum(_hold_clamped.values()),
                         ", ".join("%s x%d" % (k, v) for k, v in sorted(_hold_clamped.items()))))
            from .features.filler_curation import displaceable_filler as _disp

            def _tail_rank(x):
                if x == FILLER:
                    return 3
                if x in required:
                    return 0
                return 2 if _disp(self, x) else 1
            extras.sort(key=_tail_rank)
        _names: List[str] = [extras[k] if k < len(extras) else FILLER for k in range(slots)]
        # THE FILLER TAIL, ALLOCATED ONCE. Every slot ranked 2 or 3 above is budget; features/
        # filler_budget decides what goes in all of them in a single pass -- economy reservation off
        # the top, then consumables and juice from the remainder. There is no second pass to undo it,
        # which is the entire point (see that module's docstring for the three-pass bug it replaces).
        if shuffle:
            from .features import filler_budget as _fb
            _budget_ix = [k for k, nm in enumerate(_names)
                          if nm == FILLER or (nm not in required and _disp(self, nm))]
            _plan = _fb.plan(self, len(_budget_ix))
            for _k, _pick in zip(_budget_ix, _plan):
                if _pick is not None:      # None = keep what the check already paid (junk / Rune)
                    _names[_k] = _pick
        for _nm in _names:
            _it = self.create_item(self._pick_filler() if _nm == FILLER else _nm)
            if shuffle:
                _fb.classify(self, _it)
            pool.append(_it)
        # ONE pass. No PASS-2. The old design ran additive contributors, then in-place SWAPS over
        # the materialised pool (stone_injection, then curated_filler.curate()), then a THIRD relabel
        # in post_fill (stone_ramp) -- three owners of one resource, arbitrated by nothing but the
        # order they happened to run in. That composition silently starved the upgrade economy; see
        # features/filler_budget.py. The swaps are gone: the allocator decided the whole tail above.
        #
        # THE EARLY GUARANTEE. The stone reservation is a claim about SUPPLY -- the seed HOLDS enough
        # stones -- and on a small seed that happens to land them early because spheres 0-1 ARE most of
        # the seed. At a large num_regions it does not, and the upgrade curve goes sparse in silence.
        # So declare the early stones to AP (`local_early_items`) and let FILL place them: intent, not
        # sphere coupling. Clamped to what this pool actually holds, and it warns if it cannot pay.
        if shuffle:
            _fb.declare_early_items(self, [_it.name for _it in pool])
        self.multiworld.itempool += pool

    def pre_fill(self) -> None:
        # progression_surface (v0.2): CONFINE this world's own progression (region Locks + required/
        # gate runes + legacy keys) to a small high-confidence surface -- default MajorBoss -- via
        # fill_restrictive over the selected classes, with a feasibility ladder that widens (then spills
        # to the pool) so it never FillErrors. Runs before the general fill (locations exist,
        # get_all_state valid). Supersedes the legacy curated_fill toggle when the mode is soft/strict;
        # when the mode is off, the old curated_fill toggle is still honored for backward compatibility.
        _psm = getattr(self.options, "progression_surface_mode", None)
        if _psm is not None and int(_psm.value) != 0:
            from .features import progression_surface as _ps
            _ps.apply(self)
        # The legacy curated_fill fallback is GONE: it only ran when progression_surface_mode was OFF,
        # and that has been FROZEN to `strict` since v0.2 -- so it was dead code, and it carried the
        # retired big-ticket concept (a SECOND list of "important checks" that disagreed with the
        # surface). One surface, one definition.

    def post_fill(self) -> None:
        # ---- COVERAGE GATE (RAISING as of 2026-07-14) ------------------------------------------
        # Every EMITTED location must be DETECTABLE (a real acquisition flag the client polls, not
        # aliased, not colliding with a system flag), SUPPRESSED (if it vanilla-holds a ware, some
        # mechanism stops the game handing that ware over ALONGSIDE the AP item), and
        # REGION-CONSISTENT (every source that claims a region agrees, and the region has real kick
        # geometry).
        #
        # It shipped in report mode -- fail-open on debut, per the release rule -- and the baseline
        # has now soaked to ZERO violations, so it raises. That matters more than it sounds: EVERY
        # significant bug of 2026-07-13/14 was inside its scope and none of them errored.
        #   * play_region buckets in the wrong id space -> Weeping's lock and the ENTIRE DLC's locks
        #     had never enforced anything, in any seed (region);
        #   * check_lots keyed by raw id instead of FullID -> armour, talismans and every Ash of War
        #     double-paid (suppression);
        #   * lotItemCategory 0 and 6 "never judged" -> 13 checks handed out their vanilla ware
        #     forever, and the lot blank was the ONLY mechanism that could ever suppress them
        #     (suppression).
        # Not one of those crashed, logged, or failed a test. They were silent wrong answers, which
        # is what this gate exists to convert into loud ones.
        #
        # Runs FIRST: a seed that cannot pay its own contract should die before we spend anything
        # else on it. If it fires, DO NOT quarantine to make it green -- coverage_quarantine is for
        # locations genuinely excluded from the pool, and ACCEPTED_LEAKS is FILLER-only and needs a
        # reason and a date. Silencing this gate re-creates the exact bug it just caught.
        from . import coverage as _cov
        _cov.assert_coverage(self)

        # F (2026-07-10): progression-reachability safety net. Verify every own advancement item is
        # actually reachable from a real CollectionState; raise FillError on any stranding (an in-game
        # soft-lock under accessibility:minimal, which AP does not self-check). Runs first so a doomed
        # seed dies before the cosmetic stone-ramp work below. Fail-open on internal audit error.
        _psm = getattr(self.options, "progression_surface_mode", None)
        if _psm is not None and int(_psm.value) != 0:
            from .features import progression_surface as _ps
            _ps.audit_reachable(self)

        # stone_ramp DELETED. It was never a working mechanism that lost its inputs -- it never
        # worked: 3 stones placed on the playtest seed, 0 on the pre-freeze A/B. The economy that
        # felt good was curated_filler's, all along. Its model was unsound (it measured supply as
        # though the player 100%s every fill sphere, so its deficit was ~never positive), its failure
        # mode was unsound (`while _deficit > 0 and _li < len(_locs)` ran out of slots and shrugged in
        # silence), and it was architecturally hostile (a FOURTH pass, relabelling placements after
        # fill and locking them, bypassing progression balancing). Its one legitimate job -- low-tier
        # stones affordable early -- is now a correctly-sized, low-tier-weighted RESERVATION in
        # features/filler_budget, which needs no sphere coupling to do it. Coupling a player-visible
        # economy to an invisible fill artifact is what made it both wrong and unfixable.

    def _add_locations(self, region: Region, region_name: str) -> None:
        # A GUESSED REGION MAY NOT CARRY PROGRESSION.
        # DEFAULTED_REGION_APS = checks whose real region is unknown, so gen_data defaulted them to the
        # HUB (see gen_data._region_is_derived). AP then believes they are reachable at spawn -- but the
        # item still spawns wherever it PHYSICALLY lives, which may be behind a region Lock. Barring them
        # from the progression SURFACE is not enough: when the surface ladder widens/spills, the general
        # fill still sees a reachable hub location and will happily drop an advancement item on it.
        # (Fuzz caught exactly that: Rykard's Great Rune landed on a guessed-region Smithing Stone.)
        # So the bar has to live on the LOCATION: mark them EXCLUDED = filler only, whatever fill runs.
        # Real seed this killed: AP_55352390472076588352 -- Stormveil Castle Lock on Golden Seed f400220,
        # which actually sits in Stormveil. Caelid start. Unwinnable.
        # Capital reconciler (SPEC-capital-reconciler.md): while armed, the client keeps burn
        # flag 9116 matched to the player's capital, so m11_00 is NEVER permanently lost -- the
        # ERDTREE_BURN_APS "may not carry progression" bar is lifted (that bar exists ONLY for
        # the strand the reconciler ends). Off/foreign -> the bar snaps back: the one-flag
        # disable also restores the fill-side mitigation. The other two causes always apply.
        _barred = _NO_PROGRESSION_APS
        if getattr(self, "gf_capital_reconciler", False):
            _barred = _barred - frozenset(ERDTREE_BURN_APS)
        # confine_foreign_progression (progression_surface): the surface ap-ids that MAY host another
        # player's advancement. None => feature off. Non-surface locations get a foreign-advancement bar
        # below. Computed once in create_regions (self._foreign_confine_surface).
        _fsurf = getattr(self, "_foreign_confine_surface", None)
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            _loc = GFLocation(self.player, name, ap_id, region)
            if ap_id in _barred:
                # Bar ADVANCEMENT only, via item_rule -- do NOT use LocationProgressType.EXCLUDED.
                # EXCLUDED puts the location in AP's dedicated "Remaining Excluded" filler-only pass
                # (Fill.py:625), which must fill EVERY excluded location from the plain filler pool; the
                # weapon/shop slots among these carry their own item_rules that generic filler can't
                # satisfy, and the pass FillErrors. An item_rule keeps them in the normal fill (they can
                # still hold useful/filler, including other worlds' non-progression items) while making
                # them ineligible for anything the seed could ever REQUIRE.
                # Bars advancement from ANY player: progression stranded somewhere unreachable is just
                # as unwinnable for a foreign world as for ours.
                # ERDTREE_BURN_APS rides the same rule: killing Maliketh burns the Erdtree, switches
                # Leyndell's graces OFF and replaces m11_00 with the Ashen Capital -- 79 checks gone,
                # permanently. num_regions can unseal Farum Azula while Leyndell is sealed, so the
                # player is free to do that with those checks still uncollected. They stay CHECKS;
                # they just cannot be something the seed REQUIRES. (Alaric, playtest 2026-07-11.)
                _prev = _loc.item_rule
                _loc.item_rule = lambda item, _p=_prev: (not item.advancement) and _p(item)
            elif _fsurf is not None and ap_id not in _fsurf:
                # confine_foreign_progression ON: this is one of our FILLER (non-surface) checks, so bar
                # OTHER players' advancement from it -- foreign progression is thereby confined to our
                # surface (the same checks our own region Locks use). Our OWN advancement may still land
                # here: apply() already confined it, and its ladder/spill safety valve must stay open, so
                # a spilled own Lock is never stranded. Only foreign advancement is refused; foreign
                # useful/filler and everything of ours still fits.
                _prev = _loc.item_rule
                _fb = self._foreign_barred_fn
                _loc.item_rule = lambda item, _p=_prev, _pl=self.player, _fbf=_fb: (
                    not _fbf(item, _pl)) and _p(item)
            region.locations.append(_loc)

    def create_regions(self) -> None:
        # confine_foreign_progression: resolve the surface ap-id set ONCE (None => feature off) so every
        # _add_locations call bars foreign advancement on the same non-surface checks. Must precede the
        # location loop below.
        try:
            from .features.progression_surface import (confined_surface_ids as _confined_surface_ids,
                                                       foreign_advancement_barred as _foreign_barred_fn)
            self._foreign_confine_surface = _confined_surface_ids(self)
            self._foreign_barred_fn = _foreign_barred_fn
        except Exception:
            self._foreign_confine_surface = None
            self._foreign_barred_fn = None
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)  # Roundtable Hold is free
        self._add_locations(hub, HUB)
        created: Dict[str, Region] = {}
        for r in self._kept():  # sealed regions are simply not created
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            created[r] = reg
        # A gated child (REGION_PARENT) hangs off its PARENT region, not the hub: its entrance is
        # only traversable once the whole ancestor Lock chain is held, which is the walk-in truth
        # (its grace bundle is withheld -- features/graces.py -- so the hub warp does not exist).
        # This is what lets fill never strand progression in a child whose parent is sealed/unfound.
        # compute_kept guarantees a kept child's parent is kept; a miss here is corrupt state.
        _natural = _np.is_on(self)
        for r, reg in created.items():
            # In natural_progression the geography flattens (a lock warps you in), so most regions hang
            # off the hub and only the kept chokepoints keep a graph parent (natural_progression.
            # NATURAL_PARENT: Leyndell->Altus, Sewer->Leyndell); the entrance rule is the region's real
            # vanilla-key clause instead of has("<Region> Lock").
            parent = _np.natural_parent(r) if _natural else REGION_PARENT.get(r)
            if parent is not None and parent not in created:
                raise RuntimeError(
                    f"create_regions: gated child {r!r} kept without its parent {parent!r} -- "
                    f"compute_kept must close over REGION_PARENT")
            src = created[parent] if parent is not None else hub
            if _natural:
                _erule = _np.entrance_rule(self, r)
                rule = _erule if _erule is not None else (lambda state: True)
            else:
                lock = f"{r} Lock"
                rule = lambda state, l=lock: state.has(l, self.player)
            src.connect(reg, f"To {r}", rule=rule)
        if _natural:
            # ZERO synthetic locks, but MANY features still reason "region R is open" as
            # has("<R> Lock") (finale's Ashen-Capital prerequisites, festival_gate's Radahn->capital
            # gate, boss_locks, ...). Rather than teach each one about this mode, place "<R> Lock" as an
            # AP EVENT (code=None -> never in the item pool, never granted to the client, never a
            # received item) inside each region, reachable exactly when the region is: has("<R> Lock")
            # then means precisely "you can reach R via its real vanilla keys", so every existing
            # lock-gated rule keeps working UNCHANGED and the player still receives no synthetic lock.
            for r, reg in created.items():
                ev = GFLocation(self.player, f"{r} Reached", None, reg)
                ev.place_locked_item(GFItem(f"{r} Lock", ItemClassification.progression, None, self.player))
                reg.locations.append(ev)
        for f in _FEATURES:
            f.create_regions(self)

    def set_rules(self) -> None:
        required = self._required_runes()
        player = self.player
        if _np.is_on(self):
            # natural_progression mints NO region locks, so has_all([]) would be vacuously true: the
            # goal is instead REACHING the goal region (Leyndell), whose entrance requires 2 Great
            # Runes (features/leyndell_gate) reached through the real-key gate graph -> a genuine spine.
            #
            # ...unless Leyndell is not in this seed. Under `dlc_only` every BASE region is dropped,
            # Leyndell is never created, and `can_reach("Leyndell")` raised KeyError out of AP's
            # region cache -- inside the completion lambda, which BaseClasses evaluates on EVERY
            # fill_restrictive batch regardless of accessibility, so the crash landed in pre_fill.
            # Latent since this mode's birth commit (28d0540); found by the fuzz gate
            # (GF-fuzz-573519869-0021: natural_progression + dlc_only). goal_locations.py already
            # ruled that the goal is "never a hardcoded region" -- honour that here rather than
            # banning the combination: ask it what the END of THIS kept set is (DLC finale first,
            # else the deepest kept region), so the mode degrades to a playable seed instead of a
            # stack trace.
            _kept_now = self._kept()
            # An explicit `goal` choice wins here too, or natural_progression would complete on the
            # capital while goalLocations named a different region's boss -- two terminal claims.
            _choice = getattr(self, "gf_goal_choice", "auto")
            goal = _gl.GOAL_CHOICES[_choice][0] if _choice in _gl.GOAL_CHOICES else GOAL_REGION
            if goal not in _kept_now:
                # (no local `import ... as _gl` here: it would shadow the module-level binding
                # used two lines above and raise UnboundLocalError.)
                from .features.finale import finale_active as _fin
                _derived, _ = _gl.terminal_goal_ids(_kept_now, _choice)
                # The derived goal may be the CONDITIONAL finale region (data.FINALE_REGION, "Ashen
                # Capital"): not in REGIONS, never rolled, created by features/finale.py only when
                # its requirements are kept. Legitimate when it exists and a KeyError when it does
                # not -- exactly the bug being fixed -- so check that it is really built before
                # handing it to can_reach.
                _built = set(_kept_now) | {HUB}
                if _fin(_kept_now):
                    _built.add(FINALE_REGION)
                goal = _derived if _derived in _built else HUB
                logging.getLogger("Elden Ring").info(
                    "[greenfield] %s is not in this seed's kept regions; natural-progression goal "
                    "derived from the kept set instead: %s", GOAL_REGION, goal)
            if required:
                need = len(required)
                self.multiworld.completion_condition[player] = \
                    lambda state, g=goal, rn=required, n=need, p=player: (
                        state.can_reach(g, "Region", p)
                        and sum(1 for gr in rn if state.has(gr, p)) >= n)
            else:
                self.multiworld.completion_condition[player] = \
                    lambda state, g=goal, p=player: state.can_reach(g, "Region", p)
        else:
            locks = self.kept_lock_names()
            if required:
                need = len(required)
                self.multiworld.completion_condition[player] = \
                    lambda state, lk=locks, rn=required, n=need: (
                        state.has_all(lk, player)
                        and sum(1 for gr in rn if state.has(gr, player)) >= n)
            else:
                self.multiworld.completion_condition[player] = \
                    lambda state, lk=locks: state.has_all(lk, player)
        for f in _FEATURES:
            f.set_rules(self)

    # ---- client contract ------------------------------------------------------
    def _options_echo(self) -> Dict[str, Any]:
        """The sd["options"] sub-dict (contract.OPTIONS_SUBKEYS). F1 fix (2026-07-06): the client's
        runtime-option parsers read slot_data["options"][<key>] (er-logic/src/options.rs
        parse_bool_option et al.), but the features only emitted TOP-LEVEL copies -- so death_link/
        enable_dlc/no_weapon_requirements/scaling knobs were silently dark with "slot_data OK".
        Emitted CENTRALLY here (features never write into `options`), contract-validated at gen;
        the features' top-level emissions remain as legacy duplicates.

        ⚠️ NOT every entry is a plain echo. `completion_scaling_floor` is UNIT-CONVERTED here (percent
        -> HP multiplier) because the client parses it as a multiplier; its top-level legacy copy
        keeps the percent. Same name, two units, one deliberate conversion -- see
        features/scaling.floor_multiplier and tests/test_gf_scaling_floor_units.py."""
        from .scaling_ladder import (ceiling_multiplier as scaling_ceiling_multiplier,
                                     floor_multiplier as scaling_floor_multiplier)
        from .features.scaling import resolved_max_difficulty as scaling_resolved_max_difficulty

        def _opt(name: str, default: int = 0) -> int:
            o = getattr(self.options, name, None)
            return int(o.value) if o is not None else default
        # RESOLVED DLC bool, mirroring _eligible_regions: dlc_only implies on.
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        return {
            contract.DEATH_LINK: _opt("death_link"),
            contract.ENABLE_DLC: int(dlc_only or enable_dlc),
            contract.NO_WEAPON_REQUIREMENTS: _opt("no_weapon_requirements"),
            contract.COMPLETION_SCALING: 4,  # smoothstep curve id (nonzero = on; matches features/scaling.py)
            # UNIT CONVERSION, NOT AN ECHO. The client reads this as an HP MULTIPLIER
            # (er-logic/scaling.rs floor_tier_from_multiplier); the option is a PERCENT. Emitting the
            # raw percent here -- as this line did until 2026-07-27 -- pinned every enemy to the top
            # tier for any value above 3. See features/scaling.floor_multiplier for the full story.
            #
            # ⚠️ THE OPTION AND THE WIRE KEY HAVE DIFFERENT NAMES ON PURPOSE. The yaml option was
            # renamed to `minimum_enemy_difficulty` for legibility; the slot_data key stays
            # `completion_scaling_floor` because a RELEASED client reads it and the contract hash is
            # part of the connect handshake. Renaming a player-facing knob is free; renaming a wire
            # key is a client release plus every seed already rolled.
            contract.COMPLETION_SCALING_FLOOR: scaling_floor_multiplier(
                _opt("minimum_enemy_difficulty")),
            # The MIRROR of the floor: an HP multiplier capping the tier. 100 (default) resolves to
            # the top rung, i.e. no cap -- emitted as a constant like the rest of this echo rather
            # than appearing only when set, so the key's presence never itself carries meaning.
            # `auto` (the default) is resolved HERE, through the same fn generate_early validates
            # with, so the cap the client reads is the cap that was checked. num_regions 0 = all.
            contract.COMPLETION_SCALING_CEILING: scaling_ceiling_multiplier(
                scaling_resolved_max_difficulty(self)),
            contract.GLOBAL_SCADUTREE_BLESSING: _opt("global_scadutree_blessing"),
            contract.AUTO_UPGRADE: _opt("auto_upgrade"),  # 0 off; nonzero = raise received weapons to your live held level (features/upgrades.py)
            # 0 off; nonzero = the client equips each received weapon / armour piece on arrival
            # (features/auto_equip.py -> auto_equip.rs). The VALUE rides here like every other
            # runtime toggle; the client-feature TAG that stops an older client silently ignoring it
            # is emitted by the feature, because only the feature knows the seed actually uses it.
            contract.AUTO_EQUIP: _opt("auto_equip"),
            contract.FLATTEN_REGULAR_UPGRADES: _opt("flatten_regular_upgrades"),  # 0 off (vanilla 2/4/6); 1..4 stones/level
        }

    def _item_counts(self) -> Dict[str, int]:
        # Per-item GRANT quantity (stacks): filler_curation.STACK_QTY_BY_CATEGORY (throwables x5,
        # pots x2, greases x2, ammunition x20) -> slot_data itemCounts
        # keyed by AP item id (the client grants full_id x qty). Sparse: only stacked items appear.
        from .features.filler_curation import stack_qty_by_name
        return {str(item_name_to_id[_n]): _q for _n, _q in stack_qty_by_name().items()
                if _n in item_name_to_id}

    # The generated data's own identity (gen_data.py writes _gen_stamp.json beside the modules). It
    # rides in `versions` so a bug report says WHICH generated data the seed used -- the client and the
    # apworld ship separately, and "it's broken" with no versions is a report we cannot chase.
    @staticmethod
    def _data_inputs_hash() -> str:
        # ZIP-SAFE read: an installed apworld is a zip, so open(__file__-path) fails and every zipped
        # release would otherwise ship an EMPTY data-inputs hash in its version handshake (silent, but
        # wrong). importlib.resources reads through the loader in both the zip and unpacked cases; the
        # on-disk open() stays as the fallback for a source-tree load with no package context.
        try:
            import json as _json
            raw = None
            _pkg = __package__ or ""
            if _pkg:
                try:
                    import importlib.resources as _ir
                    raw = _ir.files(_pkg).joinpath("_gen_stamp.json").read_text(encoding="utf-8")
                except Exception:
                    raw = None
            if raw is None:
                _p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_gen_stamp.json")
                with open(_p, encoding="utf-8") as _fh:
                    raw = _fh.read()
            return _json.loads(raw).get("inputs_hash", "")
        except Exception:
            return ""

    def _base_slot_data(self) -> Dict[str, Any]:
        kept = self._kept()
        loc_flags: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            for (_n, ap_id, flag) in LOCATIONS.get(rn, []):
                # scalar {ap_id: flag} -- the client reads locationFlags via i64_to_u32_map (scalar),
                # NOT a list; a [flag] value parsed to EMPTY -> no detection table -> checks never
                # registered and goal was checked-fallback (2026-07-06). One flag per location.
                loc_flags[str(ap_id)] = flag
        # FEATURE-OWNED LOCATIONS (documented seam, pairs with create_items above): without this
        # merge a feature-created location is undetectable -- the flag poll never registers it and
        # the coverage gate's detection check fires (which is exactly how a missed merge is caught).
        for ap_id, flag in getattr(self, "gf_extra_location_flags", {}).items():
            loc_flags[str(ap_id)] = int(flag)
        region_open = {f"{r} Lock": REGION_OPEN_FLAGS[r] for r in kept if r in REGION_OPEN_FLAGS}
        # THE TRACKER'S REGION MODEL, per seed. Built from the SAME `[HUB] + kept` walk as loc_flags
        # above, so a location can never be in one and missing from the other -- which is exactly
        # what a separately-generated client table could not promise. Feature-owned locations ride
        # along through `gf_extra_location_regions` for the same reason loc_flags has that seam.
        loc_regions: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            ids = [int(ap_id) for (_n, ap_id, _f) in LOCATIONS.get(rn, [])]
            if ids:
                loc_regions[rn] = ids
        # FEATURE-OWNED LOCATIONS, the same seam loc_flags uses above -- and the reason this is a
        # REVERSE LOOKUP rather than a second `gf_extra_location_*` attribute: the finale
        # (features/finale.py) publishes Ashen Capital's checks through gf_extra_location_flags, and
        # Ashen Capital is deliberately NOT in data.REGIONS (it is conditional, never rollable). So
        # the `[HUB] + kept` walk above cannot see it, and an attribute only this code reads would
        # have to be populated by every future feature that mints a location -- i.e. it would be
        # forgotten exactly once and then be wrong forever.
        # SHIPPED WRONG ONCE (2026-07-28, caught by a smoke-test log): loc_flags carried 4879 ids
        # while loc_regions carried 4869, so the finale's 10 checks had a flag and no region. The
        # tracker cannot group them, and core.rs uses `region_table.contains_key` as its "is this
        # location ours?" test, so a hint for one of them from another player was dropped.
        _ap_region = {int(ap): rn for rn, rows in LOCATIONS.items() for (_n, ap, _f) in rows}
        _regioned = {i for ids in loc_regions.values() for i in ids}
        _unplaced = []
        for ap_id in loc_flags:
            ap_id = int(ap_id)
            if ap_id in _regioned:
                continue
            rn = _ap_region.get(ap_id)
            if rn is None:
                _unplaced.append(ap_id)
                continue
            loc_regions.setdefault(rn, []).append(ap_id)
        if _unplaced:
            # Refuse rather than ship a location the tracker cannot place. An id in locationFlags
            # with no home in LOCATIONS is a feature minting a check out of nothing.
            raise Exception(
                "locationFlags carries %d ap id(s) with no region in data.LOCATIONS: %s. Every "
                "emitted location must be placeable, or the client cannot group it and treats it "
                "as another world's." % (len(_unplaced), sorted(_unplaced)[:10]))
        for _rn in loc_regions:
            loc_regions[_rn] = sorted(set(loc_regions[_rn]))
        # COARSE key per fine region: which region's lock decides in-logic. "" = always accessible.
        # A region with locations but NO lock and no host mapping would silently become its own
        # coarse key and then find no lock item, reading as "open" forever -- so it is a hard error
        # here rather than a quiet permissive default in the client.
        # The finale is the one region with locations and NO lock of its own -- its space is gated
        # by the host's. Imported outright rather than probed through globals(): FINALE_HOST_REGION
        # was NOT imported here, so the probe silently returned None, _lockless_host stayed empty,
        # and the moment Ashen Capital entered loc_regions (the fix above) every seed would have hit
        # the raise below. A getattr-guard that hides a missing import is not a guard.
        _lockless_host = {FINALE_REGION: FINALE_HOST_REGION}
        coarse_keys: Dict[str, str] = {}
        for rn in loc_regions:
            if rn == HUB:
                coarse_keys[rn] = ""
            elif rn in REGION_OPEN_FLAGS:
                coarse_keys[rn] = rn
            elif rn in _lockless_host:
                coarse_keys[rn] = _lockless_host[rn]
            else:
                raise Exception(
                    f"region {rn!r} has locations but no region-open flag and no lockless-host "
                    f"mapping: the client would treat it as permanently accessible. Give it a lock "
                    f"or a host.")
        versions = contract.version_string(self._data_inputs_hash())
        required = self._required_runes()
        return {
            contract.VERSIONS: versions,           # apworld/contract/data identity -- the skew gate
            contract.WORLD_LOGIC: "region_lock",
            contract.LOCATION_FLAGS: loc_flags,
            contract.AP_IDS_TO_ITEM_IDS: _AP_IDS_TO_ITEM_IDS,
            contract.ITEM_COUNTS: self._item_counts(),
            contract.REGION_OPEN_FLAGS: region_open,
            contract.LOCATION_REGIONS: loc_regions,
            contract.REGION_COARSE_KEYS: coarse_keys,
            contract.OPTIONS: self._options_echo(),
            "region_count": len(kept),
            "completionScalingBasis": 1,
            # {str(i32 region id): i32 target} per the contract; the old {region NAME: float 0..1}
            # form was silently unparseable client-side (er-logic scaling.rs i32_i32_map drops
            # non-i32 keys -> empty -> scaling refused to arm). Transitional {}: the live scaling
            # wire is regionSphereTargetRanges, emitted by features/scaling.py (I2).
            contract.REGION_SPHERE_TARGETS: {},
            # ending goal contract (client shows/validates the goal). great_runes_required is the
            # EFFECTIVE (clamped) count; ending_condition reflects the resolved goal, which is
            # region_locks whenever no Great Rune is actually required this seed.
            "ending_condition": "great_runes" if required else "region_locks",
            "great_runes_required": len(required),
            "great_rune_items": list(required),
        }

    def fill_slot_data(self) -> Dict[str, Any]:
        sd = registry.merge_slot_data(self._base_slot_data(), _FEATURES, self)
        contract.validate_slot_data(sd, strict=True)
        return sd

    def write_spoiler(self, spoiler_handle) -> None:
        # Seed provenance + config, dumped so a seed is judgeable from its spoiler alone (no client
        # log needed): the completion-scaling gradient AND the full slot_data the client will receive.
        import json
        from .features import scaling as _sc
        name = self.multiworld.get_player_name(self.player)
        kept = self._kept()
        # Show what the client ACTUALLY receives: the TRUE per-seed fill-sphere targets (the same
        # computation features/scaling.py wires into regionSphereTargetRanges), NOT the spine-order
        # reference gradient. Only when the fill spheres can't be computed (no completed fill) do we
        # fall back to the spine-order ramp -- labelled as such so the table can't be mistaken for the
        # live wire. (Historically this table always printed the spine ramp, which read like a
        # regression to spine-order scaling even though the wire was fill-sphere correct.)
        region_sphere = _sc._region_fill_spheres(self)
        if region_sphere:
            # the same computation the wire uses: fill spheres -> total topological order with
            # seed-deterministic tie-breaks -> position ramp (features/scaling.py, ORDER RAMP).
            order = _sc._order_from_spheres(region_sphere, _sc._order_rng(self))
            # 🛑 THE RAMP HAS TO BE PASSED. `_targets_from_order` defaults to ramp_pct=100 (the even
            # ramp), and the WIRE calls it with ramp_pct_from_speed(difficulty_ramp_speed) -- so
            # omitting it here printed a table that was not the seed being played. Measured
            # 2026-08-05 on a difficulty_ramp_speed: 50 seed: this table said Altus 2857 while the
            # client resolved 5714 and applied tier 11, and every region above position 3 was
            # actually pinned at TARGET_MAX. The spoiler is the only place a player can see the
            # curve, so a spoiler that silently prints a DIFFERENT curve is worse than none.
            ramp = _sc.ramp_pct_from_speed(self.options.difficulty_ramp_speed.value)
            region_target = _sc._targets_from_order(order, ramp)
            basis = f"fill-sphere order ramp, difficulty_ramp_speed {self.options.difficulty_ramp_speed.value} (ramp_pct {ramp})"
        else:
            triples = _sc.sphere_target_ranges(kept)
            pid_target = {lo: t for (lo, _hi, t) in triples}
            region_target = {r: max((pid_target.get(pp, 0) for pp in _sc.REGION_PLAY_IDS.get(r, [])), default=0)
                             for r in kept}
            basis = "spine-order FALLBACK (fill spheres unavailable)"
        if region_target:
            spoiler_handle.write(f"\n\nElden Ring ({name}) completion-scaling spheres "
                                 f"(target / {_sc.TARGET_MAX}; basis: {basis}):\n")
            for region in sorted(region_target, key=lambda r: (region_target[r], r)):
                spoiler_handle.write(f"  {region:<28} {region_target[region]}\n")
        # progression_surface: record the resolved feasibility-ladder rung + how many locks confined
        # vs spilled to the pool, so a seed's progression confinement is judgeable from the spoiler.
        _psr = getattr(self, "gf_prog_surface_resolved", None)
        if _psr is not None:
            _pl = getattr(self, "gf_prog_surface_placed", "?")
            _sp = getattr(self, "gf_prog_surface_spilled", "?")
            _spn = getattr(self, "gf_prog_surface_spilled_names", None)
            spoiler_handle.write(
                f"\nElden Ring ({name}) progression surface: resolved rung {_psr} "
                f"-- {_pl} progression items confined to surface, {_sp} spilled to pool"
                + (f": {', '.join(_spn)}" if _spn else "") + ".\n")
        try:
            sd = self.fill_slot_data()
            spoiler_handle.write(f"\nElden Ring ({name}) slot_data ({len(sd)} keys) -- exactly what the client receives:\n")
            for k in sorted(sd):
                v = sd[k]
                rv = repr(v)
                if len(rv) > 220:
                    n = len(v) if hasattr(v, "__len__") else "?"
                    rv = rv[:220] + f"  ...(+{type(v).__name__}, {n} entries)"
                spoiler_handle.write(f"  {k} = {rv}\n")
        except Exception as e:
            spoiler_handle.write(f"  (slot_data dump failed: {e!r})\n")

    def generate_output(self, output_directory: str) -> None:
        # Post-fill CHECK BREAKDOWN, printed to the generate log so a seed can be judged on
        # progression shape + filler locality at a glance (not just "it genned"): how each of this
        # slot's checks was filled -- own progression / own useful / own (local) filler / another
        # world's item (foreign), split useful vs filler. Solo seeds show foreign = 0.
        p = self.player
        prog = useful = local_filler = foreign_filler = foreign_useful = 0
        for loc in self.multiworld.get_locations(p):
            it = loc.item
            if it is None:
                continue
            important = bool(it.advancement) or bool(it.classification & ItemClassification.useful)
            if it.player == p:
                if it.advancement:
                    prog += 1
                elif it.classification & ItemClassification.useful:
                    useful += 1
                else:
                    local_filler += 1
            elif important:
                foreign_useful += 1
            else:
                foreign_filler += 1
        total = prog + useful + local_filler + foreign_filler + foreign_useful
        print(
            f"[greenfield] {self.multiworld.get_player_name(p)}: {total} checks | "
            f"progression {prog} | useful {useful} | local filler {local_filler} | "
            f"foreign filler {foreign_filler} | foreign useful {foreign_useful}"
        )

        # --- per-sphere item dump (env ER_GF_DUMP_SPHERES; upgrade-curve analytics) ---------------
        # get_spheres() is heavy, so compute it ONCE for the whole multiworld (the lowest player id)
        # and write {player_name: [[item names in sphere 0], [sphere 1], ...]} to JSON. Inert unless
        # the env var is set. Only reachable, item-bearing locations appear in spheres. NOTE: one AP
        # item == one check grant, so a vanilla "x3" stack still counts as 1 here (the pool-tuning unit).
        import os as _os, json as _json
        if _os.environ.get("ER_GF_DUMP_SPHERES") and self.player == min(self.multiworld.player_ids):
            try:
                per_player = {}
                for sidx, locset in enumerate(self.multiworld.get_spheres()):
                    for loc in locset:
                        it = loc.item
                        if it is None or loc.player not in self.multiworld.player_ids:
                            continue
                        pl = per_player.setdefault(self.multiworld.get_player_name(loc.player), [])
                        while len(pl) <= sidx:
                            pl.append([])
                        pl[sidx].append(it.name)
                fn = _os.path.join(output_directory, f"GF_SPHERES_{self.multiworld.seed_name}.json")
                with open(fn, "w", encoding="utf-8") as _f:
                    _json.dump({"seed": str(self.multiworld.seed_name), "spheres": per_player}, _f)
                print(f"[greenfield] ER_GF_DUMP_SPHERES -> {fn}")
            except Exception as _e:
                print(f"[greenfield] ER_GF_DUMP_SPHERES dump failed: {_e!r}")
