"""Greenfield ER world -- CORE (stable).

Owns the parts every seed needs and every feature depends on: region scope (num_regions), the
hub-and-spoke regions, locks, goal, and the base keyless client contract. SPEC-PARITY phases live in
features/ and are aggregated here via registry.py -- adding a phase does NOT edit this file.

Data-derived + matt-free (see ../LESSONS-LEARNED.md): rules keyed by REGION only.
"""
import logging
import os
from typing import Any, Dict, List

from dataclasses import make_dataclass

from BaseClasses import Region, Location, Item, ItemClassification
from worlds.AutoWorld import World, WebWorld
from Options import PerGameCommonOptions, Range, Choice, Toggle, DefaultOnToggle

from .data import HUB, REGIONS, LOCATIONS
try:
    from .location_tags import DEFAULTED_REGION_APS   # checks whose region is a GUESS -> filler only
except ImportError:                                    # pre-regen data: fail OPEN, guard is inert
    DEFAULTED_REGION_APS = frozenset()

try:
    # m11_00 (normal Leyndell) -- DESTROYED when Maliketh dies. Same predicate, different cause.
    from .location_tags import ERDTREE_BURN_APS
except ImportError:
    ERDTREE_BURN_APS = frozenset()

# A check that can become PERMANENTLY UNREACHABLE may not carry PROGRESSION. Two independent causes,
# one rule: we don't know where it is (DEFAULTED_REGION_APS), or the player can destroy it
# (ERDTREE_BURN_APS -- kill Maliketh, the Erdtree burns, normal Leyndell ceases to exist).
try:
    from .location_tags import SHOP_RELEASE_GATED_APS
except ImportError:
    SHOP_RELEASE_GATED_APS = frozenset()

# Three ways a check can be UNREACHABLE while AP believes otherwise. All three answer the same predicate:
# a check we cannot ASSERT is reachable may not be REQUIRED.
#   DEFAULTED_REGION_APS   -- we GUESSED the region (hub fallback); the item may sit in a sealed region.
#   ERDTREE_BURN_APS       -- m11_00 is DESTROYED when Maliketh dies; the player can burn it early.
#   SHOP_RELEASE_GATED_APS -- the merchant does not STOCK the row until an unlock event fires. Region
#                             reachability is necessary but NOT sufficient: the shop can be open and the
#                             row simply not on the shelf.
_NO_PROGRESSION_APS = (frozenset(DEFAULTED_REGION_APS) | frozenset(ERDTREE_BURN_APS)
                       | frozenset(SHOP_RELEASE_GATED_APS))
from .region_spine import (compute_kept, GOAL_REGION, DLC_REGIONS,  # noqa: F401 (GOAL_REGION used by tests/features)
                           base_regions, dlc_regions, REGION_PARENT)
from . import registry
from .defaults import FROZEN_OPTIONS, apply_frozen
from . import contract
from . import features as _features  # noqa: F401  -- import triggers feature self-registration
try:
    from .region_open_flags import REGION_OPEN_FLAGS  # generated by gen_data.py (Phase 0)
except Exception:  # not yet generated -> no region-open flags (regions load unlocked)
    REGION_OPEN_FLAGS = {}
try:
    from .item_ids import ITEM_CATALOG, LOCATION_ITEM  # generated by gen_data.py (real-item-pool)
except Exception:
    ITEM_CATALOG, LOCATION_ITEM = {}, {}
try:
    from .item_ids import FILLER_POOL  # varied junk filler (generated)
except Exception:
    FILLER_POOL = []
try:
    from .item_ids import DLC_ITEM_NAMES  # DLC-only catalog names (generated); excluded when DLC off
except Exception:
    DLC_ITEM_NAMES = set()

GAME = "Elden Ring"
FILLER = "Rune"
_GOODS_NIBBLE = 0x40000000  # ER FullID category nibble for GOODS
_FILLER_GAME_ID = 2900      # Golden Rune [1] (vanilla EquipParamGoods) -- generic filler grant

_FEATURES = registry.features()

# ---- Great Runes (ending goal) ---------------------------------------------------------------
# The Great Rune items exist in the real-item-pool ONLY when ItemShuffle is on (they are the
# vanilla drops of the Great-Rune boss locations). Identified purely by name from ITEM_CATALOG, so
# this stays data-derived + matt-free. There are 6 in vanilla ER (Godrick's, Radahn's, Morgott's,
# Rykard's, Mohg's, Malenia's). The great_runes ending goal can require up to this many.
GREAT_RUNES: List[str] = sorted(nm for nm in ITEM_CATALOG if nm.endswith("Great Rune"))


# ---- core options ----------------------------------------------------------------------------
class NumRegions(Range):
    """How many regions are in play this seed. 0 = all regions (full Shattering). N > 0 seals the
    rest: only kept regions get locks, checks, and goal requirement, for a shorter run."""
    display_name = "Number of Regions"
    range_start = 0
    range_end = len(REGIONS)
    default = 0


class NumRegionsOrder(Choice):
    """How kept regions are chosen when num_regions > 0. 'spine' keeps the first N of a fixed
    progression path (Limgrave first); 'rolled' keeps N random regions. The goal region (Leyndell)
    is always kept, so the seed is always winnable."""
    display_name = "Region Selection"
    option_spine = 0
    option_rolled = 1
    default = 0


class ItemShuffle(Toggle):
    """off (default): every check pays out a generic Rune. on: each location's own vanilla item
    becomes an AP item and all of them are shuffled among the checks (74% of checks carry a real
    vanilla item; the rest fall back to Rune). Region Locks stay the only progression, so any
    shuffle is winnable."""
    display_name = "Shuffle Vanilla Items"


class EndingCondition(Choice):
    """What the seed's goal requires. 'region_locks' (default): reach the goal region -- hold every
    kept Region Lock (the classic Shattering goal). 'great_runes': ALSO collect Great Runes. Great
    Runes only exist as real items when Shuffle Vanilla Items is on, so with shuffle off this falls
    back to the region_locks goal. The requirement is auto-clamped to the number of Great Runes
    actually reachable this seed, so it can never make a seed unbeatable."""
    display_name = "Ending Condition"
    option_region_locks = 0
    option_great_runes = 1
    default = 0


class GreatRunesRequired(Range):
    """How many Great Runes the 'great_runes' ending needs. INERT unless Ending Condition is
    great_runes -- core._resolve_required_runes returns before this value is ever read.

    RENAMED from `great_runes_required` (2026-07-14). It sat one line above `leyndell_runes_required`,
    which is a completely different thing (the Great Runes needed to ENTER Leyndell, live in every
    seed), and the pair read as two settings for one mechanic. One was a no-op in the default config
    and nothing said so.

    The effective requirement is clamped down to the Great Runes reachable in the kept regions, so
    sealing away Great-Rune regions (num_regions) lowers -- never breaks -- the goal.""" 
    display_name = "Great Runes Required"
    range_start = 1
    range_end = 7
    default = 2


class EnableDLC(DefaultOnToggle):
    """Whether the Shadow of the Erdtree DLC regions (Land of Shadow, Belurat, Scadu Altus, Shadow
    Keep, Jagged Peak, Abyssal Woods) are in play. on (default): DLC regions are eligible and can be
    kept by num_regions alongside base-game regions. off: DLC regions are excluded from the region
    pool entirely -- num_regions draws only from base-game regions, and every DLC lock/check/grace is
    sealed like any non-kept region. Ignored (forced on) when DLC Only is on."""
    display_name = "Enable DLC"


class DLCOnly(Toggle):
    """off (default): normal -- base game (and DLC when Enable DLC is on) are all in play. on: ONLY
    the Shadow of the Erdtree DLC regions are eligible; every base-game region is sealed. Implies
    Enable DLC (turning this on forces the DLC in even if Enable DLC is off). The goal becomes "hold
    every kept DLC lock"; the base-game goal region (Leyndell) is sealed but is not required, so the
    seed stays winnable. Under DLC Only no Great Rune region survives, so a great_runes ending
    collapses to region_locks (the requirement shrinks to 0) rather than becoming unwinnable; a
    standalone Great Runes goal under DLC Only (runes in Land of Shadow) is scoped out of v0.2."""
    display_name = "DLC Only"


_CORE_OPTION_FIELDS = [("num_regions", NumRegions), ("num_regions_order", NumRegionsOrder),
                       ("item_shuffle", ItemShuffle), ("ending_condition", EndingCondition),
                       ("goal_great_runes", GreatRunesRequired),
                       ("enable_dlc", EnableDLC), ("dlc_only", DLCOnly)]
# v0.2 option-matrix slim: FROZEN_OPTIONS are no longer yaml-settable -- they are the BEHAVIOUR
# (see defaults.py). Their classes stay declared in the features (so the slot_data / options-echo
# keys keep being emitted and the client contract is unchanged); they are just filtered out of the
# yaml surface here and injected back as frozen stand-ins in generate_early.
GFOptions = make_dataclass(
    "GFOptions",
    [(n, o) for (n, o) in registry.collect_option_fields(_CORE_OPTION_FIELDS, _FEATURES)
     if n not in FROZEN_OPTIONS],
    bases=(PerGameCommonOptions,),
)
GFOptions.__module__ = __name__


# ---- item + location catalogs (core + feature items) ----------------------------------------
_ITEM_BASE = 7780000
_core_item_ids: Dict[str, int] = {f"{r} Lock": _ITEM_BASE + i for i, r in enumerate(REGIONS)}
_core_item_ids[FILLER] = _ITEM_BASE + len(REGIONS)
item_name_to_id: Dict[str, int] = registry.allocate_item_ids(
    _core_item_ids, _ITEM_BASE + len(REGIONS) + 1, _FEATURES)

_core_item_class: Dict[str, Any] = {f"{r} Lock": ItemClassification.progression for r in REGIONS}
_core_item_class[FILLER] = ItemClassification.filler
_item_class: Dict[str, Any] = registry.collect_item_classes(_core_item_class, _FEATURES)

location_name_to_id: Dict[str, int] = {
    name: ap_id for locs in LOCATIONS.values() for (name, ap_id, _flag) in locs
}
_AP_IDS_TO_ITEM_IDS: Dict[str, int] = {str(item_name_to_id[FILLER]): _FILLER_GAME_ID | _GOODS_NIBBLE}

# real-item-pool: register each distinct vanilla item as an AP item (id -> game FullID). GOODS are
# filler; weapons/armor/accessories/ashes are useful. Locks remain the only progression.
_REAL_ITEM_BASE = 7790000
def _classify_full(full: int) -> ItemClassification:
    return ItemClassification.filler if (full & 0xF0000000) == _GOODS_NIBBLE else ItemClassification.useful
for _idx, _nm in enumerate(sorted(ITEM_CATALOG)):
    if _nm not in item_name_to_id:
        _aid = _REAL_ITEM_BASE + _idx
        item_name_to_id[_nm] = _aid
        _AP_IDS_TO_ITEM_IDS[str(_aid)] = ITEM_CATALOG[_nm]
        _item_class[_nm] = _classify_full(ITEM_CATALOG[_nm])


class GFItem(Item):
    game = GAME


class GFLocation(Location):
    game = GAME


class GFWeb(WebWorld):
    theme = "stone"


class GreenfieldEldenRingWorld(World):
    game = GAME
    web = GFWeb()
    options_dataclass = GFOptions
    options: GFOptions
    item_name_to_id = item_name_to_id
    location_name_to_id = location_name_to_id
    origin_region_name = "Menu"

    # ---- region scope (num_regions) -------------------------------------------
    def _dlc_on(self) -> bool:
        """Resolved: is DLC content in play this seed? dlc_only implies on; enable_dlc defaults
        on. Mirrors _eligible_regions so region gating and pool-augmentation gating agree."""
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        return dlc_only or enable_dlc

    def _eligible_regions(self) -> List[str]:
        """The region pool num_regions draws from this seed, after the DLC toggles.
        dlc_only -> DLC regions only (implies DLC enabled). enable_dlc off -> base game only.
        both default -> everything. Never empty: the fallbacks below guarantee a non-empty pool so
        compute_kept always has something to keep and the seed stays winnable."""
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        if dlc_only:
            pool = dlc_regions()          # DLC only (implies enabled)
        elif enable_dlc:
            pool = list(REGIONS)          # base + DLC (default)
        else:
            pool = base_regions()         # base only

        # REGIONS WITH NO MEASURED KICK GEOMETRY ARE NOT ELIGIBLE (2026-07-13).
        #
        # A region whose play_region buckets we have not measured CANNOT have its lock enforced: the
        # client's kick is permissive on ground it has no entry for, so you would simply walk into the
        # sealed region and loot it. features/area_locks raises a ContractError rather than emit such a
        # seed -- correctly -- so the choice is not "ship it broken or not", it is "exclude it or fail
        # to generate at all".
        #
        # Excluding costs those regions' content this seed. Keeping them would ship a lock that does
        # nothing, which is precisely the bug (Weeping, and the whole DLC) that region_groups.py's
        # measured table exists to end. So: exclude, and SAY SO -- a shrinking region pool that nobody
        # announced is how you end up debugging the fill instead of the cause.
        # Generated into eldenring/region_play_ids.py by gen_data (from region_groups). Imported
        # lazily + tolerantly: an apworld generated before this existed simply has no pending set.
        try:
            from .region_play_ids import REGIONS_PENDING_BUCKET as _pending_set
        except ImportError:
            _pending_set = frozenset()
        # ONLY when region LOCKING is on. num_regions 0 = every region in play and NOTHING is locked,
        # so there is no kick to enforce and no reason to drop anything -- excluding regions there would
        # just delete 67 checks and make a "full" seed not full (which is exactly what the count-neutral
        # and DLC tests caught). The geometry only has to exist for a region whose lock must FIRE.
        n_regions = getattr(self.options, "num_regions", None)
        locking = bool(n_regions is not None and int(n_regions.value) > 0)
        pending = [r for r in pool if r in _pending_set] if locking else []
        if pending:
            logging.getLogger("Greenfield").warning(
                "[eldenring:%s] region(s) EXCLUDED from this seed -- their play_region buckets are not "
                "measured yet, so their locks could not be enforced: %s. Measure the bucket (warp to one "
                "of the region's graces and read the client's kick-watch line), move it into "
                "region_groups.PLAY_REGION_GROUPS, and drop it from REGIONS_PENDING_BUCKET.",
                self.player, ", ".join(sorted(pending)))
            pool = [r for r in pool if r not in _pending_set]

        return pool if pool else list(REGIONS)  # defensive: never seal every region

    def generate_early(self) -> None:
        # Frozen behaviour first: features read the removed knobs exactly as before (defaults.py).
        apply_frozen(self.options)
        self.gf_eligible: List[str] = self._eligible_regions()
        # DLC-off seeds must not receive DLC items as juice/filler. Publish the exclusion set
        # once here so every pool-augmentation feature reads the same resolved decision.
        self.gf_dlc_on: bool = self._dlc_on()
        self.gf_dlc_excluded = frozenset() if self.gf_dlc_on else frozenset(DLC_ITEM_NAMES)
        self.gf_kept: List[str] = compute_kept(
            int(self.options.num_regions.value),
            self.options.num_regions_order.current_key,
            self.random,
            self.gf_eligible,
        )
        # Resolve the Great-Rune goal now (once), so create_item/set_rules/slot_data agree.
        self.gf_required_runes: List[str] = self._resolve_required_runes()
        for f in _FEATURES:
            f.generate_early(self)

    def _kept(self) -> List[str]:
        return getattr(self, "gf_kept", list(REGIONS))

    # ---- ending goal (great runes) --------------------------------------------
    def _shuffle_on(self) -> bool:
        return bool(getattr(self.options, "item_shuffle", None) and self.options.item_shuffle.value)

    def _available_runes(self) -> List[str]:
        """Great Rune item NAMES that actually appear on a kept region's locations this seed --
        i.e. the ones that will be in the pool. Only meaningful when item_shuffle is on."""
        if not self._shuffle_on() or not GREAT_RUNES:
            return []
        seen: Dict[str, None] = {}
        for rn in self._kept():
            for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                nm = LOCATION_ITEM.get(ap_id)
                if nm in GREAT_RUNES and nm not in seen:
                    seen[nm] = None
        return list(seen)

    def _resolve_required_runes(self) -> List[str]:
        """The concrete set of Great Rune names completion will require. Empty unless the goal is
        great_runes AND shuffle is on. Clamped to what's reachable (available), so the requirement
        can never exceed the runes in the pool -> never makes the seed unbeatable. When regions are
        sealed so that fewer than N runes are available, the requirement simply shrinks (to 0 if no
        Great-Rune region survives, collapsing the goal to region_locks-only)."""
        ec = getattr(self.options, "ending_condition", None)
        if ec is None or ec.current_key != "great_runes":
            return []
        want = int(getattr(self.options, "goal_great_runes").value)
        avail = self._available_runes()
        want = min(max(want, 0), len(avail))
        # Deterministic pick of `want` reachable runes (sorted for reproducibility).
        return sorted(avail)[:want]

    def _required_runes(self) -> List[str]:
        return getattr(self, "gf_required_runes", [])

    # ---- items ----------------------------------------------------------------
    def _class_for(self, name: str) -> ItemClassification:
        """Classification for an item, upgrading a required Great Rune to progression so AP fill
        guarantees it lands in a reachable location (Great Runes are GOODS -> filler by default)."""
        base = _item_class.get(name, ItemClassification.filler)
        # A required Great Rune (great_runes ending), a Leyndell-gate rune (features/leyndell_gate.py),
        # or a legacy-dungeon key (features/legacy_key_gates.py, e.g. Academy Glintstone Key) must be
        # progression so AP fill guarantees it reachable (all are GOODS -> filler by default).
        if (name in self._required_runes() or name in getattr(self, "gf_leyndell_runes", [])
                or name in getattr(self, "gf_legacy_keys", [])):
            return ItemClassification.progression
        return base

    def create_item(self, name: str) -> GFItem:
        return GFItem(name, self._class_for(name),
                      self.item_name_to_id[name], self.player)

    def _pick_filler(self) -> str:
        """Varied real-junk filler (greases/boluses/butterflies/...) when varied_filler is on and the
        pool resolved; else the monotone Rune. All FILLER_POOL items are ITEM_CATALOG goods (registered,
        filler-classified, client-grantable), so this is count-neutral and fill-safe. Deterministic."""
        vf = getattr(self.options, "varied_filler", None)
        if vf is not None and vf.value and FILLER_POOL:
            _excl = getattr(self, "gf_dlc_excluded", ())
            _pool = [x for x in FILLER_POOL if x not in _excl] if _excl else FILLER_POOL
            if _pool:
                # B: over-weight smithing/somber upgrade stones when filler_upgrade_weight > 1, so the
                # measured standard-weapon starvation can be tuned away (count-neutral -- only WHICH
                # filler item is chosen). Uniform when weight == 1 (default).
                _w = getattr(self.options, "filler_upgrade_weight", None)
                _wt = int(_w.value) if _w is not None else 1
                if _wt > 1:
                    _weights = [_wt if "Smithing Stone" in x else 1 for x in _pool]
                    return self.random.choices(_pool, weights=_weights, k=1)[0]
                return self.random.choice(_pool)
        return FILLER

    def get_filler_item_name(self) -> str:
        return self._pick_filler()

    def create_items(self) -> None:
        kept = self._kept()
        lock_items: List[Item] = [self.create_item(f"{r} Lock") for r in kept]
        # Start holding ONE region's lock (precollected) so a region is open from Roundtable at run
        # start. Count-neutral -- the precollected lock leaves the pool (its freed slot becomes filler),
        # so the remaining N-1 locks stay found progression and the goal (has_all locks) still requires
        # every one. WHICH lock is features/start_grace.pick_anchor_region: size-weighted by each
        # region's emitted check count (derived from LOCATIONS right here, never a frozen table) over
        # the kept BASE regions -- the anchor IS the run's opening region, and a uniform pick over all
        # kept locks opened ~1 run in 3 on a sub-80-check corridor, every one of them DLC (no
        # scadutree blessing on a fresh character on top). DLC locks stay in the pool as normal finds
        # and only anchor when no base region is kept (dlc_only). Under a STRICT progression_surface
        # (mode 2) the MajorBoss bias INTERSECTS that eligibility (degrading, logged, never raising).
        # Deterministic via self.random.
        _slr = getattr(self.options, "start_with_region_lock", None)
        if _slr is not None and _slr.value and lock_items:
            from .features.progression_surface import regions_with_major_boss, lock_region_name
            from .features.start_grace import pick_anchor_region
            _psm = getattr(self.options, "progression_surface_mode", None)
            _strict = _psm is not None and int(_psm.value) == 2
            _counts = {r: len(LOCATIONS.get(r, [])) for r in kept}
            _region, _rule, _pool_n = pick_anchor_region(
                kept, self.random, _counts, DLC_REGIONS,
                major=regions_with_major_boss(kept) if _strict else None,
                gated=frozenset(REGION_PARENT))
            _by_region = {lock_region_name(it.name): it for it in lock_items}
            _anchor = _by_region[_region]
            lock_items.remove(_anchor)
            self.multiworld.push_precollected(_anchor)
            # Telemetry (CONTRIBUTING: a feature is armed, or it says why not). The anchor decides the
            # whole run's opening -- a silent pick is a fail at review.
            logging.getLogger("Greenfield").info(
                "[eldenring:%s] start anchor: %s (%d checks) via %s -- eligible %d of %d kept",
                self.player, _region, _counts[_region], _rule, _pool_n, len(kept))
        pool: List[Item] = list(lock_items)
        # Run pool_builder (the juice contributor) LAST, and record how many slots the OTHER
        # contributors already consumed -- locks (minus any precollected one, already popped above),
        # boss keys (boss_keys mode), progressive copies, ... = len(pool) at that point. pool_builder
        # sizes its juice against the TRUE remaining Rune tail (rune-fallback checks minus this count).
        # Previously _reserved_slots assumed only region Locks, so boss_keys/progressive were
        # uncounted and juice over-provisioned -- the over-provision trim then dropped real vanilla
        # gear past the Rune tail (a precision bug; count stayed exact via range(slots)).
        # Contributors (locks, boss keys, progressive copies). pool_builder is NO LONGER one of them:
        # its juice is a recipe category inside features/filler_budget, which is the single owner of
        # the filler tail. _gf_reserved_slots is what those contributors ate -- the allocator subtracts
        # it, exactly as pool_builder's private _rune_tail used to.
        for f in _FEATURES:
            pool += f.create_items(self)
        self._gf_reserved_slots = len(pool)
        total = len(LOCATIONS.get(HUB, [])) + sum(len(LOCATIONS.get(r, [])) for r in kept)
        # FEATURE-OWNED LOCATIONS (documented seam): a feature that creates locations beyond
        # LOCATIONS[HUB + kept] declares them in world.gf_extra_locations (generate_early) and
        # contributes exactly one pool item per entry from its create_items -- features/finale.py
        # is the model. Counting them here is what keeps items == locations when they exist.
        total += len(getattr(self, "gf_extra_locations", ()))
        slots = total - len(pool)
        shuffle = self._shuffle_on()
        required = set(self._required_runes())
        extras: List[str] = []
        if shuffle:
            _excl = getattr(self, "gf_dlc_excluded", ())
            # progressive_flasks: every Golden Seed / Sacred Tear check pays a "Progressive Flask
            # Upgrade" instead. Substituting here (rather than adding a fixed count of copies) keeps
            # the pool count-exact and lets the ladder length follow the checks the seed actually
            # kept -- num_regions and DLC scale it for free. {} when the option is off.
            from .features.progressive import vanilla_substitutions as _flask_sub_of
            _flask_sub = _flask_sub_of(self)
            for rn in [HUB] + kept:
                for (_n, ap_id, _flag) in LOCATIONS.get(rn, []):
                    nm = LOCATION_ITEM.get(ap_id)
                    # DLC off: a kept BASE / HUB location whose vanilla item is DLC-only pays Rune
                    # instead (the same rule the juice / varied-filler / filler-foreign paths follow).
                    # Without this the item_shuffle PRIMARY pool leaks DLC gear anchored to base
                    # regions (Roundtable Hold -- the HUB -- anchors Spear of the Impaler; Mohgwyn
                    # Palace; ...) into a DLC-off seed, and AP fill scatters it onto reachable
                    # checks/shops. FILLER routes through _pick_filler, which is already DLC-safe.
                    if nm and _excl and nm in _excl:
                        nm = None
                    if nm and _flask_sub:
                        nm = _flask_sub.get(nm, nm)
                    extras.append(nm if nm and nm in item_name_to_id else FILLER)
            # keep real items first; among reals, keep required Great Runes ahead of everything so
            # the over-provision trim (below) can never drop a rune the goal needs. FILLER (Rune)
            # sorts LAST, so growing `pool` (juice/locks) drops Rune off the tail.
            # pool_builder_scope=all_filler widens what juice can displace: junk-consumable vanilla
            # filler also sorts to the tail (rank 2), just ahead of the Rune sentinel (rank 3) and
            # BEHIND every protected item (required runes rank 0; useful gear + tuned economy +
            # progression keys rank 1). So the trim drops Rune first, then junk filler, and can never
            # reach a protected/progression item. displaceable_filler is the SAME predicate
            # features/pool_builder uses to size its budget, so the drop order and the juice count
            # cannot drift. Default scope=rune_tail keeps the historical 2-level sort byte-for-byte.
            # Rank every check's vanilla item so the count-trim drops the RIGHT things: the Rune
            # sentinel first (3), then displaceable junk consumables (2), never a required rune (0) or
            # a protected/real item (1). displaceable_filler is the same predicate features/
            # filler_budget sizes its budget with, so the drop order and the budget cannot drift.
            from .features.filler_curation import displaceable_filler as _disp

            def _tail_rank(x):
                if x == FILLER:
                    return 3
                if x in required:
                    return 0
                return 2 if _disp(self, x) else 1
            extras.sort(key=_tail_rank)
        _names: List[str] = [extras[k] if k < len(extras) else FILLER for k in range(slots)]
        # THE FILLER TAIL, ALLOCATED ONCE. Every slot ranked 2 or 3 above is budget; features/
        # filler_budget decides what goes in all of them in a single pass -- economy reservation off
        # the top, then consumables and juice from the remainder. There is no second pass to undo it,
        # which is the entire point (see that module's docstring for the three-pass bug it replaces).
        if shuffle:
            from .features import filler_budget as _fb
            _budget_ix = [k for k, nm in enumerate(_names)
                          if nm == FILLER or (nm not in required and _disp(self, nm))]
            _plan = _fb.plan(self, len(_budget_ix))
            for _k, _pick in zip(_budget_ix, _plan):
                if _pick is not None:      # None = keep what the check already paid (junk / Rune)
                    _names[_k] = _pick
        for _nm in _names:
            _it = self.create_item(self._pick_filler() if _nm == FILLER else _nm)
            if shuffle:
                _fb.classify(self, _it)
            pool.append(_it)
        # ONE pass. No PASS-2. The old design ran additive contributors, then in-place SWAPS over
        # the materialised pool (stone_injection, then curated_filler.curate()), then a THIRD relabel
        # in post_fill (stone_ramp) -- three owners of one resource, arbitrated by nothing but the
        # order they happened to run in. That composition silently starved the upgrade economy; see
        # features/filler_budget.py. The swaps are gone: the allocator decided the whole tail above.
        #
        # THE EARLY GUARANTEE. The stone reservation is a claim about SUPPLY -- the seed HOLDS enough
        # stones -- and on a small seed that happens to land them early because spheres 0-1 ARE most of
        # the seed. At a large num_regions it does not, and the upgrade curve goes sparse in silence.
        # So declare the early stones to AP (`local_early_items`) and let FILL place them: intent, not
        # sphere coupling. Clamped to what this pool actually holds, and it warns if it cannot pay.
        if shuffle:
            _fb.declare_early_items(self, [_it.name for _it in pool])
        self.multiworld.itempool += pool

    def pre_fill(self) -> None:
        # progression_surface (v0.2): CONFINE this world's own progression (region Locks + required/
        # gate runes + legacy keys) to a small high-confidence surface -- default MajorBoss -- via
        # fill_restrictive over the selected classes, with a feasibility ladder that widens (then spills
        # to the pool) so it never FillErrors. Runs before the general fill (locations exist,
        # get_all_state valid). Supersedes the legacy curated_fill toggle when the mode is soft/strict;
        # when the mode is off, the old curated_fill toggle is still honored for backward compatibility.
        _psm = getattr(self.options, "progression_surface_mode", None)
        if _psm is not None and int(_psm.value) != 0:
            from .features import progression_surface as _ps
            _ps.apply(self)
        # The legacy curated_fill fallback is GONE: it only ran when progression_surface_mode was OFF,
        # and that has been FROZEN to `strict` since v0.2 -- so it was dead code, and it carried the
        # retired big-ticket concept (a SECOND list of "important checks" that disagreed with the
        # surface). One surface, one definition.

    def post_fill(self) -> None:
        # ---- COVERAGE GATE (RAISING as of 2026-07-14) ------------------------------------------
        # Every EMITTED location must be DETECTABLE (a real acquisition flag the client polls, not
        # aliased, not colliding with a system flag), SUPPRESSED (if it vanilla-holds a ware, some
        # mechanism stops the game handing that ware over ALONGSIDE the AP item), and
        # REGION-CONSISTENT (every source that claims a region agrees, and the region has real kick
        # geometry).
        #
        # It shipped in report mode -- fail-open on debut, per the release rule -- and the baseline
        # has now soaked to ZERO violations, so it raises. That matters more than it sounds: EVERY
        # significant bug of 2026-07-13/14 was inside its scope and none of them errored.
        #   * play_region buckets in the wrong id space -> Weeping's lock and the ENTIRE DLC's locks
        #     had never enforced anything, in any seed (region);
        #   * check_lots keyed by raw id instead of FullID -> armour, talismans and every Ash of War
        #     double-paid (suppression);
        #   * lotItemCategory 0 and 6 "never judged" -> 13 checks handed out their vanilla ware
        #     forever, and the lot blank was the ONLY mechanism that could ever suppress them
        #     (suppression).
        # Not one of those crashed, logged, or failed a test. They were silent wrong answers, which
        # is what this gate exists to convert into loud ones.
        #
        # Runs FIRST: a seed that cannot pay its own contract should die before we spend anything
        # else on it. If it fires, DO NOT quarantine to make it green -- coverage_quarantine is for
        # locations genuinely excluded from the pool, and ACCEPTED_LEAKS is FILLER-only and needs a
        # reason and a date. Silencing this gate re-creates the exact bug it just caught.
        from . import coverage as _cov
        _cov.assert_coverage(self)

        # F (2026-07-10): progression-reachability safety net. Verify every own advancement item is
        # actually reachable from a real CollectionState; raise FillError on any stranding (an in-game
        # soft-lock under accessibility:minimal, which AP does not self-check). Runs first so a doomed
        # seed dies before the cosmetic stone-ramp work below. Fail-open on internal audit error.
        _psm = getattr(self.options, "progression_surface_mode", None)
        if _psm is not None and int(_psm.value) != 0:
            from .features import progression_surface as _ps
            _ps.audit_reachable(self)

        # stone_ramp DELETED. It was never a working mechanism that lost its inputs -- it never
        # worked: 3 stones placed on the playtest seed, 0 on the pre-freeze A/B. The economy that
        # felt good was curated_filler's, all along. Its model was unsound (it measured supply as
        # though the player 100%s every fill sphere, so its deficit was ~never positive), its failure
        # mode was unsound (`while _deficit > 0 and _li < len(_locs)` ran out of slots and shrugged in
        # silence), and it was architecturally hostile (a FOURTH pass, relabelling placements after
        # fill and locking them, bypassing progression balancing). Its one legitimate job -- low-tier
        # stones affordable early -- is now a correctly-sized, low-tier-weighted RESERVATION in
        # features/filler_budget, which needs no sphere coupling to do it. Coupling a player-visible
        # economy to an invisible fill artifact is what made it both wrong and unfixable.

    def _add_locations(self, region: Region, region_name: str) -> None:
        # A GUESSED REGION MAY NOT CARRY PROGRESSION.
        # DEFAULTED_REGION_APS = checks whose real region is unknown, so gen_data defaulted them to the
        # HUB (see gen_data._region_is_derived). AP then believes they are reachable at spawn -- but the
        # item still spawns wherever it PHYSICALLY lives, which may be behind a region Lock. Barring them
        # from the progression SURFACE is not enough: when the surface ladder widens/spills, the general
        # fill still sees a reachable hub location and will happily drop an advancement item on it.
        # (Fuzz caught exactly that: Rykard's Great Rune landed on a guessed-region Smithing Stone.)
        # So the bar has to live on the LOCATION: mark them EXCLUDED = filler only, whatever fill runs.
        # Real seed this killed: AP_55352390472076588352 -- Stormveil Castle Lock on Golden Seed f400220,
        # which actually sits in Stormveil. Caelid start. Unwinnable.
        # Capital reconciler (SPEC-capital-reconciler.md): while armed, the client keeps burn
        # flag 9116 matched to the player's capital, so m11_00 is NEVER permanently lost -- the
        # ERDTREE_BURN_APS "may not carry progression" bar is lifted (that bar exists ONLY for
        # the strand the reconciler ends). Off/foreign -> the bar snaps back: the one-flag
        # disable also restores the fill-side mitigation. The other two causes always apply.
        _barred = _NO_PROGRESSION_APS
        if getattr(self, "gf_capital_reconciler", False):
            _barred = _barred - frozenset(ERDTREE_BURN_APS)
        for (name, ap_id, _flag) in LOCATIONS.get(region_name, []):
            _loc = GFLocation(self.player, name, ap_id, region)
            if ap_id in _barred:
                # Bar ADVANCEMENT only, via item_rule -- do NOT use LocationProgressType.EXCLUDED.
                # EXCLUDED puts the location in AP's dedicated "Remaining Excluded" filler-only pass
                # (Fill.py:625), which must fill EVERY excluded location from the plain filler pool; the
                # weapon/shop slots among these carry their own item_rules that generic filler can't
                # satisfy, and the pass FillErrors. An item_rule keeps them in the normal fill (they can
                # still hold useful/filler, including other worlds' non-progression items) while making
                # them ineligible for anything the seed could ever REQUIRE.
                # Bars advancement from ANY player: progression stranded somewhere unreachable is just
                # as unwinnable for a foreign world as for ours.
                # ERDTREE_BURN_APS rides the same rule: killing Maliketh burns the Erdtree, switches
                # Leyndell's graces OFF and replaces m11_00 with the Ashen Capital -- 79 checks gone,
                # permanently. num_regions can unseal Farum Azula while Leyndell is sealed, so the
                # player is free to do that with those checks still uncollected. They stay CHECKS;
                # they just cannot be something the seed REQUIRES. (Alaric, playtest 2026-07-11.)
                _prev = _loc.item_rule
                _loc.item_rule = lambda item, _p=_prev: (not item.advancement) and _p(item)
            region.locations.append(_loc)

    def create_regions(self) -> None:
        menu = Region("Menu", self.player, self.multiworld)
        hub = Region(HUB, self.player, self.multiworld)
        self.multiworld.regions += [menu, hub]
        menu.connect(hub)  # Roundtable Hold is free
        self._add_locations(hub, HUB)
        created: Dict[str, Region] = {}
        for r in self._kept():  # sealed regions are simply not created
            reg = Region(r, self.player, self.multiworld)
            self.multiworld.regions.append(reg)
            self._add_locations(reg, r)
            created[r] = reg
        # A gated child (REGION_PARENT) hangs off its PARENT region, not the hub: its entrance is
        # only traversable once the whole ancestor Lock chain is held, which is the walk-in truth
        # (its grace bundle is withheld -- features/graces.py -- so the hub warp does not exist).
        # This is what lets fill never strand progression in a child whose parent is sealed/unfound.
        # compute_kept guarantees a kept child's parent is kept; a miss here is corrupt state.
        for r, reg in created.items():
            parent = REGION_PARENT.get(r)
            if parent is not None and parent not in created:
                raise RuntimeError(
                    f"create_regions: gated child {r!r} kept without its parent {parent!r} -- "
                    f"compute_kept must close over REGION_PARENT")
            src = created[parent] if parent is not None else hub
            lock = f"{r} Lock"
            src.connect(reg, f"To {r}", rule=lambda state, l=lock: state.has(l, self.player))
        for f in _FEATURES:
            f.create_regions(self)

    def set_rules(self) -> None:
        locks = [f"{r} Lock" for r in self._kept()]
        required = self._required_runes()
        if required:
            need = len(required)
            self.multiworld.completion_condition[self.player] = \
                lambda state, lk=locks, rn=required, n=need: (
                    state.has_all(lk, self.player)
                    and sum(1 for gr in rn if state.has(gr, self.player)) >= n)
        else:
            self.multiworld.completion_condition[self.player] = \
                lambda state, lk=locks: state.has_all(lk, self.player)
        for f in _FEATURES:
            f.set_rules(self)

    # ---- client contract ------------------------------------------------------
    def _options_echo(self) -> Dict[str, Any]:
        """The sd["options"] sub-dict (contract.OPTIONS_SUBKEYS). F1 fix (2026-07-06): the client's
        runtime-option parsers read slot_data["options"][<key>] (er-logic/src/options.rs
        parse_bool_option et al.), but the features only emitted TOP-LEVEL copies -- so death_link/
        enable_dlc/no_weapon_requirements/scaling knobs were silently dark with "slot_data OK".
        Emitted CENTRALLY here (features never write into `options`), contract-validated at gen;
        the features' top-level emissions remain as harmless legacy duplicates."""
        def _opt(name: str, default: int = 0) -> int:
            o = getattr(self.options, name, None)
            return int(o.value) if o is not None else default
        # RESOLVED DLC bool, mirroring _eligible_regions: dlc_only implies on.
        dlc_only = bool(getattr(self.options, "dlc_only", None) and self.options.dlc_only.value)
        enable_dlc = bool(getattr(self.options, "enable_dlc", None) is None
                          or self.options.enable_dlc.value)
        return {
            contract.DEATH_LINK: _opt("death_link"),
            contract.ENABLE_DLC: int(dlc_only or enable_dlc),
            contract.NO_WEAPON_REQUIREMENTS: _opt("no_weapon_requirements"),
            contract.COMPLETION_SCALING: 4,  # smoothstep curve id (nonzero = on; matches features/scaling.py)
            contract.COMPLETION_SCALING_FLOOR: _opt("completion_scaling_floor"),
            contract.GLOBAL_SCADUTREE_BLESSING: _opt("global_scadutree_blessing"),
            contract.AUTO_UPGRADE: _opt("auto_upgrade"),  # 0 off; nonzero = raise received weapons to your live held level (features/upgrades.py)
            contract.FLATTEN_REGULAR_UPGRADES: _opt("flatten_regular_upgrades"),  # 0 off (vanilla 2/4/6); 1..4 stones/level
        }

    def _item_counts(self) -> Dict[str, int]:
        # Per-item GRANT quantity (stacks): filler_curation.STACK_QTY_BY_CATEGORY (throwables x5,
        # pots x2, greases x2, ammunition x20) -> slot_data itemCounts
        # keyed by AP item id (the client grants full_id x qty). Sparse: only stacked items appear.
        from .features.filler_curation import stack_qty_by_name
        return {str(item_name_to_id[_n]): _q for _n, _q in stack_qty_by_name().items()
                if _n in item_name_to_id}

    # The generated data's own identity (gen_data.py writes _gen_stamp.json beside the modules). It
    # rides in `versions` so a bug report says WHICH generated data the seed used -- the client and the
    # apworld ship separately, and "it's broken" with no versions is a report we cannot chase.
    @staticmethod
    def _data_inputs_hash() -> str:
        try:
            import json as _json
            _p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "_gen_stamp.json")
            with open(_p, encoding="utf-8") as _fh:
                return _json.load(_fh).get("inputs_hash", "")
        except Exception:
            return ""

    def _base_slot_data(self) -> Dict[str, Any]:
        kept = self._kept()
        loc_flags: Dict[str, List[int]] = {}
        for rn in [HUB] + kept:
            for (_n, ap_id, flag) in LOCATIONS.get(rn, []):
                # scalar {ap_id: flag} -- the client reads locationFlags via i64_to_u32_map (scalar),
                # NOT a list; a [flag] value parsed to EMPTY -> no detection table -> checks never
                # registered and goal was checked-fallback (2026-07-06). One flag per location.
                loc_flags[str(ap_id)] = flag
        # FEATURE-OWNED LOCATIONS (documented seam, pairs with create_items above): without this
        # merge a feature-created location is undetectable -- the flag poll never registers it and
        # the coverage gate's detection check fires (which is exactly how a missed merge is caught).
        for ap_id, flag in getattr(self, "gf_extra_location_flags", {}).items():
            loc_flags[str(ap_id)] = int(flag)
        region_open = {f"{r} Lock": REGION_OPEN_FLAGS[r] for r in kept if r in REGION_OPEN_FLAGS}
        versions = contract.version_string(self._data_inputs_hash())
        required = self._required_runes()
        return {
            contract.VERSIONS: versions,           # apworld/contract/data identity -- the skew gate
            contract.WORLD_LOGIC: "region_lock",
            contract.LOCATION_FLAGS: loc_flags,
            contract.AP_IDS_TO_ITEM_IDS: _AP_IDS_TO_ITEM_IDS,
            contract.ITEM_COUNTS: self._item_counts(),
            contract.REGION_OPEN_FLAGS: region_open,
            contract.OPTIONS: self._options_echo(),
            "region_count": len(kept),
            "completionScalingBasis": 1,
            # {str(i32 region id): i32 target} per the contract; the old {region NAME: float 0..1}
            # form was silently unparseable client-side (er-logic scaling.rs i32_i32_map drops
            # non-i32 keys -> empty -> scaling refused to arm). Transitional {}: the live scaling
            # wire is regionSphereTargetRanges, emitted by features/scaling.py (I2).
            contract.REGION_SPHERE_TARGETS: {},
            # ending goal contract (client shows/validates the goal). great_runes_required is the
            # EFFECTIVE (clamped) count; ending_condition reflects the resolved goal, which is
            # region_locks whenever no Great Rune is actually required this seed.
            "ending_condition": "great_runes" if required else "region_locks",
            "great_runes_required": len(required),
            "great_rune_items": list(required),
        }

    def fill_slot_data(self) -> Dict[str, Any]:
        sd = registry.merge_slot_data(self._base_slot_data(), _FEATURES, self)
        contract.validate_slot_data(sd, strict=True)
        return sd

    def write_spoiler(self, spoiler_handle) -> None:
        # Seed provenance + config, dumped so a seed is judgeable from its spoiler alone (no client
        # log needed): the completion-scaling gradient AND the full slot_data the client will receive.
        import json
        from .features import scaling as _sc
        name = self.multiworld.get_player_name(self.player)
        kept = self._kept()
        # Show what the client ACTUALLY receives: the TRUE per-seed fill-sphere targets (the same
        # computation features/scaling.py wires into regionSphereTargetRanges), NOT the spine-order
        # reference gradient. Only when the fill spheres can't be computed (no completed fill) do we
        # fall back to the spine-order ramp -- labelled as such so the table can't be mistaken for the
        # live wire. (Historically this table always printed the spine ramp, which read like a
        # regression to spine-order scaling even though the wire was fill-sphere correct.)
        region_sphere = _sc._region_fill_spheres(self)
        if region_sphere:
            region_target = _sc._targets_from_spheres(region_sphere)
            basis = "fill-sphere"
        else:
            triples = _sc.sphere_target_ranges(kept)
            pid_target = {lo: t for (lo, _hi, t) in triples}
            region_target = {r: max((pid_target.get(pp, 0) for pp in _sc.REGION_PLAY_IDS.get(r, [])), default=0)
                             for r in kept}
            basis = "spine-order FALLBACK (fill spheres unavailable)"
        if region_target:
            spoiler_handle.write(f"\n\nElden Ring ({name}) completion-scaling spheres "
                                 f"(target / {_sc.TARGET_MAX}; basis: {basis}):\n")
            for region in sorted(region_target, key=lambda r: (region_target[r], r)):
                spoiler_handle.write(f"  {region:<28} {region_target[region]}\n")
        # progression_surface: record the resolved feasibility-ladder rung + how many locks confined
        # vs spilled to the pool, so a seed's progression confinement is judgeable from the spoiler.
        _psr = getattr(self, "gf_prog_surface_resolved", None)
        if _psr is not None:
            _pl = getattr(self, "gf_prog_surface_placed", "?")
            _sp = getattr(self, "gf_prog_surface_spilled", "?")
            spoiler_handle.write(
                f"\nElden Ring ({name}) progression surface: resolved rung {_psr} "
                f"-- {_pl} progression items confined to surface, {_sp} spilled to pool.\n")
        try:
            sd = self.fill_slot_data()
            spoiler_handle.write(f"\nElden Ring ({name}) slot_data ({len(sd)} keys) -- exactly what the client receives:\n")
            for k in sorted(sd):
                v = sd[k]
                rv = repr(v)
                if len(rv) > 220:
                    n = len(v) if hasattr(v, "__len__") else "?"
                    rv = rv[:220] + f"  ...(+{type(v).__name__}, {n} entries)"
                spoiler_handle.write(f"  {k} = {rv}\n")
        except Exception as e:
            spoiler_handle.write(f"  (slot_data dump failed: {e!r})\n")

    def generate_output(self, output_directory: str) -> None:
        # Post-fill CHECK BREAKDOWN, printed to the generate log so a seed can be judged on
        # progression shape + filler locality at a glance (not just "it genned"): how each of this
        # slot's checks was filled -- own progression / own useful / own (local) filler / another
        # world's item (foreign), split useful vs filler. Solo seeds show foreign = 0.
        p = self.player
        prog = useful = local_filler = foreign_filler = foreign_useful = 0
        for loc in self.multiworld.get_locations(p):
            it = loc.item
            if it is None:
                continue
            important = bool(it.advancement) or bool(it.classification & ItemClassification.useful)
            if it.player == p:
                if it.advancement:
                    prog += 1
                elif it.classification & ItemClassification.useful:
                    useful += 1
                else:
                    local_filler += 1
            elif important:
                foreign_useful += 1
            else:
                foreign_filler += 1
        total = prog + useful + local_filler + foreign_filler + foreign_useful
        print(
            f"[greenfield] {self.multiworld.get_player_name(p)}: {total} checks | "
            f"progression {prog} | useful {useful} | local filler {local_filler} | "
            f"foreign filler {foreign_filler} | foreign useful {foreign_useful}"
        )

        # --- per-sphere item dump (env ER_GF_DUMP_SPHERES; upgrade-curve analytics) ---------------
        # get_spheres() is heavy, so compute it ONCE for the whole multiworld (the lowest player id)
        # and write {player_name: [[item names in sphere 0], [sphere 1], ...]} to JSON. Inert unless
        # the env var is set. Only reachable, item-bearing locations appear in spheres. NOTE: one AP
        # item == one check grant, so a vanilla "x3" stack still counts as 1 here (the pool-tuning unit).
        import os as _os, json as _json
        if _os.environ.get("ER_GF_DUMP_SPHERES") and self.player == min(self.multiworld.player_ids):
            try:
                per_player = {}
                for sidx, locset in enumerate(self.multiworld.get_spheres()):
                    for loc in locset:
                        it = loc.item
                        if it is None or loc.player not in self.multiworld.player_ids:
                            continue
                        pl = per_player.setdefault(self.multiworld.get_player_name(loc.player), [])
                        while len(pl) <= sidx:
                            pl.append([])
                        pl[sidx].append(it.name)
                fn = _os.path.join(output_directory, f"GF_SPHERES_{self.multiworld.seed_name}.json")
                with open(fn, "w", encoding="utf-8") as _f:
                    _json.dump({"seed": str(self.multiworld.seed_name), "spheres": per_player}, _f)
                print(f"[greenfield] ER_GF_DUMP_SPHERES -> {fn}")
            except Exception as _e:
                print(f"[greenfield] ER_GF_DUMP_SPHERES dump failed: {_e!r}")
