"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT.
Placed repeatable mine-material ItemLotParam_map rows eligible for per-seed reroll.
Capstones and unplaced asset templates are deliberately absent."""
MINE_MATERIAL_LOTS = (998600, 998610, 998620, 998630, 998640, 998650, 998700, 998710, 998720, 998730, 998740)
