"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot
contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in
the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""
REGION_OPEN_FLAGS = {
    'Abyssal': 76860,
    'Ainsel River': 71211,
    'Altus': 73204,
    'Ancient Ruins': 76940,
    'Belurat': 72001,
    'Caelid': 73207,
    'Cerulean': 76831,
    "Charo's": 76841,
    'Deeproot Depths': 71231,
    'Enir Ilim': 72012,
    'Ensis': 76821,
    'Farum Azula': 71303,
    'Gravesite': 76800,
    'Haligtree': 71501,
    'Jagged Peak': 76840,
    'Leyndell': 71102,
    'Limgrave': 73100,
    'Liurnia': 73202,
    'Mohgwyn': 71251,
    'Mountaintops of the Giants': 73017,
    'Mt. Gelmir': 76350,
    'Rauh Base': 76912,
    'Raya Lucaria Academy': 71402,
    'Scadu Altus': 76900,
    'Scaduview': 76935,
    'Sewer': 73501,
    'Shadow Keep': 72102,
    'Siofra River': 71222,
    'Stone Coffin': 72201,
    'Stormveil': 71003,
    'Weeping': 73102,
}

REGION_OPEN_PENDING = [
]

_GEN_STAMP = {'inputs_hash': 'sha256:41e4d4f96491d2427b096e129f2599b5584421ff3f45b488b3df70d3b5eea2b1', 'module': 'region_open_flags.py', 'body_sha256': 'sha256:b622d059856edcf4d6f833e1d60b73f74dc4a11fdb82665df19bbc3ac6b2fa43'}
