//! shop_flags.rs — make pure-runtime shop checks detectable by writing the AP tracking flag onto the
//! live `ShopLineupParam` rows, the same idea the bake did on disk but done in memory at runtime.
//!
//! Background (see memory `er-shop-detection-pureruntime-gap`): the flag-poll detects a shop purchase
//! by watching the slot's `eventFlag_forStock`. 419/484 shop checks already work because the detection
//! table reuses the slot's VANILLA stock flag, which the unbaked game sets on buy. The other ~45 slots
//! have a vanilla stock flag the bake REWROTE to an AP tracking flag — e.g. row 100576 is `69630` in
//! vanilla but the detection table watches `150960`. So a vanilla purchase sets 69630, the poller
//! watches 150960, nothing fires. Fix: overwrite the row's `eventFlag_forStock` (69630 -> 150960) so a
//! purchase sets exactly the flag the poller already watches. `sellQuantity` is already 1 (one-time),
//! so no other field changes (the lone qty=3 row, 100506, would also want sellQuantity=1 — TODO).
//!
//! Row layout (Paramdex SHOP_LINEUP_PARAM): equipId@+0x00, value@+0x04, mtrlId@+0x08,
//! **eventFlag_forStock@+0x0C (u32)**, eventFlag_forRelease@+0x10, sellQuantity@+0x14 (s16).
//! The row pointer comes from the same `SoloParamRepository` typed lookup `params.rs` uses for goods.
//!
//! STAGED like `fmg_inject`:
//!   MODE_PROBE (default): READ-ONLY. Read `eventFlag_forStock` for a few known rows and check it
//!     matches the vanilla CSV — proves the +0x0C offset + crate row access before any write.
//!   MODE_WRITE: overwrite `eventFlag_forStock` for each (row,flag) in the injected map; idempotent.
//! SAFETY: writes only the one u32 field on rows we were explicitly given; skips if already equal;
//! param memory is the live table the game itself writes (RW). Gated in-world (params populated).

#![allow(dead_code)]

use eldenring::cs::{ShopLineupParam, SoloParamRepository};
use eldenring::param::SHOP_LINEUP_PARAM;
use fromsoftware_shared::FromStatic;

/// Byte offset of `eventFlag_forStock` (u32) within a SHOP_LINEUP_PARAM row (from the Paramdex def).
const STOCK_FLAG_OFF: usize = 0x0C;

const MODE_PROBE: u8 = 0;
const MODE_WRITE: u8 = 1;
/// PROBE confirmed 3/3 (offset +0x0C, row access) 2026-06-30 → WRITE.
const MODE: u8 = MODE_WRITE;

/// The 45 "rewrite" shop rows: (ShopLineupParam row id, AP tracking flag the detection table watches).
/// Generated by `build_shop_row_flags.py` (see `Archipelago/worlds/eldenring/shop_row_flags.json`) from
/// vanilla data — these rows have a vanilla stock flag the bake rewrote to an AP flag, so a vanilla buy
/// sets the wrong flag and the poll never fires. EMBEDDED for testing; production should pass the
/// active-seed subset via slot_data `shopRowFlags` (so non-shop-check seeds are untouched). The 20
/// `need_fresh_flag` slots are NOT here — they need an allocated flag (next step).
const REUSE_ROW_FLAGS: &[(u32, u32)] = &[
    (100576, 150960), (100585, 150970), (100575, 150980), (100501, 150060), (100500, 150080),
    (100514, 150210), (100502, 150090), (100503, 150120), (100504, 150140), (100506, 150220),
    (100539, 150480), (100525, 150490), (100540, 150500), (100551, 150550), (101800, 280060),
    (101801, 280590), (101859, 250540), (100625, 160350), (100700, 170070), (100751, 170550),
    (100752, 170560), (100750, 170570), (100950, 190540), (100951, 190550), (100925, 190290),
    (100926, 190300), (100696, 170080), (100686, 160960), (100687, 160970), (100675, 160770),
    (100837, 180460), (100825, 180270), (100827, 180470), (100101, 110060), (100650, 160530),
    (100605, 160250), (100606, 160260), (100340, 130790), (100325, 130310), (100326, 130320),
    (100743, 170540), (100725, 170500), (100875, 180790), (100886, 180940), (100876, 180810),
];

/// (row_id, expected vanilla eventFlag_forStock) — read straight from the vanilla ShopLineupParam.csv.
/// 100053 = Sellen "Glintstone Pebble" (a flag-backed/already-detectable slot, vanilla flag 100530).
/// 100576 / 100500 = two of the 45 "needs rewrite" slots (vanilla 69630 / 69620; the table wants
/// 150960 / 150080). If these read back as expected, the +0x0C offset and row access are correct.
const PROBE_ROWS: &[(u32, u32)] = &[(100053, 100530), (100576, 69630), (100500, 69620)];

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
static DONE: AtomicBool = AtomicBool::new(false);

/// Seed-accurate row->flag map from slot_data `shopRowFlags` (set by net.rs at connect). `SET` flips
/// true once net has parsed slot_data — even to an empty map (shop_checks off), which correctly means
/// "inject nothing". Until then `run` falls back to the embedded `REUSE_ROW_FLAGS` so pre-patch builds
/// (apworld that doesn't emit `shopRowFlags`) still work.
static CONFIGURED: Mutex<Vec<(u32, u32)>> = Mutex::new(Vec::new());
static CONFIGURED_SET: AtomicBool = AtomicBool::new(false);

/// Called by net.rs once slot_data is parsed. `rows` = (ShopLineupParam row id, AP tracking flag).
pub fn configure(rows: Vec<(u32, u32)>) {
    tracing::info!("shop-flags: configured {} row(s) from slot_data shopRowFlags", rows.len());
    *CONFIGURED.lock().unwrap() = rows;
    CONFIGURED_SET.store(true, Ordering::Relaxed);
}

/// Resolve the live row and return the address of its `eventFlag_forStock` field, or None if the
/// param repo isn't up yet / the row id is absent.
fn stock_flag_addr(row_id: u32) -> Option<usize> {
    // SAFETY: FD4 singleton; on the game thread (caller gates in-world). `get::<ShopLineupParam>`
    // mirrors `params.rs`'s `get::<EquipParamGoods>` — returns Option<&SHOP_LINEUP_PARAM>.
    let repo = unsafe { SoloParamRepository::instance() }.ok()?;
    let row: &SHOP_LINEUP_PARAM = repo.get::<ShopLineupParam>(row_id)?;
    Some((row as *const SHOP_LINEUP_PARAM as usize) + STOCK_FLAG_OFF)
}

fn read_stock_flag(row_id: u32) -> Option<u32> {
    let a = stock_flag_addr(row_id)?;
    Some(unsafe { (a as *const u32).read_unaligned() })
}

/// Overwrite a row's `eventFlag_forStock`. Returns Some(old) on success. Idempotent: if it already
/// equals `flag`, it still returns Some(flag) without writing.
fn write_stock_flag(row_id: u32, flag: u32) -> Option<u32> {
    let a = stock_flag_addr(row_id)?;
    let p = a as *mut u32;
    let old = unsafe { p.read_unaligned() };
    if old != flag {
        unsafe { p.write_unaligned(flag) };
    }
    Some(old)
}

/// PROBE: read the known rows and report whether the live `eventFlag_forStock` matches the vanilla CSV.
/// Returns false while the param repo isn't up yet (so the caller retries next tick); true once logged.
fn probe() -> bool {
    if read_stock_flag(PROBE_ROWS[0].0).is_none() {
        return false; // repo not ready
    }
    let mut ok = 0;
    for &(row, expect) in PROBE_ROWS {
        match read_stock_flag(row) {
            Some(got) => {
                let m = if got == expect {
                    ok += 1;
                    "MATCH"
                } else {
                    "MISMATCH"
                };
                tracing::info!("shop-flags PROBE: row {row} eventFlag_forStock={got} (expect {expect}) [{m}]");
            }
            None => tracing::warn!("shop-flags PROBE: row {row} not present in ShopLineupParam"),
        }
    }
    tracing::info!(
        "shop-flags PROBE: === {ok}/{} match; +0x{STOCK_FLAG_OFF:X} offset {} ===",
        PROBE_ROWS.len(),
        if ok == PROBE_ROWS.len() { "CONFIRMED -> safe to flip MODE_WRITE" } else { "WRONG -> do not write" }
    );
    true
}

/// Run once in-world. PROBE reads + validates; WRITE applies `row_flags` (row_id -> AP tracking flag,
/// from slot_data `shopRowFlags` / the apworld emission). Latches DONE so it doesn't re-run.
pub fn run(row_flags: &[(u32, u32)]) -> bool {
    if DONE.load(Ordering::Relaxed) {
        return true;
    }
    if MODE == MODE_PROBE {
        if !probe() {
            return false;
        }
        DONE.store(true, Ordering::Relaxed);
        return true;
    }

    // MODE_WRITE
    if read_stock_flag(PROBE_ROWS[0].0).is_none() {
        return false; // repo not ready
    }
    // Source precedence: explicit arg > slot_data `shopRowFlags` (seed-accurate; may be empty when
    // shop_checks is off) > embedded full table (pre-patch fallback). Cloned into a local Vec so we
    // don't hold the Mutex across the write loop.
    let configured: Vec<(u32, u32)> = CONFIGURED.lock().unwrap().clone();
    let owned: Vec<(u32, u32)> = if !row_flags.is_empty() {
        row_flags.to_vec()
    } else if CONFIGURED_SET.load(Ordering::Relaxed) {
        configured
    } else {
        REUSE_ROW_FLAGS.to_vec()
    };
    let row_flags: &[(u32, u32)] = &owned;
    if row_flags.is_empty() {
        DONE.store(true, Ordering::Relaxed); // shop_checks off: nothing to inject
        return true;
    }
    let mut wrote = 0;
    for &(row, flag) in row_flags {
        match write_stock_flag(row, flag) {
            Some(old) if old != flag => {
                wrote += 1;
                tracing::info!("shop-flags WRITE: row {row} eventFlag_forStock {old} -> {flag}");
            }
            Some(_) => { /* already correct (idempotent re-run) */ }
            None => tracing::warn!("shop-flags WRITE: row {row} absent; skipped"),
        }
    }
    tracing::info!("shop-flags WRITE: === injected {wrote}/{} rows ===", row_flags.len());
    DONE.store(true, Ordering::Relaxed);
    true
}
