# -*- coding: utf-8 -*-
"""Convert the randomizer's ap_location_coords dump into a per-check nearest-grace
distance lookup for the check-trim pass (SPEC-check-trim.md, Phase 2).

The randomizer (ArchipelagoForm) writes `ap_location_coords_<stamp>.txt` to the repo
root during gen: TSV rows  type<TAB>key<TAB>tileX<TAB>tileZ<TAB>gx<TAB>gy<TAB>gz
where type is 'grace' or 'item', key is the apworld location key, and gx/gy/gz are
GLOBAL coords (tile = global 256m tile). For each item we find the nearest grace in
the same or an adjacent global tile (so overworld neighbours match and each legacy/
underground map compares within itself) and record the planar (x,z) distance in metres.

Output: Archipelago/worlds/eldenring/location_remoteness.py  ->  LOC_GRACE_DIST = {key: metres}
Run after a gen:  python3 tools/build_location_remoteness.py [path_to_dump]
"""
import sys, os, glob, math

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Archipelago", "worlds", "eldenring", "location_remoteness.py")

def find_dump():
    if len(sys.argv) > 1:
        return sys.argv[1]
    cands = (glob.glob(os.path.join(ROOT, "ap_location_coords_*.txt"))
             + glob.glob(os.path.join(ROOT, "SoulsRandomizers", "ap_location_coords_*.txt")))
    if not cands:
        return None
    return max(cands, key=os.path.getmtime)

def main():
    path = find_dump()
    if not path or not os.path.exists(path):
        print("No ap_location_coords_*.txt found in repo root. Run a gen with the patched "
              "randomizer first (it writes the dump), then re-run this. Nothing written.")
        return 1
    graces = []   # (tx, tz, gx, gz)
    items = []    # (key, tx, tz, gx, gz)
    with open(path, encoding="utf-8", errors="replace") as f:
        next(f, None)  # header
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 7:
                continue
            typ, key, tx, tz, gx, gy, gz = p[:7]
            try:
                rec = (int(tx), int(tz), float(gx), float(gz))
            except ValueError:
                continue
            if typ == "grace":
                graces.append(rec)
            elif typ == "item":
                items.append((key,) + rec)
    if not graces or not items:
        print(f"Parsed {len(graces)} graces, {len(items)} items from {os.path.basename(path)} "
              "-- need both; nothing written.")
        return 1
    # bucket graces by tile for fast adjacency lookup
    from collections import defaultdict
    by_tile = defaultdict(list)
    for tx, tz, gx, gz in graces:
        by_tile[(tx, tz)].append((gx, gz))
    dist = {}
    far_count = 0
    for key, tx, tz, gx, gz in items:
        best = math.inf
        for dx in (-1, 0, 1):
            for dz in (-1, 0, 1):
                for (cx, cz) in by_tile.get((tx + dx, tz + dz), ()):  # noqa
                    d = math.hypot(gx - cx, gz - cz)
                    if d < best:
                        best = d
        if math.isinf(best):
            best = 9999.0
            far_count += 1
        dist[key] = round(best, 1)
    # write module
    lines = ["# -*- coding: utf-8 -*-",
             '"""AUTO-GENERATED by tools/build_location_remoteness.py from ap_location_coords.',
             "Per-check planar distance (metres) to the nearest Site of Grace in the same/adjacent",
             'global tile. Consumed by EldenRing._remoteness (SPEC-check-trim.md). Do not hand-edit."""',
             "",
             "LOC_GRACE_DIST = {"]
    for k in sorted(dist):
        lines.append('    %r: %s,' % (k, dist[k]))
    lines.append("}")
    with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines) + "\n")
    # stats
    vals = sorted(dist.values())
    def pct(p):
        return vals[min(len(vals) - 1, int(len(vals) * p))]
    print(f"wrote {OUT}")
    print(f"  items with coords: {len(dist)} (no grace in adjacent tile: {far_count})")
    print(f"  distance percentiles (m): p50={pct(.5)} p75={pct(.75)} p90={pct(.9)} max={vals[-1]}")
    for thr in (70, 100, 140, 200):
        print(f"  >= {thr}m: {sum(1 for v in vals if v >= thr)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
