#!/usr/bin/env python3
"""Render the complete Patch 1.17 item and acquisition-route disposition census (#1096)."""

import argparse
import importlib.util
import os
import sys


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "greenfield", "eldenring", "tarnished_pack.py")
OUTPUT = os.path.join(ROOT, "docs", "TARNISHED-PACK-CENSUS.md")


def _catalog():
    spec = importlib.util.spec_from_file_location("_tarnished_pack_census", SOURCE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def render():
    tp = _catalog()
    admitted = [row for row in tp.TARNISHED_PACK_ROUTE_CENSUS if row[2] == "admitted"]
    blocked = [row for row in tp.TARNISHED_PACK_ROUTE_CENSUS if row[2] != "admitted"]
    lines = [
        "# Tarnished Pack integration census",
        "",
        "Generated by `python tools/build_tarnished_pack_census.py`. Do not edit by hand.",
        "",
        "This is the complete disposition ledger for the Patch 1.17 rows and acquisition routes",
        "tracked by #1096. A blocked route is known content, not a missing census entry.",
        "",
        "## Item rows",
        "",
        "| Category | Total | Disposition |",
        "|---|---:|---|",
        f"| Weapons | {len(tp.TARNISHED_PACK_WEAPON_IDS)} | "
        f"{len(tp.TARNISHED_PACK_WEAPON_IDS - tp.TARNISHED_PACK_NPC_ONLY_WEAPON_IDS)} admitted; "
        f"{len(tp.TARNISHED_PACK_NPC_ONLY_WEAPON_IDS)} NPC-only |",
        f"| Armor | {len(tp.TARNISHED_PACK_ARMOR_IDS)} | all admitted |",
        f"| Goods | {len(tp.TARNISHED_PACK_GOODS_IDS)} | Spectral Steed unlock semantics blocked |",
        f"| **Total** | **{len(tp.TARNISHED_PACK_FULL_IDS)}** | "
        f"**{len(tp.TARNISHED_PACK_EQUIPMENT)} player equipment admitted** |",
        "",
        "## Acquisition routes",
        "",
        f"**{len(admitted)} admitted; {len(blocked)} blocked with an explicit evidence gap.**",
        "",
        "| Flag | Kind | Disposition | Route |",
        "|---:|---|---|---|",
    ]
    for flag, kind, disposition, label in tp.TARNISHED_PACK_ROUTE_CENSUS:
        lines.append(f"| `{flag}` | {kind} | {disposition} | {label} |")
    lines.extend([
        "",
        "The two invasion checks remain excluded until generic-invasion availability and the",
        "Leyndell-to-Ashen cutoff are proven. The three attire checks remain excluded until their",
        "asset activation and non-inventory unlock/grant behavior are proven live.",
        "",
    ])
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render()
    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as handle:
                actual = handle.read()
        except FileNotFoundError:
            actual = ""
        if actual != expected:
            print("Tarnished Pack census is stale; run tools/build_tarnished_pack_census.py",
                  file=sys.stderr)
            return 1
        return 0
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(expected)
    print(os.path.relpath(OUTPUT, ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
