#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_tile_grace.py -- map tile -> representative Site of Grace name (desc_sources layer 4b).

Emits greenfield/tile_grace.tsv (tile<TAB>grace_name). For each map tile, the representative grace is
the lowest-flag grace ON that tile that is NOT a boss-arena grace (so a legacy tile shows e.g.
"Belurat, Tower Settlement", not the Dancing Lion arena "Theatre of the Divine Beast"); if every grace
on the tile is an arena grace, fall back to the lowest-flag one.

PURE: reads only committed tsvs -- greenfield/grace_flags.tsv (grace -> tile), grace_names.tsv
(grace -> name, from tools/datamine_grace_names.py), arena_graces.tsv (arena graces to exclude). So it
runs in the sandbox with no artifacts once grace_names.tsv is committed:
    python3 tools/build_tile_grace.py
"""
import csv
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
GF = os.path.join(ROOT, "greenfield")
OUT = os.path.join(GF, "tile_grace.tsv")


def _read_names():
    names, path = {}, os.path.join(GF, "grace_names.tsv")
    if not os.path.isfile(path):
        return names
    for ln in open(path, encoding="utf-8-sig"):
        if ln.startswith("#") or not ln.strip():
            continue
        p = ln.rstrip("\n").split("\t")
        if len(p) >= 2 and p[0].strip().isdigit():
            names[int(p[0])] = p[1].strip()
    return names


def _read_tileof():
    tileof, path = {}, os.path.join(GF, "grace_flags.tsv")
    for r in csv.DictReader(open(path, encoding="utf-8-sig"), delimiter="\t"):
        try:
            tileof[int(r["warpUnlockFlag"])] = r["mapTile"].strip()
        except (KeyError, ValueError, TypeError):
            pass
    return tileof


def _read_arena():
    arena, path = set(), os.path.join(GF, "arena_graces.tsv")
    if os.path.isfile(path):
        for ln in open(path, encoding="utf-8"):
            if ln[:1].isdigit():
                try:
                    arena.add(int(ln.split("\t")[0]))
                except ValueError:
                    pass
    return arena


def main():
    names = _read_names()
    if not names:
        print("greenfield/grace_names.tsv missing/empty -- run tools/datamine_grace_names.py first. "
              "Nothing written.", file=sys.stderr)
        return 1
    tileof, arena = _read_tileof(), _read_arena()
    by_tile = {}
    for fl, t in tileof.items():
        if fl in names:
            by_tile.setdefault(t, []).append(fl)
    tile_grace = {}
    for t, fs in by_tile.items():
        non = [f for f in fs if f not in arena]
        tile_grace[t] = names[min(non)] if non else names[min(fs)]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# AUTO-GENERATED by tools/build_tile_grace.py -- map tile -> representative Site of Grace\n")
        f.write("# name (lowest-flag NON-arena grace on the tile, from grace_flags.tsv + grace_names.tsv;\n")
        f.write("# arena graces excluded via arena_graces.tsv). desc_sources layer 4b renders 'around <name>'.\n")
        f.write("tile\tgrace_name\n")
        for t in sorted(tile_grace):
            f.write(f"{t}\t{tile_grace[t]}\n")
    print(f"wrote {OUT}: {len(tile_grace)} tiles")
    return 0


if __name__ == "__main__":
    sys.exit(main())
