#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""build_nearest_grace.py -- PURE nearest-Site-of-Grace resolver for the location-description
layer 4 (desc_sources.py). Consumes a coordinate dump and writes greenfield/nearest_grace.tsv
(``flag<TAB>grace_name``), which gen_data renders as "near <grace name>".

INPUT: a coords tsv (default greenfield/item_grace_coords.tsv, produced on Windows by
tools/datamine_item_grace_coords.py) with one row per item AND per grace:

    kind<TAB>key<TAB>map_id<TAB>x<TAB>y<TAB>z<TAB>name

  kind  : 'item' or 'grace'
  key   : the check's event flag (item) / the grace's warpUnlockFlag (grace)
  map_id: witchy MSB map (e.g. m20_01_00_00); positions are MAP-LOCAL, so only compared within a map
  x/y/z : map-local coordinates (metres)
  name  : the human grace name (grace rows only; blank for items)

For each item we pick the nearest grace IN THE SAME map (map-local frame; the same rule
datamine_arena_graces.py relies on). Overworld tiles that legitimately share a border are handled by
the extractor emitting a shared/global map key; this builder only trusts same-map comparisons.

This module is import-safe and side-effect-free (tests call build_map()/nearest() directly). Run:
    python3 tools/build_nearest_grace.py [coords.tsv] [--out greenfield/nearest_grace.tsv] [--max-dist M]
"""
import argparse
import math
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_IN = os.path.join(ROOT, "greenfield", "item_grace_coords.tsv")
DEFAULT_OUT = os.path.join(ROOT, "greenfield", "nearest_grace.tsv")


def _dist(a, b):
    return math.sqrt((a[0] - b[0]) ** 2 + (a[1] - b[1]) ** 2 + (a[2] - b[2]) ** 2)


def parse_coords(lines):
    """Iterable of raw tsv lines -> (items, graces_by_map).
    items: list of (flag:int, map_id:str, (x,y,z)); graces_by_map: {map_id: [((x,y,z), name), ...]}."""
    items = []
    graces_by_map = {}
    for ln in lines:
        if not ln.strip() or ln.lstrip().startswith("#"):
            continue
        p = ln.rstrip("\n").split("\t")
        if len(p) < 6 or p[0] not in ("item", "grace"):
            continue
        kind, key, map_id = p[0], p[1].strip(), p[2].strip()
        try:
            xyz = (float(p[3]), float(p[4]), float(p[5]))
        except ValueError:
            continue
        name = p[6].strip() if len(p) > 6 else ""
        if kind == "grace":
            graces_by_map.setdefault(map_id, []).append((xyz, name))
        else:
            if not key.lstrip("-").isdigit():
                continue
            items.append((int(key), map_id, xyz))
    return items, graces_by_map


def nearest(item_xyz, graces, max_dist=None):
    """Return (name, distance) of the nearest named grace, or (None, None). Unnamed graces are
    ignored (a grace with no resolved name is useless as a descriptor)."""
    best_d, best_name = math.inf, None
    for gxyz, name in graces:
        if not name:
            continue
        d = _dist(item_xyz, gxyz)
        if d < best_d:
            best_d, best_name = d, name
    if best_name is None or (max_dist is not None and best_d > max_dist):
        return None, None
    return best_name, round(best_d, 1)


def build_map(lines, max_dist=None):
    """Raw coord lines -> {flag: grace_name}. Same-map nearest only."""
    items, graces_by_map = parse_coords(lines)
    out = {}
    for flag, map_id, xyz in items:
        name, _ = nearest(xyz, graces_by_map.get(map_id, ()), max_dist=max_dist)
        if name:
            out[flag] = name
    return out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("coords", nargs="?", default=DEFAULT_IN)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--max-dist", type=float, default=None,
                    help="drop matches farther than this many metres (default: no cap)")
    args = ap.parse_args(argv)
    if not os.path.isfile(args.coords):
        print(f"coords file not found: {args.coords}\n"
              f"Run tools/datamine_item_grace_coords.py on Windows first. Nothing written.")
        return 1
    with open(args.coords, encoding="utf-8-sig", newline="") as fh:
        mapping = build_map(fh, max_dist=args.max_dist)
    with open(args.out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("# nearest_grace.tsv -- AUTO-GENERATED by tools/build_nearest_grace.py. DO NOT hand-edit;\n")
        fh.write("# manual fixes go in greenfield/location_descriptions.tsv (layer 1, wins). See\n")
        fh.write("# docs/specs/SPEC-location-descriptions.md.\n")
        fh.write("flag\tgrace_name\n")
        for flag in sorted(mapping):
            fh.write(f"{flag}\t{mapping[flag]}\n")
    print(f"wrote {args.out}: {len(mapping)} checks matched to a nearest grace")
    return 0


if __name__ == "__main__":
    sys.exit(main())
