#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""datamine_grace_names.py -- grace warp flag -> grace display name, from vanilla game files.

Emits greenfield/grace_names.tsv (grace_flag<TAB>name), consumed by tools/build_tile_grace.py
(desc_sources layer 4b) and, later, the coord/nearest-grace layer + the map tracker.

Derivation (matt-free): BonfireWarpParam row -> `eventflagId` is the grace's warp-unlock flag (the
same key as grace_flags.tsv); `textId1` indexes the PlaceName FMG, whose entry is the grace's shown
name. DLC place names live in the item_dlc0*/PlaceName*.fmg.xml tables; base names in
item-msgbnd-dcx/PlaceName.fmg.xml -- try DLC first, then base. Yields 419/422 named (the 3 unnamed are
non-explorable system warps -- matches REGION_ID_MAP.md's own count).

Reads elden_ring_artifacts (unpacked witchy FMG xml + vanilla_params CSVs). Pure Python, no Oodle, so
it runs anywhere the artifacts are readable (Windows, or a Linux box with the folder mounted):
    python tools/datamine_grace_names.py
"""
import csv
import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
AR = os.path.join(ROOT, "elden_ring_artifacts")
OUT = os.path.join(ROOT, "greenfield", "grace_names.tsv")

_TEXT_RE = re.compile(r'<text id="(\d+)"[^>]*>(.*?)</text>', re.S)
_NULLS = ("%null%", "&lt;?null?&gt;", "x", "")


def _fmg(path):
    d = {}
    if not os.path.isfile(path):
        return d
    for m in _TEXT_RE.finditer(open(path, encoding="utf-8", errors="replace").read()):
        v = m.group(2).strip()
        if v not in _NULLS:
            d[int(m.group(1))] = v
    return d


def main():
    base = _fmg(os.path.join(AR, "msg", "item-msgbnd-dcx", "PlaceName.fmg.xml"))
    dlc = {}
    for fp in glob.glob(os.path.join(AR, "msg", "item_dlc0*-msgbnd-dcx", "PlaceName*.fmg.xml")):
        dlc.update(_fmg(fp))
    if not base and not dlc:
        print(f"no PlaceName FMGs under {AR}/msg -- nothing written.", file=sys.stderr)
        return 1
    bwp = os.path.join(AR, "vanilla_params", "BonfireWarpParam.csv")
    if not os.path.isfile(bwp):
        print(f"missing {bwp} -- nothing written.", file=sys.stderr)
        return 1
    gname = {}
    for r in csv.DictReader(open(bwp, encoding="utf-8", errors="replace")):
        fl = r.get("eventflagId", "")
        if not fl.lstrip("-").isdigit() or int(fl) <= 200:   # <=200 = system/default warps, not graces
            continue
        try:
            tid = int(r["textId1"])
        except (KeyError, ValueError):
            continue
        if tid < 0:
            continue
        nm = dlc.get(tid) or base.get(tid)
        if nm:
            gname[int(fl)] = nm
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("# AUTO-GENERATED by tools/datamine_grace_names.py -- BonfireWarpParam.eventflagId ->\n")
        f.write("# textId1 -> PlaceName FMG (base + DLC). grace warp flag -> grace display name.\n")
        f.write("grace_flag\tname\n")
        for fl in sorted(gname):
            f.write(f"{fl}\t{gname[fl]}\n")
    print(f"wrote {OUT}: {len(gname)} graces named")
    return 0


if __name__ == "__main__":
    sys.exit(main())
