#!/usr/bin/env python3
"""Emit greenfield/eldenring/death_award_pairs.json -- the (death flag, check flag) pairs behind
EMEVD corpse-treasure awards, so the client can detect a death the event system never witnessed
(clients#385; the rouqs Leyndell Tree Spirit, 2026-08-22).

THE MECHANISM. Common events 90005300/90005301 award a treasure on a character's death:
`WaitFor(CharacterRatioDead(chr))` -> set the death flag -> `ForceCharacterTreasure` puts the lot
on the corpse. Their reload branch is unforgiving when `value == 0`: a set death flag on re-entry
force-kills the corpse WITHOUT re-forcing the treasure -- so a death the event missed (despawn,
fall, death during a load) or a corpse left unlooted across one reload leaves the check
PERMANENTLY unpayable in-game. Death flag up + check flag down is therefore a complete, save-
persistent signature of a missed award, and the client can fire the check from it retroactively.

WHAT IS EMITTED. One pair per init whose lot is a CHECK (flag_lots.tsv membership), `value == 0`
sites only: the six `value == 2` sites re-force the corpse treasure on every reload, so death-up +
check-down there means "not looted yet", not "lost" -- sweeping them would eat a live corpse.
Measured on the current corpus: 185 check-joined pairs, 179 sweepable, 6 excluded.

GAME data, not seed data -- ships beside the dll like check_lots_table.json (build.ps1 -Me3Deploy
copies it; package_release stages it), read by any seed old or new. No slot_data, no contract.
"""
import json
import os
import re
import sys
import zlib
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.environ.get("ER_REPO") or os.path.abspath(os.path.join(HERE, ".."))
EVENT_DIR = os.path.join(REPO, "elden_ring_artifacts", "event")
FLAG_LOTS = os.path.join(REPO, "greenfield", "flag_lots.tsv")
OUT = os.path.join(REPO, "greenfield", "eldenring", "death_award_pairs.json")

# The death-award family. Derived by scanning common_func for events whose body waits on
# CharacterRatioDead and forces a treasure; extend here (with the measurement) if a sibling appears.
AWARD_EVENTS = ("90005300", "90005301")
RX = re.compile(r"InitializeCommonEvent\(0, (" + "|".join(AWARD_EVENTS) + r")((?:, [\-\d]+)+)\)")


def main():
    if not os.path.isdir(EVENT_DIR):
        sys.exit("FATAL: %s missing -- run tools/gen_inputs.py --ensure elden_ring_artifacts. "
                 "Nothing written." % EVENT_DIR)
    if not os.path.isfile(FLAG_LOTS):
        sys.exit("FATAL: greenfield/flag_lots.tsv missing -- the lot->check join needs it. "
                 "Nothing written.")
    lot2flag = {}
    with open(FLAG_LOTS, encoding="utf-8-sig") as fh:
        for ln in fh:
            if ln.startswith("#") or not ln.strip():
                continue
            p = ln.rstrip("\n").split("\t")
            if p[0].isdigit() and len(p) > 2 and p[1] == "map":
                lot2flag[int(p[2])] = int(p[0])

    pairs = set()
    values = Counter()
    scanned = 0
    for root, _, files in os.walk(EVENT_DIR):
        for fn in files:
            path = os.path.join(root, fn)
            with open(path, "rb") as fh:
                raw = fh.read()
            try:
                text = raw.decode("utf-8")
            except UnicodeDecodeError:
                try:
                    text = zlib.decompress(raw).decode("utf-8", "replace")
                except zlib.error:
                    continue
            scanned += 1
            for m in RX.finditer(text):
                args = [int(x) for x in m.group(2).strip(", ").split(", ")]
                # (eventFlagId, chrEntityId, itemLotId, timeSeconds, value) -- uniform 5-arg on the
                # current corpus; a shorter form defaults value to 0, the conservative direction.
                if len(args) < 3 or args[2] == 0:
                    continue
                lot = args[2]
                if lot not in lot2flag:
                    continue
                value = args[4] if len(args) >= 5 else 0
                values[value] += 1
                if value == 0:
                    pairs.add((args[0], lot2flag[lot]))
    if not pairs:
        sys.exit("FATAL: %d event file(s) scanned and ZERO sweepable pairs found -- the corpus "
                 "shape changed. Nothing written." % scanned)

    out = {
        "comment": ("AUTO-GENERATED by tools/gen_death_award_pairs.py -- (death flag, check flag) "
                    "pairs for EMEVD corpse-treasure awards, value==0 sites only (clients#385). "
                    "death UP + check DOWN in a save = the award was missed and is unrecoverable "
                    "in-game; the client fires the check."),
        "pairs": [{"death_flag": d, "check_flag": c} for d, c in sorted(pairs)],
    }
    with open(OUT, "w", newline="\n", encoding="utf-8") as f:
        json.dump(out, f, indent=1)
        f.write("\n")
    print("death_award_pairs: %d sweepable pair(s) written (value dist over check-joined inits: %s; "
          "non-zero values EXCLUDED -- their corpses re-offer) -> %s"
          % (len(pairs), dict(sorted(values.items())), os.path.relpath(OUT, REPO)))


if __name__ == "__main__":
    main()
