#!/usr/bin/env python3
"""Generate the AP location metadata table for the tracker (SPEC-item-tracker.md).

Emits `crates/er-logic/src/tracker_regions.rs` from the GREENFIELD pure-data modules.
AP-env-free: no Archipelago import, runs on any Python 3. Sources:
  - greenfield/eldenring_gf/data.py               : LOCATIONS (ap ids 7,770,000+, region membership)
  - greenfield/eldenring_gf/location_tags.py      : LOCATION_TAGS (Boss/Remembrance -> big_ticket)
  - greenfield/eldenring_gf/missable_locations.py : MISSABLE_LOCATIONS (missable ap ids)
  - greenfield/eldenring_gf/region_open_flags.py  : REGION_OPEN_FLAGS (sanity: every region has a flag)

Per AP location it emits: fine region (grouping), coarse region (the open-flag key that decides
in-logic). Greenfield has no fine/coarse split, so both are the region name; the hub (Roundtable
Hold) keeps its name as the fine grouping but gets coarse "" = always accessible. Plus
coarse-region -> lock-item name ("<Region> Lock", the exact key greenfield uses for
slot_data regionOpenFlags, core.py fill_slot_data) so the client can resolve each region to a
live open-state flag via its region_open_flags table.

    python tools/gen_location_regions.py            # regenerate + wire lib.rs
    python tools/gen_location_regions.py --check     # CI drift gate
"""
import os, importlib.util, argparse

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
GF = os.path.join(REPO, "greenfield", "eldenring_gf")
OUT_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "tracker_regions.rs")
LIB_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "lib.rs")
MOD_LINE = "pub mod tracker_regions;"

# Big-ticket tag types: loaded from the contract (single source of truth, shared with
# features/curated_fill.py) inside load_rows via load_gf("contract").BIG_TICKET_TYPES.


def load_gf(name):
    """Import a greenfield pure-data module by path (no package / AP env needed)."""
    spec = importlib.util.spec_from_file_location(
        "er_gf_" + name, os.path.join(GF, name + ".py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def load_rows():
    """[(ap_id, fine_region, coarse_region, big_ticket, missable)] sorted by id,
    plus the greenfield REGIONS list (the coarse lock-item keys)."""
    data = load_gf("data")
    tags = load_gf("location_tags").LOCATION_TAGS
    big_ticket_tags = set(load_gf("contract").BIG_TICKET_TYPES)  # contract = single source
    missable = set(load_gf("missable_locations").MISSABLE_LOCATIONS)
    open_flags = load_gf("region_open_flags").REGION_OPEN_FLAGS

    missing = [r for r in data.REGIONS if r not in open_flags]
    if missing:
        raise SystemExit(f"FATAL: regions without an open flag: {missing}")

    rows = []
    for region, locs in data.LOCATIONS.items():
        coarse = "" if region == data.HUB else region
        for _name, ap_id, _flag in locs:
            big = bool(big_ticket_tags & set(tags.get(ap_id, ())))
            rows.append((int(ap_id), region, coarse, big, ap_id in missable))
    rows = sorted(rows)
    ids = [r[0] for r in rows]
    if len(ids) != len(set(ids)):
        raise SystemExit("FATAL: duplicate ap ids in greenfield LOCATIONS")
    stray = missable - set(ids)
    if stray:
        raise SystemExit(f"FATAL: missable ids not in LOCATIONS: {sorted(stray)}")
    return rows, list(data.REGIONS)


def region_lock_items(regions):
    """coarse region name -> lock item name; greenfield locks are '<Region> Lock'
    (core.py: regionOpenFlags is keyed by exactly these names)."""
    return {r: f"{r} Lock" for r in regions}


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_rs(rows, lock_items):
    lines = []
    a = lines.append
    a("// @generated by tools/gen_location_regions.py -- DO NOT EDIT BY HAND.")
    a("// Sources: greenfield/eldenring_gf/{data,location_tags,missable_locations,region_open_flags}.py.")
    a("// Regenerate: python tools/gen_location_regions.py   (AP-env-free, pure greenfield data)")
    a("//")
    a("// Per AP location: fine region (grouping), coarse region (open-flag key for in-logic;")
    a('// "" = always accessible), big_ticket (Boss/Remembrance), missable. See SPEC-item-tracker.md.')
    a("")
    a("use std::collections::{HashMap, HashSet};")
    a("")
    a("use crate::tracker::RegionId;")
    a("")
    a("/// (id, fine_region, coarse_region, big_ticket, missable), sorted by id.")
    a("pub const LOCATION_META: &[(u64, &str, &str, bool, bool)] = &[")
    for code, region, coarse, prom, miss in rows:
        a(f'    ({code}, "{esc(region)}", "{esc(coarse)}", {str(prom).lower()}, {str(miss).lower()}),')
    a("];")
    a("")
    a("/// Coarse region name -> its region-lock ITEM name. The client resolves each to a live")
    a("/// open-state flag via `region_open_flags` (absent lock = region unlocked this seed).")
    a('/// Source: greenfield "<Region> Lock" naming (seed-independent, = regionOpenFlags keys).')
    a("pub const COARSE_LOCK_ITEMS: &[(&str, &str)] = &[")
    for r, l in sorted(lock_items.items()):
        a(f'    ("{esc(r)}", "{esc(l)}"),')
    a("];")
    a("")
    a("/// location id -> fine region name (the tracker's grouping).")
    a("pub fn location_region_table() -> HashMap<u64, RegionId> {")
    a("    LOCATION_META.iter().map(|(id, r, _, _, _)| (*id, (*r).to_string())).collect()")
    a("}")
    a("")
    a('/// location id -> coarse region key ("" = always accessible). In-logic keys off this.')
    a("pub fn location_coarse_table() -> HashMap<u64, RegionId> {")
    a("    LOCATION_META.iter().map(|(id, _, c, _, _)| (*id, (*c).to_string())).collect()")
    a("}")
    a("")
    a("/// Big-ticket (prominent) location ids.")
    a("pub fn big_ticket_set() -> HashSet<u64> {")
    a("    LOCATION_META.iter().filter(|(_, _, _, b, _)| *b).map(|(id, ..)| *id).collect()")
    a("}")
    a("")
    a("/// Missable location ids.")
    a("pub fn missable_set() -> HashSet<u64> {")
    a("    LOCATION_META.iter().filter(|(_, _, _, _, m)| *m).map(|(id, ..)| *id).collect()")
    a("}")
    a("")
    a("/// coarse region name -> lock item name.")
    a("pub fn coarse_lock_item_table() -> HashMap<RegionId, String> {")
    a("    COARSE_LOCK_ITEMS.iter().map(|(r, l)| ((*r).to_string(), (*l).to_string())).collect()")
    a("}")
    a("")
    a("#[cfg(test)]")
    a("mod generated_tests {")
    a("    use super::*;")
    a("")
    a("    #[test]")
    a("    fn nonempty_unique_sorted() {")
    a("        assert!(!LOCATION_META.is_empty());")
    a("        assert!(LOCATION_META.windows(2).all(|w| w[0].0 < w[1].0));")
    a("        assert_eq!(location_region_table().len(), LOCATION_META.len());")
    a("    }")
    a("")
    a("    #[test]")
    a("    fn coarse_keys_have_lock_items() {")
    a("        // every non-blank coarse key a location uses must resolve to a lock item")
    a("        let locks = coarse_lock_item_table();")
    a("        for (_, _, c, _, _) in LOCATION_META {")
    a("            if !c.is_empty() {")
    a('                assert!(locks.contains_key(*c), "coarse {c} has no lock item");')
    a("            }")
    a("        }")
    a("    }")
    a("}")
    a("")
    return "\n".join(lines)


def lib_has_mod():
    try:
        return MOD_LINE in open(LIB_RS, encoding="utf-8").read()
    except FileNotFoundError:
        return False


def wire_lib_rs():
    if lib_has_mod():
        return False
    text = open(LIB_RS, encoding="utf-8").read()
    nl = "\r\n" if "\r\n" in text else "\n"
    anchor = "pub mod tracker;"
    new = text.replace(anchor, anchor + nl + MOD_LINE, 1) if anchor in text \
        else text.rstrip("\r\n") + nl + MOD_LINE + nl
    open(LIB_RS, "w", encoding="utf-8", newline="").write(new)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rows, regions = load_rows()
    lock_items = region_lock_items(regions)
    new = render_rs(rows, lock_items)
    if args.check:
        try:
            cur = open(OUT_RS, encoding="utf-8").read()
        except FileNotFoundError:
            cur = ""
        if cur.replace("\r\n", "\n") != new or not lib_has_mod():
            print("STALE: run python tools/gen_location_regions.py")
            return 1
        print(f"OK: up to date ({len(rows)} locations).")
        return 0
    open(OUT_RS, "w", encoding="utf-8", newline="\n").write(new)
    wired = wire_lib_rs()
    bt = sum(1 for r in rows if r[3])
    miss = sum(1 for r in rows if r[4])
    coarse = len({r[2] for r in rows} - {""})
    print(f"Wrote {OUT_RS}: {len(rows)} locations, {bt} big-ticket, {miss} missable, "
          f"{coarse} coarse regions, {len(lock_items)} lock items.")
    print("Wired lib.rs." if wired else "lib.rs already wired.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
