#!/usr/bin/env python3
"""Generate the AP location-id -> region-name table for the item tracker.

Emits `crates/er-logic/src/tracker_regions.rs` from the apworld's
`worlds/eldenring/locations.py`. Region grouping for the tracker (SPEC-item-tracker.md,
Option A) lives as a STATIC, testable er-logic table -- this script is its source of truth.

Run on Windows in the AP dev env (the sandbox mount truncates the 6k-line locations.py):

    python tools/gen_location_regions.py            # regenerate the .rs
    python tools/gen_location_regions.py --check     # CI drift gate: nonzero if stale

It loads locations.py by path with lightweight BaseClasses/items stubs, so it does NOT
need the full Archipelago import chain (pathspec et al.). Every non-event ERLocationData
(ap_code assigned in __post_init__ from the 7_000_000 counter) is mapped to its
location_tables region key.
"""
import sys, os, types, importlib.util, argparse, hashlib

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
LOCATIONS_PY = os.path.join(REPO, "Archipelago", "worlds", "eldenring", "locations.py")
OUT_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "tracker_regions.rs")
LIB_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "lib.rs")
MOD_LINE = "pub mod tracker_regions;"


def load_location_tables():
    """Load worlds/eldenring/locations.py under a synthetic `eld` package.

    Only `BaseClasses` is stubbed (Item/Location/Region are unused at import; the
    ItemClassification metaclass resolves any flag attribute to 0). The real sibling
    modules `items` and `grace_data` load normally via the package __path__, so
    `item_table` is populated for real -- locations.py's module-level
    `location_groups()` pass needs it (KeyError otherwise).
    """
    d = os.path.dirname(LOCATIONS_PY)

    class _Meta(type):
        def __getattr__(cls, n):
            return 0

    class ItemClassification(metaclass=_Meta):
        pass

    bc = types.ModuleType("BaseClasses")
    bc.Item = type("Item", (), {})
    bc.Location = type("Location", (), {})
    bc.Region = type("Region", (), {})
    bc.ItemClassification = ItemClassification
    sys.modules["BaseClasses"] = bc

    pkg = types.ModuleType("eld")
    pkg.__path__ = [d]
    sys.modules["eld"] = pkg
    # NB: do NOT stub eld.items -- the real module builds item_table, which
    # locations.py needs. Its only non-stdlib import is BaseClasses (stubbed
    # above) and the pure-data sibling grace_data (auto-resolved via __path__).

    spec = importlib.util.spec_from_file_location("eld.locations", LOCATIONS_PY)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["eld.locations"] = mod
    spec.loader.exec_module(mod)
    return mod.location_tables


def collect_rows(location_tables):
    rows = []
    seen = {}
    for region, table in location_tables.items():
        for loc in table:
            code = getattr(loc, "ap_code", None)
            if code is None:
                continue
            if code in seen and seen[code] != region:
                raise SystemExit(
                    f"ap_code {code} maps to two regions: {seen[code]!r} and {region!r}")
            seen[code] = region
            rows.append((int(code), region))
    # dedupe (a code should appear once) and sort by ap_code
    uniq = sorted(set(rows))
    return uniq


def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_rs(rows) -> str:
    n = len(rows)
    lines = [
        "// @generated by tools/gen_location_regions.py -- DO NOT EDIT BY HAND.",
        "// Source of truth: Archipelago/worlds/eldenring/locations.py (location_tables).",
        "// Regenerate: python tools/gen_location_regions.py   (run in the Windows AP env)",
        "//",
        "// AP location id -> region name, for er_logic::tracker::build_tracker_model's",
        "// `region_of` lookup. See SPEC-item-tracker.md (Option A).",
        "",
        "use std::collections::HashMap;",
        "",
        "use crate::tracker::RegionId;",
        "",
        f"/// Every non-event AP location id paired with its region name ({n} entries),",
        "/// sorted by id.",
        "pub const LOCATION_REGIONS: &[(u64, &str)] = &[",
    ]
    for code, region in rows:
        lines.append(f'    ({code}, "{esc(region)}"),')
    lines.append("];")
    lines.append("")
    lines.append("/// Build the owned `location_id -> region` map the tracker consumes.")
    lines.append("pub fn location_region_table() -> HashMap<u64, RegionId> {")
    lines.append("    LOCATION_REGIONS")
    lines.append("        .iter()")
    lines.append("        .map(|(id, region)| (*id, (*region).to_string()))")
    lines.append("        .collect()")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod generated_tests {")
    lines.append("    use super::*;")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn table_is_nonempty_and_unique() {")
    lines.append("        assert!(!LOCATION_REGIONS.is_empty());")
    lines.append("        let map = location_region_table();")
    lines.append("        assert_eq!(map.len(), LOCATION_REGIONS.len(), \"duplicate location id\");")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn sorted_by_id() {")
    lines.append("        assert!(LOCATION_REGIONS.windows(2).all(|w| w[0].0 < w[1].0));")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def lib_has_mod() -> bool:
    try:
        with open(LIB_RS, encoding="utf-8") as f:
            return MOD_LINE in f.read()
    except FileNotFoundError:
        return False


def wire_lib_rs():
    """Insert `pub mod tracker_regions;` right after `pub mod tracker;` if absent."""
    if lib_has_mod():
        return False
    with open(LIB_RS, encoding="utf-8") as f:
        text = f.read()
    nl = "\r\n" if "\r\n" in text else "\n"
    anchor = "pub mod tracker;"
    if anchor in text:
        new = text.replace(anchor, anchor + nl + MOD_LINE, 1)
    else:
        new = text.rstrip("\r\n") + nl + MOD_LINE + nl
    with open(LIB_RS, "w", encoding="utf-8", newline="") as f:
        f.write(new)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if the committed .rs is stale (CI drift gate)")
    args = ap.parse_args()

    rows = collect_rows(load_location_tables())
    new = render_rs(rows)

    if args.check:
        try:
            with open(OUT_RS, encoding="utf-8") as f:
                cur = f.read()
        except FileNotFoundError:
            cur = ""
        if cur.replace("\r\n", "\n") != new:
            h = lambda s: hashlib.sha256(s.encode()).hexdigest()[:12]
            print(f"STALE: tracker_regions.rs out of date "
                  f"(committed {h(cur)} vs generated {h(new)}); "
                  f"run: python tools/gen_location_regions.py")
            return 1
        if not lib_has_mod():
            print(f"STALE: lib.rs missing `{MOD_LINE}`; "
                  f"run: python tools/gen_location_regions.py")
            return 1
        print(f"OK: tracker_regions.rs up to date ({len(rows)} locations); lib.rs wired.")
        return 0

    with open(OUT_RS, "w", encoding="utf-8", newline="\n") as f:
        f.write(new)
    wired = wire_lib_rs()
    print(f"Wrote {OUT_RS} ({len(rows)} locations, "
          f"{len(set(r[1] for r in rows))} regions).")
    print("Wired lib.rs (added `%s`)." % MOD_LINE if wired
          else "lib.rs already wired.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
