#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate release/ITEM-IDS.md -- the player-facing id reference for the client's `!give`.

WHY THIS FILE EXISTS. `release/GETTING-UNSTUCK.md` hand-lists the handful of ids a rescue has
actually needed so far (the seven Great Runes, the whetblades). Every other id a player might need
lived only in `greenfield/eldenring/tables/item_ids.py`, which is a generated Python dict nobody
reading a rescue doc is going to open -- so the answer to "what is the id for X" was "ask in the
thread". This renders the SAME table, the one the world already ships, as a page.

SOURCE OF TRUTH IS THE TABLE, NOT THIS FILE. `ITEM_CATALOG` maps a vanilla item name to the ER
FullID. The top nibble is the category, and it is the same space `!give`, `grant_full_id` and the
client's detour speak (see the `ConsoleCommand::Give` arm in the client's
`crates/eldenring-archipelago/src/core.rs`, and the FMG -> nibble table in `greenfield/gen_data.py`
around the `WeaponName.fmg.xml` list):

    0x0  weapons (WeaponName)      0x1  armour (ProtectorName)   0x2  talismans (AccessoryName)
    0x4  goods (GoodsName)         0x8  ashes of war / gems (GemName)

Weapons fold `+N` back to the base row (`(id // 100) * 100`) when the catalog is built -- see the
same gen_data comment -- so every weapon row here is the **+0** row, and no row in the catalog
carries an upgrade digit (asserted below).

Run:  python tools/gen_item_ids_doc.py            # write release/ITEM-IDS.md
      python tools/gen_item_ids_doc.py --check    # exit 1 if the committed file is stale
"""
import argparse
import importlib.util
import os
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(ROOT, "greenfield", "eldenring", "tables", "item_ids.py")
OUT = os.path.join(ROOT, "release", "ITEM-IDS.md")

# Category nibble -> (section heading, one-line gloss). Order is the page order: goods first,
# because that is where a rescue almost always lands (keys, tears, bell bearings, spells).
CATEGORIES = [
    (0x4, "Goods", "Key items, crafting materials, consumables, bell bearings, spells, notes."),
    (0x0, "Weapons", "Every weapon and shield, at **+0** -- see the note above the table."),
    (0x1, "Armour", "Helms, chest pieces, gauntlets and greaves."),
    (0x2, "Talismans", "Talismans and the other accessories that share their table."),
    (0x8, "Ashes of War / Gems", "Ashes of War, and the gems that carry them."),
]

HEADER = """\
# Elden Ring item IDs for `!give`

<!-- AUTO-GENERATED by tools/gen_item_ids_doc.py from greenfield/eldenring/tables/item_ids.py.
     DO NOT EDIT BY HAND -- regenerate with `python tools/gen_item_ids_doc.py`
     (CI runs `python tools/gen_item_ids_doc.py --check` and goes red on a stale copy). -->

**AUTO-GENERATED -- do not edit this file by hand.** It is rendered from the world's own item
table (`greenfield/eldenring/tables/item_ids.py`) by `tools/gen_item_ids_doc.py`; regenerate it
with `python tools/gen_item_ids_doc.py`.

## How to use it

The client's rescue console takes a full item ID:

```
!give 0x40001fad        grants one Academy Glintstone Key
!give 0x40001fad 3      grants three of them
```

* **The `0x` prefix is required for hex.** Without it the client reads the number as **decimal**,
  so `!give 40001fad` is an error and `!give 1073749933` is the same key spelled the long way.
  Both columns are in the tables below; prefer the hex one, it needs no arithmetic.
* The client **echoes the decoded category and row back before it grants**, e.g.
  `give 1073749933 (category 0x40000000, row 8109) x1 -> granted`. If that line does not describe
  the item you meant, stop -- the ID was wrong, not the grant.
* The quantity argument is optional and defaults to `1`.

## Please use it responsibly

`!give` is a **rescue and debug probe, not a cheat menu**. In a multiworld it hands you an item
the seed did not place, and neither the server nor the other players can see that happen -- so it
can quietly desync what the tracker believes from what you are holding, and it can hand you
progression someone else's world was supposed to give you. Use it to get *unstuck* (see
[GETTING-UNSTUCK.md](GETTING-UNSTUCK.md)), tell your room when you do, and leave it alone
otherwise.

## About these IDs

A full ID is `category nibble | row`. The top nibble says which of the game's tables the row lives
in, and it is **not** optional or inferred -- a bare row number will silently address the wrong
table:

| Nibble | Category |
| --- | --- |
| `0x0` | Weapons |
| `0x1` | Armour |
| `0x2` | Talismans / accessories |
| `0x4` | Goods |
| `0x8` | Ashes of War / gems |

Weapon IDs embed the upgrade level in their low digits (`base + N`), and the world's catalog folds
every `+N` back to its base row, so **every weapon listed here is the `+0` row**. Ask for a `+0`
weapon and upgrade it the ordinary way.

Names are the vanilla English names, including the base game and both DLCs. Sorted by name within
each section.
"""


def _catalog():
    spec = importlib.util.spec_from_file_location("_item_ids_table", TABLE)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.ITEM_CATALOG


def _cell(name):
    return name.replace("|", "\\|")


def render():
    catalog = _catalog()
    buckets = {}
    for name, full in catalog.items():
        buckets.setdefault((full >> 28) & 0xF, []).append((name, full))

    known = {nibble for nibble, _, _ in CATEGORIES}
    stray = sorted(set(buckets) - known)
    if stray:
        raise SystemExit(
            "item_ids.py carries unknown category nibble(s) %s -- the CATEGORIES table in "
            "tools/gen_item_ids_doc.py needs a row for each before the page can claim to be "
            "complete" % ", ".join("0x%X" % n for n in stray))

    # The claim the header makes about weapons, asserted rather than trusted: if the catalog ever
    # stops folding +N, the page would quietly start listing upgraded rows as if they were +0.
    upgraded = sorted(n for n, f in buckets.get(0x0, []) if f % 100)
    if upgraded:
        raise SystemExit(
            "%d weapon row(s) carry an upgrade digit (e.g. %s) -- the catalog no longer folds +N "
            "to the base row, so the '+0' note in tools/gen_item_ids_doc.py is now false"
            % (len(upgraded), upgraded[0]))

    out = [HEADER]
    for nibble, heading, gloss in CATEGORIES:
        rows = sorted(buckets.get(nibble, []), key=lambda pair: (pair[0].lower(), pair[0]))
        out.append("\n## %s\n\n%s\n\n%d item%s, category nibble `0x%X`.\n\n"
                   % (heading, gloss, len(rows), "" if len(rows) == 1 else "s", nibble))
        out.append("| Name | Hex | Decimal |\n| --- | --- | --- |\n")
        for name, full in rows:
            out.append("| %s | `0x%08X` | `%d` |\n" % (_cell(name), full, full))
    return "".join(out)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if release/ITEM-IDS.md differs from a fresh render")
    args = parser.parse_args(argv)
    text = render()

    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.isfile(OUT) else None
        if current != text:
            print("DRIFT: release/ITEM-IDS.md is stale; run python tools/gen_item_ids_doc.py")
            return 1
        print("--check: release/ITEM-IDS.md matches greenfield/eldenring/tables/item_ids.py")
        return 0

    fd, temporary = tempfile.mkstemp(dir=os.path.dirname(OUT), prefix=".ITEM-IDS.md.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(temporary, OUT)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise
    print("wrote release/ITEM-IDS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
