#!/usr/bin/env python3
"""Bake the bell-bearing hand-in table into the client (er-archipelago#325).

Emits `crates/er-logic/src/merchant_bell_table.rs` from `greenfield/bell_handins.tsv`
(`tools/datamine_bell_handins.py`, derived from the Twin Maidens' own talk ESD).

WHY A BAKED TABLE AND NOT A SLOT KEY. `(shop range -> bell hand-in flag)` is STATIC GAME DATA:
seed-invariant, identical for every apworld, unchanged by any option. A slot_data key would move
`CONTRACT_HASH` and force a lockstep version bump in both repos to ship a constant. Same argument
and same generator shape as `gen_sweep_boss_names.py` / `gen_area_tiers.py`. The only thing that
DOES travel is the option itself (`merchant_bells_on_talk`, an OPTIONS_SUBKEYS bool).

ASCII ONLY, ENFORCED BELOW. The names ride into an in-game toast, and the game's font has no glyph
for non-ASCII (the 2026-07-31 "Altus ? enemy scaling" screenshot). The datamine already folds
`Kale`; this refuses rather than shipping a row that renders as a box.

    python tools/gen_merchant_bells.py            # regenerate + wire lib.rs
    python tools/gen_merchant_bells.py --check    # CI drift gate (0 ok / 1 stale / 4 no client)
"""
import argparse
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
TSV = os.path.join(REPO, "greenfield", "bell_handins.tsv")
OUT_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "merchant_bell_table.rs")
LIB_RS = os.path.join(REPO, "from-software-archipelago-clients",
                      "crates", "er-logic", "src", "lib.rs")
MOD_LINE = "pub mod merchant_bell_table;"


def load_rows():
    rows = []
    with open(TSV, encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#") or line.startswith("handin_flag"):
                continue
            flag, _goods, name, lo, hi, _menu = line.split("\t")
            if not name.isascii():
                raise SystemExit(
                    f"FATAL: bell name {name!r} is not ASCII. It is rendered by the GAME's font, "
                    "which has no glyph for non-ASCII -- fix the fold in "
                    "tools/datamine_bell_handins.py rather than relaxing this check.")
            rows.append((int(lo), int(hi), int(flag), name))
    if not rows:
        raise SystemExit(f"FATAL: {TSV} has no rows -- run tools/datamine_bell_handins.py first.")
    rows.sort()
    for a, b in zip(rows, rows[1:]):
        if b[0] <= a[1]:
            raise SystemExit(
                f"FATAL: shop ranges {a[0]}..{a[1]} and {b[0]}..{b[1]} overlap, so an observed "
                "range no longer identifies one bell.")
    return rows


def render_rs(rows):
    out = [
        "// @generated by tools/gen_merchant_bells.py -- DO NOT EDIT BY HAND.",
        "// Source: greenfield/bell_handins.tsv (tools/datamine_bell_handins.py, from the Twin",
        "// Maiden Husks' own talk ESD t600001110).",
        "// Regenerate: python tools/gen_merchant_bells.py   (AP-env-free, pure greenfield data)",
        "//",
        "// STATIC GAME DATA: a merchant's ShopLineupParam row range -> the event flag the Twin",
        "// Maidens set when you hand them that merchant's Bell Bearing. Seed-invariant, so it is",
        "// baked rather than carried in slot_data -- a new wire key would move CONTRACT_HASH to",
        "// ship a constant.",
        "",
        "/// `(shop_begin, shop_end, handin_flag, bell_name)`, sorted by `shop_begin` and pairwise",
        "/// disjoint (the generator refuses to emit an overlap).",
        "///",
        "/// 🛑 THE RANGE IS THE MERCHANT'S OWN BLOCK, not a copy of it. Handing a bell to the Twin",
        "/// Maidens adds a MENU ENTRY pointing at these same rows; it does not release or duplicate",
        "/// stock. That is why setting `handin_flag` is the whole mechanism, and why the AP check on",
        "/// a row fires identically whether it was bought at the merchant or at the hub -- the row,",
        "/// and therefore its `eventFlag_forStock`, is the same row.",
        f"pub const MERCHANT_BELLS: [(i32, i32, u32, &str); {len(rows)}] = [",
    ]
    for lo, hi, flag, name in rows:
        # json.dumps, NOT repr()+quote-swap: Python's repr switches to double quotes on an
        # apostrophe, and every name here has one ("Gostoc's Bell Bearing").
        out.append(f"    ({lo}, {hi}, {flag}, {json.dumps(name)}),")
    out += [
        "];",
        "",
        "/// The bell whose merchant owns `[begin, end]`, if any.",
        "///",
        "/// Matches by CONTAINMENT, not equality. A merchant can open a narrower slice of its own",
        "/// block than the Twin Maidens do (Moore's talk opens `102270..102289` where the Maidens'",
        "/// entry opens `102250..102289`), and because the table's ranges are pairwise disjoint the",
        "/// containing range is unique when it exists.",
        "pub fn bell_for_range(begin: i32, end: i32) -> Option<(u32, &'static str)> {",
        "    if begin > end {",
        "        return None;",
        "    }",
        "    let i = MERCHANT_BELLS.partition_point(|&(lo, _, _, _)| lo <= begin);",
        "    let (lo, hi, flag, name) = *MERCHANT_BELLS.get(i.checked_sub(1)?)?;",
        "    (lo <= begin && end <= hi).then_some((flag, name))",
        "}",
        "",
        "#[cfg(test)]",
        "mod tests {",
        "    use super::*;",
        "",
        "    /// `bell_for_range` binary-searches, and the generator sorts -- a hand edit would not.",
        "    #[test]",
        "    fn the_table_is_sorted_and_disjoint() {",
        "        assert!(MERCHANT_BELLS.windows(2).all(|w| w[0].1 < w[1].0));",
        "        assert!(MERCHANT_BELLS.iter().all(|&(lo, hi, _, _)| lo <= hi));",
        "    }",
        "",
        "    /// Toast text is drawn by the GAME's font, which has no glyph for non-ASCII.",
        "    #[test]",
        "    fn every_name_is_ascii() {",
        "        for (_, _, flag, name) in MERCHANT_BELLS {",
        "            assert!(name.is_ascii(), \"flag {flag} name {name:?} is not ASCII\");",
        "        }",
        "    }",
        "",
        "    #[test]",
        "    fn every_range_resolves_to_its_own_bell() {",
        "        for (lo, hi, flag, _) in MERCHANT_BELLS {",
        "            assert_eq!(bell_for_range(lo, hi).map(|(f, _)| f), Some(flag));",
        "        }",
        "    }",
        "",
        "    /// A merchant may open a narrower slice than the Maidens' entry does.",
        "    #[test]",
        "    fn a_contained_range_resolves() {",
        "        let (lo, hi, flag, _) = MERCHANT_BELLS[0];",
        "        assert_eq!(bell_for_range(lo, hi.min(lo + 1)).map(|(f, _)| f), Some(flag));",
        "    }",
        "",
        "    /// The Twin Maidens' OWN buy menu (101800..101897) is not a merchant with a bell, and",
        "    /// it is the range the 2026-08-08 probe actually observed -- so it is the one open that",
        "    /// must resolve to nothing.",
        "    #[test]",
        "    fn the_twin_maidens_own_shelf_has_no_bell() {",
        "        assert_eq!(bell_for_range(101_800, 101_897), None);",
        "    }",
        "",
        "    #[test]",
        "    fn a_range_wider_than_its_block_is_refused() {",
        "        let (lo, hi, _, _) = MERCHANT_BELLS[0];",
        "        assert_eq!(bell_for_range(lo, hi + 1), None);",
        "        assert_eq!(bell_for_range(hi, lo), None);",
        "    }",
        "}",
        "",
    ]
    return "\n".join(out)


def lib_has_mod():
    try:
        return MOD_LINE in open(LIB_RS, encoding="utf-8").read()
    except OSError:
        return False


def wire_lib_rs():
    if lib_has_mod():
        return False
    src = open(LIB_RS, encoding="utf-8").read()
    lines = src.splitlines(keepends=True)
    mods = [i for i, l in enumerate(lines) if l.startswith("pub mod ")]
    at = max(mods) + 1 if mods else len(lines)
    for i in mods:                      # keep the list alphabetical (rustfmt orders them)
        if lines[i] > MOD_LINE + "\n":
            at = i
            break
    lines.insert(at, MOD_LINE + "\n")
    open(LIB_RS, "w", encoding="utf-8", newline="\n").write("".join(lines))
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rows = load_rows()
    new = render_rs(rows)
    if args.check:
        if not os.path.isdir(os.path.dirname(OUT_RS)):
            print("SKIP: the client submodule is not checked out -- cannot compare "
                  "merchant_bell_table.rs (git submodule update --init).")
            return 4
        try:
            cur = open(OUT_RS, encoding="utf-8").read()
        except FileNotFoundError:
            cur = ""
        if cur.replace("\r\n", "\n") != new or not lib_has_mod():
            print("STALE: merchant_bell_table.rs does not match bell_handins.tsv. "
                  "Run: python tools/gen_merchant_bells.py  (then commit the client submodule)")
            return 1
        print(f"OK: up to date ({len(rows)} bells).")
        return 0
    try:
        _cur = open(OUT_RS, encoding="utf-8", newline="").read().replace("\r\n", "\n")
    except OSError:
        _cur = None
    _wrote = _cur != new
    if _wrote:
        open(OUT_RS, "w", encoding="utf-8", newline="\n").write(new)
    wired = wire_lib_rs()
    print(f"{'Wrote' if _wrote else 'Unchanged'} {OUT_RS}: {len(rows)} bells.")
    print("Wired lib.rs." if wired else "lib.rs already wired.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
