#!/usr/bin/env python3
"""Open the next release window: bump every version site, regenerate what is derived, and lay
down the notes skeletons -- then PROVE the tree agrees before it lets you commit.

WHY THIS EXISTS (CONTRIBUTING rule 11, and the case is this repo's own history). Opening a window
is seven files across two repos, and the last three opens each found a site by GOING RED rather
than by looking:

    v0.4.4  "No client half was needed"   -> `generators` red: the pinned client did not contain
    v0.4.5  "No client half was needed"   -> the output this repo generates. client a548da4f wrote
    v0.4.6  "No client half is needed"    -> "a version bump always needs this half" and promised
                                             to correct the row it came from. It never reached the
                                             row, so the next opener read it and repeated it.

v0.4.6 then hit the same shape a second time in one window: `wizard/options-metadata.json` and the
copy inlined in `wizard/wizard.html` both embed `apworld_version`, both were stale, and the only
thing that noticed was step 12 of the `tests` job -- eight minutes and a push away from the mistake.

🛑 THE FIX IS NOT THIS SCRIPT. It is that `check_version_sites.SITES` now lists all seven sites
instead of four. That list's own comment already claimed to be the single definition of "a version
site" and was wrong by three; a gate that reports "2 sites agree" while three files disagree is
worse than no gate, because it is evidence of the thing it failed to check. This script is what
that corrected list makes possible: one command that cannot forget a site, because it does not
know any site names of its own.

    ⭐ EVERY SITE THIS TOUCHES COMES FROM `check_version_sites.SITES`. There is no list here. If
    you add a site there, this picks it up with no edit; if you were tempted to add one here, the
    other place is the one that is wrong.

WHAT IT DOES NOT DO, ON PURPOSE:

  * It does not write the prose. The changelog note and the ledger row are the valuable part of a
    window open -- they are what the next opener reads -- and a generated sentence is exactly the
    "no client half was needed" failure with more steps. Skeletons are laid down with `TODO(open)`
    markers, and `--check-notes` refuses to pass while any survive.
  * It does not push, tag, or merge anything.
  * It does not patch a GENERATED site. `contract_gen.rs` and the wizard blob are regenerated by
    their own generators and then re-checked. Hand-editing a generated file is how it gets
    reverted by the next regen, silently, in someone else's commit.

Run:
    python3 tools/open_window.py --to 0.4.7 --ap-dir _ap
    python3 tools/open_window.py --to 0.4.7 --ap-dir _ap --dry-run
    python3 tools/open_window.py --check-notes          # after you have written the prose
"""

import argparse
import datetime as _dt
import importlib.util
import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CLIENT = os.path.join(REPO, "from-software-archipelago-clients")
SEMVER = re.compile(r"^\d+\.\d+\.\d+$")
TODO = "TODO(open)"

sys.path.insert(0, os.path.join(REPO, "tools"))
import check_version_sites as _sites  # noqa: E402  -- THE list, imported, never re-typed


# ---- plumbing ------------------------------------------------------------------------------

def _run(cmd, cwd=REPO, quiet=False):
    """(ok, output). Never raises: a generator that is absent is a REPORTED skip, not a crash.

    🛑 EVERY CHILD RUNS `sys.executable`, NEVER A BARE "python3". Measured 2026-08-17 on the first
    real run of this script: the wizard generator went out to the system 3.10, which cannot import
    Archipelago at all (`cannot import name 'Self' from 'typing'`), so both wizard sites stayed at
    the old version. Step 4 caught it and refused -- correctly -- but the cause was this file
    choosing an interpreter that was not the one it was running under.
    """
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    except OSError as exc:
        return False, str(exc)
    out = (p.stdout or "") + (p.stderr or "")
    if not quiet and out.strip():
        for line in out.strip().splitlines()[-4:]:
            print("      | " + line[:140])
    return p.returncode == 0, out


def _git(*args, cwd=REPO):
    ok, out = _run(["git", *args], cwd=cwd, quiet=True)
    return out.strip() if ok else ""


def _rel(path):
    for root, label in ((REPO, ""), (CLIENT, "")):
        if path.startswith(root):
            return os.path.relpath(path, root if root == REPO else CLIENT) + label
    return path


def substitution_for(site):
    """The regex whose group(1) IS the version, for writing.

    `check_version_sites` reads a `json` site by parsing; rewriting it that way would reformat the
    whole file and bury the one-character change in a diff nobody can review. So a json site is
    written through a targeted pattern instead, and the read path stays the authority on what the
    value IS.
    """
    if site["kind"] == "json":
        return re.compile(r'("%s"\s*:\s*")(\d+(?:\.\d+)+)(")' % re.escape(site["key"])), 2
    return site["rx"], 1


def write_site(site, new_version, dry_run):
    """(status, detail). status in {written, unchanged, absent, generated, failed}."""
    path = site["path"]
    if not os.path.isfile(path):
        return ("absent" if site.get("optional") else "failed"), "not checked out"
    if site.get("generated"):
        return "generated", site["generated"]
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    rx, group = substitution_for(site)
    m = rx.search(text)
    if not m:
        return "failed", "pattern no longer matches -- the site is UNCHECKED, not clean"
    if m.group(group) == new_version:
        return "unchanged", "already " + new_version
    start, end = m.span(group)
    if not dry_run:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(text[:start] + new_version + text[end:])
    return "written", "%s -> %s" % (m.group(group), new_version)


def contract_hash():
    """Read CONTRACT_HASH by LOADING contract.py, never by matching a pattern in it.

    Every ledger row since 0.4.4 says "verified by loading contract.py after the bump, not
    assumed", because the hash is computed from the contract's shape at import time -- a regex
    would happily read a stale literal and agree with itself.
    """
    spec = importlib.util.spec_from_file_location(
        "_er_contract", os.path.join(REPO, "greenfield", "eldenring", "contract.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.APWORLD_VERSION, mod.CONTRACT_HASH


def tag_position():
    """(latest_tag, commits_past_it) -- the fact every ledger row opens with."""
    tag = _git("describe", "--tags", "--abbrev=0")
    if not tag:
        return None, None
    past = _git("rev-list", "--count", "%s..HEAD" % tag)
    return tag, int(past) if past.isdigit() else None


# ---- the notes -----------------------------------------------------------------------------

def append_channels(prev_tag, today, new_version):
    path = os.path.join(REPO, "release", "CHANNELS.tsv")
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    if not text.endswith("\n"):
        text += "\n"
    rows = (
        "stable\t%s\t%s\t%s -- what this window shipped, and why the promotion is paid HERE rather "
        "than tomorrow morning\n" % (prev_tag, today, TODO)
        + "beta\tmain\t%s\tthe open v%s window\n" % (today, new_version)
    )
    return path, rows


def skeletons(new_version, prev_tag, past, chash, today):
    """The prose skeletons. Deliberately unhelpful where a human has to think."""
    opened = ("AT THE TAG of %s with ZERO commits past it" % prev_tag if past == 0
              else "%d commit(s) PAST the %s tag" % (past, prev_tag))
    ledger = (
        "%s\t%s\tv%s -- %s. Opened %s, %s. %s: say what CONTRACT_HASH did and why, whether this "
        "window needed a client half (IT DOES IF THE VERSION MOVED -- see the three windows that "
        "learned this the hard way), and what the stable promotion paid off. CONTRACT_HASH read by "
        "loading contract.py: %s.\n"
        % (new_version, chash[:8], new_version, TODO, today, opened, TODO, chash)
    )
    changelog = (
        "## v%s — %s\n\n"
        "Window opened %s.\n\n"
        "`CONTRACT_HASH` is `%s`. %s: state whether that is unmoved and what it means for "
        "handshake compatibility — and say it after LOADING contract.py, not after assuming.\n\n"
        "%s: if the version moved, a client half is needed (`contract_gen.rs` embeds the version "
        "string). Name the client PR and confirm the gitlink rides in the same commit (AGENTS §7).\n\n"
        "`release/CHANNELS.tsv` promotes `stable` to %s in this same commit.\n\n"
        "Entries arrive below as they merge (rule 14: the release notes are part of the change, "
        "not part of the release).\n\n"
        % (new_version, today, opened, chash[:8], TODO, TODO, prev_tag)
    )
    blurb = (
        "# v%s — release blurb (draft)\n\n"
        "_Draft. Written as the window fills, not at tag time -- the moment a change lands is the\n"
        "only moment anyone remembers why it mattered._\n\n"
        "## What is in it so far\n\n"
        "Nothing yet. This window was opened %s, so this file exists before its first entry does,\n"
        "which is the point of it.\n\n"
        "## What carried over from %s\n\n"
        "%s: what is owed, and what is not. If nothing is owed, say so and say why — a blurb that\n"
        "cannot tell the difference is the one that lets a debt roll into a third window.\n\n"
        "## For whoever writes the real one\n\n"
        "The v0.4.3 blurb is the model: lead with what changed at the table, not with the option\n"
        "name. Its opening line -- \"You can get BK'ed now, and that is the point\" -- says what a\n"
        "player will feel before it says what was built, and that is the right order.\n"
        % (new_version, opened, prev_tag, TODO)
    )
    return ledger, changelog, blurb


def check_notes():
    """Refuse to call a window open while a skeleton marker survives."""
    stale = []
    for rel in ("release/CHANGELOG.md", "release/CHANNELS.tsv", "release/CONTRACT-VERSIONS.tsv"):
        path = os.path.join(REPO, rel)
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as fh:
                for n, line in enumerate(fh, 1):
                    if TODO in line:
                        stale.append("%s:%d" % (rel, n))
    blurbs = sorted(f for f in os.listdir(os.path.join(REPO, "release"))
                    if f.startswith("BLURB-v") and f.endswith(".md"))
    if blurbs:
        path = os.path.join(REPO, "release", blurbs[-1])
        with open(path, encoding="utf-8") as fh:
            for n, line in enumerate(fh, 1):
                if TODO in line:
                    stale.append("release/%s:%d" % (blurbs[-1], n))
    if stale:
        print("open_window --check-notes: %d skeleton marker(s) still unwritten:" % len(stale))
        for s in stale:
            print("   " + s)
        print("\nThese are the sentences the NEXT window-opener reads first. Three windows running,\n"
              "the one that was left wrong ('no client half was needed') cost a red CI run each time.")
        return 1
    print("OK open_window: no %s markers left in the release notes" % TODO)
    return 0


# ---- main ----------------------------------------------------------------------------------

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--to", metavar="X.Y.Z", help="the version this window opens")
    ap.add_argument("--ap-dir", default="_ap",
                    help="Archipelago checkout, for the wizard metadata generator")
    ap.add_argument("--dry-run", action="store_true", help="print every step, write nothing")
    ap.add_argument("--check-notes", action="store_true",
                    help="fail while any %s marker survives" % TODO)
    args = ap.parse_args(argv)

    if args.check_notes:
        return check_notes()
    if not args.to or not SEMVER.match(args.to):
        print("open_window: --to X.Y.Z is required", file=sys.stderr)
        return 2

    dry = args.dry_run
    today = _dt.date.today().isoformat()
    print("open_window: %s%s\n" % (args.to, "  (DRY RUN -- nothing is written)" if dry else ""))

    # 1. PRECONDITION. Every site must agree NOW, or the bump is being applied to a tree that is
    #    already inconsistent and the "they all agree" at the end would be meaningless.
    print("[1] the sites agree before we start")
    current = {}
    for site in _sites.SITES:
        version, note = _sites.read_site(site)
        if version is None:
            if note == "absent" and site.get("optional"):
                print("      SKIP %s -- not checked out" % site["what"])
                continue
            print("ERROR open_window: %s: %s" % (site["what"], note), file=sys.stderr)
            return 1
        current.setdefault(version, []).append(site["what"])
    if len(current) != 1:
        print("ERROR open_window: the sites disagree before the bump: %s"
              % ", ".join(sorted(current)), file=sys.stderr)
        print("       fix that first: python tools/check_version_sites.py", file=sys.stderr)
        return 1
    was = next(iter(current))
    print("      all readable sites read %s" % was)
    if was == args.to:
        print("ERROR open_window: already at %s" % args.to, file=sys.stderr)
        return 1

    prev_tag, past = tag_position()
    print("      HEAD is %s past %s" % ("%d commit(s)" % past if past else "0 commits", prev_tag))
    if past:
        print("      ⚠️  not opening AT a tag. That is the ORDINARY case (v0.4.4), not an error --")
        print("         but the ledger row has to say so rather than claim the tidy shape.")

    # 2. Write the sites that are written, and NAME the ones that are generated.
    print("\n[2] bump the writable sites")
    regenerate = []
    for site in _sites.SITES:
        status, detail = write_site(site, args.to, dry)
        shown = ("WOULD" if (dry and status == "written") else status.upper())
        print("      %-9s %-46s %s" % (shown, site["what"], detail))
        if status == "failed":
            print("ERROR open_window: %s: %s" % (site["what"], detail), file=sys.stderr)
            return 1
        if status == "generated":
            regenerate.append(site)

    # 3. Regenerate the derived sites. Never patched -- the next regen would revert a hand-edit
    #    silently, inside somebody else's commit.
    print("\n[3] regenerate the derived sites (%d)" % len(regenerate))
    ap_dir = args.ap_dir if os.path.isabs(args.ap_dir) else os.path.join(REPO, args.ap_dir)
    for cmd, why in (([sys.executable, os.path.join(REPO, "greenfield", "gen_contract.py")],
                      "contract_gen.rs (skips itself when the client is absent)"),
                     ([sys.executable, os.path.join(REPO, "tools", "dump_options_metadata.py"),
                       "--ap-dir", ap_dir], "the wizard metadata blob + its inlined copy")):
        print("      %s" % why)
        if dry:
            print("      | (dry run) %s" % " ".join(os.path.basename(c) for c in cmd[:2]))
            continue
        ok, _ = _run(cmd)
        if not ok:
            print("      ⚠️  that generator did not succeed. Its site(s) stay stale, and step 4")
            print("         is about to say so rather than let it through.")

    # 4. THE PROOF. Same gate CI runs, now with an --expect.
    print("\n[4] every site now reads %s" % args.to)
    if dry:
        print("      | (dry run) skipped")
    else:
        ok, _ = _run([sys.executable, os.path.join(REPO, "tools", "check_version_sites.py"),
                      "--expect", args.to])
        if not ok:
            print("\nERROR open_window: the sites do NOT all read %s.\n"
                  "       This is the failure the last three windows shipped to CI. Fix the sites\n"
                  "       named above -- for a generated one, run its generator." % args.to,
                  file=sys.stderr)
            return 1
        print("      OK")

    # 5. The hash, by loading.
    version, chash = (args.to, "0" * 64) if dry else contract_hash()
    print("\n[5] CONTRACT_HASH, read by loading contract.py")
    print("      APWORLD_VERSION = %s" % version)
    print("      CONTRACT_HASH   = %s" % chash)

    # 6. Notes skeletons.
    print("\n[6] notes skeletons (prose is yours -- %s markers mark every one)" % TODO)
    ledger, changelog, blurb = skeletons(args.to, prev_tag or "the previous tag", past or 0,
                                         chash, today)
    ch_path, ch_rows = append_channels(prev_tag or "PREVIOUS", today, args.to)
    targets = [
        (os.path.join(REPO, "release", "CONTRACT-VERSIONS.tsv"), "append", ledger),
        (ch_path, "append", ch_rows),
        (os.path.join(REPO, "release", "CHANGELOG.md"), "after-header", changelog),
        (os.path.join(REPO, "release", "BLURB-v%s.md" % args.to), "create", blurb),
    ]
    for path, how, payload in targets:
        label = os.path.relpath(path, REPO)
        if how == "create" and os.path.exists(path):
            print("      SKIP   %s -- already exists" % label)
            continue
        print("      %-6s %s" % ({"append": "APPEND", "create": "CREATE",
                                  "after-header": "INSERT"}[how], label))
        if dry:
            continue
        if how == "create":
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(payload)
        elif how == "append":
            with open(path, encoding="utf-8") as fh:
                body = fh.read()
            if not body.endswith("\n"):
                body += "\n"
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(body + payload)
        else:
            with open(path, encoding="utf-8") as fh:
                body = fh.read()
            m = re.search(r"^## v", body, re.M)
            at = m.start() if m else len(body)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(body[:at] + payload + body[at:])

    # 7. The client half: commit it on a branch, and stop there.
    print("\n[7] the client half")
    if not os.path.isdir(os.path.join(CLIENT, "crates")):
        print("      the client is NOT checked out here, so its three sites were skipped.")
        print("      🛑 THEY STILL HAVE TO MOVE. `contract_gen.rs` embeds the version string, so a")
        print("         version-only bump makes the pinned client stale and `generators` goes red.")
        print("         Check the client out (git submodule update --init) and re-run, or land the")
        print("         client half by hand before bumping the gitlink.")
    elif _git("status", "--porcelain", cwd=CLIENT):
        branch = "chore/open-v%s-window-client" % args.to
        print("      client sites changed. Committing on %s (no push)." % branch)
        if not dry:
            _run(["git", "checkout", "-b", branch], cwd=CLIENT, quiet=True)
            _run(["git", "add", "-u"], cwd=CLIENT, quiet=True)
            msg = ("chore: the client half of the v%s window\n\n"
                   "contract_gen.rs is generated from the world's contract and EMBEDS THE VERSION\n"
                   "STRING, so a version-only bump moves it even when CONTRACT_HASH does not, and\n"
                   "the world's `generators` gate stays red until the gitlink follows.\n\n"
                   "Opened by tools/open_window.py.\n" % args.to)
            _run(["git", "commit", "-m", msg], cwd=CLIENT, quiet=True)
            print("      committed %s" % _git("rev-parse", "--short", "HEAD", cwd=CLIENT))
        print("\n      NEXT, in order (AGENTS §7 -- the client commit must exist first):")
        print("        1. cd %s && git push -u origin %s" % (_rel(CLIENT), branch))
        print("        2. open the client PR and merge it")
        print("        3. back here: git update-index --cacheinfo 160000,<merge-sha>,"
              "from-software-archipelago-clients")
        print("           ...in the SAME commit as the bump.")
    else:
        print("      client is checked out and its sites are already current -- nothing owed.")

    print("\nDONE. Now write the prose, then:")
    print("    python3 tools/open_window.py --check-notes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
